### ISSUE TITLE
unable to click on few websites

### ISSUE THREAD

**Issue by HexagonWin** [akhodakivskiy/VimFx#1006]
Hello. I'm not sure if this is actually something to report, but I'm having trouble clicking buttons using 'f' on a few websites.
Most notably, the expandable menubar on this website [gigglehd.com](https://gigglehd.com/gg/bbs/) (website in korean) isn't working properly.
Those three menu categories under the main "Gigglehd.com" logo (titled "기글하드웨어", "포럼", "커뮤니티") expands on mouse hover. I can make them expand using 'f', but clicking on one of the sub menu item immediately closes the menu instead of clicking it. Though, when I expand the menu using an actual mouse I can open the item just fine.

++This works fine on Vimium (the webextension)

**Comment by girst** [comment]
the problem appears to be that we somehow manage to trigger the 
onmouseout event handler (hiding the menu), and that our 
utils.simulateMouseEvents() can't handle clicking hidden elements.

when opening links in a new tab (`F`), i can get the link to open 
reliably. this code doesn't trigger utils.simulateMouseEvents.

i guess a quick fix would be to check if the element is indeed visible, 
or fall back to element.click() if it's not. such a change could be made 
in commands-frame.coffee::commands.click_marker_element. but i'm not 
sure what other consequences this might have.

thanks for reporting - let's see what i can come up with for a fix.

here's a minimal reproducer: load the page, hit `f` to show hints, then 
wait until the button is automatically hidden. then follow the hint.

	<!DOCTYPE html>
	<button id=b onclick="alert(1)">click</button>
	<script>
	window.setTimeout(function(){ b.style.display = "none"; }, 5000);
	</script>

**Comment by girst** [comment]
[VimFx.xpi.zip](https://github.com/user-attachments/files/17894725/VimFx.xpi.zip)

@HexagonWin : i believe this version should fix your problem. the above binary corresponds to the commit published at https://git.gir.st/VimFx.git/commitdiff/040246ad0c384ff41ca4104f8509d7fa9126ecf1 . can you please try this and report back if this works for your use case?

**Comment by HexagonWin** [comment]
@girst yes, this seems to work well.

**Comment by girst** [comment]
On Wed, Nov 27, 2024 at 03:44:09PM -0800, hexagonwin wrote:
>@girst yes, this seems to work well.

thanks for testing, i'll consider this patch for the next release

**Comment by girst** [comment]
fixed in https://github.com/akhodakivskiy/VimFx/commit/e50b553f84e50bfbe0b5e29b658f31426673e98b, closing.
