### ISSUE TITLE
add support for alternative ESC as CTRL+[

### ISSUE THREAD

**Issue by shamotj** [akhodakivskiy/VimFx#113]
It would be great if we can escape hints or find or any other action with ESC as well as with CTRL+[. It works in vim and it requires less finger movement.

**Comment by lydell** [comment]
For people who find this while searching: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/questions-and-answers.md#how-do-i-re-map-escape-which-blurs-text-inputs
