### ISSUE TITLE
Read vimrc for custom bindings

### ISSUE THREAD

**Issue by jeaye** [akhodakivskiy/VimFx#155]
I'd like VimFx to actually work like my Vim setup (page up/down, tab navigation, etc); this could be done with a configuration window like the help window (like others have mentioned), or VimFx could just pull bits out of my ~/.vimrc.

Thoughts?

**Comment by haifengkao** [comment]
[Pentadactyl](https://github.com/5digits/dactyl) has custom key bindings in `$HOME/.pentadactylrc`

**Comment by lydell** [comment]
The development version lets you configure VimFx using a text file: https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/config-file.md
