### ISSUE TITLE
Fuzzy Bookmark Navigation

### ISSUE THREAD

**Issue by Morley93** [akhodakivskiy/VimFx#158]
I recently started using VimFX after using Vimium for a long time. One area that I feel is lacking is the ability to quicky navigate through bookmarks. In Vimium you can perform a fuzzy search of all your bookmarks by pressing b/B (opening them in the current tab and a new tab respectively). The o shortcut in VimFX does not offer a way of limiting search results to bookmarks alone. Would it be possible to implement a fuzzy search of bookmarks similar to the functionality to Vimium?

**Comment by lydell** [comment]
Added in the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#search-bookmarks) section of the wiki.
