### ISSUE TITLE
Make the shortcut hint tooltips translucent

### ISSUE THREAD

**Issue by danieldemus** [akhodakivskiy/VimFx#220]
The yellow key hint tooltips cover a significant portion of the link text, so if one doesn't remember which link in a list one was interested in, you have to escape and press f again after finding the relevant link. If the tooltips were say 30% translucent, you would be able to see the link text without having to press anything extra.

**Comment by lydell** [comment]
It is easy to make the hint markers 30% translucent in the development version now, which was originally requested.

Keeping #484 open for the 'when shift held down' feature.

**Comment by lindhe** [comment]
Have this stopped working for others too? Nothing happens for me anymore when i hold down shift when hints are open...

**Comment by lydell** [comment]
The shortcut had to be changed in [VimFx 0.19.0](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/CHANGELOG.md#0190-2016-09-25) (but can be changed back through custom [styling](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/styling.md)). You now need to hold both shift **and ctrl** at the same time (which is also mentioned in the Keyboard Shortcuts Help dialog).

**Comment by lindhe** [comment]
Ah, right. Thanks. I grepped the help dialog for "shift" and "hide", but nothing popped up so I assumed it wasn't there.
