### ISSUE TITLE
VimFX switches off randomly

### ISSUE THREAD

**Issue by maxrubyonrails** [akhodakivskiy/VimFx#231]
Firstly, many thanks for the great addon!

Now to the issue. VimFX keeps switching off after some events (usually it's opening GMail), btw the icon in the toolbar doesn't get grey. It's possible to switch it back via Shift+Alt+V.
Maybe the problem that Firefox (btw I have 25.0.1, Mozilla Firefox for Ubuntu Canonical 1.0) somehow imitates pressing that combination? In any case, an effective temporary low-cost solution would be to make it possible to change/unbind Shift+Alt+V combination (which would be a good feature by itself anyway).

Keep up the good work!

**Comment by anonx** [comment]
@akhodakivskiy VimFX switches off every time I mistakenly press `i` and then trying to scroll up with `k`. Is `i` + `k` is a kind of combination for disabling the plugin? It's a bit annoying to be honest.

**Comment by lydell** [comment]
@anonx `i` enters "Insert mode" (called "Ignore mode" in the development version), which ignores all VimFx commands and sends your keystrokes directly to the page instead. The VimFx toolbar button turns grey in Insert mode. You can change the keyboard shortcut for `i` if you feel like you activate it by mistake.

**Comment by anonx** [comment]
@lydell Cool. :+1: Thank you.

**Comment by esn89** [comment]
@lydell 
i would never expected 'i' to do that in VimFX, but looking at it differently now, I kind of appreciate having such feature.  Thank you for the clarification.

**Comment by abello** [comment]
It's similar to 'insert mode' in vim.
