### ISSUE TITLE
Feature request: Hint-based strategy for tab selection

### ISSUE THREAD

**Issue by jvinet** [akhodakivskiy/VimFx#236]
I've grown so fond of the hint-based system for link selection, that I'd love to see something like this for tab selection.

I can use J and K to move left/right along the tabs, but being able to jump to a specific tab by a reference key would be wonderful.  I can use Alt+1, Alt+2, etc, but it can be onerous to get back to my last-used tab if it's sitting in the middle of 15 others, where I can't eyeball the specific index number, or if it's sitting outside the 1-9 range.

Anyway, something to consider for a future release if you think it would be useful.

Love VimFX.  Thanks for it.

**Comment by lydell** [comment]
I worked on this for a while, but never finished. What I did was to add hints to all clickable browser elements, which was pretty awesome. We should totally finish that some time. At the moment there are other more important issues thogh.

**Comment by hallettj** [comment]
I would really like to able to just use VimFX to assign a shortcut to open Tabhunter.

That said, my favorite tab navigating implementation is in Vimium. It uses fuzzy matching to filter down tabs as you type. Bringing up a list of tabs in the middle of the screen is helpful if you have so many tabs that some are not visible; if you remember the title of the tab that you want to switch to, but don't remember where it is; or if you use Tree Style Tabs and some of your subtrees are collapsed.

When following a link, you are generally looking at it. So putting a hint on the link works really well. There are also issues with fuzzy title matching with links: links may be not-textual, link text may not be unique. I think that considerations for tabs are quite different. If I have a good fuzzy finder available, I tend not to look at the tab bar when switching; tabs without descriptive titles are rare; I have found that having multiple tabs with the same name is not very common.

**Comment by lydell** [comment]
@halletj You might be interested in [this](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/handy-standard-firefox-features.md#the-address-bar).

**Comment by hallettj** [comment]
@lydell Thanks - I had not been using the location bar because I did not know of a fast way to restrict suggestions to open tabs. But following that link I found out about the '% ' prefix. That will be really handy!

Now I want a shortcut to prefill the location bar with '% ' ;) It looks like maybe I can do that with the public API. I will read up.

The "Quick Find Bar" is also quite nice.

**Comment by lydell** [comment]
> It looks like maybe I can do that with the public API. I will read up.

You're at least supposed to be able to. If you succeed, you're more than welcome to share it on the [Custom Commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands) wiki page. If not, feel free too ask for help, report problems and provide feedback. The API is new and needs more testing. :)
