### ISSUE TITLE
Export and import customized shortcuts (partially fixed in dev)

### ISSUE THREAD

**Issue by zhuochun** [akhodakivskiy/VimFx#245]
Support export and import customized shortcuts?

- Export a text file of any kind, or
- Auto sync using Firefox's Sync

**Comment by lindhe** [comment]
What's the status on this? I'd really like to be able to export/import settings, since I make extensive use of custom key bindings...

**Comment by lydell** [comment]
This is not a priority right now. I’d suggest looking for an add-on that can import and export Firefox prefs in general. Perhaps [OPIE](https://addons.mozilla.org/firefox/addon/opie/) is a good choice.

**Comment by lydell** [comment]
I just realized that at least enabling Firefox Sync support for what we already have might be quick and simple. However, the MDN dkcs @evaryont linked to is now in the "Archive of obsolete content". I don't use Firefox Sync myself, so I don't know much about it. Is it no longer possible to sync add-on prefs?

**Comment by akhodakivskiy** [comment]
I do use Firefox Sync, and it is possible to sync add-on prefs. We just need to set up a few additional properties to enable sync, e.g. properties like `services.sync.prefs.sync.extensions.vimfx.some_property_to_sync`. I remember trying this back in the time, it didn't work quite well right away, but it does work well for other addons as of today.

**Comment by lydell** [comment]
I’m just worried because all Firefox sync docs on MDN are archived …

**Comment by lydell** [comment]
In the latest development version it is now possible to optionally configure VimFx via a [config file](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/config-file.md).

No Firefox Sync support yet, though.

**Comment by lydell** [comment]
https://discourse.mozilla-community.org/t/how-to-sync-preferences-of-a-bootstrapped-extension-via-sync/3024/10?u=lydell:

> The old Sync service was replaced with a new service that uses [Firefox Accounts](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts). I don't see any documentation around its sync feature, though.

Time won’t be spent on an obsolete feature. If anyone’s into this Firefox Accounts thing, feel free to open a new issue for it.

**Comment by lydell** [comment]
Import/export is now available in the development version, but no syncing.
