### ISSUE TITLE
Problems with other keyboard layouts than en-US

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#249]
VimFx unfortunately has problems with other keyboard layouts than en-US. There are several issues about this: #62, #217, #221, #207, #128, #125.

This issue gathers all of those into one, to make it easier to scan to through the issues list, and to make sure that all discussion is in one place (not split up over all of those similar issues).

**Comment by Dinduks** [comment]
Hi @lydell and thank you for your work.

Any idea about when will your patch go live? 
How can I use a dev version meanwhile?

Thanks!

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/tools.md#how-to-build-and-install-the-latest-version-from-source
