### ISSUE TITLE
Use numpad keys as "hint chars".

### ISSUE THREAD

**Issue by proedros** [akhodakivskiy/VimFx#259]
Hello as the title implies I am interested in using the numpad keys (as per initial post), is there any chance that I can use them as hint characters? I type faster with numpad than any other keys and also I never have to look at the keyboard if using only numpad keys. Also less chances of mistyping something.

**Comment by lydell** [comment]
This will be fixed by #438.

**Comment by lydell** [comment]
But you need to change the hidden `extensions.VimFx.translations` pref to [something like this](https://github.com/lydell/vim-like-key-notation#stringifyevent-options).
