### ISSUE TITLE
Allow key commands for zooming

### ISSUE THREAD

**Issue by jeaye** [akhodakivskiy/VimFx#261]
vimprobable uses zi and zI for zooming just text and the whole page, respectively. It's very handy for pages with a small design; I can just say 5zI and everything is made proportionally bigger. I'd love to see this feature in VimFx. 

Thanks for the badass piece of software.

**Comment by lydell** [comment]
No plans for zoom keys, but you can add them as [custom commands](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/config-file.md).
