### ISSUE TITLE
i removed a bunch of keys, want them back

### ISSUE THREAD

**Issue by Noitidart** [akhodakivskiy/VimFx#262]
i removed a bunch of keys, want them back, how to restore default all? or restore default individually?

**Comment by businessBoris** [comment]
+1 for a reset button on the preference or addon page.
Thank you @lydell, this might just be a way for me to finally use Vim as intended!

**Comment by lydell** [comment]
I think a factory reset button is too dangerous, if you press it by mistake. Why do you want such a drastic reset, instead of going to the specific shortcuts you miss the defaults for and pressing `<c-r>` in their text inputs?

**Comment by businessBoris** [comment]
@lydell Because newbies reset until we finds out comfortable positions/combinations.
You could add an "Are you sure?" on a drastic action. People do.
Thank you for the link; have saved! I'm not the only one who has had this desire then.

**Comment by lydell** [comment]
I decided to add a “Reset all” button after all.

**Comment by Noitidart** [comment]
Much appreciated! It will work awesome with the export feature.

**Comment by businessBoris** [comment]
@lydell Thank-you kind sir.
