### ISSUE TITLE
how to save prefs? does it work with sync?

### ISSUE THREAD

**Issue by Noitidart** [akhodakivskiy/VimFx#267]
i spent like a long time over days to finally perfect my custom hotkey set, how can i save this so i dont lose it? does it work with sync?

i would like to set up same way at work but i i dont have time at work to go through and change these keys :(

**Comment by lindhe** [comment]
Is this still the case?

**Comment by lydell** [comment]
See #245.

**Comment by lydell** [comment]
I decided to add import/export after all.
