### ISSUE TITLE
Allow custom selectors for markable elements

### ISSUE THREAD

**Issue by nxt-ext** [akhodakivskiy/VimFx#275]
[@ habr](http://habrahabr.ru/post/211430) there are spoilers that are created via div. After `vf` there is no highlight for them.
Don't know how to solve this problem. Highlighting all divs is bad idea. Maybe whitelist for div classes/ids?

**Comment by lydell** [comment]
The development version does not use xpath anymore. Extending the markable element matching algorithm is non-trivial. Also, as far as I understand extending it will be even more difficult when we support multi-process Firefox.

I think it is better to report specific problems and try to fix them in core.
