### ISSUE TITLE
VimFx for thunderbird. Is it possible?

### ISSUE THREAD

**Issue by ivanbalashov239** [akhodakivskiy/VimFx#284]
I'd like to use this addon with Thunderbird too, how can i port it/help you?

**Comment by the-solipsist** [comment]
One can use and add-on called keyconfig to override Thunderbird's internal keybindings.

**Comment by HunterGraubard** [comment]
I just discovered this amazing add-on and it's changed my life forever. I wish I could have the same thing on Thunderbird, so I'm chiming in here to add my support and to subscribe to the thread.

orschiro, if you're still following this - did you ever manage to get it working well?

**Comment by orschiro** [comment]
Unfortunately not. :-(
