### ISSUE TITLE
Open tab next to current?

### ISSUE THREAD

**Issue by zhuochun** [akhodakivskiy/VimFx#300]
I always have a lot of tabs on, when I am at the middle of tabs and press `t`, it opens a new tab to the far right of all the tabs. It troublesome to switch back to the previous active page.

Changing `browser.tabs.insertRelatedAfterCurrent` to `true` in `about:config` does not help.

Any idea on this?

**Comment by rightaway** [comment]
+1

**Comment by lydell** [comment]
This can be implemented as a custom command in the development version. See the [Custom Commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands) section of the wiki.

**Comment by lydell** [comment]
I finally found a way to do this reliably and have added it in the development version!

**Comment by zhuochun** [comment]
:+1:

**Comment by rightaway** [comment]
Will it be in the next release of the plugin? So typing 't' will open the tab to the right of the current one, no other configuration changes necessary?

**Comment by lydell** [comment]
> Will it be in the next release of the plugin?

Yes.

> So typing 't' will open the tab to the right of the current one, no other configuration changes necessary?

No. You need to type `T`. But you can of course customize the keyboard shortcuts.
