### ISSUE TITLE
Ctrl+F key clashes with default Ctrl+F find shortcut

### ISSUE THREAD

**Issue by temp4746** [akhodakivskiy/VimFx#308]
I know that this is a default vim shortcut but even vimium changed it so that it won't conflict. vimium changed it to `u` and `d`.

I suggest the default to be changed so that it's less suprising for users who commonly use Ctrl+F.

**Comment by andredasilvapinto** [comment]
some sites just "smartly" (not) bind the / to their own search boxes (e.g. Gmail - if you have enabled the shortcuts option, Jira...), so in those cases the fact that CTRL+F is hidden by VimFx actually disables any kind of search shortcut (you need to use your mouse!! - or use some strange menu bar keyboard shortcut combination).
