### ISSUE TITLE
gH, g^ to first non-pinned tab

### ISSUE THREAD

**Issue by petermehle** [akhodakivskiy/VimFx#317]
I think this would be better than current behavior, maybe as an option. Or maybe like vim has, g^ to the first non pinned tab and 0 to first pinned tab :)

**Comment by TheGreenHabi** [comment]
If I understand everything correctly it's already implemented in current dev build. Maybe this topic can be closed?

**Comment by lydell** [comment]
Issues are generally closed when they are fixed in `master`.
