### ISSUE TITLE
ctrl-o for switching between recently used tabs

### ISSUE THREAD

**Issue by petermehle** [akhodakivskiy/VimFx#319]
if in about:config you switched 'browser.ctrlTab.previews' to true, you can switch  between recently used tabs with ctrl-tab. I think this could be mapped to ctrl-o since it is quite similar to actual vim behaviour

**Comment by loonies** [comment]
:+1: 

Support switching between last two used tabs.

Use case:

Let say you are reading an article in one tab and in the other tab you
have web mail, or web chat open. This will allow easy switch to
email/chat and back.

BTW, default Vim key binding is `CTRL+^` or `:buffer #` command.

**Comment by lydell** [comment]
BTW, default Firefox key binding is `<c-tab>`.

**Comment by loonies** [comment]
Am I missing something? `c-tab` will switch tabs "in circle", unless
aforementioned `browser.ctrlTab.previews` option is enabled. And this
still isn't "truly" switch the last recently used tabs, and it will
switch tabs "in circle".

**Comment by lydell** [comment]
I’ve added `gl` as a Vim-style `<c-^>`. `<c-o>` as an alias for `<c-tab>` won’t be supported.
