### ISSUE TITLE
More control on tab groups.

### ISSUE THREAD

**Issue by ooker777** [akhodakivskiy/VimFx#323]
I use tab group as a habit. I now have five groups and change between them frequently. I would like to have a shortcut to make it faster. In Vimperator, you can handle it easily by pressing Ctrl+(Shift)+P. I suggest VimFx should have this feature too, maybe Ctrl+Shift+J,K to keep the analogousness.

Also, I would like it have create new tab group, move current tabs to other tab group. Maybe a command bar is necessary.

**Comment by lydell** [comment]
[Tab Groups are being removed from Firefox](https://support.mozilla.org/sv/kb/tab-groups-removal), so I see no point in doing anything here.
