### ISSUE TITLE
 More control on useful Firefox features: addon, download, private, upload files

### ISSUE THREAD

**Issue by ooker777** [akhodakivskiy/VimFx#324]
Especially download and upload feature. In Vimperator, we can open addon preferences, open download tab to open downloaded ones and see downloading's status. You can change dir to add picuture when you want to upload an avatar. All by pressing colon.

**Comment by lydell** [comment]
Added examples of how to open the Add-ons Manager, Preferences and Downloads to the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#open-a-specific-url) section of the wiki.

**Comment by ooker777** [comment]
wow, this rocks
