### ISSUE TITLE
Detect fancy custom text editors and enter the “auto-insert mode” there (was: Not detecting text-mode in Google Docs)

### ISSUE THREAD

**Issue by abello** [akhodakivskiy/VimFx#335]
Hello, 

I just noticed that I have to manually disable VimFx (by pressing 'i') when I'm editing a document in google drive. Even though the cursor is blinking, VimFx will still be on, hence interpret my keypresses as normal-mode commands. 

Is this happening to anyone else?

-Aleksander

EDIT by @lydell: Checklist:

- [ ] https://etherpad.mozilla.org/
- [ ] https://beta.etherpad.org/
- [ ] https://drive.google.com/
- [ ] http://wikibbs.net/index.php?mid=wikibbs2015&act=dispBoardWrite
- [ ] http://www.bandisoft.co.kr/board/honeyview/
- [ ] http://www.diychatroom.com/forum.php

**Comment by davidjb** [comment]
Fwiw, with the latest version on FF 43a02 with e10s enabled, I'm finding that if I type *anywhere* on a page (eg in this GitHub input field) my keystrokes are always interpreted as VimFx commands.  Trying to remember to type "i" first, even if my cursor and focus has entered the most plain of text boxes, is very hard -- and annoying when typing a word with an "r" in it causes that form I was editing to reload and progress lost.  It wasn't this bad originally -- certain pages like Google Docs etc didn't get detected but there were no issues on standard text boxes.

Same issue or different bug?

**Comment by lydell** [comment]
@davidjb Different bug. See #569.

**Comment by davidjb** [comment]
@lydell Thanks, details moved over there!
