### ISSUE TITLE
Ctrl-[ as escape key

### ISSUE THREAD

**Issue by raphonic** [akhodakivskiy/VimFx#347]
Hi,

I like using the Ctrl-[ to enter Normal mode since I don't have to leave home row and I think there are others too who prefer Ctrl-[ instead of Esc. It'd be nice if you could add Ctrl-[ as an additional Esc key.

Thanks.

**Comment by lydell** [comment]
For people who find this while searching: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/questions-and-answers.md#how-do-i-re-map-escape-which-blurs-text-inputs
