### ISSUE TITLE
Icon not visible in the menu

### ISSUE THREAD

**Issue by grn** [akhodakivskiy/VimFx#349]
# Problem
The VimFx icon isn't visible after adding VimFx to the menu.

# How to reproduce
1. install Firefox 30.0 (I'm on Debian Unstable)
2. install VimFx
3. customise the menu - add the VimFx icon
4. restart Firefox
5. open the menu - the icon won't be visible

**Comment by TheGreenHabi** [comment]
I think it might be related to this:
https://developer.mozilla.org/en-US/Firefox/Australis_add-on_compat
Known issues related to add-ons

    Adblock Plus, and other add-ons that have copied its toolbarbutton-insertion code, hide their toolbarbutton icon. They keep track of their insertion point by themselves.
    Even though our compatibility shims correctly insert these button initially, their detection code decides it is not in a toolbar (it is in fact in a customization target inside a toolbar, see above) and removes the icon on restart. This should be fixed within Adblock Plus and other add-ons using similar code patterns.
    NB: Adblock Plus has fixed its code in its latest version. Other add-ons might still be affected by this.

**Comment by TheGreenHabi** [comment]
Well, I looked at code and as far as I understood this is what happens.
There is no initialization of icon at startup, only when it needs to be updated - change of mode etc.
So at first there is no icon.

Also, I think icon should be added to chrome.manifest. At least, that's what I read in addon developers docs. It might help to solve this issue

But I know very little about all this, so take it with grain of salt and pinch of lemon)
