### ISSUE TITLE
. to repeat last command

### ISSUE THREAD

**Issue by RanSolo** [akhodakivskiy/VimFx#357]
using a period to repeat your last command is handy sometimes when doing multiple stroke commands like moving tabs.

**Comment by yeslsudarshan** [comment]
I'd like to see this feature too, not sure if this can be implemented as a custom command. I don't nearly have enough expertise to design a custom command for this. Useful situations for using the period key to repeat previous commands are for example nJ (move n tabs L), or deleting n tabs, scrolling down 5 lines etc. Would appreciate efforts to make this feature. Willing to help out with testing if necessary.

**Comment by lydell** [comment]
I don't see how `x...` is better than `xxxx` or `4x`. Likewise for `j...` vs `jjjj` or `4j`. etc.

**Comment by yeslsudarshan** [comment]
Well what I actually meant was regardless of what the previous command was, a period keypress would repeat the previous command. So for example if you press 4x once, you can reuse that with . next time until a new keypattern is pressed instead of pressing 4x everytime.

**Comment by lydell** [comment]
I can't see how repeating `4x` would be useful, though :)

This might be possible to implement as a custom command, by wrapping the `.run()` method of every command that you want to be repeatable and saving stuff there for `.` to use.

**Comment by yeslsudarshan** [comment]
Hmmm I see, that was just an example 4j or 4J would be other examples. 
Anyway, it is a really useful feature in vimperator and vim, so I thought I'd suggest it :).
Thanks for the suggestions.

**Comment by lydell** [comment]
If you can’t come up with a single real use case, then you don’t need the feature :)

**Comment by yeslsudarshan** [comment]
Well there's a difference in thought I guess, we can agree to disagree.
 Thanks for maintaining and growing this plugin, appreciate it.
