### ISSUE TITLE
How to override the style sheet?

### ISSUE THREAD

**Issue by pluser** [akhodakivskiy/VimFx#368]
Hi, I have a question.
I tried to use bigger font in hint markers, but I couldn't.
Maybe the reason is issue #168.
Is there any way to override the css?

**Comment by erjoalgo** [comment]
how would I change the font size within the config file?

**Comment by lydell** [comment]
Short answer: You don't.

Alternative answer: Load a CSS file from your config file, lik I do. https://github.com/lydell/dotfiles/blob/54e8708dc1d20f4a1b8501b36b98ce165b9ed51f/.vimfx/config.js#L177-L190
