### ISSUE TITLE
Integration with the NoScript addon

### ISSUE THREAD

**Issue by LemonBoy** [akhodakivskiy/VimFx#370]
It would be nice if VimFx could provide some hotkeys to enable/disable the filtering as it's a pain to reach the top corner with the mouse :)

**Comment by lydell** [comment]
The latest development version can now be extended by other add-ons making it possible too create a “VimFx-NoScript” add-on that integrates the two.

**Comment by lydell** [comment]
I’ve added this to the [integration wishlist](https://github.com/akhodakivskiy/VimFx/wiki/Other-Add-ons-that-integrate-with-VimFx) in the wiki.

**Comment by lydell** [comment]
I've added a [custom command](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#click-the-noscript-button) for clicking the NoScript button now.
