### ISSUE TITLE
Issues with making 'F' not a hint character

### ISSUE THREAD

**Issue by jalamar** [akhodakivskiy/VimFx#371]
Issue #1: Web page is scrolled to top when 'F' (not a hint character) is typed.
Issue #2: Hints appear to still be active.

To Reproduce: 
Edit preferences to remove 'F' from the "Hint Chars" list. Hit 'F' to bring up hints. Hit 'F' again. Web page is scrolled to top of page. Also, it appears that hints are still active, so scrolling back down with 'J' will result in going to the link pointed to by 'J'. The web page also seems to matter in reproducing this issue. For example, I can reproduce this issue on slashdot.org and when viewing google search results. I cannot reproduce this issue on espn.com.

Expected Results:
Similar to Vimium for Chrome - hitting 'F' removes the hints and does not scroll the page.

**Comment by lydell** [comment]
Fixed in 0.5.15.
