### ISSUE TITLE
Support multi-process Firefox and Firefox Developer Edition

### ISSUE THREAD

**Issue by akhodakivskiy** [akhodakivskiy/VimFx#378]
Per this Firefox bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1047615

Multi-process Firefox (e10s) introduction: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

Briefly: addons will run in separate processes wihtout direct access to the page DOM anymore. Frame scripts will be injected into the browser process, these scripts will have direct access to the DOM. The addon itself will have to use messages to communicate with the frame scripts.

While there is backward compatibility support it seems like either it's broken, or VimFx has an issues because it appears to make e10s hang. Going from here we would need to address the following points:

1. Investigate the hanging issue
2. Start a discussion regarding e10s support. Since all VimFx does is pretty much interfacing with the DOM (with basic processing for hints generation) running most of the code away from the <browser> process doesn't make much sense. Should we convert VimFx into the frame script? Or should we just rely on the backward compatibility layer that provides synchronous access to the DOM?

--

Edit by @lydell:

Fixing this will also fix problems in Firefox Developer Edition (and some recent Firefox versions), which are due to the shims Firefox uses for non-multi-process add-ons.

**Comment by hallabro** [comment]
Is this issue being looked into at the moment?

**Comment by lydell** [comment]
I've read lots about it and have started to form a plan on how to do it. But I can't say when it is going to happen. PRs welcome.

**Comment by lydell** [comment]
I will start working on this now.

**Comment by edrex** [comment]
Just a +1 that I'm using a self-built XPI from the latest HEAD with no problems so far.

**Comment by lydell** [comment]
Thanks for the confirmation, @edrex, that's really good to know. Stay tuned, the release is near!

**Comment by edrex** [comment]
:tada:

**Comment by lydell** [comment]
Today I got an email from AMO urging developers to support multi-process Firefox and saying that it is scheduled for release in the first quarter of 2016. Feels good already having implemented support for it :)
