### ISSUE TITLE
Catches Esc from urlbar, masks Firefox's fine default behaviour

### ISSUE THREAD

**Issue by lilydjwg** [akhodakivskiy/VimFx#380]
This happens in Fx 31 but not Fx 28.

After editing the URL in the urlbar, pressing Esc only blurs the urlbar. Expected behaviour is to restore the URL and the icon before it (I use extensions to get the old site icon display).

Disabling VimFx makes this disappear, and enabling it makes it reappear, so I think this is caused by VimFx, not some other extensions I've installed.

**Comment by lydell** [comment]
Fixed in 0.5.15.
