### ISSUE TITLE
missing command: go to url in PRIMARY selection

### ISSUE THREAD

**Issue by mauke** [akhodakivskiy/VimFx#382]
In Linux (or rather X11), there are two separate ways to copy text between applications, the CLIPBOARD and PRIMARY selections. See http://en.wikipedia.org/wiki/X_Window_selection#Selections.

I want to be able to double-click a url in the terminal (which selects it) and then hit `p` in VimFx to go to the url. Currently `p` always gets the text from the clipboard. I want to make it use the primary selection.

I think the best way to do that is to add a separate "navigate to address in primary selection" command; that way the existing default configuration doesn't change.

**Comment by darvelo** [comment]
I like the idea of using the 'selection' clipboard, but I also have vim configured to use the global clipboard for copy and pasting..  I don't mind pressing `<c-c>` to copy the selection buffer before using `p`, so could there be an option for which clipboard to use?

**Comment by Forever-Young** [comment]
+1 for option

**Comment by BohrShaw** [comment]
I don't like this inconsistency when switching between Windows and Linux.
When using Vim on Linux, it's a hassle to remember to copy to the register `*` to be able to `p` in Firefox.
I'm aware that I could `set guioptions+=a` in Vim. But I don't want that behaviour.
