### ISSUE TITLE
Higher resolution images for the button is needed

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#383]
In the “Customize” screen the icons are larger, causing VimFx’s 16x16 image to be upscaled and blurry.

**Comment by lydell** [comment]
@akhodakivskiy Could you contact Heidi and ask if there are higher resolution images we can get?

**Comment by akhodakivskiy** [comment]
Simon, we have 16x16, 32x32, and 128x128 icons. The latter is in the README.md, and in the extension resources folder - icon-large.png. I made 64x64 version by simple resizing:
![vimfx_64](https://cloud.githubusercontent.com/assets/145806/5826901/51a87bbc-a0ab-11e4-98c6-7ae17ca19ed5.png)

What size are you actually looking for?

**Comment by lydell** [comment]
I see. But we don't have high res versions of the red and grey versions do we?

> What size are you actually looking for?

I don't know yet. Need to look it up on MDN.

**Comment by TheGreenHabi** [comment]
Hi.
I found this info. Source:
https://developer.mozilla.org/en-US/Firefox/Australis_add-on_compat

Icon sizes in toolbars have changed, and you should ideally provide a larger icon for your add-on's buttons, should they exist, for use in the menu panel and customization area (palette). The new icon sizes are the same on all platforms and are:The menu panel can be targetted by selecting [cui-areatype="menu-panel"]. When in the customization area (palette), the button will be wrapped in a toolbarpaletteitem with a place attribute set to palette. Putting it all together, your updated CSS might look like this:

#my-addon-button {
    list-style-image: url(icon16.png);
}
#my-addon-button[cui-areatype="menu-panel"],
toolbarpaletteitem[place="palette"] > #my-addon-button {
    list-style-image: url(icon32.png);
}

/* High-resolution displays */
@media (min-resolution: 2dppx) {
    #my-addon-button {
        list-style-image: url(icon32.png);
    }
    #my-addon-button[cui-areatype="menu-panel"],
    toolbarpaletteitem[place="palette"] > #my-addon-button {
        list-style-image: url(icon64.png);
    }
}

    Toolbars:
    16px (32px @2dppx) without padding
    Existing 16px icons should display just fine, and won't be distorted or scaled (except for higher resolution displays).
    Menu panel/Customization area (palette):
    32px (64px @2dppx)
    Please note that smaller icons will be upscaled.

**Comment by TheGreenHabi** [comment]
Also we need to update to high-res icon16-blacklist.png and icon16-blacklist_inverse.png

**Comment by TheGreenHabi** [comment]
Okay. I made 3 different colors: normal, red and black&white and optimized png with tinypng.
![opimization](https://cloud.githubusercontent.com/assets/9500028/5864645/48de1a04-a28c-11e4-9a3c-2ba6c6e69e52.JPG)

Here are they. Sizes from 32 to 128
![icon32-bw](https://cloud.githubusercontent.com/assets/9500028/5864650/4f6c2942-a28c-11e4-8eaf-1f5b52d3efc6.png)
![icon32-normal](https://cloud.githubusercontent.com/assets/9500028/5864652/4f9013c0-a28c-11e4-96f7-90f321188de2.png)
![icon32-red](https://cloud.githubusercontent.com/assets/9500028/5864654/4f91e7cc-a28c-11e4-8260-33d89f22af80.png)
![icon64-bw](https://cloud.githubusercontent.com/assets/9500028/5864653/4f9112fc-a28c-11e4-80f3-c089cdb26427.png)
![icon64-normal](https://cloud.githubusercontent.com/assets/9500028/5864655/4f96d606-a28c-11e4-8313-a03bcebc5464.png)
![icon64-red](https://cloud.githubusercontent.com/assets/9500028/5864651/4f85319e-a28c-11e4-9afc-de21da904646.png)
![icon128-bw](https://cloud.githubusercontent.com/assets/9500028/5864656/4f9ab230-a28c-11e4-9e92-223a0067e0bd.png)
![icon128-normal](https://cloud.githubusercontent.com/assets/9500028/5864657/4f9d5c24-a28c-11e4-8cab-3a335245d322.png)
![icon128-red](https://cloud.githubusercontent.com/assets/9500028/5864658/4fa3e6e8-a28c-11e4-851e-a582f690981c.png)

**Comment by TheGreenHabi** [comment]
I will try to update code to accommodate changes for new highres icons and hi-dpi screens, but don't have very high hopes :)

**Comment by lydell** [comment]
Wow, thanks!

**Comment by TheGreenHabi** [comment]
BTW, it would be great if you could get your hands on original file. I think it was vector file. Maybe there will be need for 1024x1024 for future screens)))

**Comment by TheGreenHabi** [comment]
I'm reading specs on addons:
https://developer.mozilla.org/en-US/Firefox/Australis_add-on_compat

Here is interesting part:
We're changing the way toolbar buttons are added. While we've attempted to maintain some measure of backward compatibility, the following are deprecated and will be removed in the near future: the __toolbar.insertItem__ method, the __toolbar.currentSet__ property, and the __currentset__ attribute on toolbars. If possible, please stop relying on them. Instead, you should use the CustomizableUI module.

VimFx uses those methods.

**Comment by TheGreenHabi** [comment]
More useful info:
https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action#ActionButton%28options%29

https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action
In Firefox 36 there is new feature: badged buttons. It can be used for status updates of VimFx or to display mode of VimFx.

Just sharing ideas

**Comment by TheGreenHabi** [comment]
I have read a lot of documentation and cannot find a way to do this. It's just way over my head.
And it's not ok to use 32x32 as default, because toolbar max height is 18x18 and it makes toolbar larger in height.

I understand that there might be a way to ask Firefox where VimFx button is placed. In Toolbar or in new "Popup Sidebar" of Firefox and what size of icon browser is asking for.
So it would be possible to modify this code in button.coffee from this

```coffeescript
iconUrl = (kind) ->
  url = utils.getResourceURI("resources/icon16-#{ kind }.png").spec
  return "url(#{ url })"
```
to something like this

```coffeescript
iconUrl = (kind) ->
  url = utils.getResourceURI("resources/icon#{ size }-#{ kind }.png").spec
  return "url(#{ url })"
```

But I just have not found a way to do this.

Also, icon in VimFx/extension/icon.png
should be updated to 64x64
