### ISSUE TITLE
Return to Default Find Behaviour Not Possible

### ISSUE THREAD

**Issue by the-solipsist** [akhodakivskiy/VimFx#390]
I've removed the VimFx shortcuts ["C-f" (scroll full page down)](https://github.com/akhodakivskiy/VimFx/issues/186), "/", "n", "N" (all relating to Find), hoping that that would restore the default Firefox behaviour relating to Find, but no such luck.  The regular Firefox Find function allows you to press "Enter/Return" to go to the next instance of a found string (instead of closing the input box and having to press "n").  I want that functionality back.

I even tried going into insert mode, and then pressing C-f.  However, upon pressing C-f, VimFx goes out of insert mode.

How do I get the default Find back without disabling VimFx, which is a fantastic add-on?

**Comment by cheflo** [comment]
Hi,
Has there been any progress on this issue? I am really enjoying VimFx, but would like to revert to the default find behaviour if possible.

Cheers

**Comment by cheflo** [comment]
sorry missed the commit
