### ISSUE TITLE
ESC not working on bookmark dialog

### ISSUE THREAD

**Issue by loonies** [akhodakivskiy/VimFx#393]
VimFx 0.5.14, Firefox 32

Steps:
- Invoke bookmark page dialog (`CTRL+d`)
- Pressing ESC will not close dialog

Workaround:
- Invoke bookmark page dialog (`CTRL+d`)
- Focus previous "arrow" (`SHIFT+TAB`)
- Pressing ESC will now close dialog

ESC should close bookmark page dialog no matter what element is focused.

**Comment by lydell** [comment]
Fixed in 0.5.15.
