### ISSUE TITLE
"search hit BOTTOM, continuing at TOP" notification feature

### ISSUE THREAD

**Issue by willemw12** [akhodakivskiy/VimFx#398]
Feature request:
Notify the user when a forward or backward search has reached the bottom or top of the page, similar to the "search hit BOTTOM, continuing at TOP" and "search hit TOP, continuing at BOTTOM" notifications in vim.

**Comment by lydell** [comment]
I think this is best solved by adding a general notifications system to VimFx, using standard [`Notification`](https://developer.mozilla.org/en-US/docs/Web/API/Notification)s, and then let the Find commands use that (copying the output, and possibly the icon, in the findbar).
