### ISSUE TITLE
VimFx does not work on mimetypes text/xml or application/xml

### ISSUE THREAD

**Issue by nbeaver** [akhodakivskiy/VimFx#401]
VimFx version: 0.5.14
Firefox version: Iceweasel 31.1.0
keyboard layout: us
operating system: Debian Linux

VimFx does not work on these sites:

http://www-sop.inria.fr/marelle/tralics/htralics-rr.xml
text/xml
Standards compliance mode
windows-1252

https://www.senate.gov/legislative/LIS/roll_call_lists/vote_menu_112_1.xml
application/xml
Standards compliance mode
UTF-8

http://greenbytes.de/tech/tc/httpcontenttype/httpcontenttype.xml
application/xml
Standards compliance mode
windows-1252

ftp://ftp.fu-berlin.de/doc/rfc/authors/rfc6502.xml
text/xml
Standards compliance mode
windows-1252

It appears that the text/xml and application/xml mimetypes are the commonality,
since sites that use e.g. the application/xhtml+xml mimetype work just fine.

http://jblevins.org/log/xml-tools
application/xhtml+xml
Standards compliance mode
UTF-8

**Comment by lydell** [comment]
Will be fixed by #512.
