### ISSUE TITLE
Window commands missing

### ISSUE THREAD

**Issue by morphles** [akhodakivskiy/VimFx#402]
It seems VimFx has absolutely no support working with windows. At work I do not use tabs at all (though firefox tryies to make it as hard as possible), so support for bindings to open links in new windows would be needed, or maybe just an option to switch commands "oppend in new tab" to "open in new window".

**Comment by haxwithaxe** [comment]
i'd like the same ability for the same reason. i'd like to use a single unified window managemnet rather than similar tab management per application. i've been using uzbl but it has issues with many google services. what would really be cool is a fully exposed interface to firefox's controls that we can map key combos to, but i realize that is likely way more work than anyone is going to be willing to do any time soon :)

**Comment by lydell** [comment]
I see. Since I only use one window, all I can say for now is: PRs welcome.

One thing I'd like to add, though, is the ability to extend VimFx with another extension. Imagine a "window commands for VimFx" extension.

**Comment by lydell** [comment]
It was decided in #493 that we should a a Windows category of commands in addition to the Tabs category.

Please help by listing the commands _you_ actually _need_ and suggest default shortcuts for them!

**Comment by lydell** [comment]
Possibly:

- `gF`: Open link in new window
- `w`: New window
-`W`: New private window
- `gw`: Move tab to new window
- `q`: Close window
- `Q`: Restore window

**Comment by sumit0190** [comment]
The defaults suggested look reasonable enough to me. But I wasn't aware of a 'restore window' functionality in Firefox. If I quit a window (regular or private), I see no way of restoring it back with all of its tabs. The pages visited in the now-gone window (if it was a regular one) do appear in the history, but clicking on those items restores the pages in the present window.

**Comment by morphles** [comment]
I also agree that suggested commands seem to cover all what I can think of currently. Though maybe I'd like window closing to be a bit more involved maybe two keystrokes or modifier + q. But of course one can live with single letter:).

**Comment by lydell** [comment]
Just realized that we shouldn’t add a command to close the window. Every operating system already has one, and many people customize it (I use super+q). Why learn a different way to close Firefox windows when you could use your existing muscle memory? Also, as @morphles points out, there’s a great risk such a command make more damage than good.

**Comment by tecepe** [comment]
Is it possible to add a shortcut to reopen a window, similar to what we have for tabs? For now, what I'm doing is: opening a new window and using the history the reach the last website visited.

**Comment by lydell** [comment]
In the "History" menu there's a "Recently Closed Windows" sub-menu. From there, you can choose which window to restore. That menu also tells me that `<c-s-n>` is the default Firefox shortcut for restoring the most recently closed window. It is possible create custom VimFx commands that use these features. You need to figure out what code they use, and then use VimFx's tab commands as inspiration:

- `X`: https://github.com/akhodakivskiy/VimFx/blob/c8fa3c5351462fc043c3bbb5c34c10e9c25dbe00/extension/lib/commands.coffee#L401
- `gX`: https://github.com/akhodakivskiy/VimFx/blob/c8fa3c5351462fc043c3bbb5c34c10e9c25dbe00/extension/lib/commands.coffee#L411

**Comment by interleaved** [comment]
FTR for this PR if someone also searchig for these commands. I added two custom commands to the wiki: [Close Window](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#close-window) and [Minimize Window](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#minimize-window).
