### ISSUE TITLE
Feature: Auto follow mode on given urls by regex

### ISSUE THREAD

**Issue by erjoalgo** [akhodakivskiy/VimFx#408]
When I perform a google search, I proceed 99% of the time to open one or more links, so I would like for follow-mode to be activated automatically. 

Let the user provide a list of url-regexes (similar to the blacklist url-regex list):

"https://www.google.com/search?q=.*"

where follow-mode should be automatically activated when the page is first loaded without the need to press  eg. 'f'.

**Comment by hyiltiz** [comment]
It would be nice to see it!

**Comment by lydell** [comment]
In the latest development version you could add the following into a [config file](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/config-file.md):

```js
vimfx.on('load', ({vim, location}) => {
  if (location.hostname === 'example.com') {
    vim.window.setTimeout(
      () => vimfx.modes.normal.commands.follow.run({vim}),
      1000
  }
})
```
