### ISSUE TITLE
Make hint generation faster (possibly by pre-computing them in the background) 

### ISSUE THREAD

**Issue by erjoalgo** [akhodakivskiy/VimFx#409]
Pre-compute hints in the background whenever the visible part of the document changes, to be able to provide near-instant display of the available link-hints.

**Comment by erjoalgo** [comment]
@lydell Why do you think this is not possible?

**Comment by lydell** [comment]
Because I cab't think of any way to do it. However:

> to be able to provide near-instant display of the available link-hints.

That is true in the develop version. So I don't think this issue is very relevant anymore.r

**Comment by erjoalgo** [comment]
I'm running the latest development version and the link generation is still painfully slow, particularly for sites with a large number of links. If you have facebook, you can try scrolling down a few pages in your news feed and then asking for hints. On my machine, this actually takes a few *seconds*, I suppose because it's generating hints for all the links which are not even visible on the page, which is a huge performance bug.

Also, "can't think of any way to do it" doesn't mean it can't be done.

**Comment by lydell** [comment]
But you still notice a major improvement compared to 0.5.17, don't you? I do, at least.

> I suppose because it's generating hints for all the links which are not even visible on the page, which is a huge performance bug.

Sorry, but that pisses me off. I've spent weeks on improving the hints feature. In fact, I think all code used for it today is written by me. So I can tell you for sure that we're definitely _not_ generating hints for elements not visible. (If you think about, you can verify this yourself: If we did you'd notice the hints being very long for no reason.) In fact, in the develop version we use a super-fast Firefox API that returns all elements in the current viewport so we don't even touch elements outside the screen.

> Also, "can't think of any way to do it" doesn't mean it can't be done.

Of course, but that doesn't stop me from thinking it's impossible (with the APIs available today) ;)

But don't get me wrong now, I'm open for discussion and would love to be proven wrong :)

**Comment by erjoalgo** [comment]
Sorry. But on my machine, it usually takes at least second, and sometimes more to generate the hints, and that's very annoying.  I appreciate that you put effort on the code and on optimizations, but I'm sure there's more that can be done. My machine is not very powerful but it still should not take seconds to display hints. I'm not familiar enough with the problem now but if I have time I will try to contribute (or fork)

**Comment by lydell** [comment]
**But you still notice a major improvement compared to 0.5.17, don't you? I do, at least.**

> it usually takes at least second, and sometimes more to generate the hints, and that's very annoying

Yes, that’s very annoying.

> I'm sure there's more that can be done.

So am I.

> I will try to contribute (or fork)

Don’t worry, you wouldn’t have to maintain a fork. Such a contribution would be merged straight away :)

**Comment by erjoalgo** [comment]
I think that, at least in the version I'm using, link hints is O(n) with respect to number of links in the page. Try 
https://www.gnu.org/software/bison/manual/bison.html#Introduction
In my machine (a much more powerful one than the one I normally use), it takes about one second, even if the number of links actually visible on the page is a small number. The page is a very simple html with not much javascript.

(Like I said previously, I might have time to work on this issue, but I guess not at the moment)

**Comment by lydell** [comment]
I’ve started experimenting with generating hints in two passes. The results so far generate most hints at half the time, and the rest show up after the same time as now. Hopefully, this will be a successful experiment.

**Comment by lydell** [comment]
The experiment turned out to be successful. On many pages, the hint generation feels twice as fast now. However, the https://www.gnu.org/software/bison/manual/bison.html#Introduction is still a slower example because of the huge amount of links. I’ll try this out on the develop branch for a while before making a release.

**Comment by lydell** [comment]
A few facts:

- This issue has been open for one and a half years and not seen much activity.
- I’ve thought about to and from since it was opened.
- VimFx 0.15.0 scratches my itch: On the pages where I felt VimFx was slow it isn’t anymore. (Even though things are not perfect and VimFx still _can_ be “slow” on some pages.)
- Nobody has stepped up to help with this issue, or even suggest an algorithm.

So I’m going to close this one. That doesn’t mean that there never will be any more improvements to the hints, though. I’m constantly on the lookout for performance improvements. I just don’t think this issue serves a purpose anymore.

**Comment by erjoalgo** [comment]
As the one who originally opened this issue, thank you for taking the time to consider it and make improvements. I was originally hoping to try to contribute myself, but never got around to it. I've since upgraded most of my hardware so I don't notice issue as much, and I suspect this new experiment will make it even less noticeable. I'd love to contribute to this wonderful project so I'll keep an eye and try to offer help if needed.
