### ISSUE TITLE
Evernote webapp is broken with vimfx

### ISSUE THREAD

**Issue by pva** [akhodakivskiy/VimFx#416]
After I've installed vimFx it is impossible to edit subject reliably in evernote http://evernote.com/ webapp. For example:

I press to create new note, put cursor to subject line enter few words. After that it is expected that note (even with empty body) will be saved, but instead if I select another note this note disappears line nothing was entered. There are many more workflows that are broken due to this and basically Evernote is unusable with VimFx at the moment.

Firefox 33.0. VimFx 0.5.14
I don't think this is regression.

**Comment by TheGreenHabi** [comment]
Hello. I checked topic issue. Win 8.1, Firefox 36 beta, VimFX dev channel 2015-01-21 build. I cannot replicate this problem. Everything works as expected. Notes are saved etc
