### ISSUE TITLE
Key shortcut of 'disable vimfx' can't work in version 34

### ISSUE THREAD

**Issue by CommonCarp** [akhodakivskiy/VimFx#432]
The shortcut `shift-alt-v` cannot work properly in version 34. It just activate `View Menu`. Hope fixed soon.

**Comment by lydell** [comment]
The whole disable feature might be removed; see #327. It would be very interesting to know how/why you use this feature.

**Comment by CommonCarp** [comment]
I have glanced over #327, you have already summarized my need in comment: To use website shortcuts (which may use `Esc`, especially quit input box of some websites) but not quit insert mode by typing `Esc`. 
For another reason, sometimes I will be away from keyboard, I prefer a key shortcut to disable VimFx in ALL TABS rather than do it by entering addons tabs or keep a button in tool bar.(lazy...)
BTW: I suggest 'the mode status' could display in address bar or by a floating frame or any other ways, not only by a button. Not easy to focus among buttons and no button state.
