### ISSUE TITLE
Hint keys do not support umlauts.

### ISSUE THREAD

**Issue by rdinse** [akhodakivskiy/VimFx#433]
There appears to be a text encoding issue with the hint keys. I have added an "ö" to the list, however the hints display this key as Ã or ¶ and ö key presses do not get recognized.

**Comment by lindhe** [comment]
Will this also mean that ö can be used as a shortcut key? Or is it just support for the lables?

**Comment by lydell** [comment]
ö can be used as a shortcut key in the development version.

**Comment by lindhe** [comment]
I'm glad to hear that. jklö is the new hkl :D

**Comment by lindhe** [comment]
I just made a build off of the most recent version of the develop branch (at 0a1fbee), and bound ö to "Next tab", but it does not seem to work.

**Comment by lydell** [comment]
That’s _not_ the latest commit at the develop branch. And it works for me. Try the latest commit. If that does not work, please provide more information.

**Comment by lindhe** [comment]
Lol, never mind. I'm a dummy. I synced my forc with my fork, not with your repo. It works great, good work! ;)
