### ISSUE TITLE
Page marks like Vimium

### ISSUE THREAD

**Issue by eush77** [akhodakivskiy/VimFx#434]
One feature I miss from Vimium is its `Marks.activateCreateMode` and `Marks.activateGotoMode` commands (`m` and `｀ ` keys, respectively).

The former would bind the position on the page to a character, and the latter would jump (or scroll) to that position.

Any chance of implementing this feature in VimFx?

**Comment by ikhthiandor** [comment]
Any pointers on how this can be implemented? I'm curious to know.

**Comment by lydell** [comment]
Add a `marks` object to [`vim.state`](https://github.com/akhodakivskiy/VimFx/blob/8d5fc55f14f24846dcb8b9a4546437d31be47ae7/extension/lib/vim-frame.coffee#L44).

Make the `m` command save the current `document.documentElement.scrollTop` (note `document.body?` needs to be used in quirks mode) for the requested mark in `vim.state.marks[mark]`.

Make the `` ` `` command look into `vim.state.marks`. If the requested mark exists there, scroll to the saved position.

The `m` command probably needs to enter its own mode to be able to capture the next key press (and then return to normal mode).

**Comment by lydell** [comment]
@eush77 When starting to implement this I realized that Vimium also has _global_ marks, which you did not mention. They are way more complicated to implement, so I now wonder if they're worth the trouble? Can anyone come up with a good use case for them?

**Comment by eush77** [comment]
@lydell I didn't use global marks and I don't find them as useful as local marks. I think that situations in which are useful are quite esoteric and don't come up as often. I would be happy to limit this feature request to local marks specifically.

**Comment by BohrShaw** [comment]
@lydell 
> They are way more complicated to implement.

Then, maybe ignore it for now.

> I now wonder if they're worth the trouble?

I actually only recently started to utilize global marks quiet often in Vim and I say it's valuable to a non-simple workflow. But it does require _manual_ marking before hand, which is similar and more powerful to the purpose of tab arrangements in the browser.
However, in my current web browsing workflow, I generally only keep several tabs. So global marks is not as useful as in Vim.

**Comment by BohrShaw** [comment]
@lydell I'm used to hit `''` to jump to the location before the last jump. So I would map `'` to `` ` `` after this feature is implemented. But can I map a key to the native `'` then?

**Comment by lydell** [comment]
@BohrShaw Thanks for confirming thata Vimium-style markers are not needed (at least for now). 

Regarding your question, you'd either have to add a custom command, or use `I'`. Perhaps we should add `g/` as an alias to `'` by default in VimFx, though.

**Comment by BohrShaw** [comment]
@lydell I've just tried this feature but ``` `` ``` jumps to the position *after* executing a jumping command like `G`. The mark `` ` ``(and probably also `'`) should be set *before* `G`, `gg`, `n`, etc.

**Comment by lydell** [comment]
@BohrShaw As always, please provide Firefox version, multi-process enabled, OS. I can't reproduce.

(Also, there is no `'` mark.)

**Comment by BohrShaw** [comment]
Firefox 42.0 without multi-process on Windows 10.
