### ISSUE TITLE
Youtube Play-Stop with Spacebar

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#442]
VimFx shorcut _Scroll full page down_ [Spacebar] interferes with Youtubes play-stop with spacebar. In traditional and fullscreen modes

**Comment by lydell** [comment]
Could you add the following after [this line](https://github.com/akhodakivskiy/VimFx/blob/6ba3eb88e883d330e90adfd4b1e2e5cef7deebcf/extension/lib/commands.coffee#L154):

```coffee
  console.log event.target
```

Then press `<space>` when you expect it to toggle play/pause on YouTube and report what was logged to the console.

**Comment by TheGreenHabi** [comment]
What I did:
1. Changed code, built VimFx, updated, restarted Firefox
2. Restored shortcut for _Scroll full page down_ to <space>
3. Opened console, youtube video fullscreen and pressed spacebar. I have YouTube Center script for GreeseMonkey. It has shortcuts. If I have shortcut for VimFx set to spacebar it doesn't log anything. If I remove it, I see this

"[Player Listener] Event onStateChange was called with" Array [ 1, 1 ] YouTubeCenter.js:2022:25
"[Tab Event] Calling player.pauseVideo();" YouTubeCenter.js:2022:25
"[Title Listener] "title" => "title"" YouTubeCenter.js:2022:25
"[Title Listener] "title"" " => "title"" "" YouTubeCenter.js:2022:25
"[Player Listener] Event onStateChange was called with" Array [ 2, 1 ] YouTubeCenter.js:2022:25

**Comment by lydell** [comment]
Did you look in the _browser_ console? (Not the web console.)

**Comment by TheGreenHabi** [comment]
I had no idea they are different) Live and learn.
Here is log:
```
"[Player Listener] Event onFullscreenChange was called with" Array [ Object ] YouTubeCenter.js:2022:25
<div class="ytp-button ytp-button-play" role="button" tabindex="6000" aria-label="Play"> commands.js:183
<div class="ytp-button ytp-button-play" role="button" tabindex="6000" aria-label="Play"> commands.js:183
<div class="ytp-button ytp-button-play" role="button" tabindex="6000" aria-label="Play"> commands.js:183
"[Player Listener] Event onFullscreenChange was called with" Array [ Object ] YouTubeCenter.js:2022:25
```

I pressed spacebar 3 times

**Comment by lydell** [comment]
Thanks. I'll see what I can do.

**Comment by TheGreenHabi** [comment]
If you need anything to test, I'm glad to help
