### ISSUE TITLE
No hints on http://pixologic.com/blog/pixologic-news/

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#444]
Hi!
Just noticed that hints are not generated and displayed for this urls:
http://pixologic.com/blog/pixologic-news/
http://pixologic.com/blog/category/zbrush-industry/3d-printing/

On the main page:
http://pixologic.com/
they are displayed

Though other functionality of VimFx works (reload, tab switching etc)

Also, at once I had a moment of hints displayed on http://pixologic.com/blog/pixologic-news/ and then I think I pressed escape and tried to display them again and they would no longer display.

VimFx dev build 2015-01-21, Firefox beta 36, Win 8.1

UPD:
OK, hints are generated if I press "f" while page is still loading. But when it finished loading hints are no longer displayed. But this trick is not stable. Doesn't always work

**Comment by lydell** [comment]
I can’t reproduce this.

**Comment by TheGreenHabi** [comment]
Oh well. It's not that important )

**Comment by TheGreenHabi** [comment]
I think I found problem.
At first, I thought I used VimFx dev build 2015-01-21 but it silently updated to 0.5.16 and I found this only when tried "Go to the first non-pinned tab" and it didn't work. I'm like: where this function disappeared? And then I saw that I use 0.5.16.

Just updated to dev build 2015-01-22. Hints are working now. Maybe this bug related to 0.5.16. Anyway, no issue now.

**Comment by TheGreenHabi** [comment]
I'm closing the issue as if there is any problem in current stable build it's already fixed in dev

**Comment by lydell** [comment]
We shouldn't have closed this so quickly. However, it is tracked in #447 now.
