### ISSUE TITLE
Search for selected text with default search engine

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#445]
I think it would be very useful to search for selected text with default search engine by simple press of a key customizable in VimFX.
BTW, I really like how easy it's to configure VimFX)

**Comment by lydell** [comment]
Well, if your system has a “selection” clipboard, you could just select the text and press `p` or `P`.

**Comment by TheGreenHabi** [comment]
It works if I copy selection into clipboard first. Thanks for tip. Anyway, it would be great to have one extra step removed)

**Comment by lydell** [comment]
That’s what I meant with a “selection” keyboard. Selecting text is enough to copy. Many GNU/Linux distribution have this feature (but not Windows).

**Comment by TheGreenHabi** [comment]
Oh. Nice feature) It's bad Windows doesn't have this

**Comment by lydell** [comment]
Added to the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#search-for-the-selected-text) section of the wiki.
