### ISSUE TITLE
Google Groups causes VimFx to fail in several Google apps

### ISSUE THREAD

**Issue by abastardi** [akhodakivskiy/VimFx#446]
As of sometime today, VimFx no longer works in Gmail, Google Calendar, or Google Groups. Specifically, it seems that hitting the "f" key causes VimFx to completely stop working on these sites (using other VimFx shortcuts does not appear to cause any problems).

I have used VimFx successfully in all of these web apps for several months (including most of today). This problem just arose in the last couple hours. I am using Firefox 35.0 on Windows 8.1. I also checked on a completely separate Windows 7 machine with a fresh install of VimFx in a Firefox that has no add-ons, and the same problem occurred.

Perhaps the Google apps code was recently updated and now causes some interference with VimFx. Note, there is no problem with Vimium on Chrome.

Initially, the problem appeared only in Google Groups, but now Gmail and Google Calendar are affected as well.

**Comment by lydell** [comment]
VimFx version?

**Comment by lydell** [comment]
Closing in favor of #447.
