### ISSUE TITLE
Cannot follow link on http://uniqlo.com

### ISSUE THREAD

**Issue by izzyleung** [akhodakivskiy/VimFx#448]
Version of VimFx: 0.5.16

Description:
I can press `f` or `F` to follow a link on the page when the page is still loading.
However, when the page finishes loading, and when I press `f` or `F, it will enter search page mode with the search box when pressing `cmd + F` popping up.

It happened with some Google search page as well. And it has never happened to me before the update before 0.5.16.

**Comment by lydell** [comment]
Duplicate of #447.
