### ISSUE TITLE
Bug: No request for Firefox restart after VimFx installation

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#453]
VimFx installation behaves like restartless addon, but Firefox need to be restarted for VimFx to work
_VimFx dev build 2015-01-23, Firefox 36 beta, Win 8.1_

**Comment by lydell** [comment]
It does?

**Comment by TheGreenHabi** [comment]
Just checked again. My fault. It seems icon just disappears if I update, but it works. If I delete, restart Firefox and then install VimFx it works right away.
