### ISSUE TITLE
Focus/Move tab left/right bug with ctrl+number shortcuts

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#459]
Problem test:
Test 1:
I have 5 pinned tabs, 6 unpinned
I try to move current active tab positioned as last one with `gJ - Move tab left`
I press once `gJ` and it moves to be first one after 5 pinned tabs, or to position number 6 from left.
I can move it farther back with `gJ`, it moves skipping one pinned tab, Position -2 or to be 5th from left.
If I try to move it forward, it stops after 5 pinned tabs in unpinned state and I can't move it farther to the right.

Test 2:
I have 5 pinned tabs, 7 unpinned
I try to move last one with `gJ - Move tab left`
I press once `gJ` and sometimes current tab moves to be second one after 5 pinned tabs, or to position number 7 from left.
I can move it farther back with `gJ`, it moves skipping one pinned tab, Position -2 or to be 5th from left.
If I try to move it forward, it stops after 5 pinned tabs in unpinned state and I can't move it farther to the right.

P.S. Why it was decided to make command_close_tab behave differently in pinned tabs and not close them?

**Comment by lydell** [comment]
Your tests are too complicated to understand :) Could you please write what was expected in each case and what actually happened.

> P.S. Why it was decided to make command_close_tab behave differently in pinned tabs and not close them?

#77.

**Comment by TheGreenHabi** [comment]
In another words:
I expect current tab to be moved to left (current position -1) with `gJ - Move tab left`. But instead it skips like 5 tabs and moves current tab to (current position -5). If I try to move if forward, I cannot do this. It simply doesn't work. And if current tab is right after pinned tab and I move it with `gJ` it skips one pinned tab and moves to (current position -2)

**Comment by TheGreenHabi** [comment]
I think problem is here:
```helper_move_tab.bind(undefined, -1)``` sends args to
```helper_move_tab = (direction, vim, event, count)``` and index is calculated with 
```index = absoluteTabIndex(direction * count, gBrowser)```
Order of arguments in ```helper_move_tab.bind(undefined, -1)``` looks incorrect to me


```coffeescript
helper_move_tab = (direction, vim, event, count) ->
  { gBrowser }    = vim.rootWindow
  { selectedTab } = gBrowser
  { pinned }      = selectedTab

  index = absoluteTabIndex(direction * count, gBrowser)

  if index < gBrowser._numPinnedTabs
    gBrowser.pinTab(selectedTab) unless pinned
  else
    gBrowser.unpinTab(selectedTab) if pinned

  gBrowser.moveTabTo(selectedTab, index)

# Move the current tab backward.
command_tab_move_left = helper_move_tab.bind(undefined, -1)
```

**Comment by TheGreenHabi** [comment]
BTW, why is there need to calculate ```helper_switch_tab.bind(undefined, +1)``` and ```absoluteTabIndex``` etc ?
I found method that switches between tabs without all that:
https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Tabbed_browser#Changing_active_tab
```coffeescript
command_tab_move_left = (vim) ->
  { gBrowser }    = vim.rootWindow
  gBrowser.tabContainer.advanceSelectedTab(-1, true);
```
And other methods like:
`command_tab_first`, `command_tab_first_non_pinned`, `command_tab_last` are not using this helper anyway

**Comment by lydell** [comment]
`gBrowser.tabContainer.advanceSelectedTab` only works with `+1` and `-1`, unfortunately. We need any number.

**Comment by TheGreenHabi** [comment]
I just noticed, that there is certainly some king of problem. Not only for moving tabs, but also for switching between tabs. Sometimes when switching quite a few tabs are skipped

**Comment by lydell** [comment]
Are you sure that you’re not using counts by mistake? Such as `5J` or `5gJ`?

**Comment by TheGreenHabi** [comment]
Certainly not. I can record video if you want. Most of the time this happens when I jump to tab by cntrl+number, then move to the right, wrap around, go through pinned tabs and usually jump occurs right after pinned tabs or close to that

**Comment by lydell** [comment]
Are you sure that you’re not using counts by mistake? Such as `5J` or `5gJ`?

> Problem test:
> Test 1:
> I have 5 pinned tabs, 6 unpinned
> I try to move current active tab positioned as last one with gJ - Move tab left
> I press once gJ and it moves to be first one after 5 pinned tabs, or to position number 6 from left.

Just tried this. `gJ` moves the active (last) tab once to the left as expected.

> Test 2:
> I have 5 pinned tabs, 7 unpinned
> I try to move last one with gJ - Move tab left
> I press once gJ and sometimes current tab moves to be second one after 5 pinned tabs, or to position number 7 from left.

Just tried this too. `gJ` always moves the active (last) tab once to the left as expected.

> I expect current tab to be moved to left (current position -1) with gJ - Move tab left. But instead it skips like 5 tabs and moves current tab to (current position -5).

Your expectation is correct. What you expect to happen happens for me. I cannot reproduce what happens for you.

> If I try to move if forward, I cannot do this. It simply doesn't work.

Cannot reproduce this.

> And if current tab is right after pinned tab and I move it with gJ it skips one pinned tab and moves to (current position -2)

In this case, yes one pinned tab is “skipped”, but the moved tab is not moved to index `current - 2`: it is moved to `current - 1`, as expected. If you have 5 pinned tabs and a sixth unpinned and press `gJ` on the unpinned tab it will move from index 6 to index 5, which results in 6 pinned tabs. Nothing wrong here in my opinion.


> Order of arguments in helper_move_tab.bind(undefined, -1) looks incorrect to me

Why? It does not look wrong to me.

> For now the best way to reproduce it is to jump to any tab with control+[number] (like cntrl+5) and then to start switching between tabs. Especially if it's a tabs that are close to pinned tabs.

Finally something I can reproduce! This is not just the _best_ way to reproduce it, it is _the_ way to do it. I guess this has to do with us relying on `gBrowser._numPinnedTabs`—that property probably starts with an underscore for a reason. This needs investigation.

**Comment by TheGreenHabi** [comment]
> Just tried this. gJ moves the active (last) tab once to the left as expected.

I tried to replicate it in new Firefox window with new tabs, it worked as expected. Then I added pinned tabs, it worked too. This left me very puzzled, because now I have same setup and different results.

I found a way to replicate this.
My main window have tabs, pinned tabs and __tab groups__!
If I create new window, create some tabs (even empty), then go to tab groups and create a new tab group with some tabs it doesn't work! So the problem is __tab groups__.

**Comment by lydell** [comment]
> gBrowser._numPinnedTabs—that property probably starts with an underscore for a reason. This needs investigation.

That's probably a red herring. I think U what the problem is now: Since there's a number in ctrl+number, VimFx thinks that you've used a count. I'll fix it this afternoon; it's very simple.

> So the problem is related to tab groups.

No. I haven't tested yet, but if there's a problem with tab groups it is a _different_ issue.

**Comment by lydell** [comment]
I believe I have fixed this now. Feel free to open a new issue about tab groups if needed and you know more about it.

**Comment by TheGreenHabi** [comment]
Thank you. No problems  with switching between tabs anymore. I will open a new issue regarding tab movement
