### ISSUE TITLE
Bugged tab movement in window with tab groups

### ISSUE THREAD

**Issue by TheGreenHabi** [akhodakivskiy/VimFx#462]
How to replicate:
1. Open new window
2. Add tabs (4-6, they can be empty)
3. Add tab group in newly opened window
4. In new tab group add tabs (4-6, they can be empty)
5. Move last tab to the left with `gJ`. Movement skips few tabs
6. Move currently active tab to the right with `gK`. No movement at all

**Comment by lydell** [comment]
[Tab Groups are being removed from Firefox](https://support.mozilla.org/sv/kb/tab-groups-removal), so I see no point in doing anything here.
