### ISSUE TITLE
Problem in the inline rich html editor (XpressEditor)

### ISSUE THREAD

**Issue by noisia04** [akhodakivskiy/VimFx#466]
1. go to any site which is using “XpressEngine” CMS
2. click [write] button or add comment using WYSIWIG editor (XpressEditor)
3. trying to write some text in the WYSIWIG editor
4. VimFX's keyboard shortcuts are works, and maybe your text is wiped out

**Comment by lydell** [comment]
Could you please give a URL to such a site?

**Comment by noisia04** [comment]
http://wikibbs.net/index.php?mid=wikibbs2015&act=dispBoardWrite
(please don't upload posts. that board can't delete your posts.)

**Comment by lydell** [comment]
Thanks. Note to self: The editor is a `<body style="font-size: 12px;" class="xe_content editable"><br></body>` inside an iframe.

**Comment by noisia04** [comment]
another XE board.
http://www.bandisoft.co.kr/board/honeyview/

**Comment by bobobox** [comment]
Having a similar problem with this board which is (I think) vBulletin: http://www.diychatroom.com/forum.php

Attempting to reply via inline WYSIWYG editor box results in keystrokes interpreted as VimFx commands

**Comment by lydell** [comment]
Merging into #335.
