### ISSUE TITLE
Scrolling commands conflict with the FireGesturess addon

### ISSUE THREAD

**Issue by noisia04** [akhodakivskiy/VimFx#469]
i using [VimFX] and [FireGestures] extension in my firefox. and, i found little conflict between two extensions. if i using vimfx's navigating features(scroll up or down) in the page, then firegestures's [ScrollTop] or [ScrollBottom] feature doesn't work. and after page refresh, firegesture's features are works again.

**Comment by lydell** [comment]
The scrolling commands will soon be re-implemented: see #461. Let’s revisit this issue when that has been merged.

**Comment by lydell** [comment]
The scrolling commands have now been re-implemented. Would you like to test the latest development version?

**Comment by TheGreenHabi** [comment]
Hi @lydell!
I recently updated my VimFx to latest development version.
My Firefox version is: 40.0a2 (2015-06-28) Developer Edition, and Windows 8.1
Now I experience inconsistent behavior of scrolling. Some websites scroll very slowly and other scroll by few pages.

**Comment by lydell** [comment]
Thanks for testing it, @TheGreenHabi. If you find steps to reproduce your scrolling issues please open an issue for it.
