### ISSUE TITLE
type 'gi' to focus the first entry on the web page

### ISSUE THREAD

**Issue by xiangxw** [akhodakivskiy/VimFx#47]
vimium and Vimperator both have this shortcut.

**Comment by lydell** [comment]
'gi' has been implemented in the develop branch now. If you’re tired of waiting, go grab and build it!

**Comment by eproxus** [comment]
Any estimate on when this will land in stable?

**Comment by lydell** [comment]
No. Every time I’ve made an estimate I have failed to live up to it. All I can say is that after the next version has been published we’ll switch to a more rapid release cycle. The next version will be the last “big” update.

**Comment by eproxus** [comment]
:+1:

**Comment by stevepugh99** [comment]
Looking forward to this feature. It's the single most important missing feature of VimFx in my view!
