### ISSUE TITLE
Hint markers misplaced on duckduckgo

### ISSUE THREAD

**Issue by marlun** [akhodakivskiy/VimFx#470]
If I go to duckduckgo and search for vimfx and hit `f` the hint markers are not placed on the titles of the search results. I'm on da5fb6d5c981eded85ab6674d2edce2080fc89f3 and Firefox 35.0.1

![screen shot 2015-02-22 at 22 36 26](https://cloud.githubusercontent.com/assets/19663/6320660/12a34200-bae4-11e4-99b0-ac994109b3dd.png)

**Comment by TheGreenHabi** [comment]
Hi!
I just built latest dev VimFx + Firefox beta 36 (20150219...) and I don't see problem. Everything is aligned for me. I also tried different zoom settings.
![duck_vimfx](https://cloud.githubusercontent.com/assets/9500028/6320741/d7b69858-baee-11e4-8e1c-afbf37003a96.JPG)

**Comment by marlun** [comment]
I tried Developer Edition since I've got it installed already and it works fine there 
![screen shot 2015-02-23 at 07 41 26](https://cloud.githubusercontent.com/assets/19663/6323720/7e452974-bb2f-11e4-807c-b00f32a897c4.png)

**Comment by lydell** [comment]
Have you tried it in a clean profile in Firefox 35? Is only duckduckgo affected?

**Comment by marlun** [comment]
Is there an easy way to try it in a clean profile or do I have to go to about:support and click Refresh Firefox? :smile:

**Comment by TheGreenHabi** [comment]
Multiple Firefox profiles:
https://developer.mozilla.org/en-US/docs/Mozilla/Multiple_Firefox_Profiles

**Comment by marlun** [comment]
On a new profile it works in Firefox 35.0.1 too. Will refresh the one that doesn't work and see if that will fix it or if it's some other addon that is causing it.

**Comment by marlun** [comment]
Worked great after refresh. Forgot to get back to this.
