### ISSUE TITLE
Cannot focus to text input area when VimFx enabled

### ISSUE THREAD

**Issue by xshuai1006** [akhodakivskiy/VimFx#473]
When VimFx enabled, nearly no text input area can be accessed, I cannot input search words or username or something alse.

**Comment by lydell** [comment]
Does the problem go away if you disable the "Prevent autofocus" option?

**Comment by xshuai1006** [comment]
Yes, the problem go away as soon as I disable the "Prevent autofocus" option. Thank you very much!

**Comment by lydell** [comment]
What OS are you using? Firefox version? VimFx 0.5.17? Keyboard layout? Do you use an input method for Chinese or similar? Does it happen on all sites or just some? Did it use to work before?

**Comment by xshuai1006** [comment]
I am using Win7 64bit, Firefox 36.0.1 and VimFx 0.5.17. your hint is right, the problem only happen when I enable Chinese input method (Google Pinyin for Chinese) and it seems to affect most websites, but when I disable Chinese input method, this problem go away without uncheck "prevent autofocus". VimFx conflicts with Chinese input method, is this the very reason to the problem?

**Comment by lydell** [comment]
Yes, that seems to be the problem. Unfortunately, I'm not very familiar with input methods, so I gladly welcome help on this issue.

**Comment by lydell** [comment]
Merging into #497.
