### ISSUE TITLE
Auto-disable VimFX when input or text field is selected in e10s

### ISSUE THREAD

**Issue by ChimeraCoder** [akhodakivskiy/VimFx#476]
I'm a recent newcomer to VimFX, migrating from Vimperator (at least for my Nightly install). I'm running Nightly 39.0a1 (2015-03-28) with e10s enabled.

When I select a text field, I have to remember to press `i` to enter insert mode, or else the next time I type a character corresponding to a VimFX shortcut, I will switch to a new tab, close the tab I'm currently on, etc. This happens whether I select a field with the mouse or using VimFX. As a result, it's very easy to accidentally lose my entire input (which almost happened as I type this very issue!).

**Comment by LordJZ** [comment]
Part of #378

**Comment by edrex** [comment]
Recommend to reopen this one. 

Under Arch Linux/Firefox Aurora 44.0a2/VimFX [v0.6.1)](https://github.com/akhodakivskiy/VimFx/releases/tag/v0.6.1) , I must press `i` in this text box to avoid command interpretation.

I haven't seen this in my usual OS X workstation with FF DE so maybe it's a Linux-only issue. Can anyone on Linux confirm that this is still an issue with Firefox Aurora?

**Comment by lydell** [comment]
@edrex See #569.

**Comment by edrex** [comment]
Missed that, thanks
