### ISSUE TITLE
Help window in intermediate layer

### ISSUE THREAD

**Issue by rahulmutt** [akhodakivskiy/VimFx#477]
If you visit [here](www.pcmag.com/article2/0,2817,2365692,00.asp), you'll find that you'll find that the help page for VimFX will be layered below the top toolbar.
![screenshot - monday 30 march 2015 - 12 57 34 ist](https://cloud.githubusercontent.com/assets/8035100/6891941/9c46ffba-d6dc-11e4-8801-97f090ab29d1.png)

**Comment by lydell** [comment]
The same thing can happen with hint markers. I've already fixed that in the development version. Doing the same for the help dialog is one of my next tasks.
