### ISSUE TITLE
Not working 'Add Rule...' in Firebug style panel

### ISSUE THREAD

**Issue by VovanR** [akhodakivskiy/VimFx#479]
If `Prevent auto focusing inputs` property is enabled in *VimFx*. In *Firebug* not working `Add Rule...` feature (Panel 'HTML' -> 'style' -> right click).

VimFx 0.5.17
Firebug 2.0.8
Ubuntu 14.04

**Comment by WishCow** [comment]
Can confirm. The input element looses focus as soon as it appears, and you have no way of activating it again. It happens with the "new property" option too, but at least the input element stays visible there, so you can click back into it.

**Comment by lydell** [comment]
Merging into #497.
