### ISSUE TITLE
Text selection mode (possibly using something like caret browsing)

### ISSUE THREAD

**Issue by Joe5** [akhodakivskiy/VimFx#480]
Hey, I was wondering if it would be possible to add support for selecting text using caret browsing? Sometimes I need to select/copy some text for further google search and so on and currently the only reasonable way is to use mouse or turn on caret browsing and slowly select it using arrow keys which is most of the time slower than using the mouse.
 
I am thinking of something like hitting some keybinding which would turn on caret browsing than show hints (like "f" does for links/inputs) which would allow quickly put cursor to some position in the page. Even this would be great time saver but it would still require us to use arrow keys.

This could be enhanced if the arrow keys were mapped to regular vim movement keys (h, j, k, l) or even better if it would support other vim-like commands. Of course only during this special mode. For example yanking of words (y2w), or inner/outter blocks (yi" and so on) maybe even whole paragraphs or to the end of the line...

After that the caret browsing could be automatically disabled until it would be invoked again.

In case it is not clear what I am talking about it can be enabled by hitting F7.

**Comment by lydell** [comment]
Perhaps we should change the `vf` command to, say, `zf` to free up `v` for this feature. `z` is a general “namespace” key in vim so it should make sense.

**Comment by Joe5** [comment]
That would be great. I found that https://github.com/philc/vimium this one supports visual mode. Hope it helps.

**Comment by nashamri** [comment]
:+1: for this.
vimium implementation is actually pretty good for this feature.

**Comment by ikhthiandor** [comment]
:+1: This is a crucial one missing from the vimfx workflow.

**Comment by geimerus** [comment]
That's a one of the best idea for vimfx! I'm still waiting for it!

**Comment by lydell** [comment]
I've been working on it for a few days now.

**Comment by geimerus** [comment]
Cool! Good luck to you! I will donate when I will have some money! You made surfing in Firefox such a good thing!

**Comment by lydell** [comment]
A small update: I’m still working on it, and have made great progress. I have nothing to show off yet, though. But it’s coming :)

**Comment by nashamri** [comment]
Good job @lydell waiting for the new updates :+1: :smile:

**Comment by lydell** [comment]
Status report:

I’ve experimenting _a lot_ with text selection now. The experience has been pretty horrible, because the available APIs are very difficult to work with and require lots of hacks. I’ve also found that a text selection mode has the potential to become _very_ large because Vim has so many commands one might want to implement.

So, I’ve started to think about what problem we’re trying to solve. I think this is the answer: Make it easier to copy text.

With the above paragraph in mind, I’ve come up with an alternate, a lot simpler solution. I’m going to try it out for a couple of days to see if it works.

**Comment by lydell** [comment]
Today I've more or less finished the first iteration of this feature. Check out the caret branch if you're interested. Unless I find bugs I'll merge it into develop near the end of this week, or sometime next week. Then a release shouldn't be too far away.

**Comment by lydell** [comment]
Found a few major bugs today (and a few enhancement ideas), when I tried it in my main profile (outside the test cases). Required some re-thinking, but I fixed them. I'm really starting to learn now what is possible and what isn't possible to do reliably.

**Comment by lydell** [comment]
I just merged to develop. You can read the [docs for Caret mode](https://github.com/akhodakivskiy/VimFx/blob/b82618ee7c9c7641b34a84ca7dc7b5c5943a5c69/documentation/commands.md#the-v-commands--caret-mode) if you want to get a sneak peek.

I have a related feature upcoming. I'll try to finish that and then we'll cut a release :)

**Comment by zkanda** [comment]
Wow, awesome, thanks for this @lydell

**Comment by nashamri** [comment]
Yes! thanks @lydell
