### ISSUE TITLE
Temporary hide lables

### ISSUE THREAD

**Issue by lindhe** [akhodakivskiy/VimFx#484]
Sometimes (particularly in narrow lists) the lables can obscure the anchor content, making it hard to know which shortcut to use. It would be greatly useful to be able to temporary hide the lables when holding down a button (e.g. shift).

**Comment by lydell** [comment]
Related: #220.

**Comment by lindhe** [comment]
Sorry I didn't find that issue before opening a new one. I searched for "hide". :) But at least this is a bit different.

**Comment by lydell** [comment]
Idea: Add a `vimfx-held-modifiers` property on the top browser `window` element which updates as soon as you press and release modifiers. The you could style the markers with CSS, such as `#main-window[vimfx-held-modifiers~='shift'] #VimFxMarkersContainer .marker {opacity: 0.1;}`.
