### ISSUE TITLE
Configurable attrs array for helper_follow_pattern

### ISSUE THREAD

**Issue by reuben364** [akhodakivskiy/VimFx#489]
The follow pattern configuration for the `[` and `]` keys is not versatile enough to capture a lot of next and previous links that people may want to configure for. Allowing the `attrs` array in the `helper_follow_pattern` function to be set in the configuration can alleviate this a bit.

**Comment by lydell** [comment]
Examples?

**Comment by reuben364** [comment]
Buttons whose only telltale attribute is their id or title.

**Comment by lydell** [comment]
_Specific_ examples?
