### ISSUE TITLE
Bookmark a webpage

### ISSUE THREAD

**Issue by andysaini** [akhodakivskiy/VimFx#490]
What's the relevant shortcut?

**Comment by loonies** [comment]
ctrl+d

**Comment by andysaini** [comment]
@loonies how about a VimFx shortcut?

**Comment by lydell** [comment]
When VimFx sometime far in the future supports custom commands this could be done.

**Comment by lydell** [comment]
Added to the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#bookmark-page) section of the wiki.
