### ISSUE TITLE
non-responsive after switching between Firefox and other applications

### ISSUE THREAD

**Issue by hezhaobin** [akhodakivskiy/VimFx#491]
I start to notice this anomaly after upgrading to 0.5.17 and Firefox 38, on Ubuntu 12.04. The symptom is, after switching from Firefox to another app, e.g. terminal, and back, vimFx will become non-responsive -- the webpage shows correctly and all mouse and arrow keys work, but vim key combinations don't. I find if I just hit any of the location bar, search bar or the settings button to the right of search bar, VimFx key-bindings will be activated again. I didn't have this problem on my mac.

**Comment by lydell** [comment]
Hi @hezhaobin, VimFx 0.6.0 has just been released. Would you like to try it out and check if your issue happens in that version as well?

**Comment by hezhaobin** [comment]
Hi,

I solved the original problem by wiping Firefox clean on linux (app-get
purge with several options, which I forgot), then reinstalling it. It
has recurred twice, and each time I have to do that again. I'd be happy
to try that. Moreover, as an amateur programmer, I'm curious as to what
could be the origin of the problem (which part of the key response is
somehow inactivated upon tab / app switching?)

Cheers
Bin
On Mon, Nov 09, 2015 at 11:30:17AM -0800, Simon Lydell wrote:
> Hi @hezhaobin, VimFx 0.6.0 has just been released. Would you like to try it out and check if your issue happens in that version as well?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/akhodakivskiy/VimFx/issues/491#issuecomment-155166271

-- 
Sincerely yours

Bin HE
HHMI Post-doctoral fellow
O'Shea Lab, Harvard University
email: binhe@fas.harvard.edu

**Comment by lydell** [comment]
@hezhaobin I just read through this again, and suddenly I remembered a possibly similar issue I had myself for some time, when I used a program called “unclutter” which hides the mouse pointer after not having moved for some time. While that was really nice, I eventually stopped using it because it caused problems in Firefox. Most notably, sometimes when focusing the location bar, it didn’t really look focused, but I could still type in it. However, no autocomplete results showed up. The problem went away if I clicked just about anywhere inside Firefox. I _think_ it caused problems to VimFx as well, but I don’t remember exactly.

Perhaps you use some other program that causes interference?

**Comment by hezhaobin** [comment]
Hi Simon,

Thanks for the thought. I didn't use that addon, but it could be something
else I used at that time, as the problem has not occurred for a while. It
could also be that VimFx itself has fixed some bug. In any case, thanks for
your response!

Bin

On Sun, Dec 6, 2015 at 11:59 AM, Simon Lydell <notifications@github.com>
wrote:

> @hezhaobin <https://github.com/hezhaobin> I just read through this again,
> and suddenly I remembered a possibly similar issue I had myself for some
> time, when I used a program called “unclutter” which hides the mouse
> pointer after not having moved for some time. While that was really nice, I
> eventually stopped using it because it caused problems in Firefox. Most
> notably, sometimes when focusing the location bar, it didn’t really look
> focused, but I could still type in it. However, no autocomplete results
> showed up. The problem went away if I clicked just about anywhere inside
> Firefox. I *think* it caused problems to VimFx as well, but I don’t
> remember exactly.
>
> Perhaps you use some other program that causes interference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akhodakivskiy/VimFx/issues/491#issuecomment-162328897>
> .
>



-- 
Yours sincerely

Bin HE
Postdoctoral researcher
O'Shea Lab, HHMI, Harvard University
email: binhe@fas.harvard.edu
website: http://binhe.org
