### ISSUE TITLE
The *Go to next/previous page* commands are broken?

### ISSUE THREAD

**Issue by baskerville** [akhodakivskiy/VimFx#496]
The *Go to next/previous page* commands don't do anything here.

I'm using version 0.5.17, Firefox 38.0.1.

**Comment by akhodakivskiy** [comment]
Which page are you talking about? These commands are prone to breakage because they rely on keywords in HTML attributes. But they do work for me on GitHub issues list on in GMail.

**Comment by baskerville** [comment]
The commands aren't working for me on GitHub issues list.

**Comment by lydell** [comment]
Probably fixed by #396.

**Comment by baskerville** [comment]
My bad: I was using *]]* instead of *]* as binding for *Go to next page* but I specified it as *]]* instead of *],]*.

Works great.
