### ISSUE TITLE
Decision to open link in new or current tab while typing markers

### ISSUE THREAD

**Issue by hybridtupel** [akhodakivskiy/VimFx#500]
I have a request for a little feature: 
Let the user decide if he wants to open the link in a new tab or the current one not just by hitting f or F beforehand.
It would be great if the user could hit (lowercase) f and then decide afterwards to switch to a new tab by just typing the marker keys in upper case. This way one doesn't have to decide beforehand if a new tab should be opened or not. (Btw. this behavior is implemented in vimium, too)

**Comment by lydell** [comment]
See #421.
