### ISSUE TITLE
add support for `ctrl+[`

### ISSUE THREAD

**Issue by timabell** [akhodakivskiy/VimFx#501]
I've taught myself to use `ctrl+[` instead of `esc` as per http://vim.wikia.com/wiki/Avoid_the_escape_key

This appears to be used for back/forward (`ctrl+[`/ `ctrl+]' respectively) in firefox, would it be possible to remap to the vim shortcut instead?

Thanks for a great addon.

**Comment by lydell** [comment]
Probably fixed by #249.

**Comment by lydell** [comment]
For people who find this while searching: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/questions-and-answers.md#how-do-i-re-map-escape-which-blurs-text-inputs
