### ISSUE TITLE
suddenly stopped working, key not responding (mac os 10.10.3 + firefox 38.0.5)

### ISSUE THREAD

**Issue by rekhubs** [akhodakivskiy/VimFx#502]
don't know why, just stopped working at all, not one key
tried banning all other addons, tried re-installing VimFx, not working.....

**Comment by lydell** [comment]
#419, perhaps?

**Comment by raj-kesavan** [comment]
Same issue on my end. #419 did not resolve.
40.0a2 (2015-06-03), Ubuntu Trusty.

**Comment by akhodakivskiy** [comment]
Any errors/exceptions in the Browser Console? Tools->Web Developer->Browser Console (Cmd-Shift-J or Ctrl-Shift-J)

**Comment by raj-kesavan** [comment]
No.

**Comment by akhodakivskiy** [comment]
Try resetting VimFx related settings in about:config, extensions.VimFx.*

**Comment by raj-kesavan** [comment]
I reset all the settings; didn't work before or after a restart. Do you
think reinstalling Firefox might help? Today I installed  a fresh copy of
Firefox and VimFx on OS X and it worked great.


---
Balachandar 'Raj' Kesavan

**Comment by lydell** [comment]
You could try creating a new profile.

**Comment by rekhubs** [comment]
@lydell ok, that's pretty much like re-installing firefox to me.....
i'm now doing that...
