### ISSUE TITLE
Suggestion: Add information of the behavior of ctrl+click to readme

### ISSUE THREAD

**Issue by fatjing** [akhodakivskiy/VimFx#505]
Hello, if I don't get it wrong, the 'follow link in a new tab' is implemented by mimicking ctrl+clicking the link. Problem is that, [the ctrl+click can open a link either in background or foreground tab, depending on checking or unchecking a tab setting] (https://support.mozilla.org/en-US/kb/mouse-shortcuts-perform-common-tasks). To get the 'right' behavior one should uncheck the 'When I open a link in a new tab, switch to it immediately' setting.
This has bugged me for so long and I have no clue how to deal with it until I stumbled upon the link above. I think it should be mentioned explicitly to the user.

**Comment by lydell** [comment]
The develop version has one command for opening tabs in new background tabs and one for foregrounds tabs. This is implemented without relying on ctrl+click.
