### ISSUE TITLE
Support for exiting follow links mode using Ctrl-C

### ISSUE THREAD

**Issue by sgtpep** [akhodakivskiy/VimFx#506]
VIM supports returning to normal mode using Ctrl-C shortcut, not only Esc. A lot of VIM users uses Ctrl-C instead of Esc, which is located to far on keyboard to easily reach it.

**Comment by lydell** [comment]
See #421.

**Comment by sgtpep** [comment]
OK, but I don't see any mention of Ctrl-C in #421.

**Comment by lydell** [comment]
True. But what I meant over there is that in the development version you can choose _any_ shortcut to exit hints mode (or any mode for that matter).

**Comment by sgtpep** [comment]
Oh, I see now. I've tried to bind Ctrl-C (in addition to Esc) for "Entering normal mode". And it brokes copy shorcut Ctrl-C in all input fields. That's why vim allows to bind separate mappings for different modes (cmap, imap, vmap, etc.) For desired functionality Ctrl-C should be mapped like `nmap <C-C> ...` for working only in normal mode. Should I create separate issue for that?

**Comment by lydell** [comment]
Before answering your question, I need to know one thing. Did you use the latest release or the latest development version?

**Comment by lydell** [comment]
> For desired functionality Ctrl-C should be mapped like `nmap <C-C> ...` for working only in normal mode

Do you mean <strong>i</strong>map?

**Comment by sgtpep** [comment]
Sorry, I've misguided you by mentioning insert mode, thinking that keybinding in text field editing mode is an actual insert mode, but VimFx has it's own page wide "insert" mode outside of text fields.

I mean, the solution with binding <C-C> to "Enter normal mode (remove hint markers, exit insert mode) or blur/close active element" is not working, because it triggers not only on page but on any text fields overriding the native Ctrl-C shortcut for copying on Windows/Linux.

**Comment by lydell** [comment]
Sorry, I'm really confuses now. In which situation do you want `<c-c>` to do what?
