### ISSUE TITLE
Integration with the Fastest Search addon (was: / search supports regex)

### ISSUE THREAD

**Issue by hyiltiz** [akhodakivskiy/VimFx#508]
It would be awesome to support a regex based search when using `/` on page. However, since that is not the default behavior in Firefox and vimFX does not try to alter/enhance a default behavior of Firefox too much, maybe this should be left to users via installing other add-ons that provide this functionality.

Or would it be possible to bind `/` key with add-on [Fastest Search](https://addons.mozilla.org/zh-cn/firefox/addon/fastest-search/)?

**Comment by lydell** [comment]
> since that is not the default behavior in Firefox and vimFX does not try to alter/enhance a default behavior of Firefox too much, maybe this should be left to users via installing other add-ons that provide this functionality

Yes.

> would it be possible to bind / key with add-on Fastest Search?

I’m working on that.

**Comment by lydell** [comment]
The latest development version now has support for custom commands, making this possible to do.

**Comment by hyiltiz** [comment]
That is great to know! So about how often, do you think, does it take for it to a) merge this dev feature into master release and b) downstream that to the official Mozilla addons repo?

**Comment by lydell** [comment]
> So about how often, do you think, does it take for it to a) merge this dev feature into master release

Once.

> the official Mozilla addons repo

What's that?

**Comment by hyiltiz** [comment]
I am so sorry for not being correct on my last response. I meant *how long* rather than *how often*. And I meant this place: https://addons.mozilla.org/ by [Official Mozilla Addons Repository](https://addons.mozilla.org/).

**Comment by lydell** [comment]
The next release will come out when its done. All I can say is that this will be the last "big" release. Then we'll switch to a more rapid release cycle.

**Comment by lydell** [comment]
I’ve added this to the [integration wishlist](https://github.com/akhodakivskiy/VimFx/wiki/Other-Add-ons-that-integrate-with-VimFx) in the wiki.
