### ISSUE TITLE
Offer gettext file (.po) for translators

### ISSUE THREAD

**Issue by atilacamurca** [akhodakivskiy/VimFx#513]
How do you guys edit your translations files (.properties)?

Edit in a common editor is painful and error prone. I suggest you guys offer a gettext file (.po) for a better way to edit the translations files. Gettext is well-known by translators and has great tools to help edit, such as [Gtranslator](https://wiki.gnome.org/Apps/Gtranslator) and [POEdit](https://poedit.net/).

**Example**: in a properties file you'll have to edit the string in place, let's say you copy the string to the line above. It's easy to make some mistakes:

* forget to remove the copy
* thought that you copy when actually you're editing other string

in a gettext file you have a better structure to translate.

1. You already have both the original and the translation string in the same file
2. You have great tools to help you:
    * See how much strings are not translated
    * See the original string right above the input for translation string
    * Better break line handling
3. Well-known technology by translators

As you guys already use properties file to translate you'll have to use [Translator Toolkit](http://translate-toolkit.readthedocs.org/en/latest/index.html) to convert .po to .properties, both way.

And finally you'll be able to use an on-line service, if works better, called [Transifex](https://www.transifex.com/). It's free for open source projects. And has an api to fetch and push translations ([link](http://docs.transifex.com/api/translations/)).

As a developer in many projects before I think it's worth it.

**Comment by lydell** [comment]
Thanks for all those links! :)

However, I might not get around reading them :) Would you mind writing a specific example? “For example, using gettext (.po) you can do _this_ instead of _this_ which is much better because _that_ is much easier than _that_.” That’d help getting things going.

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/issues/543#issuecomment-154734677:

> One of the things I talk about in #513 is about to know what strings I need to translate, so the way the project is now, I have to check all strings to see what is new.

Since that was super easy to add to the `gulp sync-locales` command, I just did so: You may now run for instance `gulp sync-locales --pt-BR?` to see how many percent of the “pt-BR” locale is done, and which lines (including line numbers) are untranslated.

With that out of the way and thinking about some of the feedback from #543 I’m going to close this. The gettext system sure is cool, but I don’t think its worth it here.

**Comment by atilacamurca** [comment]
great man!
