### ISSUE TITLE
f broken on pages that load an svg+xml object in -develop

### ISSUE THREAD

**Issue by Spittie** [akhodakivskiy/VimFx#517]
Hi, 

pressing f on pages that embed an svg+xml object (Phoronix.com is the only one I've found in the wild) to hang VimFx. No "tag" appear, and I have to press ESC to have VimFx working again.

How to reproduce: Go to any page on Phoronix.com that has a PTS/OpenBenchmarking graph, make sure the graph it's currently visible, and press f.
Example pages: 
* http://www.phoronix.com/scan.php?page=article&item=linux-411-gallium&num=2
* http://www.phoronix.com/scan.php?page=news_item&px=AMD-15.7-Linux-Driver-Bench
* http://paste.c99.nl/957b5247e860361a843f.html (small test-case)

This is shown in the Browser console (ctrl+shift+j):
```
"TypeError: ref is undefined
  createMarkers@/lib/hints.js:126:15
  createMarkers@/lib/hints.js:163:1
  injectHints@/lib/hints.js:57:3
  .onEnter@/lib/modes.js:122:12
  Vim.prototype.call@/lib/vim.js:110:35
  Vim.prototype.enterMode@/lib/vim.js:78:1
  commands.follow@/lib/commands.js:476:10
  .onInput@/lib/modes.js:102:9
  Vim.prototype.call@/lib/vim.js:110:35
  Vim.prototype.onInput@/lib/vim.js:92:16
  windowsListeners.keydown@/lib/events.js:132:18"
```

Firefox Version: Firefox 39, tested on a computer running Arch and one running Windows 8.1.
VimFx version: Latest from -develop, manually compiled
The last stable appears to be working fine instead.

Hope this isn't already reported, I searched the issues and didn't find anything. Also thanks for VimFx!

**Comment by lydell** [comment]
Thanks for the great bug report! This is probably due to some property that exists on HTML elements but not on SVG elements – that has happened before. Should be easy to fix. Might even just be a `?` that needs to be added.

**Comment by Spittie** [comment]
I pushed ^ before running the tests, and obviously it broke a bunch of them. So forget about it I guess :|

Anyway the issues seems to be that ```getElements``` gets called with document = SVGDocument on that page, which causes it to return undefined (which then causes the stacktrace I posted before).

**Comment by Spittie** [comment]
Okay, this ^ doesn't break the tests.
Do you think this is good enough? If so I can send a pull request if you want.

**Comment by lydell** [comment]
It's better to fix `getElements`.
