### ISSUE TITLE
Detect “Search for text when I start typing” mode

### ISSUE THREAD

**Issue by proedros** [akhodakivskiy/VimFx#519]
Hello, I am using vimfx for years but not its full potential, as I have enabled the firefox option:
*Search for text when I start typing*
therefore I am only using vimfx's options:
- focus element
- follow a link  on the current page
- follow a link  on the current page in new tab

So my keyboard browsing is a combination of vimfx and "Search for text when I start typing"

My issue is that when I start typing a link (without using vimfx) after pressing the enter key the link gets highlighted but it needs another press of enter to open. If I just disable the vimfx the page opens normally, is it possible to fix this, as sometimes the second enter press opens another page and confuses me, thanks.

**Comment by lydell** [comment]
See #390.

**Comment by akhodakivskiy** [comment]
The find mode in VimFx should have a flag that indicated if the mode was initiated by VimFx (i.e. using the shortcut) or by Firefox (i.e. using "Search for text when I start typing" or by the default search shortcut - ctrl+f). If it's started by Firefox then no special Enter key handling should occur.

**Comment by lydell** [comment]
No I remember: At some point VimFx worked more or less like @akhodakivskiy describes, but then people where confused that `<enter>` did _not_ close the find bar, or that `n` and `N` didn’t work. Tough problem. IMO, we should only detect the “Search for text when I start typing” case.

**Comment by lydell** [comment]
Let’s keep things as simple as possible. Let’s keep things the way they are in the development version for now. We’ll release that and then revisit this.

**Comment by lydell** [comment]
Hi @proedros, VimFx 0.6.0 has just been released which allows to disable VimFx’s Vim-style `<enter>` behavior in the find bar. Would you like to try it out and tell us if that cuts it for you?

**Comment by lydell** [comment]
Closing because no response.

**Comment by proedros** [comment]
hey sorry I have not seen your message of about a month ago, I saw it now,
unfortunately the last version that works as I want is vimfx-0.5.12-fx
and this is what I am using now, the new version 0.60 is the same as the
others regarding my issue, again sorry about late reply

**Comment by lydell** [comment]
@proedros Did you remove `<enter>` from the “Close find bar” command?

**Comment by lydell** [comment]
ping @proedros

**Comment by proedros** [comment]
hey lydell new version is working great now after I removed <enter> from find command.
thanks for your efforts and the great addon
