### ISSUE TITLE
Can't highlight comment text fields on Facebook.

### ISSUE THREAD

**Issue by lindhe** [akhodakivskiy/VimFx#524]
Well, not quite. I can highlight/click the comment text field at a facebook post, but only after using the mouse to click the field first, or somehow "activating it" once. After that point the field is targetable by VimFx.

So far I have only tried with 0.5.17.1, I'll get back if I get time to try with the latest dev. version.

**Comment by lydell** [comment]
I don’t really use Facebook that much, but I think I remember experiencing the same thing not too long ago using the development version. As far as I remember, the DOM changes after having activating it once, to something that VimFx can detect. A workaround is to hit the “Comment” link of the post instead (it should be targetable by VimFx).
