### ISSUE TITLE
No updates on addons.mozilla?

### ISSUE THREAD

**Issue by digital-carver** [akhodakivskiy/VimFx#525]
VimFx has made my browser usage much more pleasant, but I keep waiting to be able to use these new features (mainly the plaintext config file and the count-based operations). It seems like the main codebase has been stable for two months too, but the last update at https://addons.mozilla.org/en-US/firefox/addon/vimfx/ apparently was 8 months ago. 

I highly prefer installing from the mozilla site since (a) it's a good security practice in general to get it from the official, mozilla-verified source, (b) it makes the update and maintanence process much smoother, and relatedly (c) it makes it easier to keep my addons sync'ed across OS's/machines. 

Is there a plan to release an xpi on addons.mozilla.org, or is self-compilation going to be the only avenue moving forward?

**Comment by lydell** [comment]
There is a plan to release on AMO. The idea is to get this one "big" release out and then switch to a rapid release cycle, just like Firefox. I'll come back with more info this weekend.

**Comment by marcbelmont** [comment]
I'm also waiting for an update on AMO and I'm happy to help if there's something I can do..

**Comment by silentboatman** [comment]
Yes! I'm also waiting :)

**Comment by lydell** [comment]
See #535.

I’ve moved twice the past six months and haven’t been able to devote as much time to VimFx as I had liked. Now it seems like there will be more time :)

**Comment by lindhe** [comment]
That's good to hear. Hope all went well with your moving.

**Comment by rightaway** [comment]
+1
