### ISSUE TITLE
Shortcut keys don't do anything in 42.0a2

### ISSUE THREAD

**Issue by sheldond** [akhodakivskiy/VimFx#527]
Hello!

I'm using VimFx with Firefox Developer Edition 42.0a2 on OSX 10.10.5, VimFx is the only addon that I have enabled, and I have the multi-process option disabled.

None of the VimFx shortcut keys do anything, I've tried several different websites that are not in my black-list, and I've tried pressing almost all of the different VimFx shortcuts.

Let me know if I can provide any more info that would be helpful! Love VimFx! :heart: :v: 

Edit: I should add that I'm using VimFx 0.5.17.1-signed

**Comment by lydell** [comment]
Duplicate of #378. See #512 for progress.

**Comment by sheldond** [comment]
@lydell just to clarify: I have multi-process disabled, so I did not think it was a duplicate, but I will let you organize the issues. Thanks!

**Comment by sheldond** [comment]
I removed and reinstalled VimFx and also cleared the preferences in about:config and now it's working again! :smiley:
