### ISSUE TITLE
Holding j or k scrolls too fast

### ISSUE THREAD

**Issue by eulerreich** [akhodakivskiy/VimFx#529]
How can I either turn off the "hold to scroll faster" feature or lower the speed of it?

**Comment by lydell** [comment]
0.5.x `j` and `k` work like the arrow keys do even without Firefox. [In the devlopment version they're a bit slower](https://github.com/akhodakivskiy/VimFx/pull/461#issuecomment-119725356).

For 0.5.x you can try fiddling with the `general.smoothScroll.{lines,pages,other}.duration{Min,Max}MS` prefs. That's just standard Firefox stuff, so I'm sure you can find more information about it if you search the Internet.
