### ISSUE TITLE
Mode indicator (normal mode / insert mode)

### ISSUE THREAD

**Issue by kgrossjo** [akhodakivskiy/VimFx#530]
WIBNI there was a status display somewhere that shows whether I'm in insert mode or in normal mode?

**Comment by lydell** [comment]
The toolbar button acts as one: It is colorful normally and grey in insert mode. If it is not on your toolbar, enter the customization mode and drag it out.

**Comment by jck** [comment]
While this works on most cases, it does not work when a text box is focused.

**Comment by lydell** [comment]
Yes it does. When a text box is focused, insert mode is _not_ entered. Instead VimFx just ignores most commands. In the development version Insert mode is called Ignore mode and you can customize which commands are available in text boxes.

**Comment by jck** [comment]
very cool!
I hope that the appearance of toolbar button is also customizable in this case.

**Comment by lydell** [comment]
It is! :)

**Comment by kgrossjo** [comment]
Thank you @lydell .  The VimFx toolbar button is hard to find because it is blank in the toolbar.  But it does work very well.  _Very_ well.  I will close this issue.
