### ISSUE TITLE
Allow passing Esc to vim-style modal-editing text boxes when in its “insert mode” (was: Conflicting with Pterosaur)

### ISSUE THREAD

**Issue by glacambre** [akhodakivskiy/VimFx#532]
I recently discovered another vim-inspired addon, Pterosaur (https://github.com/ardagnir/pterosaur). It enables you to edit every input as you normally would with vim (same modes, motions etc). Unfortunately, when using Pterosaur with VimFx, pressing the "escape" key makes the input lose focus, preventing you from switching between modes.
Pterosaurt isn't maintained anymore but works pretty well on its own (at least it does on Iceweasel 38.2.0). From what I have gathered, it also works with vimperator and pentadactyl, that's why I think it may be a VimFx issue.

Do you think this is a VimFx issue ? If so, do you plan on fixing it ?

My exact config is : Iceweasel 38.2.0, VimFx 0.5.17.1 and Pterosaur 1.1.2.1.

Sorry if this is a duplicate, I couldn't find anything with a title that would suggest talks about Pterosaur.

**Comment by lydell** [comment]
For now I have no plan. As a workaround you can rebind Esc in one of the programs.

Just to be sure I understood correctly, you want Esc only to blur text boxes when Pterosaur is in normal mode, right?

**Comment by glacambre** [comment]
Yes, this is exactly what I would like it to do.
I just realized that this behavior also prevents CodeMirror's vim emulation (https://codemirror.net/demo/vim.html) from working properly.

**Comment by bag-man** [comment]
@lydell 

This also conflicts with [Wasavi](https://github.com/akahuku/wasavi). When VimFX + Wasavi are enabled, once you enter insert mode in Wasavi, you can't exit it, as the Escape character gest picked up by VimFX

**Comment by akahuku** [comment]
Hi, I am author of [wasavi](https://github.com/akahuku/wasavi).
I'm looking for the way to make VimFx and wasavi (or other textarea enhance extensions) cooperate, too.
For example, if there is a method like `suspend()` in the VimFx's API set, it is very good.

**Comment by lydell** [comment]
VimFx does not expose anything to the public.

What about this:

VimFx could easily detect if the wasavi editor is currently focused. If so, VimFx could simply choose to do nothing at all.

However, as I understand it, users want to be able to press `<esc>` in wasavi’s Normal mode to blur the editor. (By default VimFx allows you to blur any text input by pressing `<esc>`.) Is it possible to customize wasavi to blur the editor if you press `<esc>`? If so, that feels like a really simple solution.

**Comment by lydell** [comment]
The development version now recognizes wasavi’s editor as an editable element, allowing you to type in it. However, `<escape>` still always blur the editor.

**Comment by lydell** [comment]
@glacambre Pterosaur does not seem to work in Firefox anymore. When I install it, the browser console says it contains syntax errors. Thoughts?

**Comment by akahuku** [comment]
Thank you.

While VimFx is running, nothing wasavi can do to `<esc>` key event. Because the event doesn't reach wasavi.

"Textarea enhancer" such as Pterosaur, wasavi, should want to consume all keyboard input by itself.
Therefore, to resolve this problem, I think it's necessary that VimFx suspends a keyboard handling  temporarily.

**Comment by lydell** [comment]
Yes, that’s my thinking as well. That’s also very simple to do. However, there’s one problem: @glacambre said that he wanted `<esc>` to blur pterosaur (or wasavi in this case) when in pterosaur/wasavi’s normal mode. That’s why I asked this question:

> Is it possible to customize wasavi to blur the editor if you press `<esc>`?

**Comment by lydell** [comment]
The problem basically boils down to: If you let the “textarea enhancer” handle _all_ keys, how do you exit it using the keyboard?

**Comment by glacambre** [comment]
@lydell
>Pterosaur does not seem to work in Firefox anymore.
Yes, looks like it's broken on Iceweasel 44. Wasavi seems to be a worthy replacement though :).
As for having to press <esc> in order to leave Wasavi, I'd be fine with using wasavi's :wq command (and so would be most users I suppose).
I took a quick look at how Wasavi works, in my opinion the cleanest way to solve this problem would be to implement some kind of public API in VimFX as @akahuku suggested.
Another solution would be to have VimFx check whether an element called wasavi_cover exists when a textarea is blurred (a blur event is fired when Wasavi is started) and go in passthrough mode if it does. VimFX can then listen on a change event on the blurred textarea to go back in non-passthrough mode.

**Comment by akahuku** [comment]
wasavi returns to usual textarea element by the `:wq` command as @glacambre says.

Also, I think @glacambre describes important thing about the direction of solution. That is, which should take the lead, VimFx or wasavi/Pterosaur?

When some code should be added to VimFx, 073db9d would be right.
Or if the wasavi should responsible for cooperation, I'd add a code to wasavi (in this case, as mentioned abobe, an API to make VimFx suspend is needed).

**Comment by lydell** [comment]
I think it makes the most sense if VimFx takes the lead.

If people are fine using `:wq` to exit wasavi (and letting `<esc>` be a no-op in wasavi’s normal mode), then I’ll just take commit 073db9d one step further and also pass through `<esc>` if wasavi is focused.

**Comment by lydell** [comment]
Either way, I’m still interested in this question :)

> Is it possible to customize wasavi to blur the editor if you press `<esc>`?

I imagine that being a simple yes-or-no question :)

**Comment by akahuku** [comment]
Ah, "yes"!

**Comment by lydell** [comment]
Cool! Is there some documentation I could link to from VimFx’s documentation to achieve that? Or could you paste the needed configuration here?

**Comment by akahuku** [comment]
Wait...to be exact, it is "no" in the present, I will code the functionality today.

Perhaps a new option `esctoquit` would be added to wasavi.
Then,  input `:set esctoquit` or put this line into the wasavi's exrc, wasavi in normal mode would treat `<esc>` key as `:quit` command.

By the way, 
>Is it possible to customize wasavi to blur the editor if you press `<esc>`?

let me confirm that "to blur" means just "to quit wasavi"? or is it also somewhat necessary about focus? (for example, `document.body.focus()` and so on)

**Comment by lydell** [comment]
"Blur" means doing what happens when you press `<esc>` today when you have VimFx installed: The wasavi editor loses focus, but still remains on screen. It is not exited, like pressing `:wq`. Blurring it allows temporarily switching to another tab while writing to, for example, copy some text or a link, and then go back to wasavi and paste that. In other words, "blurring wasavi" would work as if you click outside wasavi so that your keypresses are not caught by wasavi: Instead of typing into the wasavi editor or executing wasavi commands, the key presses do what they normally do.

**Comment by akahuku** [comment]
Thank you.
That means, when a user presses `<esc>` in wasavi's normal mode,
* wasavi does not have to quit
* wasavi has to blur the focus

Is this right? I'm still confused a little.

**Comment by lydell** [comment]
Yes, that's correct!

But perhaps you shouldn't implement that until a user asks for it. I was mainly curious :)

**Comment by lydell** [comment]
The development version can now automatically enter and exit Ignore mode based on the currently focused element. That's the solution to the Vim-style editors problem. The development version currently recognizes wasavi and CodeMirror (but not Pterosaur since it's broken in the latest Firefox). We'll add support for more Vim-style editors as people ask for it.

**Comment by akahuku** [comment]
Thank you!
I upgrade wasavi and wrote a topic about cooperation with VimFx in the [readme](https://github.com/akahuku/wasavi#vimfx).

**Comment by bag-man** [comment]
@lydell @akahuku Thank you guys so much! I can confirm this is working on the VimFX develop branch and Wasavi@0.6.602!
