### ISSUE TITLE
Next/Previous Tab default shortcuts

### ISSUE THREAD

**Issue by andredasilvapinto** [akhodakivskiy/VimFx#538]
Is there any reason why J is used for previous tab and K for next tab, when j is used for down and k for up? As in most cultures we tend to read from left to right and top to down I would find it more intuitive to have J be next tab and K previous tab in order to be consistent with Vim top down keys. This is especially confusing for people with vertical tabs (like me) where going up on the page is K, while going down on the tabs is also k.

I understand there might be different opinions and if it was set as that on purpose (e.g. to replicate left and right with horizontal tabs) you can just close this issue. I only want to understand the reasoning behind it.

**Comment by lydell** [comment]
The J and K shortcuts are inherited from Vimium. As you're suggesting, I think they come from that J is left of K, and vice versa.

Before I started using a vertical tab bar I had used J and K so much that it oddly enough was _not_ confusing for me when I switched!

Also see #192.

Good defaults are really important, so thanks for raising the issue, but in this case I think we're better off leaving things the way they are.
