### ISSUE TITLE
Deselect Text Input on Tab Switch

### ISSUE THREAD

**Issue by karlfloersch** [akhodakivskiy/VimFx#541]
I continually have the issue that I have one tab in which text is selected. From a different tab I start flipping through my opened tabs with **J** or **K** but I get stuck on the page which still has text selected.  Inevitably I'll add "JJJJJ" to my open email.

Could there be a way to automatically deselect text immediately on tab switch?

**Comment by lydell** [comment]
That's how things used to work, but for some reason it doesn't anymore. This annoys me every day, too.

**Comment by lydell** [comment]
After starting working on tgis in #542 I realized that we might not be talking about the exact, though similar, use case.

I'm annoyed by those pages that automatically re-focus some text input when you switch back to that tab. That seems to be fairly simple and non-destructive to do. Would that cut it for you as well?

**Comment by karlfloersch** [comment]
Awesome!  This is exactly what I was hoping for.  You understood my use case perfectly and this should fix my issue.  Thanks! :+1:

**Comment by karlfloersch** [comment]
@lydell Would you suggest I use the develop branch so I can get this feature?  Instead of waiting for the Firefox plugin to update?

**Comment by lydell** [comment]
Yes. But the feature isn't even fully done yet. I plan to finish it tomorrow. You can build from my PR if you'd like. The next release is scheduled for the end of the year.

**Comment by lydell** [comment]
@karlfloersch I’ve merged my PR into the develop branch now.
