### ISSUE TITLE
Update locales

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#543]
At the end of the year a new VimFx version will be released! (See #535.)

There have been lots of changes since the last version, including in the locale files. Now, no more changes are planned that will affect locales, so it’d be great if we could update them before the release! That’s at least one and a half months away, so there is plenty of time.

Here’s the current translation status:

    de:    98%
    el-GR: 59%
    fr:    99%
    hu:    53%
    id:    100%
    it:    98%
    ja:    100%
    nl:    99%
    pl:    60%
    pt-BR: 99%
    ru:    100%
    sv-SE: 99%
    zh-CN: 100%
    zh-TW: 100%

(It might be impossible to reach 100% in some languages, because some strings won’t differ. That’s totally fine.)

Remember to not only translate the untranslated, but also **go through already translated strings.** The English strings have been **shortened and simplified.** Please try to reflect that in translations! :)

Anyone is welcome to help! Pinging the current translators:

@Kambfhase @sirodoht @m-r-r @thenonameguy @comepradz @cbertoldi @pluser @HJTP @grn @morethanoneanimal @atilacamurca @akhodakivskiy @mymedia2 @harius @lindhe @zhuochun @mozillazg @cyberrob @leVirve

Translation contributors might also want to check that their name is correctly spelled in [PEOPLE.md](https://github.com/akhodakivskiy/VimFx/blob/develop/PEOPLE.md).

**Comment by lydell** [comment]
Thanks to @benediktg the “de” locale is now complete! (#544)

**Comment by lydell** [comment]
Thanks to @comepradz the “id” locale is now complete! (#545)

**Comment by lydell** [comment]
Thanks to @HJTP the “nl” locale is now complete! (#546)

**Comment by lydell** [comment]
Thanks to @mozillazg the “zh-CN” locale is now improved (even though it was already 100%)! (#548)

**Comment by lydell** [comment]
Thanks to @pluser the “ja” locale is now complete! (#549)

**Comment by lydell** [comment]
Thanks to @m-r-r the “fr” locale is now complete! (#550)

**Comment by lydell** [comment]
Thanks to @leVirve the “zh-TW” locale is now complete! (#551)

**Comment by lydell** [comment]
Thanks to @Kambfhase the “de” locale is now improved! (#556)

**Comment by lydell** [comment]
Thanks to @cbertoldi the “it” locale is now complete! (#561)

**Comment by lydell** [comment]
Thanks to @mymedia2 the “ru” locale is now complete! (#567)

**Comment by lydell** [comment]
Thanks to @atilacamurca the “pt-BR” locale is now complete! (#570)

**Comment by lydell** [comment]
It’d be really nice if you who have worked on translating VimFx would share your thoughts on how the process of doing so was to you. Do you think #513 would make things easier, or does it seem overkill for such a small program as VimFx? (There are currently only 102 different strings, many of which are only up to four words each.)

**Comment by Kambfhase** [comment]
I think as VimFX is a small-scale program the ad-hoc approach works best. Letting translators use the editors they prefer, is better than requiring them to learn a new tool *gettext* (or at least for me its new).

Btw, I think the ping in the first post was a really nice idea.

**Comment by atilacamurca** [comment]
One of the things I talk about in #513 is about to know what strings I need to translate, so the way the project is now, I have to check all strings to see what is new. I still think that, even small, it's worth the change.

**Comment by lydell** [comment]
Guess I’m too developer-y/geeky …

```
$ grep -Fxof extension/locale/{en-US,sv-SE}/vimfx.properties
pref.hint_chars.desc=
pref.prev_patterns.desc=
pref.next_patterns.desc=
pref.prevent_autofocus.desc=
pref.timeout.title=Timeout
```

**Comment by benediktg** [comment]
Since it only were a few lines I had to edit, for me it was appropriate to use the „text editor“ integrated in Github. I don't apperciate the use of Transifex since it is not a free (as in freedom) web service and you have to ask for permission to even propose some translations. None of the three translation projects I requested to be a member about three weeks ago of have accepted it yet.

As an alternative I would mention the free web service weblate.org (some free software projects have got hosting here: https://hosted.weblate.org/) since I could at least propose some translations there without the need to register anywhere.

**Comment by lydell** [comment]
It’s awesome to see that all but three locales were updated in just three weeks! Awesome job everyone!

VimFx 0.6.0 has now been released, so I’m closing this one. But updates to locales are of course still welcome, and will be released as soon as possible! (I’m talking to you @thenonameguy, @grn and @sirodoht ;) )

Also thanks @Kambfhase, @atilacamurca and @benediktg for your input regarding the translation experience. Feel free to continue the discussion here and in #513.
