### ISSUE TITLE
misplaced hintchars in hint mode (vimfx dev; ff aurora 43.0a2; win10)

### ISSUE THREAD

**Issue by gregist** [akhodakivskiy/VimFx#554]
screenshot:

![2015-10-23_19-49-50](https://cloud.githubusercontent.com/assets/6292095/10691871/5fa4efbe-79bf-11e5-9f31-d384af55e99e.png)

**Comment by gregist** [comment]
page zoom seems to have caused this issue, still needs fix though.

**Comment by lydell** [comment]
As far as I remember, the hints were slightly off on every odd zoom level, but fine every even level. Do you experience something similar?

**Comment by gregist** [comment]
no. this screenshot is at 80% level, not looking good...
normal 100% is fine though.

![2015-10-23_20-11-42](https://cloud.githubusercontent.com/assets/6292095/10692198/6b24458a-79c2-11e5-8696-9dff3576c2c1.png)

**Comment by lydell** [comment]
Did you zoom _after_ you had entered hints mode?

**Comment by gregist** [comment]
of course not.

are you having trouble recreating this problem?

**Comment by lydell** [comment]
Yes :)

**Comment by gregist** [comment]
Oh, anything that I can do to help you debug it?

**Comment by lydell** [comment]
You could provide the exact commit you use.

**Comment by gregist** [comment]
https://github.com/akhodakivskiy/VimFx/commit/d751835f68b56b7bdea23c77b40b33f2f9447f49

**Comment by lydell** [comment]
Here's another thing you could do:

0. Reset the zoom.
1. Make sure `devtools.chrome.enabled` is set to `true` in about:config.
2. Open the [browser console].
3. Run the following snippet:

   ```
   window.ZoomManager.getZoomForBrowser(window.gBrowser.selectedBrowser)
   ```

   It is supposed to return 1.

4. Zoom in once.
5. Switch back to the browser console and run the snippet again. It is supposed to return something >1 (such as 1.1).
6. Repeat steps 4 and 5 a few times. Also try zooming out.

[browser console]: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console

**Comment by gregist** [comment]
Yes, I tried. The return values are the same as supposed. So?

also, are you using the latest version of aurora? It broke vimperator hint mode since last update. Hence I moved to vimfx...

**Comment by lydell** [comment]
That the zoom level was reported wrongly was the most likely reason for the bug. Now we know it's not that, at least.

I only test in Firefox Stable and Nightly.

**Comment by lydell** [comment]
Do you have the possibility to test Firefox Stable and/or Nighly? That'd be super helpful.

**Comment by gregist** [comment]
nightly works fine! It might be that the aurora guys just messed some scripts up. hopfully this problem will go away on next update.

Thanks for your time. nice porject. :+1:

**Comment by lydell** [comment]
Great to hear! Let's reopen this in the future if needed.

**Comment by gregist** [comment]
I imported my profile to FF nightly and the problem appeared again. Do you
know of any (mis)configurations that might cause this problem?

I have disable all addons except vimfx so it is not likely an addon
conflict.

**Comment by gregist** [comment]
It seems that hint chars shrink/expand to a greater ratio than the zoom
ratio.

**Comment by lydell** [comment]
Ouch. I’ve also run into problems that I could only reproduce in my own profile a couple of times during all the years I’ve been using Firefox. Then I’ve made a new one from scratch, manually installing all add-ons and customizing all options I need…

**Comment by gregist** [comment]
so much pain... #dogeface

thanks anyway.

**Comment by gregist** [comment]
just FYI, the stable version works without a problem under exactly the same
profile.

I will go without gi then...

**Comment by lydell** [comment]
I almost never zoom myself. Since this zoom issue is a deal breaker for you, it sounds as if you use zoom a lot! Do you? Would you mind sharing your zooming habits and the reasons for them? I think I might learn something from it. :)

**Comment by gregist** [comment]
I use my 13 inch laptop a lot, sometimes I want to fit a little more into
one page. so...

In vimperator it is very convenient to switch zoom using +-= keys. any
plans to implelement these in vimfx? :D

**Comment by lydell** [comment]
No plans for zoom keys, but you can add them as [custom commands](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/config-file.md).

**Comment by lydell** [comment]
@gregist I just added zoom commands to that wiki page :)

**Comment by gregist** [comment]
Thanks you.

The native ctl +- is concise enough though.

**Comment by lydell** [comment]
Then why did you ask about plans for implementing them in VimFx?

**Comment by gregist** [comment]
I did not know about it then. sorry, my bad. :)

**Comment by lydell** [comment]
@gregist I think you’re experiencing #594. The quick fix: Disable “Zoom text only”. (Uncheck View > Zoom > Zoom text only).

**Comment by gregist** [comment]
@lydell cool. thanks!
