### ISSUE TITLE
scroll length settings not present in vimfx dev

### ISSUE THREAD

**Issue by gregist** [akhodakivskiy/VimFx#555]
I really miss this feature.

also would anybody please explain to me what ```<force><late><tab>``` means? thanks.

**Comment by lydell** [comment]
Scrolling: https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/options.md#scrolling-prefs

Special keys: https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/shortcuts.md#special-keys

Feel free to continue the discussion here if needed :)

**Comment by NoahTheDuke** [comment]
I can't seem to make the page-distance settings work right. `toolkit.scrollbox.verticalScrollDistance` is what I'm looking to change, right? When I change it, the distance doesn't change on <space>. Have I missed it?

**Comment by lydell** [comment]
> `toolkit.scrollbox.verticalScrollDistance` is what I'm looking to change, right?

I don't know, because you didn't say which commands you are trying to adjust. However, raising `toolkit.scrollbox.verticalScrollDistance` from `3` (the default value) to `30` made the `j` and `k` commands scroll significantly longer for me.

Also, you didn't mention your VimFx version, Firefox version and OS.

**Comment by NoahTheDuke** [comment]
I don't know why I suddenly forgot how to write a proper question. Sorry about that.

My issue and question is thus: I wish to slightly decrease the distance of "page down", either by the key or by spacebar. Changing various options hasn't rendered a solution. Is this an option I can change?

VimFx: 0.9.0, Firefox: 42.0, OS: Windows 7, SP1.

**Comment by lydell** [comment]
That’s currently not possible. Perhaps we should slightly decrease the distance of “page down” by default; I’ve been thinking about this as well.

**Comment by NoahTheDuke** [comment]
Thanks for the consideration. I hope you add something. :-)
