### ISSUE TITLE
f key active when typing

### ISSUE THREAD

**Issue by CryptoCopter** [akhodakivskiy/VimFx#560]
Hello there,

the f key appears to also be active during (some) text input. The cases I notices are when typing in the address bar (not for the search bar though) and the text search field - this makes opening URLs or searching for text with 'f' in them quiet impossible.

VimFX: 0.5.17.1
Firefox: 41.0.2
OS: Ubuntu 15.4
Keyboard Layout: German

**Comment by lydell** [comment]
Hi @CryptoCopter, VimFx 0.6.0 has just been released. Would you like to try it out and check if your issue happens in that version as well?

**Comment by lydell** [comment]
Closing because no response.
