### ISSUE TITLE
Remaping browser:back and browser:forward to work with international keymaps

### ISSUE THREAD

**Issue by frodeseverin** [akhodakivskiy/VimFx#563]
First off, thank you for a nice extension.

Then I have a question. How to move back and forth in the tab browsing history?

https://github.com/akhodakivskiy/VimFx/blob/develop/extension/lib/defaults.coffee
says to use '[' and ']'. This is, however, not working for my Norwegian keymap on Windows. I need to press Alt-Gr + 8 to produce [, and VimFx seems to ignore this keypress alltogether.

Note: defaults.coffe is only present in branch develop?

Anyway, how do I change the keybinding to someting more accessible on my keyboard, i.e. '<'?

**Comment by lydell** [comment]
`[` and `]` finds links to the previous/next page and goes to them. Handy when going through paginated search results.

`H` and `L` go backward/forward in history, which seems to be what you’re looking for.

Yes, defaults.coffee only exists in the develop branch. You might be interested in #535.

How to change keyboard shortcuts? In the stable version, head into VimFx’s settings page in the Add-ons Manager and click the “Customize” button. That’ll open the Keyboard Shortcuts dialog, which both serves as a help screen and as the UI to customize shortcuts. (In the development version all keyboard shortcuts are customized directly in VimFx’s settings page in the Add-ons Manager.)

The stable version has problems with other keyboard layouts than en-US. See #249.
