### ISSUE TITLE
Ability to customize which elements do and don’t get hint markers

### ISSUE THREAD

**Issue by eush77** [akhodakivskiy/VimFx#565]
Add configuration option for custom selectors that should be omitted from `F` key marks, optionally limited by a URL pattern. Alternatively, display “Are you sure?” prompts when selecting elements that match such selectors.

**Use case:** I enjoy using VimFX on GitHub, but not once have I unstarred or starred repositories or posted half-baked posts by mere accident, just pressing the wrong key after `F`. It is so easy to make a mistake it is depressing. In the best case scenario I notice what happened and fix it, but only after it already generated noize in my (and probably others') activity feed. In the worst case the repo disappears from my stars and I wonder what was it when I search for it later. (Luckily, GitHub prompts me anyway when I attempt to delete a repository so the destructive effect is limited, but still.)

I would happily add all buttons (or at least some of them) on GitHub to this blacklist, probably on other sites, too.

**Comment by lydell** [comment]
Interesting! Thanks for such a nicely written feature request. Will need to think about this.

**Comment by lydell** [comment]
We should find a way to provide a public API to frame scripts. Then, in a config file, you should be able to do:

```js
vimfx.addHintsMatcher((commandName, element, {type, semantic}) => {
  // - `commandName` tells which of the `f` commands is being run.
  // - `element` is an element inside the viewport. The function is run once for each such element.
  // - `type` is the type of the element that VimFx has identified, or `null` if VimFx determined it shouldn’t get a hint. Set it to a valid type to add a hint to the element, or to `null` to make sure it does _not_ get a hint.
  // - `semantic` is `true` for elements VimFx considers to be `semantic` (when it comes to clickability), and `false` otherwise. Semantic elements get better hints than unsemantic ones. Update as needed.
  return {type, semantic}
})
```

- Allows to make custom matching both before and after VimFx’s own matching (whichever suits the user’s needs best).
- Very simple to implement.
- Very flexible.

For example, you could use `if (element.matches(selector)) type = null` to blacklist elements based on selectors.

**Comment by eush77** [comment]
This would be awesome to have!
