### ISSUE TITLE
Add a reverse search binding

### ISSUE THREAD

**Issue by RageYL** [akhodakivskiy/VimFx#566]
Hi,

Is it possible to provide a binding for reverse search (equivalent to '?' in vim).
It would work the same as '/' but it would look backward with 'n' and forward with 'N'.

Thanks and good job for this very useful add-on.

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/blob/ce657c3d36b5a87de5141a49ffd0350b86389737/documentation/questions-and-answers.md#will-vimfx-provide-advanced-find-features

**Comment by RageYL** [comment]
I searched only in sources/questions/pull-requests, i forgot the doc.

Sorry i wasted your time.

**Comment by lydell** [comment]
No problem! I don’t expect anyone to have read the docs yet, since they’re written for the development version which isn’t even released yet.
