### ISSUE TITLE
Escape does not exit ignore mode

### ISSUE THREAD

**Issue by LordJZ** [akhodakivskiy/VimFx#568]
8d5fc55f14f24846dcb8b9a4546437d31be47ae7
Windows 10
Nightly 45.0a1 (2015-11-06) / Beta 43
e10s enabled/disabled

The only way to exit ignore (`i`) mode is to click the icon with mouse

**Comment by lydell** [comment]
The default shortcut is `<s-escape>`, not `<escape>`. That can also be seen in the keyboard shortcuts help dialog, and be customized in VimFx’s settings page in the Add-ons Manager.
