### ISSUE TITLE
<force><late> when address bar is selected

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#571]
Thanks for releasing 0.6.0.

The default shortcuts `<force><late><tab>` and `<force><late><s-tab>` for selecting next/previous element do not work well when the address bar is selected.  In other words, one cannot use tab/s-tab to cycle through the address bar auto-completion entries, but instead VimFx's commands takes precedence.

Running Firefox 42 on Arch Linux.

Also, please consider changing the casing of "Hint Chars," "Previous Page Patterns," and "Next Page Patterns" to match with the "default style" (I don't feel like this deserves an issue on its own).

**Comment by lydell** [comment]
Ah, I had no idea you could press `<tab>` to cycle between auto-completion entries in the address bar! Thanks for reporting!

> Also, please consider changing the case of "Hint Chars," "Previous Page Patterns," and "Next Page Patterns" to match with the default style

Sorry, I don’t understand what this means.

**Comment by d125q** [comment]
@lydell Thanks for the super quick response.

What I meant by the casing of those preference options is: the new ones are written in sentence case, i.e. "**I**gnore **k**eyboard **l**ayout", so I suggest that "**H**int **C**hars" is changed to "**H**int **c**hars."  Nothing serious :)

**Comment by lydell** [comment]
Note to anyone stumbling upon this issue:

The workaround until the bug is fixed is to remove the `<force><late><tab>` and `<force><late><s-tab>` from the “Focus next element” and “Focus previous element” commands. The only drawback is that if you focus a text input using `gi`, `<tab>` and `<s-tab>` won’t cycle only through text inputs, but through _all_ elements (as usual).

---

@d125q Thanks for clarifying! Good point, I’ll fix it straight away.

**Comment by izzyleung** [comment]
Question is, I used to use `<esc>` or `<c-[>` to clear the focus on the address or search bar and back to normal mode in the browser.

But now I am not able to do this, so I just wonder if I can achieve this in the coming version of VimFx.

Thank you guys for making this brilliant plugin for Firefox. :-)

**Comment by lydell** [comment]
@izzyleung See #577.

**Comment by izzyleung** [comment]
@lydell Thank you. That solves my problem.
