### ISSUE TITLE
Parsing of blacklist preference does not work well when entering via about:addons

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#573]
Okay, something is very weird.  I created a fresh Firefox profile and installed VimFx.  I went to its about:addons page, and entered `*example.com*` in the Blacklist preference.  Nothing happened -- on the next visit the preference was empty (`extensions.VimFx.black_list` stayed empty, too).  Same with `*example.com*  http://example.org/editor/*`.

After a while, `*example.com*` magically appeared there (and in `extensions.VimFx.black_list`), but I have no idea what caused it to appear out of nowhere.  Can anyone please try to reproduce this?

**EDIT:** Same happens when there are no wildcards, too.

**Comment by lydell** [comment]
Just tried it in Firefox 41.0.2, in a fresh profile, on Trisquel 7. I had no problems whatsoever.

**Comment by lydell** [comment]
I don’t think we’ll be able to reproduce this. Closing.
