### ISSUE TITLE
Custom hint style

### ISSUE THREAD

**Issue by lindhe** [akhodakivskiy/VimFx#574]
I love everything about 0.6, except the new look of the hints. Maybe I have crappy font packages on my end, but the shadow makes the letters too fuzzy to be easily readable. This could be resolved by being able to set a custom font style (and why not color options too, while we're on it).

**Comment by akhodakivskiy** [comment]
Feel free to submit your font/style suggestion to change the global styles.

**Comment by lindhe** [comment]
Hm, maybe next year. :) I'm studying 125 % atm. Makes it hard to keep up with side projects like this.

Exceptional work with [the latest release](https://youtu.be/StTqXEQ2l-Y) btw!

**Comment by lydell** [comment]
It is possible to change the appearance of the hint markers: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/styling.md

Would you mind posting a screen shot of what it looks like on your machine? Here’s what it looks like for me:

![](https://addons.cdn.mozilla.net/user-media/previews/full/168/168128.png?modified=1447096855)

I’m glad that you like the new version! (Bonus points for referencing one of my favourite movies!)

**Comment by lindhe** [comment]
Yeah, I just found that! I'll look into it tomorrow, That is probably what I'm looking for.

This is wat it looks like to me:
![screenshot from 2015-11-09 22-45-48](https://cloud.githubusercontent.com/assets/7773090/11047644/ebdf1e2e-8733-11e5-913b-44340fa16cc2.png)

**Comment by lydell** [comment]
As you can see in my screen shot, there’s no shadow at all. I just checked the code: We don’t add any shadow. Looks like the shadow is inherited, perhaps from that light-weight theme you’re using?

- What operating system do you use?
- Would you mind disabling your light-weight theme (or try VimFx in a new profile) to see if that’s the cause?
- Can you try to add the following code to custom styling and see if it removes the shadow? If so, we should add that to the default styles. It looks horrible in your screen shot.

  ```css
  #VimFxMarkersContainer .marker {
    text-shadow: none;
  }
  ```

**Comment by lindhe** [comment]
Yes, it was because of my theme. I guess I'll have to live without that then. This is obviously not your fault, but the theme that does some black magick.

I'm running Arch Linux btw.

**Comment by lydell** [comment]
Considering that that theme is one of the most popular, I added a reset for `text-shadow`. Thanks for reporting it! The default experience is important.

**Comment by lindhe** [comment]
Wow, this was interesting. I think disabling the theme made hint generation quicker.

**Comment by lydell** [comment]
Might be because of the text-shadow. The biggest reason the hint markers do not look the same in 0.6.0 is performance: They used to have more “expensive” styling such as box-shadow, text-shadow (although very slight) and border-radius.

**Comment by lydell** [comment]
Just realized that the same things happens for the Keyboard Shortcuts help dialog as well, and pushed a commit for it.
