### ISSUE TITLE
Location bar ESC map

### ISSUE THREAD

**Issue by mcchrish** [akhodakivskiy/VimFx#577]
I used to be able to map `<c-c>` or `<c-[>` to unfocus the location bar. After I was updated to 0.6.0 this doesn't work anymore. How can I use other keys to unfocus from the location bar without using the ESC button?
Also, how can I unfocus from a text input?

**Comment by tsyim21** [comment]
Same issue here. Can no longer use <c-[> even with it keybinded everywhere <escape is>

**Comment by lydell** [comment]
The esc command used to be a special case, but isn't anymore. `<force><c-c>` and `<force><c-]>` should work. You may read more about `<force>` here: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/shortcuts.md#force
