### ISSUE TITLE
Option to wrap when selecting tabs even when count > 1

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#578]
At the moment, wrapping occurs if and only if [the counter is set to 1](https://github.com/akhodakivskiy/VimFx/blob/master/extension/lib/commands.coffee#L181).  Would it be possible to add an option to explicitly wrap around even when the counter is greater than 1? For example, pressing `2gt` at the moment while on the last tab will do nothing, whereas having this option on would make it move to the second tab.

**Comment by lydell** [comment]
Would you mind stating your use case?

**Comment by d125q** [comment]
Well, if you ask me, it is pretty unintuitive to be at the last tab, press `2gt`, and stay there (whereas a simple `gt` would wrap around and get you to the first tab).

**Comment by lydell** [comment]
What about when you’re _not_ at the last tab?

**Comment by d125q** [comment]
Well, Pentadactyl (and apparently Vimium) wrap around in that case, too.  I'm not too sure.  It may be convenient, it may be not (i.e. one might "overshoot").  Maybe make it so that wrapping occurs only when at the last tab?

**Comment by lydell** [comment]
Hmm, your idea about only when at the last tab sounds good.

**Comment by d125q** [comment]
Let's not forget the *first* tab, too, in the case of `gT`.

**Comment by lydell** [comment]
Good point.

**Comment by d125q** [comment]
Okay, so I guess a nice condition for wrapping would be `(at the first tab AND moving in the negative direction) OR (at the last tab AND moving in the positive direction)`.  I guess one could also wait to see what others think about it.
