### ISSUE TITLE
let shift change whether a link will be opened in current or new tab

### ISSUE THREAD

**Issue by janek-warchol** [akhodakivskiy/VimFx#579]
When I open a page and want to follow a link on it, I can press `f` or `F` - but I need to know beforehand whether I want to open this link in the same tab or in a new one.  What about making shift change this behaviour dynamically?  E.g. if I press `f` and type hint without shift, it follows the link in current tab, but if I type a hint with shift, it will open that link in a new tab.

Similarly, if I press `F` or `af` and decide that I want to follow the link in the same tab after all, I can just type its hint with shift.  What do you think?  To me it looks quite vimish, and doesn't seem to conflict with any part of current interface.

Thanks for making VimFx!

**Comment by janek-warchol** [comment]
PS I just found out that Vimium (for Chrome) has such functionality :)

**Comment by lydell** [comment]
This is already supported. See the end of this section of the documentation: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/commands.md#the-f-commands-1

**Comment by benjiyo** [comment]
The trick to press ctrl and then the letters on the link should be mentioned in the help box! And why didn't you just say that ctrl worked instead of just linking to the docs ;)
