### ISSUE TITLE
Support different keyboard layouts with something like vim's `langmap`

### ISSUE THREAD

**Issue by janek-warchol** [akhodakivskiy/VimFx#580]
I use a different keyboard layout - in particular, I have hjkl keys in different positions on the keyboard, which makes using them for navigation inconvenient.  Of course, I could remap each of VimFx's keyboard shortcuts, but that would be a lot of remapping (especially painful when I swich computers often...).  Maybe VimFx could have something like vim's `langmap`, which allows to remap the whole keyboard layout (i.e. I could specify that in all shortcuts pressing `h` should work like pressing `y` etc)?

Thanks!

**Comment by lydell** [comment]
You're looking for the [Ignore keyboard layout](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#ignore-keyboard-layout) option.
