### ISSUE TITLE
Cannot return to normal mode with an input element in focus

### ISSUE THREAD

**Issue by abastardi** [akhodakivskiy/VimFx#583]
In the previous release of VimFx, if an input element was in focus, you could hit <escape> and it would return to normal mode (input element would lose focus). With this new release, neither <escape> nor <s-escape> will force a return to normal mode. With an input element in focus, as far as I can tell, the only way to return to normal mode is to use the mouse to click somewhere on the page (or tab to the next available non-input element). Am I missing something?

For now, I have reverted to the previous release.

**Comment by lydell** [comment]
The same underlying issue as in #577.

I’ll write a migration script so people don’t keep getting bitten by this.
