### ISSUE TITLE
Pressing `<Esc>` in Developer Tools to show/hide console

### ISSUE THREAD

**Issue by darvelo** [akhodakivskiy/VimFx#586]
As in #572, I'm really used to pressing `<Esc>` in Developer Tools to show/hide the console as a split within the Tools tab that I'm using (usually the Inspect tab). I've already set `<force><escape>` on `Blur/close active element` to preserve blur on the AwesomeBar if that's somehow related. Not sure if a special-case is needed like in 56c4b7c514ea8b58d2cdcecf3d2654648c48ca31 or if I can work around it somehow in settings.

VimFx: 0.6.1
Firefox: 42 and Developer Edition, e10s multi-process disabled
OS: Linux
Keyboard Layout: US English

**Comment by lydell** [comment]
Exactly this case _is_ special-cased in the code: https://github.com/akhodakivskiy/VimFx/blob/bb948cb85eb3b71c0a90321f45862e26935fb223/extension/lib/modes.coffee#L94-L97:

```coffee
      # However, an exception is made for the dev tools (<c-K>).
      # There, trying to unfocus the dev tools using Escape would annoyingly
      # open the split console.
```

If `<escape>` _did_ toggle the split console, how would you unfocus the dev tools?

**Comment by darvelo** [comment]
I'm not really sure the best way to handle it... When I want to scroll the page with the dev tools open I either use the mouse or close the dev tools with F12 first. For me the split console is super important because of the easy way to select an element in the Inspect tab and use `$0` to reference it in the console. It's also [useful for debugging](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Split_console).

This goes without saying but, thanks so much for all your hard work on VimFx. I've used it for a year and it's one plugin I can't live without.

**Comment by lydell** [comment]
I looked a bit more into this. Removing the special case from the code is not enough. Then, `<escape>` does open the split console, but it gets unfocused immediately. To fulfil your request, we’d need to detect if the dev tools are open and in the Inspector tab and if so do nothing. Hmm.

Not being able to unfocus the dev tools inspector using `<escape>` nearly drove me insane for a while, so when I fixed it (according to my point of view) it was a great relief. Apparently you don’t agree.

I don’t use the split console. I prefer the “regular,” large console. I use `<c-K>` to switch to the console, and `<c-C>` to switch to the inspector.

**Comment by darvelo** [comment]
I see what you mean. In general it would be cool if native mappings and preferences could work, but I'll go with your workflow while waiting for more discussion (if any) to arrive, or until time allows for more niche stuff like this to happen. So far, though, great work with VimFx.

**Comment by lydell** [comment]
> In general it would be cool if native mappings and preferences could work

I agree 100%. That's one of the top goals of VimFx. But in this case I don't know what to do :( Any help and ideas welcome!

**Comment by darvelo** [comment]
I wish I could help but I'm really, really busy! In the meantime I've mapped "Return to Normal mode" back to `<s-escape>` which helps. :)

**Comment by darvelo** [comment]
@lydell Do you think this might be solved with a new keymapping: "Run one Ignore Mode command"? It could allow a single keypress/key combination then return VimFx to normal mode. It might work like this:

1. Press F12 to open Dev Tools.
2. Run one Ignore Mode command, press `<Esc>` to open split console, VimFx stays active (`<Esc>` now would unfocus dev tools)
3. Type whatever in console
4. Run one Ignore Mode command, press `<Esc>` to close split console, VimFx stays active

I've recently discovered the `zF` shortcut which lets me refocus the Dev Tools after pressing `<Esc>` in normal mode. That's just brilliant. This plugin just keeps getting better.

**Comment by lydell** [comment]
You're looking for the `I` command. Also, you can re-focus the console with `<c-K>`.

**Comment by darvelo** [comment]
You're right. It seems VimFx enters a kind of suspended state when inside a textbox, and `<esc>` unfocuses the textbox wakes it up. But in order for this to work, we would need to have VimFx in ignore mode before we hit escape, but VimFx doesn't take commands (to press `I` or a remap to something like `<c-x>`) when in this suspended state..

I guess this has no solution. I'm closing it for this reason and lack of public interest. Thanks for trying, though. :)

**Comment by lydell** [comment]
You _can_ use VimFx commands in text inputs: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/shortcuts.md#force

You could also try making a custom command that sends a fake `<esc>`, a bit like in #642.

**Comment by darvelo** [comment]
Ah, now I understand how useful `<force>` is. Thanks, it worked. :smile:

**Comment by lydell** [comment]
Glad to hear, @darvelo! Would you mind sharing your solution, so others finding this issue can benefit too?

**Comment by darvelo** [comment]
Sure. I set `Pass next keypress through to the page` to `I <force><c-x>`. I then:

1. Press F12 to open the devtools
2. Press `<c-x><esc>` to open and use the split console
3. Press `<c-x><esc>` to close the split console

To me this is an improvement over setting the normal mode mapping to `<s-esc>`. It's consistent, and I can use VimFx to scroll and use  the page and `<c-K>` to get back to the split console when I need to.
