### ISSUE TITLE
Cannot assign commands to Number Keys

### ISSUE THREAD

**Issue by betamint** [akhodakivskiy/VimFx#587]
Thanks for release 0.6.1.

Number keys 1-9 cannot hold commands. I see there's a new feature for "counts" #374 in 0.6.0. It seems "counts" override commands.

When assigned to a command, number key should perform the command rather than counts. It used to work before 0.6.0.

Running Firefox 41 on openSUSE.

**Comment by lydell** [comment]
This used to work, but unfortunately regressed before 0.6.0 was released. Thanks for spotting.
