### ISSUE TITLE
All links with href="#?" get the same hint

### ISSUE THREAD

**Issue by knobhead** [akhodakivskiy/VimFx#596]
Hi, thanks for this wonderful tool, I can't imagine working without it anymore! :+1: :bow:

Unfortunately the recent update (on a clean profile FF 42/Win7 ) broke hinting for me, because all links on a page that have ```href="#"``` now get assigned the same hint key. Especially on javascript-heavy pages/web-apps this renders VimFx close to useless, because many ```<a>```-tags that have ```onClick=""``` events use the empty "#"-anchor for their ```href=""```)

Expected (and previous) behaviour is for all links that have ```href="#"``` to get a separate hint.

In general it might be efficient to give the same hint key to links with identical ```href=""```-attributes, but just not for ```href="#"``` :)

Any ideas?

BTW: This might be related to #584 ?

**Comment by lydell** [comment]
No, this is not related to that issue. VimFx already makes sure that links with `href="#"`, `href=""` and `href="javascript:"` are given the same hint, for exactly the reason you state, so you’ll have to give me a specific URL where it happens; probably that site uses some variation that we don’t catch yet.

**Comment by knobhead** [comment]
Hi Simon,
wow, you're quick. Unfortunately it's an internal application with a rather oldish (around 2004-7) and crappy web front-end), so I can't give you a link. But I'll dig into it and try to find the changes in VimFx code. Funny thing is that it used to work in the last version. 
Cheers,
Philipp

**Comment by lydell** [comment]
> Funny thing is that it used to work in the last version.

The feature of giving the same hint to links that go to the same place didn’t exist then.

---

One thing you could do is to post the HTML of some of those links. If we’re lucky that’ll be enough to debug.

**Comment by lydell** [comment]
Oops, just saw that you edited the issue title. Do the links have `href="#?"`? I’ve never seen that pattern before. That case is not covered.

**Comment by knobhead** [comment]
```html
<a href="#?" name="GoTo_LISSH_SimpleSearch" starweb_type="Action Trigger" onclick="caSubmit(this,self,'411','','','','_self','false',false,undefined)" language="JavaScript">
» Einfache Suche
</a>
```

That code sure is a mess.

**Comment by lydell** [comment]
Thanks! Should be as easy as adding `#?` to the exclusion list then.

**Comment by knobhead** [comment]
whoop-whoop! awesome :+1: where can I donate without paypal? :)

**Comment by lydell** [comment]
I’m afraid there is no way of donating without PayPal. But you’ve already encouraged me by writing a great bug report and being very quick to reply :)

**Comment by bodqhrohro** [comment]
I've got the same issue but with `#form` anchor and different `onclick` handlers. It seems this is not enough to exclude several anchors because modern sites frequently use the hash navigation and there can be several links with the same anchor and different functions for some reason.

**Comment by lydell** [comment]
@bodqhrohro URL, please.

**Comment by lydell** [comment]
Btw, the workaround is to focus the link using `zf` and then activating it using `<enter>`.

**Comment by bodqhrohro** [comment]
F. e. https://neboard.me/thread/30467/

The workaround works, thanks.

**Comment by lydell** [comment]
Thanks @bodqhrohro, but I have a hard time finding the problematic links there. Could you post a screen shot where you’ve marked some of them, please?
