### ISSUE TITLE
Ignore Mode workflow

### ISSUE THREAD

**Issue by BohrShaw** [akhodakivskiy/VimFx#597]
I suggest the following change:

- `<Escape>` to exit the Ignore Mode entered by `i`.
- `<S-Escape>` to exit the Ignore Mode entered by `I`

Reason:

1. This is compatible to the behavior of Vimium, which would make my whole experience better.
1. I generally prefer residing in Ignore Mode for a while, rather than passing through a single key.
1. The keys happen to be symmetric, which is good for mnemonic.

**Comment by lydell** [comment]
I don’t understand. Marking as wontfix until convinced.
