### ISSUE TITLE
<force><late><tab> breaks KeePassX Autotype

### ISSUE THREAD

**Issue by xconstruct** [akhodakivskiy/VimFx#599]
Hey, got a new bug that conflicts with KeePassX :)

KeePassX Autotype normally inserts a sequence of `username<tab>password<enter>` into text fields to handle auto-login. When using the default `<force><late><tab>` shortcut for Focus Next Element, the tab-character is ignored, so the whole "usernamePassword" gets written into the username-field only.

If I remove the shortcut, it works again, so no big deal for me, just letting you know. The problem occurs on both 0.6 and 0.6.1

Thanks!

**Comment by lydell** [comment]
Sigh. This special behavior of `<tab>` after`gi` is starting to get really annoying. Hope people enjoy it.

**Comment by xHN35RQ** [comment]
I have this same issue. However, removing `<force>` from 'Focus Next Element' fixes the issue. `<late><tab>` works fine with KeepassX.

**Comment by lydell** [comment]
@xHN35RQ The “Focus previous/next element” commands work _exactly_ like Firefox’s native `<tab>`/`<s-tab>` (or, rather, are _supposed_ to…), _except_ that if you’ve focus a text input using `gi`, the two commands change into “Focus previous/next **text input** (ignoring other focusable elements)”. That exception is the only reason the commands exist. And it also makes them need `<force>`.

**Comment by xHN35RQ** [comment]
I understand now. Thanks for explaining! :smile: For now I've rebound "Focus previous/next text input" to `<force><a-j>`/`<force><a-k>` since I actually prefer unique keybinds and prefer to leave native `tab`/`s-tab` in place.

Thanks again for all the explanation, and for `gi` - it's definitely a handy tool. With my re-binds it works well. :+1:

**Comment by lydell** [comment]
> I've rebound "Focus previous/next text input" to <force><a-j>/<force><a-k> (as recommended in the docs)

You misread the docs. The docs give an example of adding `<force><a-j>` and `<force><a-k>` as complements to, or replacements for, `J` and `K`.

**Comment by xHN35RQ** [comment]
Oops. I see that now. Thanks for clarifying.

**Comment by lydell** [comment]
I've started experimenting on reworking `<tab>` handling: #603.

**Comment by xHN35RQ** [comment]
:+1: nice
