### ISSUE TITLE
Next/Previous page not working properly 

### ISSUE THREAD

**Issue by alx741** [akhodakivskiy/VimFx#602]
I think i just found a bug, hope is not a false alarm.
I was browsing `Vimscript the hard way` by Steve Losh and tried to go to the next page from the chapter 8 to 9 but it just scroll half page down. It works ok in the rest of the pages.

This is the page where it stop working: http://learnvimscriptthehardway.stevelosh.com/chapters/08.html

Pressing `]` takes me here: http://learnvimscriptthehardway.stevelosh.com/chapters/08.html#more-abbreviations

When moving through the other chapters it works flawlessly.

**Comment by lydell** [comment]
Thanks for your report!
