### ISSUE TITLE
Can't blur comment field with Esc on facebook

### ISSUE THREAD

**Issue by lindhe** [akhodakivskiy/VimFx#604]
When I click the comment field it is focused, but I can't blur it by pressing <kbd>Esc</kbd>. I have to click somewhere else or tab out of it. This is not the case if I disable VimFX.

I have "Blur/close active element" set to <code>\<force\>\<escape\></code> in VimFX preferences.

Off topic: A bit ironic that I've also reported #524 - I can neither focus the input field nor blur it. :P

**Comment by lydell** [comment]
Hehe, what on earth are Facebook doing to their text inputs? :)

**Comment by lindhe** [comment]
I think this shouldn't be labled as enhancement, but as a bug. Something is broken. Fixing something that is broken is technically an enhancement, but... ;)

**Comment by lydell** [comment]
Compromise.

**Comment by lindhe** [comment]
Lol

**Comment by lindhe** [comment]
This also seems to be the case in the input field on Google Hangout chats on gmail.com. Kind of obscure.
