### ISSUE TITLE
Allow gJ and gK to only cycle between non-pinned tabs

### ISSUE THREAD

**Issue by kikiotsuka** [akhodakivskiy/VimFx#606]
I tested moving a tab left/right on 5 pinned tabs + 2 regular tabs and I cannot move a tab to the right of the regular tabs.

I tested it once more on 5 pinned tabs + more than 10 regular tabs, and I cannot move a tab to the right of the 9th tab.

Additionally, moving a tab can change it from a regular to a pinned tab. Is there a way this can be changed so that it only wraps within the regular tabs/pinned tabs?

**Comment by lydell** [comment]
Do you use Tab Groups?

> Additionally, moving a tab can change it from a regular to a pinned tab. Is there a way this can be changed so that it only wraps within the regular tabs/pinned tabs?

Currently not.

**Comment by kikiotsuka** [comment]
Yes I use tab groups.

**Comment by lydell** [comment]
About tab movement and Tab Groups: See #462.

**Comment by lydell** [comment]
Perhaps this makes more sense:

- If the current tab is pinned, `J` and `K` should only cycle between pinned tabs only.
- If the current tab is _not_ pinned, `J` and `K` should cycle between non-pinned tabs only.
- Use `gp` explicitly if you want to change the pinned state.
