### ISSUE TITLE
Commands do not work with non-english keyboard layout

### ISSUE THREAD

**Issue by hdghg** [akhodakivskiy/VimFx#607]
It worked well a few days ago, but after one of the recent updates it got broken. (The update that enlarged markers)

Environment: OS: Ubuntu 15.04, 14.04 LTS. Browser: Firefox updated to last version via update manager. desktop environment: mate. Keyboard layout: ru. VimFx: 0.6.2

How to reproduce:
1. Start browser and follow [google](http://google.com/) url
2. Switch keyboard to russian
3. Press f or F.
Markers are not shown

**Comment by lydell** [comment]
Enable the [Ignore keyboard layout option](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#ignore-keyboard-layout).

**Comment by seniorivn** [comment]
@lydell this solution not work for not qwerty layouts, is it possible to edit this hardcoded layout? or solve this problem any other way?

**Comment by lydell** [comment]
From the link I gave you in the last comment:

> (If you’d like VimFx to pretend that some other keyboard layout than the standard en-US QWERTY is always used, you may do so with the special option [`translations`].)

[`translations`]: #translations

Feel free to ask here if you need more help.

**Comment by hdghg** [comment]
Thanks

**Comment by hdghg** [comment]
I have enabled this. Now my capslock doesn't work as escape (It was remapped to escape in my environment). I'll try to remap it at lowlevel configuration later.

**Comment by lydell** [comment]
Adding something like `"CapsLock": "Escape"` to your `translations` should do the trick, no?

**Comment by hdghg** [comment]
I think I managed to solve it replacing <escape> to <capslock> in my plugin config.

**Comment by hdghg** [comment]
Cannot install API extension to firefox. As soon as I restart firefox, directory named {ec8030f7-c20a-464f-9b0e-13a3a9e97384} is removed from my /home/hdghg/.mozilla/firefox/xcmlvxjt.default/extensions. If it is named ec8030f7-c20a-464f-9b0e-13a3a9e97384, it isn't removed, but no "Hello, world!" output to console.

**Comment by hdghg** [comment]
Got it. It should have been named VimFx-custom@vimfx.org

**Comment by lydell** [comment]
... or whatever you choose in install.rdf as mentioned in the docs

**Comment by hdghg** [comment]
Since you are here can you please tell me where to put "CapsLock": "Escape" in theese files?

**Comment by lydell** [comment]
```js
vimfx.set('translations', {
  'CapsLock': 'Escape',
})
```

anywhere in vimfx.js

**Comment by hdghg** [comment]
Thank you one more time, it finally works as I wish.
