### ISSUE TITLE
Show if currently in "insert mode"

### ISSUE THREAD

**Issue by hdghg** [akhodakivskiy/VimFx#608]
It's easy to get confused and pass a series of commands to page instead of typing.
I suggest to display current mode in icon.

**Comment by lydell** [comment]
The [button](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/button.md) becomes red in Ignore mode. What are you suggesting?

**Comment by hdghg** [comment]
I'm suggesting to add one more colour state in input mode, when textbox selected. Textbox may be selected in top of page, outside of my visible square, so icon could be helpful.

**Comment by lydell** [comment]
Good idea!

**Comment by sammcj** [comment]
+

**Comment by hdghg** [comment]
Ah, it's so gratifying. Thanks, I misstype more rarely now.
