### ISSUE TITLE
Text input autofocus disable not working after Google search

### ISSUE THREAD

**Issue by jbodah** [akhodakivskiy/VimFx#609]
I swear that with a previous version I was able to do the following:

* Go to google.com
* Type `hello<Enter>` to search for "hello"
* `vf` to show highlights
* Go to link

Now it seems that even with autofocus disabled that doing this will cause "vf" to appear in my search bar instead:

<img width="776" alt="hello_fresh_-_google_search" src="https://cloud.githubusercontent.com/assets/6093002/11146784/4db92768-89df-11e5-9c55-22f5ab199a13.png">

FF 42.0
OSX 10.10.5
VimFx 0.6.2

**Comment by lydell** [comment]
`vf` has been changed to `zf`. This is mentioned in the changelog.
