### ISSUE TITLE
Switch to absolute tab index using counts

### ISSUE THREAD

**Issue by iven** [akhodakivskiy/VimFx#610]
Currently we can use `g0` and `g$` to switch to the first and last tab. It'll be great if we can use `4gt` to switch to the fourth tab, like in pentadactyl.

**Comment by d125q** [comment]
Counts do work since version 0.6.0, but `[n]gt` at the moment means move to the n-th tab from the current on the right (or the last one; see #578 for discussion on wrapping).

Maybe counts can be added to `g0`, `g^`, and `g$` to allow for "absolute" indexing (i.e. `[n]g0` goes to the n-th tab, `[n]g$` goes to the n-th tab from the end)?

**Comment by iven** [comment]
Oh sorry, I was using an old version when I found this feature missing.

Should we make `[n]gt` behave the same with vim, which uses absolute indexing, and use another shortcut to represent the relative indexing?

**Comment by lydell** [comment]
The behavior of `[count]J` and `[count]K` won’t change. We’re following Vimium’s lead here.

> Maybe counts can be added to `g0`, `g^`, and `g$` to allow for "absolute" indexing (i.e. `[n]g0` goes to the n-th tab, `[n]g$` goes to the n-th tab from the end)?

Great idea!

**Comment by lydell** [comment]
In the development version you can add custom commands if you want a 100% vim-style `gt`, using something like the following:

```js
let {commands} = vimfx.modes.normal
vimfx.addCommand({
  name: 'tab_select_next_absolute_count',
  description: 'Next tab',
  category: 'tabs',
  order: commands.tab_select_next.order + 1,
}, (args) => {
  let {count = 1} = args
  if (count === 1) {
    commands.tab_select_next.run(args)
  } else {
    commands.tab_select_first.run(args)
  }
})
```
