### ISSUE TITLE
Start in 'ignore mode' or easily customisable toggle for it?

### ISSUE THREAD

**Issue by sammcj** [akhodakivskiy/VimFx#612]
I want to use vimfx but it's really frustrating that it starts in command mode and there doesn't seem any way to change this behavior.

I'd like to choose to start it in ignore mode by default and toggle vimfx on with say the the shift key or something similar to that.

I appologise if there is a way to do this and I've missed it.

**Comment by lydell** [comment]
Set the [blacklist](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#blacklist) option to `*`.

**Comment by sammcj** [comment]
Oh! thanks, that's great :)
