### ISSUE TITLE
Ctrl-^ switch recent tab

### ISSUE THREAD

**Issue by alx741** [akhodakivskiy/VimFx#613]
Months ago i was a `vimperator` user, a nice feature it has is to switch to the last used tab with `ctrl-^` as in vim *edit alternative file*. 

This is useful when:  Open a new tab with `t` and then what to come back to the tab you were before that using `ctrl-^`.

I would love this feature to be implemented in VimFx.

**Comment by lydell** [comment]
I think this is a duplicate of #319.
