### ISSUE TITLE
Going 'back' doesn't work

### ISSUE THREAD

**Issue by DavidVentura** [akhodakivskiy/VimFx#618]
Hi. I can't navigate backwards/forwards with my keyboard layout, to type "[" or "]" I must press shift-{, and it doesn't seem to work. Pressing mouse4/5 does go backwards/forwards so it's exclusively something to do with the addon/layout

**Comment by lydell** [comment]
Duplicate of #563.

**Comment by DavidVentura** [comment]
You are right. This plugin is awesome, thanks
