### ISSUE TITLE
Guide to key symbols?

### ISSUE THREAD

**Issue by Noitidart** [akhodakivskiy/VimFx#620]
Is there a guide that explains what difference is between comma and plus? And also like what is the `$`. I can't figure out what to do for `gx$`

**Comment by loops** [comment]
Hi there,

If you press ? you'll get a page that desccribes a couple of the things you're asking:

gx$  closes all the tabs to the right of the current tab.
$  scrolls to the far right.

I'm not sure what you're asking about the comma and the plus though.

**Comment by Noitidart** [comment]
Oh thanks, I thought dollar sign meant like hold shift or something like that. Didn't know i really had to press dollar sign. Thanks!
