### ISSUE TITLE
add 'Up' navigation autodetection

### ISSUE THREAD

**Issue by nilsbecker** [akhodakivskiy/VimFx#623]
i just discovered the 'next', 'previous' navigation via the `[`, `]` shortcuts, which is great. (incidentally, the fact that the 'next', 'previous' patterns are what is accessed via '[', ']' is not obvious from the preferences dialog.)

many webpages that have 'next', 'previous' navigation also provide an 'up' navigation button to navigate a tree-like hierarchy of webpages. e.g. the api documentation of programming languages, or navigation of directories via http. it would be great if the `[`, `]` navigation could be extended also to feature 'Up' auto-detection. not sure about the shortcut key, maybe `u` (this is what NERDtree uses)

**Comment by lydell** [comment]
Have you tried the `gu` command?

> the fact that the 'next', 'previous' patterns are what is accessed via '[', ']' is not obvious from the preferences dialog.

What is "the preferences dialog" ans what is unclear?

**Comment by nilsbecker** [comment]
ok, `gu` seems to do the trick. it's probably ok for almost all cases -- although it's not strictly the same thing: the 'Up' link does not always have to point at the url minus the last token. anyway, probably, `gu` is good enough

what i called "the preferences dialog" is just what you get when you go to `about:addons` and then press the preferences button for vimfx. 

at the top of that page, one can configure patterns to be matched 'next', '>' and so on. way down the page, the shortcut keys for that functionality can be configured. to me, at first it was not clear what the patterns even did...

**Comment by lydell** [comment]
Did you read the documentation?

**Comment by lydell** [comment]
I'm afraid that there isn't enough space in VimFx's settings page in the Add-ons Manager to do anything more. The documentation should add up for it.

Anyone is free to suggest improvements here, but I'm closing for now.

**Comment by nilsbecker** [comment]
i admit i did not read the docs. one suggestion might be to give a name to the feature, like 'auto-navigation' or 'auto-page-flipping' and use the same name both in the title for the pattern match and for the shortcuts.
