### ISSUE TITLE
unresponsive in first tab of a new window

### ISSUE THREAD

**Issue by loops** [akhodakivskiy/VimFx#624]
After opening a new window, VimFX doesn't recognize any keystrokes at all.  Using the mouse to open a second tab, and close the original tab restores everything to working order.  Anyone else seeing this?

**Comment by lydell** [comment]
VimFx version, Firefox version, multi-process enabled, OS version

**Comment by lydell** [comment]
Likely the same issue as #569 (see the end of the discussion).

**Comment by loops** [comment]
Hi Simon,

Sorry for not including proper information the first go round, I somehow felt this must be a local problem.

VimFX:  0.7.3
Firefox:  42.0
Multi-process:  Don't think this version even supports it??
OS:  Fedora Linux 4.2.6-300.fc23.x86_64 SMP
browser.tabs.remote.autostart:   false

When opening the new window the VimFX icon looks normal, not greyed out, but clicking it does nothing.  Will try your debug keylogging version you posted in the #569 thread and report back if the console output looks interesting at all.

Thanks

**Comment by loops** [comment]
So I will post the whole log, but this stands out;

```
NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED)        bootstrap.js:26:0
[nsISyncMessageSender.sendSyncMessage]
```
which is from the line:

```
    data = sendSyncMessage('VimFx:tabCreated')[0];
```

**Comment by loops** [comment]
So I modified the code to loop around until sendSyncMessage doesn't throw an exception.. only ever takes one extra iteration... and doesn't help the problem at all.  VimFX still totally unresponsive on that first tab.  Sorry for the red herring.  

If you can give me any guidance on what would be helpful to debug this, i'm happy to spend some time on it.

Cheers.

**Comment by lydell** [comment]
From the log it looks like you tried to press `<a-f>` and `<a-x>`. Perhaps it is only an issue with shortcuts including the alt modifier? Have you tried a simple “just a letter” shortcut? (You probably have, but I had to ask.)

How do you open the new window?

**Comment by loops** [comment]
Sorry that log was a bit of a red herring all over.. it was actually for the entire browser, rather than just that one unresponsive tab.  So the `<a-f>` was me opening the file menu to select "New Window".  Once inside that window, in the unresponsive tab, nothing at all was registered in the console log, not any keystroke, single, or otherwise.  It's like VimFX isn't registered in that tab at all.

**Comment by lydell** [comment]
Does this happen in 0.8.0 as well? That version has touched the window handling code quite a bit, so there’s at least a chance things have changed here too.

**Comment by loops** [comment]
Unfortunately there's no change with 0.8.0.  This probably doesn't have anything to do with VimFX in a way.  Nobody else seems to be complaining about this issue.  Maybe it's a Firefox on Fedora specific problem.  Not sure.  But for whatever reason VimFX is just not processing any keystrokes in that initial tab at all, no matter what I try.

I've just gotten used to typing   ^T [ESC] J ^W  after opening a new window and everything works fine from there on out.

**Comment by loops** [comment]
Hi there,

Okay, mystery solved on this one.  This is a bad interaction with another addon that I am using "Beyond Australis".  However, things work fine as long as VimFX is installed first!

If you happen to have installed Beyond Australis first, then all you have to do is go into the addon manager, and disable, and then reenable "Beyond Australis", which acts a bit like uninstalling it, and then reinstalling it (but quicker and keeps all your settings).  From then on out, there is never a problem with the first tab and VimFX.

Looking at what is going on, it seems that addons are "bootstrapped" upon startup of Firefox in the order in which they were installed.   There is a list of addons that need to be initialized each time Firefox is started.  When you install a new addon, it is appended to the end of this list.  Thus, if you install VimFX after having installed all your other addons, it will be initialized LAST, and obviously it then has to contend with any strange interaction with every other plugin having already been started up before it.

So the moral of the story is...  always install VimFX as your very first addon, before installing anything else.  This will ensure that it is first in the list to be initialized each time Firefox starts up.

This issue can be closed.

**Comment by lydell** [comment]
- A takeaway: Always try to reproduce bugs in  a clean profile.
- Ideally, add-on startup order shouldn’t matter, so we should find out how “Beyond Australis” breaks VimFx, and fix it, or, most likely, ask “Beyond Australis” to fix it.
