### ISSUE TITLE
export

### ISSUE THREAD

**Issue by tmos** [akhodakivskiy/VimFx#625]
Hi,

I have customized a lot of the keys used in VimFX (dvorak keyboard here), and I would like to export my customs to be used in all my computers.
Could you tell me where is the config file ? Or maybe an option to export this if it doesn't exists ?

Thanks :)
Tom

**Comment by lydell** [comment]
I'd recommend writing a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md).

You could also copy your entire profile between computers, or use an extension such as [OPIE](https://addons.mozilla.org/firefox/addon/opie/).

See also #245.
