### ISSUE TITLE
When holding keys to scroll the scrolling quickly stops (while tapping at intervals works) in multi-process Firefox

### ISSUE THREAD

**Issue by Pratyush** [akhodakivskiy/VimFx#627]
Hi,

I'm using VimFX 0.7.3 on Firefox Nightly 45.0a1, and I can't seem to scroll properly. Holding j/k doesn't scroll like holding up/down does. It scrolls for one steps, and then stops moving. Thanks!

**Comment by lydell** [comment]
I think this only happens in multi-process Firefox.

**Comment by lydell** [comment]
Current workarounds:

- Turn off multi-process-
- Use Firefox's native scrolling with the arrow keys.
- Take the opportunity to practise getting rid of the subjectively bad habit of holding `j` and `k` to scroll (applies to both Vim and VimFx), using more "appropriate" means instead such as scrolling by page and searching :)

**Comment by Pratyush** [comment]
Is there something I can do to help? I do have some programming experience. Regarding the workarounds, I spam `j` and `k` when I want to view what I'm scrolling past. When I don't care I press `<space>`

**Comment by lydell** [comment]
This _might_ be a Firefox bug. The following bug contains a test case that uses about the same scrolling implementation as VimFx, and it has the same problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1131740

It might be worth checking that test case out.

One way could also be to implement smooth scrolling ourselves.

**Comment by lydell** [comment]
Scroll related code:

- https://github.com/akhodakivskiy/VimFx/blob/1723f8b86f5e60fc6dfa9252a0a100dbaed6b2ec/extension/lib/commands.coffee#L118-L158
- https://github.com/akhodakivskiy/VimFx/blob/1723f8b86f5e60fc6dfa9252a0a100dbaed6b2ec/extension/lib/commands-frame.coffee#L42-L69

It seems like multi-process Firefox has problems starting another smooth scroll while another one is still running.

**Comment by lydell** [comment]
I’ve reported this on bugzilla now: https://bugzilla.mozilla.org/show_bug.cgi?id=1228407

**Comment by lydell** [comment]
Best workaround so far: Disable `layers.async-pan-zoom.enabled` in about:config.

**Comment by lydell** [comment]
The Firefox bug has been fixed now, so I’m closing this one.

**Comment by Pratyush** [comment]
thanks =)
