### ISSUE TITLE
Add function to save links to a stack in order to open them later

### ISSUE THREAD

**Issue by AllanLRH** [akhodakivskiy/VimFx#628]
This is a suggestion for a new feature.

It would be a nice feature to be able to add (multiple) links to a stack, and pop them off to open them afterwards.

Firefox can be slow if it's loading a lot of tabs simultaneously, and when I'm opening a lot of tabs from a page, it's usually because I don't want to go back and open another link – not because i want to read them all simultaneously.

I'm thinking that a link from the stack could be opened like links in the clipboard can be opened with the  <kbd>p</kbd> and <kbd>P</kbd> keys.

**Comment by lydell** [comment]
Perhaps you're looking for the [Load Tabs Progressively Fixed](https://addons.mozilla.org/firefox/addon/load-tabs-progressively-fixed/) add-on?

**Comment by lydell** [comment]
Closing because no response.

**Comment by AllanLRH** [comment]
Sorry, didn't realize that I should reply – thought your reply was more of a friendly hint :)

It helps, but it isn't the exact functionality that I'm looking for – I'd still prefer to be able to save links and later open them in bulk… but I understand if this isn't really the focus of this plugin, albeit it could provide a neat way of saving the links.
