### ISSUE TITLE
Request: Make it possible to use command to popup current tab history as right clicking the back button

### ISSUE THREAD

**Issue by av2000ii** [akhodakivskiy/VimFx#630]
Hi Lydell，VimFx is a great addon for firefox. Can you make it possible to use command to popup current tab's history as the effect of right clicking the back button of the browser. I did not find the feature with awesome bar, so I think use keyboard command to view the current tab's history is good to enhance browsing experience. Sorry for my english, BEST wishes for you and other developers.

**Comment by lydell** [comment]
Sounds like a good idea. In the mean time, if you use Firefox 43 or later you can use a count with `H` and `L`, which is close to what you're requesting, but not quite the same.

**Comment by av2000ii** [comment]
Thank you for your reply. I am still use the stable Firefox 42 and can't see the new function with Firefox 43. May be the feature is worth adding in the future.

**Comment by lydell** [comment]
“In the meantime” means “until the feature is implemented” here ;)

**Comment by lydell** [comment]
Note to self:

```coffee
document.getElementById('backForwardMenu')?.openPopupAtScreen(100, 100, true)
```
