### ISSUE TITLE
Show pressed keys on screen like vim

### ISSUE THREAD

**Issue by mozillazg** [akhodakivskiy/VimFx#632]
vim:
![0151203191321](https://cloud.githubusercontent.com/assets/485054/11559201/03fecf56-99f2-11e5-99fa-4a9f63585971.png)

**Comment by lydell** [comment]
Are you suggesting that if you have typed part of a multi-key shortcut, the keys typed so far should (optionally) be shown in a VimFx notification?

**Comment by mozillazg** [comment]
@lydell Yep.

**Comment by d125q** [comment]
It would be nice to show counts, too.

**Comment by lydell** [comment]
Good ideas!
