### ISSUE TITLE
Scrolling not working on http://nim-lang.org/

### ISSUE THREAD

**Issue by loops** [akhodakivskiy/VimFx#633]
Using -dev branch, scroll keys don't work when first navigating to the site
http://nim-lang.org.

**Comment by loops** [comment]
Just discovered the "zf", focus command! That works a treat, just have to focus any element on the page and then scrolling works.  Unless you're interested in this particular site as a test case, this issue should probably just be closed.  VimFX can already be made to work as-is.

**Comment by lydell** [comment]
Yes, that's a workaround, but not the solution to the problem. I've found why it's happening, and will push a fix later today or tomorrow.

**Comment by loops** [comment]
Okay... Just didn't want to be a pain in the ass ;o)

But since you're interested, here's another test case; maybe the same problem:

https://easyengine.io/

**Comment by lydell** [comment]
Thanks for being so nice in your bug reports! That really encourages me to fix things. :smile: :+1: 

Also thanks for that second text case. It was indeed the same problem, and helped me test that my fix works.
