### ISSUE TITLE
"Move to tab" hotkeys work only after full page load

### ISSUE THREAD

**Issue by azrdev** [akhodakivskiy/VimFx#634]
I used to open links in new tabs, then immediately (when the site just starts loading) use Shift-J/K to go back to the tab where I came from. Since some recent update (I think 0.6, when all the keybindings changed), the effect of Shift-J/K is delayed until the page is fully loaded.
In effect, I open the link, press Shift-J, wait some seconds for it to go back, then go back manually (e.g. by clicking on the tab), and then after some seconds VimFx will go further back, to a tab where I never wanted.
Versions:
* VimFx 0.7.3 installed&updated through AMO
* Firefox 42
* Archlinux rolling

Please make the tab-changing shortcuts work before page load is complete.
Also, it might be worth considering they should only have an effect if the visible tab has not been switched from the one they were issued in.

**Comment by lydell** [comment]
Is this the same issue as #588?
