### ISSUE TITLE
role=link in SVG will only find some of the nodes when following links

### ISSUE THREAD

**Issue by cburgmer** [akhodakivskiy/VimFx#635]
It looks like adding a `role=link` attribute to clickable nodes in SVGs makes VimFx pick those up when typing `f`, awesome. However it seems only some of the ~10 elements are being offered shortcuts.

I am implementing a sunburst diagram (on top of http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad) and annotate the tree nodes closest to the root element with said role (not showing too much key shortcuts). It seems to mostly consistently offer shortcuts for the same nodes, while omitting others.

Could you point me to the code responsible for finding clickable nodes? I'll try to read myself through.

Firefox 42.0, OSX, VimFx 0.7.3

**Comment by lydell** [comment]
Three conditions must be fulfilled for an element to get a hint:

1. The element must be inside the viewport.
2. The element must have the correct type and/or attributes (etc).
3. The element must not be considered to be covered by another element, or be `display: none`:ed, etc.

The relevant code is in [hints.coffee from line 153](https://github.com/akhodakivskiy/VimFx/blob/38d984c58004ef4a1220f76c5ebdae881085121f/extension/lib/hints.coffee#L153) and [commands-frame.coffee from line 80](https://github.com/akhodakivskiy/VimFx/blob/master/extension/lib/commands-frame.coffee#L80).

I’m closing this until there is anything actionable. Feel free to ask more questions and continue commenting here.
