### ISSUE TITLE
Add support for the Reader View

### ISSUE THREAD

**Issue by duguyipiao** [akhodakivskiy/VimFx#637]
Vimperator has [implemented](https://github.com/vimperator/vimperator-labs/pull/262) a similar function. Hope it can be implemented in VimFx.

The implementation of addon [Open in Reader View](https://github.com/rNeomy/reader-view) is also for your reference.

**Comment by duguyipiao** [comment]
Thanks for the implementation. I have another problem about the Reader View.

By default, VimFx and Firefox, can enter the Reader View only if it is "available". Indeed, every page can be "forced" to enter the Reader View.

For example, the Reader View for https://vimium.github.io/ is not available by default. But we can enter the Reader View by visiting about:reader?url=https://vimium.github.io/ , i.e., adding a prefix `about:reader?url=` to the current url.

I think this implementation is more friendly for users. Or, add another shortcut, e.g. `gR`, for Force Reader View.

The code [here](https://github.com/rNeomy/reader-view/blob/master/src/lib/main.js) is for your reference.

**Comment by lydell** [comment]
Example URL where this is useful, please.

**Comment by lydell** [comment]
While `about:reader?url=https://vimium.github.io/` does give a reader view, `about:reader?url=https://github.com/` (for example) does not: Then you end up on the regular `https://github.com/` page. I find that too confusing, so I won’t change this.

You seem to be at least a _bit_ into code, so I’d suggest making a custom command that suits your needs. Feel free to ask for help doing so.

**Comment by duguyipiao** [comment]
@lydell Thank you for the suggestion. It will be great helpful if you can give the code about how to implement this with a custom command.
