### ISSUE TITLE
Customize hotkey to disalbe VimFx

### ISSUE THREAD

**Issue by jkirk** [akhodakivskiy/VimFx#64]
It might be a window manager problem but Alt-Shift-V does not work for me. Here pressing Alt-Shift-V opens up the the View-Menu in Firefox (like only pressing Alt-V).

It would be nice if it where possible to change the hotkey to something else.

**Comment by andredasilvapinto** [comment]
Please make the shortcut configurable or change it to something cross-platform compatible.
