### ISSUE TITLE
Remap <up> and <down> keys

### ISSUE THREAD

**Issue by mcchrish** [akhodakivskiy/VimFx#642]
Is it possible to have a feature to remap `<up>` and `<down>` arrow keys to `<c-p>` and `<c-n>` browser-wide?

Edit: sorry, some words are not showing up because of markdown.

Well, an example of this is in google search autocomplete suggestion. I have to use the arrow keys to select the suggestions. What I want is to use the standard key binding in vim for next and previous which are `<c-p>` and `<c-n>`, instead of using the arrow keys.

**Comment by lydell** [comment]
I don't understand.

**Comment by lydell** [comment]
There is no feature to make one key stroke behave as another. VimFx only has commands, and lets you choose which shortcuts should trigger them. I’m not going to add that feature either, because it is too complicated to make it work in generally.

That being said, you might still be able to achieve your goal. As I said, it is difficult to get it working _generally,_ but you could likely get it to work in _most cases **you** actually need._

Create a [config file](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/config-file.md) and add the following custom commands:

config.js:

```js
vimfx.addCommand({
  name: 'send_up',
  description: 'Send the <up> key'
}, helper_send_key.bind(null, 'up'))

vimfx.addCommand({
  name: 'send_down',
  description: 'Send the <down> key'
}, helper_send_key.bind(null, 'down'))

function helper_send_key(key, {vim, uiEvent}) {
  if (uiEvent) {
    let {sendKey} = Cu.import('chrome://VimFx-config/content/send-key.js', {})
    sendKey(vim.window, key)
  } else {
    let {messageManager} = vim.window.gBrowser.selectedBrowser
    messageManager.sendAsyncMessage('VimFx-config:sendKey', key)
  }
}
```

frame.js:

```js
let {utils: Cu} = Components

addMessageListener('VimFx-config:sendKey', ({data: key}) => {
  let {sendKey} = Cu.import('chrome://VimFx-config/content/send-key.js', {})
  sendKey(content, key)
})
```

send-key.js: (you need to create this file; it is not mentioned in the docs)

```js
const EXPORTED_SYMBOLS = ['sendKey']

const KEY_CODES = {
  up: 38,
  down: 40,
}

const EVENT_SEQUENCE = ['keydown', 'keypress', 'keyup']

function sendKey(window, key) {
  EVENT_SEQUENCE.forEach(name => {
    let event = new window.KeyboardEvent(name, {
      keyCode: KEY_CODES[key],
    })
    window.document.activeElement.dispatchEvent(event)
  })
}
```

Feel free to ask if you have more questions.

**Comment by aleprovencio** [comment]
Is this code still valid? I couldn't manage to get it working...

**Comment by lydell** [comment]
@aleprovencio Here’s updated code:

```js
// config.js

let {utils: Cu} = Components
let {sendKey} = Cu.import(`${__dirname}/shared.js`, {})

vimfx.addCommand({
  name: 'send_up',
  description: 'Send the <up> key'
}, helper_send_key.bind(null, 'up'))

vimfx.addCommand({
  name: 'send_down',
  description: 'Send the <down> key'
}, helper_send_key.bind(null, 'down'))

function helper_send_key(key, {vim, uiEvent}) {
  console.log('send key', Boolean(uiEvent), sendKey)
  if (uiEvent) {
    sendKey(vim.window, key)
    console.log('ui done')
  } else {
    vimfx.send(vim, 'sendKey', {key})
  }
}
```

```js
// frame.js

let {utils: Cu} = Components
let {sendKey} = Cu.import(`${__dirname}/shared.js`, {})

vimfx.listen('sendKey', ({key}) => {
  sendKey(content, key)
})
```

```js
// shared.js

const EXPORTED_SYMBOLS = ['sendKey']

const KEY_CODES = {
  up: 38,
  down: 40,
}

const EVENT_SEQUENCE = ['keydown', 'keypress', 'keyup']

function sendKey(window, key) {
  EVENT_SEQUENCE.forEach(name => {
    let event = new window.KeyboardEvent(name, {
      keyCode: KEY_CODES[key],
    })
    window.document.activeElement.dispatchEvent(event)
  })
}
```

(@doy you might also be interested in this, as it shows how to share code between config.js and frame.js.)

**Comment by aleprovencio** [comment]
Brilliant, thanks!!

**Comment by doy** [comment]
Oh, thanks!

**Comment by aleprovencio** [comment]
@lydell these shortcuts used to work also on the search bar until the last update, do you know why it does not on the current version?
