### ISSUE TITLE
Scroll help window

### ISSUE THREAD

**Issue by progandy** [akhodakivskiy/VimFx#643]
I love using VimFx, but it is annyoing that I cannot scroll to the second half of the help window without using the mouse. Id love to be able to scroll it with j/k but it would be perfectly acceptable if it would work with arrow up/down or page up/down while the search field is focused.

**Comment by lydell** [comment]
Screenshot please.

**Comment by lydell** [comment]
In the development version:

- The search input is no longer autofocused. Instead, it is hidden until you press `/`.
- All scrolling commands now works in the help dialog.

**Comment by progandy** [comment]
Thanks, that works really well.
