### ISSUE TITLE
v0.10.0 in AMO

### ISSUE THREAD

**Issue by 9seconds** [akhodakivskiy/VimFx#645]
Hi,

As far as I can see, v0.10.0 is released but it is not in AMO yet. Does it have some problems or you've just forgot to upload it? :)

**Comment by lydell** [comment]
The AMO reviewers are slow this time. Perhaps busy with preparing for Christmas.

**Comment by lydell** [comment]
Also, you can access it here: https://addons.mozilla.org/firefox/addon/vimfx/versions/
