### ISSUE TITLE
some keycodes are stolen by VimFx even if they are not assigned

### ISSUE THREAD

**Issue by mjauvin** [akhodakivskiy/VimFx#646]
One of my website uses keyboard shortcuts (like 0, 1, 2, 3, 4) but only "0" (zero) is left alone by VimFx and can be used by the website's Javascript code.

Note: these shortcuts are *NOT* used in my VimFx shortcuts.

**Comment by d125q** [comment]
They are used by counters.

**Comment by lydell** [comment]
As @d125q points out, they're used by _counts._ Perhaps we need a pref to disable them. One way of trigbering the site shortcuts is to press for example `I2`.
