### ISSUE TITLE
Request feature to copy object location or link under focus

### ISSUE THREAD

**Issue by letientai299** [akhodakivskiy/VimFx#647]
I know that we already have `yf` but it requires a little bit time to look and think for what is the next key(s) to press. I find it faster to do like this:
- First, use `'` or `/` for find the link that I feel interesting.
- Then, copy the link and paste it somewhere else.

How do you think?

**Comment by lydell** [comment]
1. Use search command of choice.
2. Press the Menu key on your keyboard (which opens up the context menu).
3. Hit the acces key for the "Copy link address" menu item.
