### ISSUE TITLE
TypeError: keyStr.match(...) is null

### ISSUE THREAD

**Issue by Kambfhase** [akhodakivskiy/VimFx#648]
Yesterday, Firefox updated to version 43 and now VimFx stopped working. Even after using a fresh download, the VimFx button won't show up. The following error appears in the browser console.

```
1450538378499   addons.xpi  WARN    Error loading bootstrap.js for VimFx@akhodakivskiy.github.com:
  TypeError: keyStr.match(...) is null legacy.js:46:10
  JS Stack trace:
    convertKey@legacy.js:46:10
    < migrations[0]/convert@migrations.js:110:1
    < migrations[0]@migrations.js:121:36
    < applyMigrations@legacy.js:35:7
```

Firefox: 43
VimFx: 0.9.0
OS: Ubuntu 15.10

**Comment by Kambfhase** [comment]
The problem does not exist on a new profile. Any ideas?

**Comment by lydell** [comment]
Quick fix: Set `extensions.VimFx.migration.0.applied` to `true` in about:config. (Right-click and choose “New > Boolean” if the pref is missing.) But please read on before you do so!

Migrations are supposed to only run once. The stack trace you posted tells that migration 0 was run at startup and failed. That’s really weird. It should only have run if you upgraded from VimFx 0.5.x to any later version.

Migration 0 migrates old VimFx 0.5.x shortcut customizations to the new VimFx 0.6.0+ format. That’s why it doesn’t happen for you in a new profile; there are no old shortcut customizations to migrate.

The quick fix I mentioned above tells VimFx that migration 0 already has been applied, so it won’t run again. If you’re saying that you ran VimFx 0.9.0 before you updated Firefox to version 43, there are supposed to be 5 `extensions.VimFx.migration.X.applied` (where X goes from 0 to 4) all set to `true` in about:config. If that’s not the case for you, something is really weird.

It would also be helpful if you search for `vimfx.commands.` in about:config and post a screenshot of the result.

(I just upgraded to Firefox 43, but did not get any problems.)

**Comment by Kambfhase** [comment]
I guess the problem was that I had my local repo on an old version. And by old I mean 2dfff39 which is from December last year. Apparently that has problems with Fx43, thus I tried to update and something went wrong there.

I am now having 0.9.0 installed via the Addons Manager. These are the entries for `vimfx.commands`: 

![vimfx_commands](https://cloud.githubusercontent.com/assets/295387/11918905/1d583408-a742-11e5-88ca-f0fe212eeb36.png)
For `vimfx.migration` there are no entries. Added `extensions.VimFx.migration.0.applied` and now VimFX runs again! :+1:

Thanks for the help. ♥

**Comment by lydell** [comment]
I see, so the update to Firefox 43 was a red herring. It was all about you updating VimFx and the VimFx migration breaking because of that empty string in your `extensions.VimFx.commands.tab_move_right.keys` pref.

**Comment by Kambfhase** [comment]
> … that empty string in your `extensions.VimFx.commands.tab_move_right.keys` pref.

Should I remove that?

**Comment by lydell** [comment]
It doesn’t really matter if you remove it or not now.

**Comment by Kambfhase** [comment]
Ok, thanks anyway.
