### ISSUE TITLE
"Focus last focused text input" (gi) doesn't work on WhatsApp Web

### ISSUE THREAD

**Issue by franzwr** [akhodakivskiy/VimFx#649]
Operating System: OS X 10.11
Firefox version: 43.0.1
VimFx version: 0.9.0
Keyboard layout: en-US

How to replicate:
* Go into https://web.whatsapp.com/ and log in.
* Select a conversation and focus on the message input box.
* Press \<escape\> to defocus the box.
* Input `gi` -- the contact search input is focused instead of the message input box.

I don't know if this worked previously.
Thanks!

**Comment by lydell** [comment]
I won’t get a WhatsApp account, so we’ll have to do this the hard way.

Could you right-click the message input box, choose “Inspect Element” and post a screen shot of the web inspector that then opens? (It’d be helpful if you resize the web inspector to be quite large.)

**Comment by franzwr** [comment]
No problem
<img width="1382" alt="screen shot 2015-12-20 at 21 47 17" src="https://cloud.githubusercontent.com/assets/4754508/11920026/69a69036-a763-11e5-82a5-014cf2c4366d.png">

**Comment by lydell** [comment]
Perfect! That confirmed my suspicion. Currently, `gi` only operates on `<input>` and `<textarea>` elements, not “contenteditable” elements like in this case. Perhaps it _should_ include contenteditable elements.

**Comment by franzwr** [comment]
Thanks @lydell . Would you mind if I attempt to implement it and send a pull request?

**Comment by lydell** [comment]
No, not at all, go for it!
