### ISSUE TITLE
Scroll down occasionally triggering back in history

### ISSUE THREAD

**Issue by volt4ire** [akhodakivskiy/VimFx#653]
About twice a day while browsing my scroll down and up shortcuts (j & k, though more often the latter) will trigger going back in history. The only way I've found to fix this behavior is to restart Firefox. It happens about once a day. Do you have suggestions for how to fix this? Thanks!

**Comment by lydell** [comment]
- Have you tried it in a clean Firefox profile?
- Does it happen on a specific site?
- VimFx version, Firefox version, OS, keyboard layout?
- When it starts happening, do `j` and `k` _always_ trigger going back in history after that?

**Comment by lydell** [comment]
Closing because no response.
