### ISSUE TITLE
[question] How to make my extension compatible with VimFx

### ISSUE THREAD

**Issue by Anon1234** [akhodakivskiy/VimFx#654]
I'd like to know how to make my extension to be compatible with VimFx.

**Comment by Anon1234** [comment]
So what I want to do: there is a useful extension called [mpv-youtube-dl-binding
](https://github.com/antoniy/mpv-youtube-dl-binding), it adds a context menu command which allows to open any link with mpv media player (or any other one). I'm using it to watch videos/playlists with on Youtube with mpv. 
I'd like to implement a custom command in VimFx, that allows to select a link (similar to `focus/follow link`) and pass it to a function in `mpv-youtube-dl-binding` extension.

**Comment by lydell** [comment]
That's not possible, and I have no intention to support it. I suggest doing the following:

1. Focus the link using `zf`.
2. Press the menu key on your keyboard (which opens the context menu).
3. Press the access key for the mpv media player menu item.

**Comment by dcrystalj** [comment]
i love mpv-youtube, i would love to see this feature as well. pressing ```zf``` on youtube does nothing

**Comment by Anon1234** [comment]
@dcrystalj, I did it writing [custom command](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#play-a-link-with-an-external-media-player). It also has [this feature](https://github.com/antoniy/mpv-youtube-dl-binding/pull/17) integrated. Feel free to check it out :smiley:

**Comment by dcrystalj** [comment]
sir i set: 
* devtools.chrome.enabled to true,
* downloaded config template and extract it to ~/.mozilla/extensions/VimFx-config@vimgx.org
* changed the config.js and frame.js
* restarted browser
* open youtube and press ```zf``` select link and press ```M``` 

it does nothing.

**Comment by Anon1234** [comment]
Hmm... It might be an issue with [a new extensions signing thing](https://wiki.mozilla.org/Add-ons/Extension_Signing):

> Will there be a setting or other overrides to disable signature checks?
> 
> * Firefox Release and Beta versions will not have any way to disable signature checks. Signature checks can be disabled in other versions, as described in detail 
> 
> What are my options if I want to install unsigned extensions in Firefox?
> 
* The Developer Edition and Nightly versions of Firefox will have a setting to disable signature enforcement. There will also be special unbranded versions of Release and Beta that will have this setting, so that add-on developers can work on their add-ons without having to sign every build. To disable signature checks, > you will need to set the xpinstall.signatures.required preference to "false".
> * type about:config into the URL bar in Firefox
> * in the Search box type xpinstall.signatures.required
> * double-click the preference, or right-click and selected "Toggle", to set it to false.

So, if switching off the `xpinstall.signatures.required` isn't helping you, you need  to move to Dev or Nightly, unfortunately.
Maybe @lydell knows a better way to make it work?

**Comment by lydell** [comment]
@dcrystalj 

> devtools.chrome.enabled to true,

That has nothing to do with this.

> downloaded config template and extract it to ~/.mozilla/extensions/VimFx-config@vimgx.org

That’s the wrong location. You probably meant something like `~/.mozilla/firefox/dz9zivt4.default/extensions/VimFx-config@vimfx.org`.

> selected link and press M

You have to set `M` as a [shortcut for your new command](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md#configjs) first.

---

It sounds like you have one or more of the following problems:

- You put the files in the wrong location.
- You forgot to set `M` as a shortcut for your new command.
- Mozillas choice to require extensions to be “signed” to be able to install them might get in your way. If you’re running Firefox < 43 you should be fine. If you run Firefox 43 you can set `xpinstall.signatures.required` to `false`. If you run Firefox > 43, you should consider yourself a developer and install Firefox Developer Edition. Unfortunately there is no better way currently.

I’d recommend that you start with following the [setup instructions](https://github.com/lydell/VimFx-config/#setup) a bit more closely and just try to get your config add-on installed and running. Check the Add-ons Manager and the browser console!

Then try to add @Anon1234’s custom command.

**Comment by lydell** [comment]
FYI, I just added support for [custom hints commands](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#custom-hints-commands).
