### ISSUE TITLE
[question] How to get access to a page from the config file

### ISSUE THREAD

**Issue by Anon1234** [akhodakivskiy/VimFx#655]
Hi all!
I am new to an extensions development and would like to know how to get this code to work:
```js
vimfx.addCommand({
    name: 'play_with_mpv',
    description: 'Play the focused link with MPV'
}, function(args) {
    console.log("Playing", args.vim.window.document.activeElement.href)
})
vimfx.set('custom.mode.normal.play_with_mpv', 'M')
```
I'm using it like this: `zf` -> *select a link on a page* -> `M`.
In the browser's console (ctrl+shift+j) i get `Playing undefined`.

P.S. Originally I wrote this question to the mailing list but not shure if it working.

**Comment by lydell** [comment]
Just slightly changing the example in the [config file documentation](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md#framejs) should work.

Replace `console.log(...)` with this:

```js
let {messageManager} = vim.browser
let callback = ({data: {href}}) => {
  console.log('href', href)
}
messageManager.addMessageListener('VimFx-config:currentHref', callback)
messageManager.sendAsyncMessage('VimFx-config:getCurrentHref')
```

And add the following in frame.js:

```js
addMessageListener('VimFx-config:getCurrentHref', () => {
  let {href} = content.document.activeElement
  sendAsyncMessage('VimFx-config:currentHref', {href})
})
```

**Comment by Anon1234** [comment]
Thank you!
