### ISSUE TITLE
How to customize the shortcut in new version of VimFX?

### ISSUE THREAD

**Issue by zhou13** [akhodakivskiy/VimFx#656]
> There are of course many more shortcuts! Press ? to see them all. That opens the keyboard shortcuts dialog, which helps you remember the shortcuts, and lets you customize every single one of them. You can also look at all default shortcuts here.

However, it seems that I cannot customize my shortcuts using `?` in the new version of VimFX.

**Comment by lydell** [comment]
Ah, I forgot to update that part of the readme, good catch. You customize all keyboard shortcuts in VimFx's keyboard shortcuts dialog in the Add-ons Manager, where you always have changed other VimFx settings.
