### ISSUE TITLE
Dropdown menues in Gmail not targetable

### ISSUE THREAD

**Issue by lindhe** [akhodakivskiy/VimFx#660]
In the gmail web client there are some dropdown menues ("Select", "More" etc, just above the list with emails). These buttons are targetable with VimFX, but the menues aren't. That is probably because they are not naturally clickable. The buttons are `div`'s with the attribute `role="button"`. The dropdown menus however dont have this attribute, but instead have `role="menuitem"`.

I haven't really put myself into the code of VimFX, but I would assume we could simply look for this attribute to make them targetable.

I don't know how `menuitem` should be used (or usually is used), but it seems reasonable to make them targetable - usually you would like to target menu items. Also, gmail is so widely used that it makes  sense to fix this, even if it so happened that Google is using `menuitem` unconventionally. Let's make an exception for the big guy...

**Comment by lydell** [comment]
We actually already target `role="button"`, so I'm not sure what's going on really. But you are right that no hints are currently generated in those cases.

Luckily, there's a workaround: Open the menu using VimFx, then select the menu item of choice using the arrow keys.

**Comment by lindhe** [comment]
I think you misread. `role="button"` works, it's `role="menuitem"` that doesn't.

Nice, I didn't know that. I tried tab, which got me nowhere, and I guess I didn't bother to experiment further. Thanks, that'll get me through the days until `role="menuitem"` is targetable.
