### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by jonnyrobbie** [akhodakivskiy/VimFx#661]
I tried to look at https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands, but it went slightly over my head.

I want a custom shortcuts `g1` - `g9` to open a new tab and go to a custom predefined address - kinda like bookmarks. I basically want to associate newtab links with numpad.

I figured I'd probably had to mess up with custom commands, but I don't know where to start.

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#open-a-specific-url

Feel free to ask more questions here if needed.
