### ISSUE TITLE
Marks mode does not work properly

### ISSUE THREAD

**Issue by duguyipiao** [akhodakivskiy/VimFx#663]
Open any webpage, and mark any position with for example `ma`, then go to other position in this page and press `` `a ``, VimFx doesn't go to that position and all VimFx shortcuts do not work. Hover over the VimFx icon, it shows "VimFx is in Marks mode. Click to return to Normal mode." ``` `` ``` doesn't work too.

Firefox 43.0 VimFx 0.10 Ubuntu 14.04

**Comment by lindhe** [comment]
I was just wondering why I couldn't get it to work. Good to see there is a fix now. :)
