### ISSUE TITLE
Misplaced Hints when using "Default Full Zoom Level" addon

### ISSUE THREAD

**Issue by darvelo** [akhodakivskiy/VimFx#665]
I have a 15" monitor at 1920x1080, so having a default zoom of ~130% for all firefox tabs is a must for me since everything by default is too small to read. Unfortunately, FF doesn't have this feature, but the "Default Full Zoom Level" addon does and it works well. Unfortunately the hint markers for VimFx are out of place when this happens. 

FF Dev Edition
VimFx 0.10.0

![2016-01-10-183222_1920x1080_scrot](https://cloud.githubusercontent.com/assets/523169/12224875/31ba5510-b7c9-11e5-9d78-8a6639336b00.png)

**Comment by lydell** [comment]
I just tried this with:

- Ubuntu 15.04
- Firefox Devloper Edition 45.0a2
- VimFx 0.10.0 as well as latest master
- A completely new Firefox profile

This is exactly what I did:

1. Installed [Default FullZoom Level](https://addons.mozilla.org/firefox/addon/default-fullzoom-level/?src=ss)
2. Clicked "Preferences" for that addon in Add-ons Manager.
3. Set the "Default FullZoom Level (percent)" to 130.
4. Noticed how every page displayed larger than normally
5. Tried the `f` command on various sites.

I could not notice misplaced markers (as opposed to your screenshot).

Perhaps I’m missing something?

**Comment by lydell** [comment]
I think I found it: If I also enabled the "Change default Mode to Zoom Text Only" option of the addon I get misplaced markers.

**Comment by darvelo** [comment]
Thanks! I finally worked up the courage to create a new profile (after tab groups were axed) and everything works.

**Comment by LL25255252** [comment]
Off Topic:
Sorry for posting in this 2016 thread but I wonder do you by any chance still use this "Default Full Zoom Level" addon or have it in a backup of an old profile from the time  you were using it ?

If so, can you please share it with me ?

The addon is no longer on AMO (addons.mozilla.org) and I can't find its xpi on the internet.

Found its page on the wayback machine but its xpi can't be installed.
https://web.archive.org/web/20160303220246/https://addons.mozilla.org/en-US/firefox/addon/default-fullzoom-level/

BTW - I have NoSqint but still I want to try that addon.

Many thanks in advance.

pale Moon 27.3.0 
Win 7 x64
