### ISSUE TITLE
VimFx breaks Google Sign-In

### ISSUE THREAD

**Issue by lknix** [akhodakivskiy/VimFx#670]
When trying to sing-in on https://www.moo.do/, which uses Google sign-in, I get an empty window if  VimFx is enabled. 

VimFx disabled:
![vimfx_disabled](https://cloud.githubusercontent.com/assets/954612/12390674/6038a292-bde2-11e5-9ddb-c097e27c57a5.png)

VimFx enabled:
![vimfx_enabled](https://cloud.githubusercontent.com/assets/954612/12390681/6e7d7094-bde2-11e5-9f02-cfef5a0a00fa.png)

I've tried versions back to 0.5.16-signed and it doesn't work.

VimFx: 0.11 - 0.5.16-signed
Firefox: 43.0.4
OS: Linux (Arch)
Keyboard layout: English

**Comment by lydell** [comment]
I just tried this, but couldn’t reproduce. Here’s what I did:

1. Went to https://www.moo.do/.
2. Clicked the blue “Sign up / Login” button in the top-right corner using the `f` command.
3. A popup window opened, asking me to sign in with my Google Account.

VimFx 0.11.0, Firefox 43, Trisquel 7, new profile.

I don’t see what’s wrong. Perhaps I’m missing something?

**Comment by lknix** [comment]
Hm, that's weird. Let me run a few more tests and report back.

**Comment by lydell** [comment]
Closing because no response.

**Comment by lknix** [comment]
@lydell I finally tested this and it seems there is a combination of FVD Speed Dial and VimFx that break the sign-in. If I disable either one of them Google Sign-In works.
