### ISSUE TITLE
DuckDuckGo image search can't be targeted

### ISSUE THREAD

**Issue by lindhe** [akhodakivskiy/VimFx#671]
Actually, the results of none of the search categories (Images, Videos, News, ...) are targetable.

I a glance I can't find any obvious thing missing (like a "click-me" class or whatever), so I guess it might be them being bad with semantics...

I'd much appreciate being able to use VimFX for these results (I never use the Google search engine any more, for me DuckDuckGo is much better), but it seems unduly to expect VimFX to add some obscure syntax to target, that may or may not change in the future.

Do you think it would be possible to fix reasonably easily, or should I start looking into the DuckDuckGo repo instead?

**Comment by lydell** [comment]
We already have a bunch of site-specific hacks in code, so I guess we could add yet some here.

Still, you’re doing a good thing if you suggest/help DuckDuckGo to improve their accessibility. This is not a problem to VimFx, but to all non-mouse users.

**Comment by lydell** [comment]
Btw, [`VimFxHintMatcher`](https://github.com/akhodakivskiy/VimFx/blob/develop/documentation/api.md#vimfxhintmatcher) can also be used in a [config file](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md) to target things that VimFx by default doesn’t (yet).

**Comment by lydell** [comment]
@lindhe Work in progress: #676

**Comment by lindhe** [comment]
Wihuuu!!!
