### ISSUE TITLE
Leaving text input field with <force><esc> doesn't focus canvas (?) anymore

### ISSUE THREAD

**Issue by knobhead** [akhodakivskiy/VimFx#673]
Hi,
once again thanks for this wonderful add-on. And for fixing #664 which was killing me :)

Unfortunately, since the last update, I'm no longer able to use Firefox default keys (arrow keys or <kbd>PgUp</kbd>/<kbd>PgDn</kbd> or <kbd>Space</kbd> etc.) to scroll the page, after I left a text field with <kbd>Escape</kbd>. When I mouse-click on the page background, these keys work again. Is this intended behaviour? Do I have to remap these keys? 

I'm on FF 43.0.4 Win64 here. 

Thanks!

**Comment by d125q** [comment]
I am unable to reproduce this.  Firefox 43.0.4 on ArchLinux, VimFx 0.11.0.

**Comment by lydell** [comment]
I'm also unable to reproduce.

**Comment by lydell** [comment]
Closing because no response.
