### ISSUE TITLE
Where to put additional config files config.js / frame.js?

### ISSUE THREAD

**Issue by knobhead** [akhodakivskiy/VimFx#674]
Hi,
sorry, maybe I'm just blind here: I can't find anything in the docs on where to place config.js
I even dared taking a quick glance at VimFx source code, but couldn't find any hints there. Could somebody add information to the docs on this? Or give me a hint here? Thanks!

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md#setup
