### ISSUE TITLE
VimFx breaks some features in www.codecademy.com

### ISSUE THREAD

**Issue by DominicAntonacci** [akhodakivskiy/VimFx#680]
With VimFx enabled, text is not written to the online terminal in some codecademy courses. The key presses are sent to VimFx rather than their terminal screen.

Confirmed courses
Command Line: https://www.codecademy.com/en/courses/learn-the-command-line/lessons/navigation/exercises/your-first-command
Git: https://www.codecademy.com/en/courses/learn-git/lessons/git-workflow/exercises/git-init

Once VimFx is set to Ignore Mode, the problem goes away.

VimFx Version: 0.11.0
Firefox Version: 43.0
OS: Linux Mint and Windows 7 (have confirmed in both)
Keyboard Layout: qwerty
Worked Before? No

**Comment by lydell** [comment]
Thanks for the excellent bug report! Fixed.

(Also note that you can focus the terminals with the `f` command. Just need to press `<space>` once to see the correct hint.)
