### ISSUE TITLE
Regenerate (rather than just reset) markers when following multiple links

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#681]
Steps to reproduce:

1. Find a button whose job is to toggle the visibility of some elements which, preferably, contain links;
2. Go ahead and follow multiple links (`af`, for example);
3. Press the button.

What happens is the new links which were unhidden by pressing the button do not get hints.  Also, if the new elements revealed by the button pushed some of the old ones out of the viewport, their hints remain despite the elements not being visible on the screen.

VimFx version: 0.11
Firefox version: 44.0
OS: Arch Linux
Keyboard layout: en-US QWERTY
Worked before: no
Example URL(s): the notifications on your GitHub home page.  Try pressing the `More` button.

**Comment by lydell** [comment]
In ideal world, we'd definitely do this. But in reality, it's too slow. I often use `af` to open several links in a list in rapid succession. If we would regenerate the hints between each time that wouldn't be possible.

**Comment by d125q** [comment]
How feasible it is to at least hide the markers which get pushed out of the viewport?

**Comment by lydell** [comment]
Why does it matter if markers whose elements have gone outside the viewport still show?

**Comment by d125q** [comment]
Because the markers shown on the screenshot below look pretty ugly and distracting, in my opinion.
![screenshot1453925158](https://cloud.githubusercontent.com/assets/7765538/12626625/e486e758-c539-11e5-82b7-563188ef273c.png)

**Comment by lydell** [comment]
Sorry, it's not worth it in my opinion.

**Comment by d125q** [comment]
I don't really understand.  You already iterate through the markers at a certain interval to check for movements.  Why not also check if they've gone out of the viewport, and in that case, hide/invalidate them?

**Comment by lydell** [comment]
Make a PR, then.
