### ISSUE TITLE
Ctrl shortcuts and Multi-process

### ISSUE THREAD

**Issue by rafaelndev** [akhodakivskiy/VimFx#683]
In VimFx I modified the shortcuts scroll down and scroll up to `<c-d>` and `<c-u>` (removed the original shortcuts from firefox first), without multi-process it works normally, but when you enable multi-process is necessary to press the keys twice, for example, if I use `<c-d>`, I need to press another key to activate the command.

VimFx Version: 0.11.0
Firefox Version: 46-47 with multi-process
OS: Manjaro 15.12
Keyboard Layout: qwerty
Worked Before? No

**Comment by lydell** [comment]
This is what I did:

1. Went VimFx's settings page in the Add-ons Manager.
2. Replaced `h`, `l`, `j`, `k`, `<space>`, `<s-space>`, `d`, `u`, `gg` and `G`
   with `<c-h>`, `<c-l>`, `<c-j>`, `<c-k>`, `<c-space>`, `<c-s-space>`, `<c-d>`, `<c-u>`, `<c-g>` and `<c-G>`, respectively.
3. Went to https://github.com/ and resized the window so I got both vertical and horizontal scrollbars.
4. Tried all of the shortcuts listed above.

It all worked as expected. Am I missing something?

VimFx version: 0.11.0 as well as latest master
Firefox version: 47 with multi-process enabled
OS: Ubuntu 15.04
Keyboard language: en-US

**Comment by rafaelndev** [comment]
Well, my mistake, it's a bug with the Customizable Shortcuts extension, when i disabled it and installed Menu Wizard (to change default shortcuts) everything worked.

Sorry by the false alarm, and thanks for this awesome extension ;)
