### ISSUE TITLE
'H' key does not trigger the 'Back IS Close' add-on

### ISSUE THREAD

**Issue by dontdieych** [akhodakivskiy/VimFx#685]
Hello,

I've used vimfx with 'back is close' addon. So when I've hit 'H' (back) at the head of history, tab closed then go to last tab.

I don't remember when this function does not working anymore. But I missed this so much.

Any information about this would appreciated.

Thanks for vimfx development!

**Comment by lydell** [comment]
You’ll need a [custom command](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md) for this:

```js
let {commands} = vimfx.modes.normal
vimfx.addCommand({
  name: 'history_back_backisclose',
  description: 'Go back in history or close tab',
  category: 'location',
  order: commands.history_back.order + 1,
}, (args) => {
  let {vim} = args
  let {window} = vim
  if (!window.gBrowser.canGoBack) {
    window.setTimeout(() => {
      window.BrowserBack()
    }, 0)
  } else {
    commands.history_back.run(args)
  }
})
```

**Comment by dontdieych** [comment]
Thanks a lot !!

It works like a charm.
