### ISSUE TITLE
Add "How to install" section

### ISSUE THREAD

**Issue by yggdr** [akhodakivskiy/VimFx#686]
Am I really the only one starring at the Readme, the documentation, the wiki, and nowhere seeing a "How to install" section? Please add such a section to the main readme, even if it's just a single line.

**Comment by lydell** [comment]
I've never heard about a Firefox user before thst doesn't know what an addon is and how to install one, but sure, we can do that :)

Until then, use the link at the top of https://github.com/akhodakivskiy/VimFx:

> https://addons.mozilla.org/firefox/addon/vimfx

You can learn more about Firefox addons here: https://addons.mozilla.org/

**Comment by yggdr** [comment]
lol, I think you misunderstood :D
For example pentadactyl, which I used until recently, you can either install the addon via addons.mozilla.org, or clone their repo and compile an XPI of the development version yourself.

**Comment by lydell** [comment]
The readme links to the [documentation](https://github.com/akhodakivskiy/VimFx/tree/master/documentation) which now links to the [installation](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/installation.md) section near the top.
