### ISSUE TITLE
Won't disable on Whatsapp Web

### ISSUE THREAD

**Issue by Firesphere** [akhodakivskiy/VimFx#689]
VimFX won't disable itself on Whatsapp Web. It doesn't recognize div type="input" it seems, and (on and off) captures the keyboard.

**Comment by lydell** [comment]
When you creatwd this issue, GitHub asked you to read through the following: https://github.com/akhodakivskiy/VimFx/blob/master/CONTRIBUTING.md

Please do so. Closing until then.
