### ISSUE TITLE
Feature Request: Page Marks / Bookmark Navigation

### ISSUE THREAD

**Issue by DavidVorick** [akhodakivskiy/VimFx#695]
One of my favorite features of other vim-browsers was page marks. Marks in VimFx remember where you are on a page, but I would also like to be able to mark across pages. Perhaps when marking a page with a capital letter e.g. `mA` it remembers the URL + the scroll height (or maybe just the URL).

**Comment by lydell** [comment]
Why didn't you follow the instructions in the issue template? It's impossible to implement features like this without enough data :) Closing until provided.

**Comment by DavidVorick** [comment]
ah sorry, skimmed the template and it seemed to be bugs only. I've added more information.

**Comment by lydell** [comment]
Thanks for the extra information! Now you've described a bit how the proposed commands work. Could you give a detailed, specific use case example that shows how this feature is useful?

**Comment by DavidVorick** [comment]
Sure. My browsing habits mean that 80% of my time is spent on about 10 different pages.

Reddit, Facebook, Github, Github Sia repo, Hacker News, and a small number of others. So I'd add a quickmark to each of them. Then, when I want to browse to my regular sites, instead of 'oreddit.com', I'd type \`R, which is much faster. Then, to check out the Sia issue tracker, instead of 'ogithub.com' -> [navigate to issue tracker], I'd just run \`S.

**Comment by lydell** [comment]
Cool! But what about scroll position?

**Comment by DavidVorick** [comment]
I don't think that I would need scroll position to be saved, might even be annoying if you saved at a weird height. So I think I would change the feature request to not save the scroll height.

Thanks for walking through this with me.

**Comment by lydell** [comment]
What you want can actually already be accomplished using custom commands: https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#open-a-specific-url

(However, setting up a config file to be able to add custom commands is currently a bit complicated, but that has been fixed in the development version.)
