### ISSUE TITLE
fullpagedown go down too far when page has top fixed nav bar

### ISSUE THREAD

**Issue by dontdieych** [akhodakivskiy/VimFx#698]
Steps to reproduce:

1. Go https://inbound.org/blog/confessions-of-a-google-spammer
2. Rememer last line then press space or whatever key mapped fullpagedown
3. It goes too far so one or two lines hide by top nav bar.

If I unmap space or go to insert mode, space (firefox default fullpagedown) does not go further.

VimFx version: 0.12.0
Firefox version: 44.0.2
OS: Linux(Arch)
Keyboard language: en
Worked before: 
Example URL(s): https://inbound.org/blog/confessions-of-a-google-spammer or go to medium.com then select any blog article.

**Comment by lydell** [comment]
Firefox used to have the same problem, but apparently they have improved things! Thanks for letting me know, I had no idea about that.

The big problem is: I wonder how Firefox does it.

**Comment by lydell** [comment]
Seems like Firefox started fixing this already three years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=780345

Then they’ve only gone further down the rabbit hole:

Fixed a few months ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1081272
Also fixed a few months ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1224307
Still unresolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1225201

So, it looks like we have to reproduce Firefox’s heuristics for finding these terrible fixed headers and footers.

This seems to be their current algorithm (more or less):

```
for every `position: fixed` element in the current viewport
  check if the width of the element is >= to half of the viewport width
    ... or at least 800px
    ... and the height of element is <= a third of the viewport height
    ... also, be careful to take `transform: translate(...)` into account
      if so, consider it a fixed header or footer element

  of the possible header and footer elements, find the likely header element
    a header is an element whose top is outside the top of the viewport
      ... or exactly at the top of the viewport
      ... or an element which overlaps a header element

  of the possible header and footer elements, find the likely footer element
    a footer is an element whose top is outside the bottom of the viewport
      ... or exactly at the bottom of the viewport
      ... or an element which overlaps a footer element

  calculate the page height by measuring the distance between
    ... the bottom of the header
      ... but maximum a third of the viewport height from the viewport top
    ... and the top of the footer
      ... but maximum a third of the viewport height from the viewport bottom
```

The above was interpreted from: https://hg.mozilla.org/mozilla-central/file/4d75bd6fd234/layout/generic/nsGfxScrollFrame.cpp#l3829

**Comment by lydell** [comment]
The development version now seems to pass all the tests mentioned in the above bugzilla bugs.
