### ISSUE TITLE
"Scroll step size" option to set scroll speed for "j" and "k"

### ISSUE THREAD

**Issue by feluxe** [akhodakivskiy/VimFx#699]
In Vimium there is an option called "Scroll step size" to set scroll speed for "j" and "k".
In VimFx I couldn't find an option to set the speed. In my case the scroll speed is way to slow for my taste.

Any idea how to increase the speed?

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#scrolling-prefs

**Comment by jonasagx** [comment]
The right property to change at `about:config` is `toolkit.scrollbox.verticalScrollDistance` its default value is 3, increase that value to scroll faster.
