### ISSUE TITLE
Close tab and focus left or right

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#70]
I have three mouse gestures for closing the current tab. One that focuses the left tab afterwards, one for right tab, and one that uses Firefox's own close tab function. I'm very used to this, and find it very useful.

Now I am trying to stop using the mouse. I can use the 'x' key to replace my third mouse gesture. I would really like keys for the other two as well. Does anyone else?

I know that Vimperator provides such keys, but I prefer this excellent extension.

**Comment by ainola** [comment]
I realize this is an ancient bug, so forgive me if this comes off poorly.

I'm a Pentadactyl refugee that sorely misses the ability to control which direction to tab-delete in. In vimperator/pentadactyl, `d` would delete and focus the right tab while `D` would focus the left. Is there any interest in exposing some option to introduce similar functionality?

**Comment by lydell** [comment]
No. You can create such commands yourself, though, by using a [config file](https://github.com/akhodakivskiy/VimFx/blob/72485ddbf4e0c8a57201fe27f1dc69502542e01f/documentation/config-file.md).

**Comment by bill-mybiz** [comment]
Howdy. My Vimperator seems to be breaking lately so I'm checking VimFX out...and I :heart: it so far. Really neat.

This drop tab issue is one of the big ones AFAICT, and I tried searching elsewhere but couldn't find anyone who had shared this particular custom command. So I did it, and here is what I came up with:

```
vimfx.addCommand({
  name: 'close_tab_goto_prev_tab',
  description: 'Closes the current tab and sets the selected tab to the one just before it.',
}, ({vim}) => {
  let gBrowser = vim.window.gBrowser
  let prevTabIndex = gBrowser.tabContainer.selectedIndex - 1
  gBrowser.removeCurrentTab()
  gBrowser.selectTabAtIndex(prevTabIndex)
})
vimfx.set('custom.mode.normal.close_tab_goto_prev_tab', 'D')

vimfx.addCommand({
  name: 'close_tab_goto_next_tab',
  description: 'Closes the current tab and sets the selected tab to the one just after it.',
}, ({vim}) => {
  let gBrowser = vim.window.gBrowser
  let nextTabIndex = gBrowser.tabContainer.selectedIndex
  gBrowser.removeCurrentTab()
  gBrowser.selectTabAtIndex(nextTabIndex)
})
vimfx.set('custom.mode.normal.close_tab_goto_next_tab', 'd')
```

I wanted to post it because this is a top search result in google for me and I thought it may be helpful.

**Comment by letientai299** [comment]
@bill-mybiz  How about post your custom command on [this wiki page](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands)?

**Comment by bill-mybiz** [comment]
@letientai299 Done. I didn't realize I could make an edit to someone else's wiki page :smile:
