### ISSUE TITLE
Toolbar icon disappears in HiDPI mode (layout.css.devPixelsPerPx=2)

### ISSUE THREAD

**Issue by Hexcles** [akhodakivskiy/VimFx#702]
Steps to reproduce:

Under high-DPI mode (`layout.css.devPixelsPerPx=2` in about:config), the toolbar icon of VimFx disappears. It shows correctly when `layout.css.devPixelsPerPx` is 1.

See the screenshot below (the little empty space between the camera icon and the LastPass icon is where VimFx is supposed to be):

![screenshot](https://i.imgur.com/qzjwnog.png)

It seems to somehow relate to issue #591, where the icon became too large under HiDPI mode. That issue was fixed and if my memory serves, everything was working normally in some version before, but now in 0.12.0 the icon disappears under HiDPI.

VimFx version: 0.12.0
Firefox version: 44.0.2
OS: ArchLinux x86_64
Worked before: YES (probably 0.11.0?)

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/issues/591#issuecomment-167820745
