### ISSUE TITLE
Enhancement: gx0: Close all tabs to the left

### ISSUE THREAD

**Issue by girst** [akhodakivskiy/VimFx#707]
Detailed use case example:

type `gx0` to close all tabs to the left, similar to the 'close all tabs to the right' `gx$`
This extension provides this as a menu: https://addons.mozilla.org/en-US/firefox/addon/close-tabs-to-the-left/ - it would be nice to also be able to use VimFX for that

VimFx version: 0.12.0
Firefox version: 44.0.2
OS: Ubuntu Linux 15.10
Keyboard language: de_AT-nodeadkeys
Worked before: n/a
Example URL(s): n/a

**Comment by lydell** [comment]
I think we should follow Firefox’s lead and only include a command for closing tabs to the right. Instead, I added this to the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#close-tabs-to-the-left) section of the wiki.
