### ISSUE TITLE
Missing/tiny icon with Firefox 45 + HiDPI

### ISSUE THREAD

**Issue by spacepluk** [akhodakivskiy/VimFx#708]
The icon is either tiny or invisible depending on the theme.

**Default theme**
![default theme](http://i.imgur.com/msmpsP0.png)

**FXChrome Theme** ([link](https://addons.mozilla.org/en-US/firefox/addon/fxchrome/?src=api))
![fxchrome theme](http://i.imgur.com/negzzl2.png)

VimFx version: 0.12.0
Firefox version: 45
OS: Arch Linux 
Keyboard language: US
Worked before: I'm not sure...

**Comment by lydell** [comment]
Sigh, I’m getting so tired of this “high DPI” stuff that I cannot test. See also #702 and #591.

/cc @Hexcles @dwhinham

**Comment by lydell** [comment]
@spacepluk You’ve set `layout.css.devPixelsPerPx` to `2`, right?

**Comment by dwhinham** [comment]
Rebooted into my Linux system, updated to 45 - the icon is indeed invisible.

On my system, setting `layout.css.devPixelsPerPx` to 2 does nothing to Firefox or the button, as my desktop environment passes the correct value to Firefox. Setting it to 2 or -1 (the default) produces identical results for me. Having to override this to 'fix' Firefox, to me, implies broken system configuration, and not a problem with Firefox or VimFx.

Setting it to 1, however, makes the UI shrink as expected, and the icon reappears.

I'm going to try the code from the other issue. Bear with me.

**Comment by spacepluk** [comment]
@lydell I'm using the default setting `-1` because I switch between HiDPI and regular screens. I'll try the dev version later. Thanks!

**Comment by spacepluk** [comment]
@lydell it works great thanks!
