### ISSUE TITLE
Mapping <c-n> to next tab still opens a new window.

### ISSUE THREAD

**Issue by spacepluk** [akhodakivskiy/VimFx#709]
Steps to reproduce:

1. Map `<c-n>` to switch to next tab
2. Try to switch to the next tab using `<c-n>`
3. It switches, but it also opens a new window.

I've been using VimFx with `<c-n>` and `<c-p>` mappings to switch tabs for a while without problems.  But after upgrading to Firefox 45 when I switch tabs using `<c-n>` it also opens a new window.  I'm not sure whether this is a change/bug in Firefox or VimFx, but it used to work well before.

VimFx version: 0.12.0 
Firefox version: 45
OS: Arch Linux
Keyboard language: en-US
Worked before: yes

**Comment by lydell** [comment]
Sorry, but I can’t reproduce this.

**Comment by lydell** [comment]
My guess is that this is an extension conflict. Please try it out in a clean profile. Closing until then.

**Comment by spacepluk** [comment]
Hi @lydell,
You're right, there's something wrong with my profile.  Thanks for checking.
