### ISSUE TITLE
Export as config?

### ISSUE THREAD

**Issue by Noitidart** [akhodakivskiy/VimFx#713]
Is it possible export my settings as config? I didn't add any custom commands, just changed the hotkeys

**Comment by lydell** [comment]
No, it is not. But thanks for the idea. I’ve been thinking about it the last couple of days.

I’ve come to the conclusion that VimFx is not a JavaScript code generator.

I think it is easy enough to copy the output of `grep 'extensions\.VimFx' ~/.mozilla/firefox/$YOUR_PROFILE/prefs.js` into your text editor of choice (such as Vim—especially its `<c-v>` mode), and then adjust it.

**Comment by Noitidart** [comment]
Aw darn. Popular things I am replacing with VimFx (Mouse Gesutres Redox) had this awesome feature. Because I customize things so much, to set it up in my other profiles is a pain. I'll try out that `grep` thing, it sounds advanced and powerful.

I am working on an addon called mousecontrol, i have an export feature there because my average user couldn't figure out. But my average user is different then yours, you know yours better. Anyways super cool product!

**Comment by lydell** [comment]
The average VimFx user does not write a config file.

It also sounds like you should find some generalized tool or add-on for keeping your Firefox profiles in sync.

**Comment by Noitidart** [comment]
Totally understand.

I have different profiles on different computers for testing different
things, so I can't sync this to my main. I only sync my main across
computers with the awesome Firefox Sync! :)

VimFx I found to be so helpful I needed it on these non-main profiles I
had. Great tool you got here!

**Comment by lydell** [comment]
I’ve added something close to this suggestion in the development version: https://github.com/akhodakivskiy/VimFx/blob/8126a7275494f23be11c15b8c3627a3831055779/documentation/config-file.md#configjs

**Comment by Noitidart** [comment]
Very very cool. I wasn't able to figure out the way you recommended. So on my other systems I never could use VimFx because I could never set it up to the way I needed. 

It would be cool if this synced to "Sync" that would be cool too. :)
