### ISSUE TITLE
Config.js console.log not showing

### ISSUE THREAD

**Issue by parantapa** [akhodakivskiy/VimFx#718]
I am trying to move my older version of config to newer VimFx.
Previously I had a jetpack addon which interfaced with VimFx.
To make sure that I can debug through the process,
I started with a empty frame.js (contains a single line of comment)
and config.js which contains only the following.

    // VimFx config
    
    console.log("Loading vimfx config ...");

I expected to see the message on the browser console as described in the docs.
However, the message doesn't show up.
I have tried enabling and disabling VimFx,
I have tried changing console.log to console.error,
but the message still doesn't show up on my browser console.

VimFx version: I am using the current develop branch of VimFx (commit 645e35d)
Firefox version: Firefox developer version 47.0a2
OS: ArchLinux

**Comment by lydell** [comment]
1. What did you set `extensions.VimFx.config_file_directory` to?
2. Is that where `config.js` and `frame.js` are?
3. Did you run the `zr` command?
4. Did you get a successful or unsuccessful notification?
5. Are your sure you've opened the browser console and not the web console?
6. Are you getting any errors in the browser console?

I just tried this out, and it works for me, so I'm going to close this issue. But feel free to ask for more help in this issue! We'll re-open if needed.
