### ISSUE TITLE
Interfering with Firebug (editing HTML)

### ISSUE THREAD

**Issue by Forever-Young** [akhodakivskiy/VimFx#721]
Steps to reproduce:

1. Open Firebug
2. Choose HTML tab
3. Click Edit
4. Edit something, using VimFX hotkeys (i.e. using letters which are also VimFX hotkeys)

Expected result: 
Edits in text

Actual result: 
VimFX handles key presses

VimFx version: 0.13.0
Firefox version: 45.0.2
OS: Linux

**Comment by lydell** [comment]
I checked it out, and there’s no easy way to fix this, because Firebug has implemented their text inputs in a really crappy way. It’s also not worth investing in it: https://blog.getfirebug.com/2016/02/08/merging-firebug-into-the-built-in-firefox-developer-tools/
