### ISSUE TITLE
Can't install on Firefox version 45 and 46

### ISSUE THREAD

**Issue by EhtogShtam** [akhodakivskiy/VimFx#722]
| ✦ First: Search for DUPLICATES – also closed issues.
| ✦ Just updated VimFx? Check out the change log:
|     https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md
| ✦ Remove lines starting with `|` when done.

Steps to reproduce:

1. From about:addons install VimFX.
2. 
3. 

Expected result: 
VimFx should be installed.

Actual result: 
The installation seems to hang. VimFX is downloaded but not installed. I have tried several times the latest two weeks and with two versions off Firefox. On my addons page the status is Null. After a restart the addon is gone.

When starting Firefox from the command line, I get the following error message:

A coding exception was thrown in a Promise rejection callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError:  is not iterable
Full stack: AddonInstall.prototype.onStopRequest/<@resource://gre/modules/addons/XPIProvider.jsm:5800:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:936:21
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:11

| OR, for feature requests:

Detailed use case example: 

| ALWAYS include:

VimFx version: 
Firefox version: 
OS: 
Keyboard language: 
Worked before: 
Example URL(s): 

| EXAMPLE:
|
| Steps to reproduce:
|
| 1. Go to one of the online terminals on codeacademy.com.
| 2. Focus the online terminal.
| 3. Type something into it.
|
| Expected reult: VimFx recognizes the terminal as a text input, automatically
| allowing to type into it.
|
| Actual result: Instead of typing into the terminal I end up activating VimFx
| commands.
|
| A work-around is to use Ignore mode.
|
| VimFx version: 0.11.0
| Firefox version: 43
| OS: Ubuntu 15.04
| Keyboard language: en-US
| Worked before: No
| Example URL(s):
| - https://www.codecademy.com/en/courses/learn-the-command-line/lessons/navigation/exercises/your-first-command

**Comment by gyhor** [comment]
me too.
Tor 6.0 based on Firefox 45.1.1
