### ISSUE TITLE
When writing on Twitter, shortcuts may get in the way.

### ISSUE THREAD

**Issue by vincentbernat** [akhodakivskiy/VimFx#725]
Steps to reproduce:

1. Go on Twitter. Write a new tweet
2. Repeat the sequence "t" and "Backspace" in random order. For example "tttt" "Backspace" "ttt" "Backspace" "t"
3. At some point, observe a new tab has been opened

Expected result: 

No new tab should be opened as I am writting in a text area.

Actual result: 

At some point (in less than 5 seconds), a new tab is opened upon pressing "t". More annoying results can happen, when using "x" for example which may ends up closing the current tab. It seems that it only happens on Twitter. Unable to reproduce this on GitHub for example.

VimFx version: 0.14.3
Firefox version: 46
OS: Linux/Debian
Keyboard language: ?
Worked before: No
Example URL(s): https://twitter.com

**Comment by rpattabi** [comment]
This is not only true for typing on twitter, I also found this happening while typing on medium.com, disqus. This is very disturbing.

VimFx 0.14.3
Firefox 46.0
OS: Ubuntu 14.04 (64bit)

**Comment by vincentbernat** [comment]
I am using 0.15.1 and I still have a variation of the same problem. I have added `<backspace>` to "Go back in history" and just leaving the backspace key pressed in a tweet text area box will change the current page to the previous one.

**Comment by lydell** [comment]
@vincentbernat 

1. Added `<backspace>` to “New tab”.
2. Focused a new tweet text input.
3. Held `a` for a while to fill it up.
4. Held `<backspace>` to erase all `a`s.
5. Kept holding `<backspace>` for a while.

At no point was the “New tab” command triggered. I’ve tested this in both multi-process and non-multi-process Firefox with both VimFx 0.15.1 and latest master.

Have you tried adjusting the [`blur_timeout`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#blur_timeout) pref?

**Comment by vincentbernat** [comment]
I just tested the same steps as you and I reproduce the issue on two of my Firefox. However, my interest was more about assigning `<backspace>` to "Go back" but I just noticed that this is already a defaut binding for Firefox. And the "bug" doesn't happen with other keys (like "t" for example), so I am all good.

Also, adjusting `blur_timeout` doesn't change anything.

**Comment by lydell** [comment]
Then I recommend [disabling Firefox’s `<backspace>` handling](https://support.mozilla.org/en-US/questions/924490) and only use `<backspace>` in VimFx’s command.

**Comment by vincentbernat** [comment]
Not using `<backspace>` in VimFx and keeping its usage in Firefox works too. Thanks.

**Comment by lydell** [comment]
> works too

Eh? When _doesn’t_ it work then?

**Comment by vincentbernat** [comment]
Having both `<backspace>` bound in VimFx as "Go back" and enabled in Firefox for the same function.
