### ISSUE TITLE
Implement option to customise the size of hints.

### ISSUE THREAD

**Issue by tajjada** [akhodakivskiy/VimFx#727]
This is a usability issue.

I have a low-DPI monitor (physically large screen, relatively low resolution for the size), so I tend to browse the web zoomed out a lot (everything is too big with the default firefox settings). This means that certain areas on web pages can become densely populated with clickable elements. When I request hints, sometimes they overlap and are difficult to read. This is especially evident in reddit comments with RES.

Screenshot:

![test_scrot](https://cloud.githubusercontent.com/assets/4050671/15272661/2053734e-1a78-11e6-85a7-4e32377511f5.png)

Notice how many of these hints overlap and are difficult to read. Sometimes, I get unlucky, and the first letter of a hint I care about happens to be behind another hint, so I don't even know what first letter to type, to even get some of the irrelevant hints to disappear.

An easy way to solve this problem would be to provide an option to change the font size for the hints, and the size of the hints in general. I would personally prefer the hints to be smaller, with smaller text. However, no such option is currently available. At least, I did not find one.

**Comment by d125q** [comment]
Please consult [the docs](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/styling.md).

**Comment by lydell** [comment]
What @d125q said.

Other than that, all we can do is to adjust the default size. However, that’s very difficult. I want the defaults to be useful, pretty, fast and not broken—which results in a trade-off between all of those things. There are so many things to take into account: System font, respecting people’s system font size (everyone is not perfectly sighted), shadows may be slow, localized hint chars (some use characters like Ö which need enough spacing for those dots to fit), etc.

But I’ll make it easier to find in the docs in a minute.

**Comment by tajjada** [comment]
Thank you. Sorry for wasting your time. It was my fault for not looking through the documentation more thoroughly.
