### ISSUE TITLE
Update locales

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#728]
This is the plan:

1. [ ] Wait a few weeks.
2. [ ] Release 1.0.0.

Once 1.0.0 is released, there are no major changes planned. I hope to only focus on bug fixes and making sure that VimFx works with future Firefox versions.

It would be awesome if we could update all locales before 1.0.0!

Current status:

    de:    99%
    es:    100%
    fr:    99%
    id:    100%
    it:    99%
    ja:    100%
    nl:    100%
    pt-BR: 99%
    ru:    100%
    sv-SE: 99%
    zh-CN: 100%
    zh-TW: 100%

The locales with the most work to do have about 65 strings to translate, of which about half are only three words long or less. Many are also very repetitive, such as “Left”, “Right”, “Up”, “Down”. That’s not much work, is it? :)

@Kambfhase @benediktg @just-barcodes @strel @m-r-r @comepradz @cbertoldi @pluser @HJTP @atilacamurca @akhodakivskiy @mymedia2 @harius @lindhe @zhuochun @mozillazg @av2000ii @cyberrob @leVirve

**Comment by lindhe** [comment]
I won't pitch in at all during May, because of my BSc thesis wrapping up along with an exam in another course in the beginning of June. But I think you'll be able to handle the remaining 1% for sv-SE @lydell, if the window for translation runs out before exam week is over. ;)

**Comment by lydell** [comment]
@lindhe Don't worry. That last percent comes from one string being the same in both Swedish and English. I mentioned you mostly because I quickly copy-pasted a list of people who have contributed translations in the past (but also because you did a better job than me when you initially added the sv-SE locale). Good luck with your exams!

**Comment by lindhe** [comment]
Thanks :)

**Comment by lydell** [comment]
Summary of the first week: 5 people chimed in, and 4 locales were completed. Awesome! There are 7 locales left to complete.

**Comment by lydell** [comment]
Summary of the second week: 2 people helped completing 2 locales. Thanks!. That means 5 more to go – the ones that AMO warns about being too out-of-date every time I release a new version.

I know that @m-r-r is almost finished with the fr locale. Keep up the good work! :+1:

@cbertoldi, @atilacamurca, @akhodakivskiy, @mymedia2, @harius, @cyberrob, @leVirve: Do you have the intention to take half an hour or so and make a contribution sometime in the upcoming couple of weeks? Please drop a note here. I understand if you don’t have the time or motivation to do it.

**Comment by leVirve** [comment]
Forget to push previous commits and pull request last week. :cry: 
I will finish translation in `zh-tw` soon. Now I'm polishing the locale strings, and will update it today.

**Comment by m-r-r** [comment]
Hello,

I've updated the french locale some days ago, but I did not have the time to test it. I'm planning to test it and to make a pull request this evening.

**Comment by lydell** [comment]
Summary of the third week: 2 people helped completing 2 locales. @av2000ii went the extra mile and improved some already translated strings! Now, there's just 3 locales left.

**Comment by lydell** [comment]
Summary of the fourth week: 1 person completed 1 locale.

Summary of the first month: All locales except two have been completed. Awesome!

I think I’ll wait another two weeks or so before releasing 1.0.0, so there’s still time to update the pt-BR and ru locales before the “great release”!

**Comment by lydell** [comment]
Now all locales are fully updated! Thanks everyone!

**Comment by lydell** [comment]
Sorry, everyone. I decided to add that you can use shift, ctrl and alt in Hints mode to VimFx’s Keyboard Shortcuts dialog. This means that there are four new lines to translate:

```
help.last_hint_char=last_hint_char
mode.hints.peek_through=Hold to peek through markers
mode.hints.toggle_in_tab=Toggle whether to open a link in a new tab or not
mode.hints.toggle_in_background=Toggle whether to open a link in a background or foreground tab
```

It’s totally fine to simply drop translations of those in a comment here if that’s easier for you, and I’ll add them for you.

Sorry to nag you all again. I really hope there won’t be more changes now!

@just-barcodes @strel @m-r-r @comepradz @cbertoldi @pluser @HJTP @atilacamurca @mymedia2 @mozillazg @av2000ii @leVirve

**Comment by HJTP** [comment]
Why does the first one contain underscores? 
help.last_hint_char=laatste_hint_karakter
mode.hints.peek_through=Houd ingedrukt om door markeringen heen te kijken
mode.hints.toggle_in_tab=Links openen in nieuw tabblad of niet
mode.hints.toggle_in_background=Links openen in een tabblad op de voorgrond of op de achtergrond

**Comment by lydell** [comment]
@HJTP Thanks!

> Why does the first one contain underscores?

Because it is shown like this in the Keyboard Shortcuts help dialog:

```
<c-last_hint_char>
    Hold to peek through markers
<a-last_hint_char>
    Toggle whether to open a link in a new tab or not
```

**Comment by atilacamurca** [comment]
~~~
help.last_hint_char=último_caractere_de_dicas
mode.hints.peek_through=Segure para espiar através de marcadores
mode.hints.toggle_in_tab=Alternar quando abrir um link em uma nova aba ou não
mode.hints.toggle_in_background=Alternar quando abrir um link em segundo plano ou primeiro plano
~~~

**Comment by cbertoldi** [comment]
Italian:

help.last_hint_char=ultimo_carattere_d_'_aiuto
mode.hints.peek_through=Tieni premuto per dare un'occhiata alle marcature
mode.hints.toggle_in_tab=Determina l'apertura di un collegamento in una nuova scheda
mode.hints.toggle_in_background=Determina l'apertura di un collegamento nella scheda in primo o secondo piano

**Comment by lydell** [comment]
@cbertoldi That `_'_` looks really odd to me. I don't know Italian, but isn't that supposed to be `ultimo_carattere_d'aiuto`?

**Comment by cbertoldi** [comment]
Yes, without I've erroneously added a _ as space.

**Comment by comepradz** [comment]
locale-id

**Comment by comepradz** [comment]
locale-id

help.last_hint_char=karakter_petunjuk_terakhir
mode.hints.peek_through=Tahan untuk melirik melalui penanda
mode.hints.toggle_in_tab=Aktfifkan membuka link di tab baru atau tidak
mode.hints.toggle_in_background=Aktifkan membuka link di tab background atau foreground

**Comment by just-barcodes** [comment]
de
```
help.last_hint_char=letzter_Hinweis_Zeichen
mode.hints.peek_through=Gedrückt halten um durch Markierungen zu spähen
mode.hints.toggle_in_tab=Umschalten ob ein Link in einem neuen Tab geöffnet wird oder nicht
mode.hints.toggle_in_background=Umschalten ob ein Link im Hinter- oder im Vordergrund geöffnet wird
```

**Comment by lydell** [comment]
@m-r-r @pluser @mymedia2 Only you left :)

**Comment by m-r-r** [comment]
Hello,

I'm going to do that tonight, sorry for the delay :-/

**Comment by mymedia2** [comment]
@lydell sorry for the late reply

**Comment by lydell** [comment]
@mymedia2 No worries! Are you satisfied with that commit you’ve made? If so, either make a PR, or just let me know here and I’ll merge it.

**Comment by mymedia2** [comment]
@lydell, yes, I am. This is final form. You can merge it.

**Comment by lydell** [comment]
@m-r-r Did you ever get around translating those last 3 lines? :)

**Comment by m-r-r** [comment]
@lydell I had totally forgotten :-(

```
help.last_hint_char=dernier_caractere_marqueur
mode.hints.peek_through=Maintenir pour voir à travers les marqueurs
mode.hints.toggle_in_tab=Activer ou désactiver l'ouverture dans un nouvel onglet
mode.hints.toggle_in_background=Activer ou désactiver l'ouverture dans un nouvel onglet en arrière-plan
```

**Comment by lydell** [comment]
@m-r-r Thanks! When I was going to put those translations in, I noticed that `mode.hints.increase_count=Increase count` had accidentally been blanked out instead of translated back in October last year. Would you mind translating those two last words while at it?

**Comment by m-r-r** [comment]
@lydell 

```
mode.hints.increase_count=Augmenter le nombre
```
