### ISSUE TITLE
Evernote web clipper 

### ISSUE THREAD

**Issue by mirguest** [akhodakivskiy/VimFx#733]
Steps to reproduce:

1. Install VimFx and evernote web clipper (6.2.0)
2. Click evernote button to clip a web site, then the clipper box will pop up.
3. Press some keys in title or tags. For example, Press d.

Expected result: 
The pressed key d should be in the input box.

Actual result: 
The VimFx command d is triggered.

VimFx version: 0.14.3
Firefox version: 46.0.1
OS: Windows 7 (64 bit)
Keyboard language: en-US

**Comment by mirguest** [comment]
![nvw4oqwdce](https://cloud.githubusercontent.com/assets/831611/15416677/a6df5232-1e80-11e6-96fe-0251fda8f714.gif)

**Comment by lydell** [comment]
Thanks for your excellent bug report! The fix will be released soon.
