### ISSUE TITLE
VimFx doesn't enter insert mode when composing e-mail and focusing in Message Body text area in Outlook Web Access (OWA) 2010

### ISSUE THREAD

**Issue by helkaluin** [akhodakivskiy/VimFx#735]
Steps to reproduce:

1. Visit an OWA 2010 (v. 14) instance and compose a new e-mail.
2. Focus on the message body text area (bug doesn't happen in other text areas such in the To: and CC: fields).

Expected result: VimFx should enter insert mode.

Actual result: It doesn't.  Keys are still captured by VimFx, resulting in haphazard behaviour such as reloading all tabs when you type "Dear" as "ar" gets captured.

VimFx version: 0.15.0
Firefox version: 46.0.1
OS: Ubuntu Linux 16.04
Keyboard language: en-UK
Worked before: N/A
Example URL(s): Cannot provide example URL as it depends on my work credentials to log in.

**Comment by lydell** [comment]
> Cannot provide example URL as it depends on my work credentials to log in.

That plus the fact that I have no idea what OWA is, is a deal breaker. Sorry.

**Comment by helkaluin** [comment]
OWA (Outlook Web Access) is the webmail interface exposed by Microsoft Exchange servers.  It basically allows you to access your Outlook mail (and contact book and calendar) via your web browser.

Is there any way that I could perhaps save an offline copy of the webpage in question so that you could look at it?

**Comment by lydell** [comment]
Perhaps. Try hitting `<c-s>`.

**Comment by helkaluin** [comment]
Here you go, all tar'd up: https://dl.dropboxusercontent.com/u/21952910/owa-compose.tar.gz

**Comment by lydell** [comment]
I just unpacked your tar file. Unfortunately, the message body text area consists of:

```html
<iframe id="ifBdy" class="w100" src="14.3.279.2/scripts/premium/blank.htm" frameborder="0"></iframe>
```

... and `14.3.279.2/scripts/premium/blank.htm` is missing, so I can't test anything. (Did you try it out before uploading?)

Feel free to make new attempts. Closing until then.

**Comment by helkaluin** [comment]
I've struggled with "translating" that during saving.  It keeps pointing to that IP.  Even tried using MHT, no luck.

Regardless, the content of that blank.htm is just the following:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<meta http-equiv = "Content-Type" content = "text/html; charset=utf-8" />
	</head>
	<body>
	</body>
</html>
```

**Comment by lydell** [comment]
Firefox interprets `14.3.279.2`  as a _directory,_ not an IP (it'd have to start with a protocol or `//` otherwise). I made a `blank.htm` file with the contents you posted and changed the `src` attribute to `src="blank.htm"`. That sure gave me a big, blank canvas at the bottom of the screen, but I wasn't able to interact with it in any way.

**Comment by helkaluin** [comment]
Ah well, I'm out of ideas.  Sorry for wasting your time on this --- I'll just remember to hit <ignore> next time I start typing an e-mail!
