### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by Q-Tran** [akhodakivskiy/VimFx#740]
Steps to reproduce:

1. Press and hold any navigation hjkl

Expected result: 
On key press, smooth scroll.
On key hold down, nothing.
On key unpress, stop scrolling

Actual result: 
On key press, go down 1 line (I can set this to a different constant, but result is still the same)
On key hold down key press a bunch (this leads to repeated 1 line jagged movements)
On key unpress, nothing

Since this project is aiming to emulate vimium. Note that vimium smooth scrolls like expected

**Comment by qqldd** [comment]
Hi, I want to know what is the status of this issue? Is there any updates?

I also want the same feature as described above.
