### ISSUE TITLE
focusing and scrolling iframes

### ISSUE THREAD

**Issue by redgda** [akhodakivskiy/VimFx#746]
Steps to reproduce:
1. go to http://www.w3schools.com/html/html_iframe.asp 
2. focus on first element on left iframe by "zf" (HTML tutorial), 
3. try to scroll by "j" key 

Expected result: 
scroll down focused iframe

Actual result: 
scroll main page

Workaround:
scrolling by up/down arrows works

VimFx version: 0.16.1
Firefox version: 46.01
OS: Linux Mint 17.3
Keyboard language: EN
Worked before: dont know
Example URL(s): 
http://www.w3schools.com/html/html_iframe.asp

**Comment by lydell** [comment]
That's not how VimFx works. You need to focus the frame itself, not elements within it, to be able to scroll the frame with VimFx's commands. Hint markers for scrollable elements have a scrollbar-looking right border.
