### ISSUE TITLE
Firefox crash using search keys on nim-lang.org

### ISSUE THREAD

**Issue by delurker** [akhodakivskiy/VimFx#747]
Steps to reproduce:

1. open [](http://nim-lang.org/docs/manual.html)
2. Hit "/" to search, type "object", hit "n" for next, hit enter to follow link, hit "n" for next
3. Firefox freezes (on windows), usually crashes on Linux.

Expected result: 
Find next instance of the word "object"

Actual result: 
Freeze or application crash

The above steps seem to be pretty consistent in reproducing the problem, but it happens all the time on several pages of this site (http://nim-lang.org), when using the search commands: "/" and "n" and "N" .  Sometimes the search bar at the bottom is not shown, but the cursor is still active in it.

Seems to be a problem when there is '#' in the url.

Used to work fine.  Must have been a recent update.

Otherwise, best vim keybindings on Firefox.

VimFx version: 0.16.1
Firefox version: 46.01 (Windows), not sure on Linux but up to date.
OS: Windows 10 and Arch Linux
Keyboard language: US Keyboard, English (Australia)
Worked before: Yes
Example URL(s): http://nim-lang.org/docs/manual.html

**Comment by lydell** [comment]
Thanks for your great report, but I cannot reproduce.

VimFx version: 0.16.1
Firefox version: 46.0.1, new profile, tried both multi-process and non-multi-process
OS: Ubuntu 16.04
Keyboard language: en

Try disabling the [`find_from_top_of_viewport`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#find_from_top_of_viewport) pref and see if it helps.

**Comment by d125q** [comment]
I can reproduce.  However, all I get is a small freeze.  @lydell, make sure you're trying http://nim-lang.org/docs/manual.html, and not some other page.

Disabling [`find_from_top_of_viewport`](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#find_from_top_of_viewport) does prevent this from happening.

VimFx version: 0.16.1
Firefox version: 46.0.1, new profile
OS: Arch Linux
Keyboard language: en-us

**Comment by lydell** [comment]
Yes, I used the provided example URL.

**Comment by d125q** [comment]
Note that all I'm experiencing is a freeze that sometimes goes away rather quickly, but sometimes stays for a few seconds.

**Comment by lydell** [comment]
I guess I have to remove the find_from_viewport feature altogether.

**Comment by lydell** [comment]
Now I can reproduce as well. I had to scroll down a bit first.

**Comment by lydell** [comment]
Perhaps we can replace this feature with being able to decide where to search from by using the `v` command.

**Comment by lydell** [comment]
I found an easy way to drastically speed things up.
