### ISSUE TITLE
Scroll mark command improvements

### ISSUE THREAD

**Issue by loonies** [akhodakivskiy/VimFx#750]
### Respect timeout for the scroll mark command

Steps to reproduce:

1. Press `m` (scroll mark command)
2. Do nothing

Expected result: 

The `Mark scroll position (press a key...)` notification goes away after
defined timeout (default _2000_ ms).

Actual result:

VimFx stays in pending mode forever.

### Don't use "special" keys as scroll markers

This use case applied to the `ESC` key. Maybe some other "special" keys
should be considered as well.

Steps to reproduce:

1. Press `m` (scroll mark command)
2. Press `ESC`

Expected result: 

The scroll mark command is canceled.

Actual result:

The `ESC` key is used as a scroll mark (test with `` `<ESC>``).

---

VimFx version: 0.16.1
Firefox version: 46.0.1
OS: Linux
Keyboard language: en-US
Worked before: Not sure
Example URL(s): Any

**Comment by lydell** [comment]
> notification goes away after defined timeout (default 2000 ms).

No VimFx notifications go away after a timeout (but such a feature was mentioned in #576). Convince me that it's useful.

> Don't use "special" keys as scroll markers

Why?

**Comment by loonies** [comment]
How do I escape from accidentally entering mark pending mode?

**Comment by loonies** [comment]
> No VimFx notifications go away after a timeout (but such a feature was mentioned in #576). Convince me that it's useful.

It was meant more of "get out of scroll mark pending mode" than
notification issue. I used "notification" to describe the problem.

**Comment by loonies** [comment]
Actually this notification should go away after defined timeout.
How is staying in scroll mark pending mode forever a good idea.

**Comment by lydell** [comment]
> How do I escape from accidentally entering mark pending mode?

Press any key. (If you already have marks that you don't want to override, simply don't use those keys.)

> defined timeout

Are you talking about the [timeout](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#timeout) option?

> Scroll mark pending mode should be canceled after defined timeout and notification cleared, otherwise it's misleading.

Would you mind elaborating on this?

**Comment by loonies** [comment]
>> How do I escape from accidentally entering mark pending mode?

> Press any key. (If you already have marks that you don't want to
> override, simply don't use those keys.)

 1. What you're saying is like designing a car without ability to turn
    it off, but instead shift into the 1st gear, pull hand brake and
    release clutch; or leave car running until gas runs out.
    
 2. Current behaviour is misaligned with other commands (say `gg`) where
    pressing `g` starts pending mode and expires after defined timeout
    if no other key is pressed.

>> defined timeout

> Are you talking about the timeout option?

Yes

>> Scroll mark pending mode should be canceled after defined timeout and
>> notification cleared, otherwise it's misleading.

> Would you mind elaborating on this?

Proposed enhacement should cancel `m` command after timeout
if no key is pressed in that window and notification message
(`Mark scroll position (press a key...)`) cleared so it's not
misleading. Basically the same way `g` command behaves.

**Comment by lydell** [comment]
Ok, I'm convinced. Thanks for your insight! :)

**Comment by loonies** [comment]
![](http://i.giphy.com/wti2YqFsdzucE.gif)
