### ISSUE TITLE
Question: How to turn off scrolly-lagish start of scrolling?

### ISSUE THREAD

**Issue by dulex123** [akhodakivskiy/VimFx#755]
No problem here, I think this is normal behaviour but it is rather irritating. 

When you press j or k scroll bar scrolls for one line, pauses(like 500ms) and then continues scrolling. Is it possible to disable this "feature"? Like it needs "time" to change directions (up and down). How to turn this off? Thanks

**Comment by dulex123** [comment]
Can you at least point in some way where to search for solution?

**Comment by d125q** [comment]
Go to `about:config`, type "smoothScroll" in the search bar, and fiddle with the preferences as much as your heart desires.

**Comment by dulex123** [comment]
@d125q Thanks for replying. I have tried turning off all of the smoothScrolling settings and decreasing all time intervals to 0. Nothing solves it :/ Maybe I wasn't clear about my problem.

 If you have Vimium on chrome/ium when you press j or k it scrolls instantly, while with VimFX it first scrolls a few lines, waits like ~150ms and continues to scroll. It is reaaaally unnecessary. Do you know if there is solution? 

Thanks
