### ISSUE TITLE
Is there a way to activate vimfx on a textarea

### ISSUE THREAD

**Issue by Jzarecta** [akhodakivskiy/VimFx#756]
I wonder if there is a way to activate the vim shortcuts on a text area like this,  a special escape button to get the visual and _normal mode_

**Comment by lydell** [comment]
Not really sure what you’re asking for, but you might be interested in these links:

- https://github.com/akhodakivskiy/VimFx/blob/master/documentation/shortcuts.md#force
- https://github.com/akahuku/wasavi
