### ISSUE TITLE
Both hints on bookmarks icon in toolbar open the same function

### ISSUE THREAD

**Issue by imsodin** [akhodakivskiy/VimFx#766]
First I would like to thank you for this great addon and the quick fix for #759. The update arrived and unfortunately I encountered a new problem:
The bookmarks icon in the main toolbar consists of two parts: On the left the star icon, on the right something like a briefcase. There are two hints displayed on the left of this icon and both perform the same action: They click the star symbol. I cannot access the briefcase i.e. the dropdown menu with the bookmarks.

Steps to reproduce:

1. Press zF
2. Select any of the hints located near the bookmarks icon on the main toolbar.

Expected result: One of the hints should open the dropdown menu with all the bookmarks.

Actual result: The current page gets bookmarked or if already bookmarked, the dropdown menu to edit this particular bookmark is opened.

VimFx version: 0.17.2
Firefox version: 46.0.1
OS: Debian testing
Keyboard language: En-UK
Worked before: unknown (due to #759)
Example URL(s): -

**Comment by progandy** [comment]
The same happens with other icons that are split into a toggle button and a menu like Greasemonkey, Referrer Control, or Session Manager. Both hints toggle the button and the menu is never displayed.
