### ISSUE TITLE
Follow link in a new private window

### ISSUE THREAD

**Issue by marcotc** [akhodakivskiy/VimFx#771]
VimFx currently supports opening a new private window, but there's no support for following links in a private new window.

Current workaround: Copy link, open new private window, paste link.

VimFx version: 0.17.3
Firefox version: 49.0a2 (2016-06-27)
OS: Windows 7 64-bit
Keyboard language: En-US

**Comment by lydell** [comment]
We already have too many `f` commands. I occasionally use the technique you describe (`yf<hintchars>Wp`), but seldom enough to justify a new command for it.

We'll reopen if there turns out to be popular demand for this feature.

**Comment by lydell** [comment]
I've added this to the [custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#open-a-link-in-a-new-private-window-using-hint-markers) section of the wiki now.

**Comment by lydell** [comment]
I changed my mind and added this anyway.
