### ISSUE TITLE
Cannot scroll in `about:config`

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#772]
Steps to reproduce:

1. Open `about:config`;
2. Blur the search bar if it's focused;
3. Try a scrolling VimFx command.

Expected result: Cannot scroll.

Actual result: Should be able to scroll.

VimFx version: 0.17.3
Firefox version: 47.0
OS: Arch Linux
Keyboard language: us
Worked before: Unsure
Example URL(s): `about:config`

**Comment by lydell** [comment]
I don't think it's worth investing time in figuring out how to scroll a XUL `<tree>`. It's a rare edge case. Also, Firefox's own `<space>`, `<pagedown>` and `<pageup>` don't work either. I think it's better to filter the prefs with the search input, press `<tab>` to focus the tree area, and then use the arrow keys, `<home>`, `<end>` etc. to navigate/scroll.
