### ISSUE TITLE
Blacklist not working for localhost

### ISSUE THREAD

**Issue by joelostblom** [akhodakivskiy/VimFx#777]
Steps to reproduce:
1. Add `localhost:*`, `localhost:8888/*`, `*localhost:8888*`, `127.0.0.1:/*` or similar to the VimFx blacklist.
2. Navigate to any of the localhost pages on the blacklist. 
3. Press VimFx shortcutes, such as 'F' and they still work. The only one that does not work so far is Shift + Escape. 

Expected result:
Blacklisted localhost sites should ignore VimFx shortcuts and instead let the served application make use of its shortcuts (in my case Jupyter notebooks). 

Actual result: 
VimFx shortcutes, such as 'F', still work. The only one that does not work so far is Shift + Escape.

VimFx version: 0.17.3
Firefox version: 47.0
OS: Antergos Linux (Arch derivative) with Gnome
Keyboard language: en-US
Worked before: No
Example URL(s):  Any localhost url. I tried with Jupyter Notebooks and mesa agent based modelling simulations.

**Comment by lydell** [comment]
As mentioned in the documentation, the [patterns must match the _entire_ URL to take effect](https://github.com/akhodakivskiy/VimFx/blob/6f84d15bf44e68e3664fafa34aa39a1e67c7373a/documentation/options.md#blacklist).

- `localhost:*`: Needs to be changed to `*localhost:*` or `http://localhost:*`.
- `localhost:8888/*`: Needs to be changed to `*localhost:8888/*` or `http://localhost:8888/*`.
- `*localhost:8888*: This one works for me.
- `127.0.0.1:/*: That `:/` slash is weird. While Firefox seems to understand it, it will never show up in the location bar (which is what you're matching against.) `*127.0.0.1:*`, for example, works fine for me. Also note that while `localhost` and `127.0.0.1` many times mean the same thing, the blacklisting feature is only a stupid string matcher.

Please post the exact URLs you're having trouble matching, and the exact value of your blacklist setting. Closing until then.

**Comment by joelostblom** [comment]
Thanks, sorry for not seeing that. When I could not get `*localhost:8888*` to work, I assumed something else was the problem rather than the full string match. But the same entry works today, so I must have missed something yesterday. I added `*localhost*` and `*127.0.0.1*` and all locally served pages seems to be ignored correctly now.

I still have the problem where I can't use Shift+Escape to temporarily ignore VimFx, but I noticed that is the case on all pages and it is not imoprtant to me now that the blacklisting is working.

**Comment by lydell** [comment]
You have misunderstood Ignore mode. By default, you're in Normal mode. In Normal mode, there is no `<s-escape>` shortcut. That's why it "doesn't work" for you. If you press `i`, or blacklist the current URL, you end up in Ignore mode (that's when VimFx's button is red). That's where `<s-escape>` exists; pressing it returns you to Normal mode again.

**Comment by lydell** [comment]
See also https://github.com/akhodakivskiy/VimFx/blob/6f84d15bf44e68e3664fafa34aa39a1e67c7373a/documentation/questions-and-answers.md#how-do-i-disable-vimfx

**Comment by joelostblom** [comment]
Ah ok, I see. Thanks for clarifying and sorry for the confusion.
