### ISSUE TITLE
Follow Link: inconsistent results between `f` and `F` (default bindings)

### ISSUE THREAD

**Issue by czipperz** [akhodakivskiy/VimFx#778]
Steps to reproduce:

1. Enable default key bindings
2. Go to a web page: [example](http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e)
3. Hit `f`: "Follow link, focus text input, or click button", see resulting hints, `ESC`
4. Hit `F`: "Follow link in a new background tab", see resulting hints, `ESC`

3 result:
https://i.sli.mg/SuKISn.png

4 result:
https://i.sli.mg/07BRRb.png

VimFx version: 0.17.3
Firefox version: 47.0
OS: Arch Linux, kernel version 4.0.7-2 x86_64 GNU/Linux
Keyboard language: US English (C locale)
Worked before: Don't know
Example URL(s): http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

I believe the problem has to do with how the different commands categorize links.  For example, the inbox link is not a option for `F` to select.  I think we should change the algorithm to filter links after putting hints on them.

**Comment by lydell** [comment]
Hi! I looked at your screenshots, and the one with `F` markers has fewer markers – as [expected](https://github.com/akhodakivskiy/VimFx/blob/6f84d15bf44e68e3664fafa34aa39a1e67c7373a/documentation/commands.md#the-f-commands--hints-mode).

You didn't say what your problem is, though. :) Closing until then.

**Comment by czipperz** [comment]
Well my problem is that I sometimes open something with `f` (lets say the hint is `A`), then realize I need to actually open it in a new tab.  I have a good memory so I just go `hFA`, hoping it will open it in a new tab.

I realize now after looking through the bindings that `Duplicate tab > Go back in history > Next tab` accomplishes this well enough for me.  Thanks.

**Comment by lydell** [comment]
What you really want to do is to hold ctrl while typing the last hint character.That toggles whether the link will open in a new tab or not. (You can alternatively hold alt to toggle between foreground and background tab. Currently, these are only mentioned in the documentation, but will be visible in VimFx's Keyboard Shortcuts help dialog in the next version).
