### ISSUE TITLE
AwesomeBar only works if I click on the location bar

### ISSUE THREAD

**Issue by elvis-sik** [akhodakivskiy/VimFx#782]
Steps to reproduce:

1. open Firefox with no extensions enabled (just to be sure it's not some weird interaction that is causing the problem)
2. focus on the location bar with `o`
3. type something, e.g. `awesome`

Expected result: 

Many suggestions based on my past navigation and bookmarks, such as `awesome` github lists, `awesomebar` links, etc.

Actual result: 

The dropdown list of suggestions seems to pop up for a fraction of a second, maybe without anything in it. It vanishes.

Notice that if I instead click on the bar, and type `awesome`, all expected suggestions come up.

VimFx version: 0.17.3
Firefox version: 46.0.1
OS: Arch Linux
Keyboard language: pt-br, though I use en-us as well and both reproduce
Worked before: as far as I remember, this hasn't work for the past several months since I've been using VimFx. I didn't even know I was missing something until now.
Example URL(s): this doesn't apply.

**Comment by lydell** [comment]
Do you by any chance you a program that auto-hides the mouse pointer?

**Comment by lydell** [comment]
Also, does it happen if you use any of the standard Firefox shortcuts to focus the location bar, such as `<c-l>` or `<f6>`?

**Comment by elvis-sik** [comment]
It was the program that auto-hides the pointer. I killed it and soon everything was back to normal.

Personally, I feel compelled to just stop using it. The reason that led me to start using it some time ago no longer applies.
