### ISSUE TITLE
Using XMLHttpRequest (XHR) in custom commands

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#784]
Is it possible to use [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) in custom commands?  If not, is there some alternative?

I would like to create custom commands for copying *shortened* URLs (using something like https://is.gd/), but have no idea how to send a GET request without using XHR.  Excuse the question, but the gazillion JavaScript APIs in Firefox are confusing to me.

**Comment by lydell** [comment]
You can use `vim.window.XMLHttpRequest` or, even better, [`vim.window.fetch`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch).
