### ISSUE TITLE
Find commands become buggy if attempt to open find bar while page is loading

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#786]
Steps to reproduce:

1. Type an address in the URL bar, preferable one that takes a while to load on your computer.  I am using https://en.wikipedia.org/wiki/Firefox.  Some large file/folder in GitHub works better, I guess.
2. Hit Enter.
3. Press / a few times right after the page has begun loading (Firefox indicates 'Waiting for ...').

Expected result: VimFx should open the find bar with the first /, and type in the rest of the /'s as a find string.

Actual result: 'Quick Find' bar opens (sometimes even _two_ times), which is what Firefox does by default when / is pressed.  VimFx find commands often become buggy afterwards.

VimFx version: 0.17.4
Firefox version: 47.0.1
OS: Arch Linux
Keyboard language: us
Worked before: Unsure

**Comment by lydell** [comment]
What happens if you change "Focus the search bar" to `/`? Does the Quick Find bar open instead of focusing the search bar then too? I'm trying to understand if your problem is related to the Find bar or not.

**Comment by d125q** [comment]
The search bar is focused.

**Comment by lydell** [comment]
Ok. Let's fix this at the same time as #760.

**Comment by lydell** [comment]
@d125q Can you reproduce this if you disable the [find_from_top_of_viewport](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#find_from_top_of_viewport) pref?

**Comment by d125q** [comment]
Sorry for being absent.  Yes, it does occur.

**Comment by lydell** [comment]
Thanks for letting me know that it wasn't related to the `find_from_top_of_viewport` option. I was sure that was the cause, but it turned out it wasn't. I managed to fix it. No need to wait for #760. Btw, I found this page to be really good to test on: https://html.spec.whatwg.org/
