### ISSUE TITLE
The scroll bar does not clickable at the bottom of screen

### ISSUE THREAD

**Issue by nammidd** [akhodakivskiy/VimFx#787]
With VimFx the scroll bar of browser does not clickable at the bottom of screen, if the scroll bar is small, it impossibly to drag without a wheel mouse (or VimFx).

VimFx version: 0.17.4
Firefox version: 47.0.1
OS: Arch Linux
Keyboard language: us
Worked before: Unsure

**Comment by lydell** [comment]
I canät reproduce this. This is what I did:

1. Went to https://addons.mozilla.org/en-US/firefox/
2. Resized the Firefox window until a horizontal scrollbar appeared.
3. Moved the mouse pointer on top of the scrollbar.
4. Held down the left mouse button on the touch pad of my laptop.
5. Moved another finger left-right on the touch pad.

Result: The page was scrolled horizontally as expected.

Closing until more information is provided.

VimFx version: 0.17.4
Firefox version: 47.0, with a new profile
OS: Ubuntu Gnome 16.04

**Comment by nammidd** [comment]
Way to reproduce it

1. Open any longest web page, for example this http://www.solutionstudios.com/
2. Scroll to the bottom of the page
3. Move the mouse pointer on the scrollbar
4. Hold down the left mouse button
5. Try to drag it

Basically this way you cant drag it, because it becomes bugged with VimFx.

**Comment by nathanmusoke** [comment]
I can confirm this.

In a new firefox profile I can drag the scroll bar from the bottom of the
page @nammidd suggested. After installing VimFx I cannot.

**Comment by nathanmusoke** [comment]
Actually, it does not seem to be restricted to long pages; this issues page is sufficient. If you have a big screen you may need a slightly longer page so that you get a scroll bar.

Scroll to the bottom of the page, and move the mouse pointer to the bottom of the scrollbar. It cannot be selected. The top and middle can be. The difference with a long page is that the whole scrollbar doesn't work.


Firefox version: 47.0.1

**Comment by lydell** [comment]
Ah, you're talking about the _vertical_ scrollbar (not the horizontal scrollbar as I thought), and only the bottom-most 20px or so. Now I see.
