### ISSUE TITLE
Change some default shortcuts before 1.0.0?

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#788]
Good defaults are important. I just haven't thought about them so much since I use a custom keyboard layout and have remapped most VimFx shortcuts because of that anyway.

The current defaults are a mixture of:

- Similarity to Vimium
- Similarity to Vim
- Things bolted on along the way as new commands have been implemented

One thing in particular that I'm not very satisfied with is the plethora of `f` commands. It's hard to remember which command does what, and there's no room for new `f` commands. Here's one idea:

- `zf` → `ef` (f as in focus)
- `zF` → `eb` (b as in browser)
- `gf` → `et` (t as in tab)
- `gF` → `ew` (w as in window)
- `zv` → `av` (you actually select _all_ of the element’s text)
- `zr` → `gC` (this frees up z entirely, and C as in config)

`yf`, `af`, `yv` stay the same because of the strong `y`-as-copy operator from Vim, and because `a` is a common prefix in VimFx to mean "all". I don't think it's worth adding `ey`, `ea`, `eV` (or something) as aliases.

`e` was chosen because it is close to `f` both alphabetically and physically on a QWERTY keyboard.

`` ` `` → `'` because `'` is easier to type – both on an en-US QWERTY keyboard and on some international layouts, such as the sv-SE layout.

Does the above make sense?

Are there any other default shortcuts you think should be changed?

**Comment by progandy** [comment]
> ```e``` was chosen because it is close to ```f``` both alphabetically and physically on a QWERTY keyboard.
I think ```c``` might be good, too. It is physically close and can be remembered as an abbreviation for choose or click, so choose/click an element and do something with it.

> I don't think it's worth adding ey, ea, eV (or something) as aliases.
That is my opinion, too. Those who want these shortcuts can configure them. Better keep the list of default commands free of duplicates and stay with well-known vim defaults.

**Comment by lydell** [comment]
@progandy Thank you very much for your input!

> I think `c` might be good, too.

Good idea. `c` is better than `e` in every way except that `e` is easier to type (in my opinion). Not sure what's best here.

> If you wish to replace `af`, then the simple follow `f` should be replaced, too I think.

Ideally, `f` should be changed to `ff` and all other variants should be `f<whatever>`. However, I think it's a bad idea to make one of the most common shortcuts a two-letter shortcut.

> Personally, I prefer `-`, `a-`, `g-` on my german keyboard layout for the search mode, but that should not be included in an international layout.

`/` is pretty sucky on a Swedish keyboard layout as well (shift+7). However, `/` is a very strong carry-over from Vim, and even Firefox has a `/` shortcut itself (quick find, which VimFx shadows).

**Comment by lydell** [comment]
To anyone reading this, please also comment if you strongly prefer not to change any defaults.

**Comment by progandy** [comment]
> Good idea. c is better than e in every way except that e is easier to type (in my opinion). Not sure what's best here.
```e``` is better for typing with the left hand (and if you have both hands on the keyboard). Sometimes I use only my right hand on the home row with middle finger on ```f```, little finger on ```j``` and index finger on ```c```. That works surprisingly well for navigating webpages and following links if you don't have to type any text.
