### ISSUE TITLE
Latest version of VimFx (0.15.0) not compatible with latest Firefox (44.0.2)

### ISSUE THREAD

**Issue by paullb514** [akhodakivskiy/VimFx#790]
Latest version of VimFx (0.15.0) (check for updates did not yeild a newer version) is listed as being incompatible with the latest version of firefox (44.0.2)

(I'm sure you guys are on top of this but there did not seem to be a corresponding issue, so I've ceated a ticket

**Comment by lydell** [comment]
The latest Firefox version is 48.

The latest VimFx version is 0.17.4.

VimFx has required Firefox 45 or later since version 0.13.0 (released in March this year).

**Comment by businessBoris** [comment]
@paullb514  Do you mean the ESR release? That's at 45 now.
