### ISSUE TITLE
What about broken <link rel=prev/next?

### ISSUE THREAD

**Issue by lolilolicon** [akhodakivskiy/VimFx#792]
For the `]` command, `<link rel="next"`, if found, is followed _unconditionally_. This is OK in most cases, but there are broken sites who mess it up, e.g. on `http://example.com/1` it goes,

    <link rel="next" href="example.com/2">

when clearly it means to say,

    <link rel="next" href="//example.com/2">

`]` on that page would go to `http://example.com/example.com/2`.

So what are the options? How about,

+ Fix this case automatically, by using simple heuristics; or
+ Allow user to override per site, to ignore (or transform `href` of) `<link rel` in `<head>`.

Actually example page: http://cnx.org/contents/AgQDEnLI@6.20:TrIRM88K@3/Introduction-to-Sociology

**Comment by lydell** [comment]
I think this is best solved via custom commands.

```js
// config.js
let {commands} = vimfx.modes.normal

vimfx.addCommand({
  name: 'follow_previous_custom',
  description: 'Click “Previous” link (custom version)',
  category: 'browsing',
  order: commands.follow_next.order + 1,
}, followPreviousOrNext.bind(null, 'follow_previous'))

vimfx.addCommand({
  name: 'follow_next_custom',
  description: 'Click “Next” link (custom version)',
  category: 'browsing',
  order: commands.follow_next.order + 2,
}, followPreviousOrNext.bind(null, 'follow_next'))

function followPreviousOrNext(name, args) {
  vimfx.send(args.vim, 'followPreviousOrNext', {name}, didFollow => {
    if (!didFollow) {
      commands[name].run(args)
    }
  })
}
```

```js
// frame.js
vimfx.listen('followPreviousOrNext', ({name}, callback) => {
  let {location} = content
  let next = (name === 'follow_next')

  if (location.hostname === 'cnx.org') {
    let selector = next ? '.foobar-next' : '.foobar-prev'
    let link = content.document.querySelector(selector)
    if (link) {
      link.click()
      return callback(true)
    }
  }

  callback(false)
})
```

**Comment by lolilolicon** [comment]
Well, thank you, that's impressive... but also a lot of lines!

I'd argue that an option to ignore `<head><link>`s would only require few lines of code in `commands-frame.coffee` (and defaults/docs etc...). A simple heuristics would require even less code, such as

    if (link.getAttribute('href').startsWith(document.domain))
        // ... prefix with '//' ...

Not so bad, no?

**Comment by lydell** [comment]
Yes, that’s an unfortunate number of lines.

Let’s revisit your (good!) ideas when we find a few more than _one_ example that has broken `<link rel="{prev,next}">` tags.

**Comment by lolilolicon** [comment]
Fair enough, damn this damn site damn it!
