### ISSUE TITLE
'follow' command is rather slow & expensive

### ISSUE THREAD

**Issue by lolilolicon** [akhodakivskiy/VimFx#793]
## Steps to Reproduce

1. Add the following config,

```js
//config.js

vimfx.on("locationChange", ({vim, location}) => {
  let {hostname} = location;
  vimfx.send(vim, "setHintMatcher", {hostname}, matched => {
    if (!matched) {
      vim.hintMatcher = null;
    }
  });
});
```

```js
// frame.js

vimfx.listen("setHintMatcher", ({hostname}, cb) => {
  vimfx.setHintMatcher((id, element, type) => {
    return null; // no one ever gets a hint
  });
  return cb(true);
}
```

1. Reload config.

1. Go to [Reddit](https://www.reddit.com/) or [Hacker News](https://news.ycombinator.com/). Remember we need the `locationChange` event.

1. When the page is fully loaded, press `f` and observe how long it takes for the notification `No markable elements found` to show up. Also try other similar 'follow' commands. For instance, `F` is much faster, `yf` noticibly slow.

---

The relevant code here,

```coffee
#commands-frame.coffee

  filter = (element, getElementShape) ->
    type = matcher({vim, element, getElementShape})
    if vim.hintMatcher
      type = vim.hintMatcher(id, element, type)
```

I think the problem is no matter what `hintMatcher` is, `matcher` is always run first. So all `setHintMatcher` does performance wise is add time to the whole process. What I expected at first was `setHintMatcher` would allow me to specify exactly how I want to look up the a particular page, so as to optimize the performance.

---
VimFx version: 0.17.4
Firefox version: 48.0
Example URL(s): https://www.reddit.com/ https://news.ycombinator.com/

**Comment by lydell** [comment]
Everything you say is correct. I don't think there's anything to do here.

**Comment by lolilolicon** [comment]
What is it that makes `commands.follow` so slow compared to `commands.follow_in_tab`? Is it the selectors passed to `helper_follow`?

Can't something be done to optimize the performance of those commands? Say restricting the target DOM to filter through, or change the selectors, you know allow some sort of custom settings.

**Comment by lydell** [comment]
To clarify, the hint matcher added using `setHintMatcher` is not meant to completely replace how elements are matched. It is supposed to _slightly tweak_ how elements are matched. As you can see in the VimFx source code you quoted, the added hint matcher takes the `type` returned from VimFx's own `matcher` as input.

Here are some relevant links for you:

- #409 (performance issue)
- #565 (request for `setHintMatcher`)
- #785 (request for custom hint commands)
- [Documentation explaining some hints performance
  stuff](https://github.com/akhodakivskiy/VimFx/blob/84ab80520b351e38c7fc8f02bf5252aea9145e32/documentation/options.md#hint-chars)
- [Documentation explaining hints and Hints
  mode](https://github.com/akhodakivskiy/VimFx/blob/84ab80520b351e38c7fc8f02bf5252aea9145e32/documentation/commands.md#the-hint-commands--hints-mode)

**Comment by lolilolicon** [comment]
Great, thanks for the elaboration. I'll read through those.
