### ISSUE TITLE
Lots of locationChange events fired

### ISSUE THREAD

**Issue by lolilolicon** [akhodakivskiy/VimFx#794]
## Steps to Reproduce

1. Add the following config,

```js
// config.js

vimfx.on("locationChange", ({vim, location}) => {
  let {hostname} = location;
  console.log(">>> " + hostname);
});
```

1. Reload config.

1. Open Browser Console; enable Logging.

1. Open any URL in a new tab.

## Expected Result

There should be _one_ log ">>> ..."

## Actual Result

Hundreds or thousands of repeats of ">>> ..." in the console log.

So that's a lot of `locationChange` events fired.
Is that expected? Because that would be unexpected...

Refreshing page generates one ">>> ...", at least at first. But after a link on the page is opened in a new tab, refreshing the original page displays the same issue.

---
VimFx version: 0.17.4
Firefox version: 48.0

**Comment by lydell** [comment]
Your expectations are correct. However, I can't reproduce. Here's my console output (with added comments).

```
>>>                 // When I opened a new, blank tab.
>>> www.reddit.com  // After I typed in "reddit.com" in the location bar.
>>> www.reddit.com  // After I reloaded the page.
>>> imgur.com       // After I opened a link in a new tab.
>>> www.reddit.com  // After I reloaded the page again.
```

VimFx version: 0.18.0
Firefox version: Developer Edition 50.0a2
OS: Ubuntu 16.04

**Comment by lolilolicon** [comment]
You don't get the red bubble thing on the right saying 1000? Hmm, could be some of my addons?

**Comment by lydell** [comment]
> You don't get the red bubble thing on the right saying 1000?

Correct.

> Hmm, could be some of my addons?

Very likely.

**Comment by lolilolicon** [comment]
How strange, now that I've restarted the browser, I can't reproduce this issue myself.
Let's see when it comes up again.

**Comment by lydell** [comment]
> `f` isn't actually so slow for you when you tested it, right?

Correct – it isn’t very slow for me. But it is noticeably a little bit slower on crowded pages such as on reddit and hackernews than on many other pages.

**Comment by lolilolicon** [comment]
Yes, but a big part of the time spent is for rendering the labels, so `setHintMatcher` on such sites does help with performance, actually. Thanks for this feature.

**Comment by lolilolicon** [comment]
Just some more info for future reference.

This seems to be some bug in Firefox, probably Dev Tools related. It seems to happen after I mess around with Inspector / Web Console & possibly some errors as logged in Browser Console... I don't know. What I know is right now, I'm having this issue (although on a much smaller scale... namely 3, LOL) and the symptom is this: I press `]` on Google Images which I've configured so it clicks that little button for next image; what happens is it goes to the 3rd image after, basically doing `element.click()` 3 times. So yeah... definitely same issue here, Firefox...
