### ISSUE TITLE
Create another method of acessing marks

### ISSUE THREAD

**Issue by aleprovencio** [akhodakivskiy/VimFx#797]
Keyboard layouts with deadkeys such as pt_BR, due to a firefox limitation can't do a `` ` `` because the required space would scroll down the page so it's currently impossible to access a mark. By the time I used pentadactyl I could access them with the `:marks` command. Can we have an additional interface to marks?

**Comment by aleprovencio** [comment]
Hello @lydell, any reasons on why you closed this issue?

**Comment by lydell** [comment]
I try to spend as much (of my free) time and provide as much information as the issue opener does on an issue.

**Comment by aleprovencio** [comment]
My bad :/

Rephrasing:

Firefox has a known bug on deadletter keyboard layouts such as "pt_BR" on which although it is able to normally do accented letters such as `á`, `à`, etc, it's not possible to reproduce the an `'`, ````` nor any other accents themselves, because they require a `<space>` to be pressed after them, and when that happens the scroll downwards movement happens and the accent is not reproduced.

That means that on VimFx, i can create a mark (i.e. `ma`), but can't access it (i.e. `'a`).

Not for the reason above, Pentadactyl provides a `:marks` command  that shows all the created marks and permits me to choose then with `<tab>`. I'm not suggesting that `:marks` should be implemented on Vimfx, but maybe we can come up with something.

VimFx version:  0.18.0
Firefox version: 48
OS: Arch Linux
Keyboard language: pr-BR
Worked before: No
Example URL(s): any scrollable

**Comment by lydell** [comment]
Well, VimFx 0.18.0 changed the defaults from `` ` `` to `'` exactly for this reason :) And, of course, nothing is stopping you from changing `` ` `` to whatever key you like.

**Comment by aleprovencio** [comment]
The `'` would also not work because it's a deadletter on my layout but only then I realized there's this `ignore_keyboard_layout` which is a sweeeeet thing.

Thank you for your good job @lydell, and all the vimFx crew!

**Comment by progandy** [comment]
It should also be possible to enter dead keys by pressing them twice instead of using space. I think that should work with VimFX.

**Comment by aleprovencio** [comment]
Hello @lydell, sorry for this offtopic question but can you suggest me a solution like vimfx's `ignore_keyboard_layout` for vim itself? I mean something that changes to us-layout when in normal mode and then when going to insert mode changes back to the default configured layout?

**Comment by lydell** [comment]
@aleprovencio Sorry, I don't know how to do that in Vim.
