### ISSUE TITLE
Feature request: export/backup config settings

### ISSUE THREAD

**Issue by nobk** [akhodakivskiy/VimFx#802]
When we reinstall firefox on new PC, we need quick import our config settings from backup. 
The vimrc/vimrc.js is good start, but not everyone have the time or ability write their own rc script by hand, using default GUI finish config settings and save/export a backup will more efficient.

**Comment by lydell** [comment]
See #245, #267, #625 and #713.

In other words, find a general way to sync/backup/export your Firefox stuff. Every add-on shouldn’t re-implement a prefs export/import system.

> The vimrc/vimrc.js is good start, but not everyone have the time or ability write their own rc script by hand,

To avoid confusing other readers: What @nobk is talking about here is a [config file](https://github.com/akhodakivskiy/VimFx/blob/62f2f030b3a9ddec4cd087c8b9ec41875cef6626/documentation/config-file.md), which is written in JavaScript.

**Comment by nobk** [comment]
because I dont want sync all my profile and extensions.

**Comment by progandy** [comment]
@nobk, you might be interested in [OPIE](https://addons.mozilla.org/en-US/firefox/addon/opie/)

**Comment by lydell** [comment]
I decided to add import/export after all.

**Comment by amn** [comment]
:,-( Saddened to see VimFx adding features that strictly speaking are not its business. One should use an extension that can select a namespace for export/import. Just my rant. Now I have stuff in my VimFx that I will never use.

**Comment by lydell** [comment]
@amn Fork and remove everything you don't need.
