### ISSUE TITLE
Closing pinned tab not working

### ISSUE THREAD

**Issue by mesuutt** [akhodakivskiy/VimFx#805]
Pressing `x` key for close tab on the pinned tab not working.

**Comment by lydell** [comment]
Correct. Neither does Firefox's default shortcut for closing tabs, `<c-w>`. This is by design.

**Comment by mesuutt** [comment]
Ok then why closing not pinned tabs with pressing `x` exist ?
I am using `x` instead `<c-w>` for close tabs and I want to close pinned tabs with `x` also. How can I do this?

**Comment by zachthompson** [comment]
Ran into this as well.  What about listing "gpx" in the shortcuts? Or do you not want to get into combinations of commands?
