### ISSUE TITLE
VimFx appears to make tabs slow to close

### ISSUE THREAD

**Issue by mcomella** [akhodakivskiy/VimFx#806]
Steps to reproduce:

1. Open a handful of tabs (I typically have sites like developer.android.com, search results, and stackoverflow.com open)
2. Wait a while
3. Close them in quick succession (e.g. cmd+w or vimFx shortcut)

Expected result: Tabs close as quickly as you trigger keyboard shortcut

Actual result: Some tabs close quickly but others can freeze for a few seconds. This occurs on two machines I use, both running Firefox 50, and similar versions of OS X, one of which is modern.

Without VimFx installed, I cannot reproduce the behavior (caveat: I haven't tried too hard)

VimFx version: 0.18.1
Firefox version: 50a2 (9/5/16)
OS: OS 10.11.6
Keyboard language: US – Dvorak
Worked before: Unknown

**Comment by lydell** [comment]
Ouch. This is _very_ unlikely to ever get solved. I don't test on macOS, and I have never experienced this myself. I'm going to leave this open for a while to attract other people, but most likely you'll have to:

1. Learn to live with it.
2. Fix it yourself.
3. Stop using VimFx.

**Comment by mcomella** [comment]
> Fix it yourself.

Any ideas what could be causing this? My uninformed guess would be GC cleanup after a tab closes.

Do you run multi-process? I do and the tab switching behavior changed slightly since it was added so I wonder if that could be related.

**Comment by lydell** [comment]
Unfortunately, I have no clue at all what could be causing this. If I had, I would probably have responded with something like: "I have this idea of what it _could_ be – can you try this experiment out and see if it helps?"

I _do_ run multi-process.

Please keep asking questions here. I'm happy to help with whatever you struggle with when diving into the code!

Even just reading the code and pointing out here that "hey, this looks suspicious" can be of help!
