### ISSUE TITLE
Scrolling with j & k triggers back 

### ISSUE THREAD

**Issue by volt4ire** [akhodakivskiy/VimFx#807]
Steps to reproduce:

1. Follow a link on a page
2. Press j or k to move up or down the page

Expected result: 
Scrolling up or down the page is triggered

Actual result: 
I am returned to the previous page in my history. This can be fixed by manually going forward to the page on which I wanted to scroll down

VimFx version: 0.18.1
Firefox version: 48.0.1
OS: Mac OS X 10.11.6
Keyboard language: en_US
Worked before: the bug went away in an update sometime earlier this year (I forget when exactly), but returned in the 0.18.0 release
Example URL(s): arstechnica.com

**Comment by lydell** [comment]
Here's what I did (in a completely new profile):

1. Went to http://arstechnica.com/
2. Went to http://arstechnica.com/science/2016/09/how-i-learned-to-stop-worrying-and-love-the-big-nasa-rocket/ by using the `f` command.
3. Pressed `j` a couple of times.

Result: The page was scrolled down. At no point was I returned to the previous page in the history.

VimFx version: 0.18.1
Firefox version: 48.0
OS: Ubuntu 16.04
Keyboard language: sv-SE

**Comment by volt4ire** [comment]
The issue only triggers occasionally while browsing; I've been trying to isolate the specific actions I take before it happens, but it seems to occur quite randomly. I can keep trying to find specific use patterns under which it occurs though

**Comment by volt4ire** [comment]
I've been able to isolate a specific circumstance under which the bug occurs consistently.

1. Open a new tab
2. Go to [en.wikipedia.org](en.wikipedia.org)
3. Go to [pcmag.com/reviews](pcmag.com/reviews)
4. Press space bar to scroll down

Expected result
Press k a few times to scroll back up 

Actual result
k triggers going back in history

**Comment by lydell** [comment]
Thanks for your update! I've tried to follow your steps exactly, but unfortunately I can't reproduce the problem now either. Have you tried this in a clean profile?

**Comment by volt4ire** [comment]
I just tried it in a blank profile (after installing VimFX) as per [these instructions](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and the same error occurred. Sometimes it requires pressing j or k a few times before triggering back, and other times it triggers immediately when pressing j at the top of the page in step 3.

**Comment by fprawits** [comment]
Just wanted to let you know that I also tried the exact same steps in ff 48 on ubuntu 16.04 and everything worked fine.
