### ISSUE TITLE
Remove trailing / at the end of URL copied with yy command

### ISSUE THREAD

**Issue by M5oul** [akhodakivskiy/VimFx#810]
Hi, thanks for this awesome Firefox extensions.
I would suggest to remove trailing `/` at the end of the URL copied with `yy` command.
It's a useless char. I always remove it, typo nazi…
Thanks.

**Comment by M5oul** [comment]
Will you accept If I do a pull request?

**Comment by lydell** [comment]
No. Make a custom command via a [config file](https://github.com/akhodakivskiy/VimFx/blob/c82d7a4c2ee8ccb1003fe0b06a24ca3dc347ea8c/documentation/config-file.md#config-file).

**Comment by M5oul** [comment]
Ok, thanks for this anwser. I will take a look at this config file.
