### ISSUE TITLE
Scroll without stopping

### ISSUE THREAD

**Issue by dseter** [akhodakivskiy/VimFx#811]
After pressing the button j or k page scrolls a bit, then stops for a second and scrolled further. This stop is very annoying. In Vimium no such problem.

VimFx version: 0.18.1
Firefox version: 48.0.2
OS: OS X 10.11.6
Keyboard language: en-US
Worked before: I dont know
Example URL(s): any

**Comment by dseter** [comment]
Why not? It is difficult or impossible?

**Comment by lydell** [comment]
Yes.

- The standard Firefox and Chrome arrow key shortcuts for scrolling work the same way.
- Actually, most programs work that way.
- It takes [~300 lines of non-trivial code](https://github.com/philc/vimium/blob/4b1654f820b645a339f98160a1607c042217bf9d/content_scripts/scroller.coffee) to do.
- IMO, holding `j` or `k` to scroll is an anti-pattern.

This is not something that bothers me, so I don’t feel like making a big time investment for it.

**Comment by braham-snyder** [comment]
> IMO, holding j or k to scroll is an anti-pattern.

Can you elaborate? With a sufficiently smooth scroll, holding j or k allows one to concurrently scroll and read.

**Comment by braham-snyder** [comment]
for what it's worth, if you happen to be using OS X, you can use something like this in Karabiner to achieve equivalent behavior:

```
<item>
    <name>1 ms DelayUntilRepeat for CTRL-E and CTRL-Y</name>
    <identifier>delayless_scroll</identifier>

    <only>FIREFOX, EMACS, TERMINAL</only>

    <autogen>
      __KeyToKey__
      KeyCode::Y, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL,
      KeyCode::Y, ModifierFlag::CONTROL_R,
      <!-- 1 millisecond -->
      DelayUntilRepeat::RawValue::1,
      <!-- <!-\- 1 millisecond -\-> -->
      <!-- KeyRepeat::RawValue::1, -->
    </autogen>

    <autogen>
      __KeyToKey__
      KeyCode::E, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL,
      KeyCode::E, ModifierFlag::CONTROL_R,
      <!-- 1 millisecond -->
      DelayUntilRepeat::RawValue::1,
      <!-- <!-\- 1 millisecond -\-> -->
      <!-- KeyRepeat::RawValue::1, -->
    </autogen>

</item>
```

**Comment by volt4ire** [comment]
@braham-snyder this looks like a great solution, but Karabiner no long works in 10.12. Do you know if there's a way to do something similar in its successor, [Karabiner-elements](https://github.com/tekezo/Karabiner-Elements)?

**Comment by braham-snyder** [comment]
@volt4ire full-featured Karabiner is precisely why I'm still using 10.11--no clue whether `DelayUntilRepeat` in particular has been implemented in elements yet

also, for what it's worth: though I still have that Karabiner item enabled, I almost always press <kbd>j</kbd> or <kbd>k</kbd> instead--I think I only use those chords if I'm already holding down control from, e.g., <kbd>C</kbd>-<kbd>d</kbd>
