### ISSUE TITLE
addKeyOverrides & Hints mode

### ISSUE THREAD

**Issue by lolilolicon** [akhodakivskiy/VimFx#812]
1. Add config,
```js
// config.js
vimfx.addKeyOverrides(
  [ () => true, [ "j" ] ]
);
```

1. For this to take effect, you *may* need to disable then enable VimFx in about:addons
1. Open a web page with links.
1. Press `f` then `j`, assuming there is a hint mark starting with `j`
1. This `j` is ignored by VimFx.

In summary, if `addKeyOverrides` is at all used on a page, Hints mode will be partially broken.

---
VimFx version: 0.18.1
Firefox version: 48.0.2

**Comment by lydell** [comment]
You probably want this:

```js
// config.js
vimfx.addKeyOverrides(
  [ (location, mode) => mode === 'normal', [ "j" ] ]
);
```

Problems:

- The above isn’t very clear in the documentation.
- The example in the documentation does _not_ check for `mode === 'normal'`, and thereby suggests a bad pattern.
- Is there a use case for applying `addKeyOverrides` in any other mode than Normal mode?

**Comment by lolilolicon** [comment]
Ouch, I didn't check the doc before posting the issue, my bad.
Yeah, basically I coasted along and just added another entry modelled upon the same pattern, without thinking of an optional `mode` argument.
I'm adding `mode === 'normal'` to all my rules here. I can't think of a case where you'd use `addKeyOverrides` for other modes... perhaps change the default value of `mode` to `normal`?

**Comment by lydell** [comment]
I’m thinking about scrapping the `mode` argument completely and only applying `addKeyOverrides` in Normal mode.

**Comment by lolilolicon** [comment]
Probably no problem doing that :+1:
