### ISSUE TITLE
Can't get the elements vim.window.document.getElementsByTagName()

### ISSUE THREAD

**Issue by typetonk2** [akhodakivskiy/VimFx#815]
Referring to the window object from web console, I can get the elements.
Referring to the vim.window object from VimFx, I can't get the elements.

How do I get the elements from VimFx?

### Steps to reproduce:

1. To prepare the following custom command.

    ```
    vimfx.addCommand({
      name: 'get_test',
      description: 'getElementsByTagName test',
    }, ({vim}) => {
      let elem = vim.window.document.getElementsByTagName('p');
      vim.notify("elem: "+ elem[0].innerHTML);
    })
    vimfx.set('custom.mode.normal.get_test', 'yc')
    ```

2. Execute a custom command.

### Expected result:  

Get element is output to the notification area. (usually, it lower right)

### Actual result: 

Not output.
Check the browser console, the following message is output.

    TypeError: elem[0] is undefined[Learn More]

### Additional information:

* If execute the same command directly from web console, can get the element.

    ```
    let elem = window.document.getElementsByTagName('p'); print (elem[0].innerHTML);
    "This file documents VimFx’s <a href="/akhodakivskiy/VimFx/blob/master/documentation/config-file.md">config file</a> API."
    ```

* If vim.window.document.title, it can be get from VimFx.

---
VimFx version: 0.19
Firefox version: 52.0a1(Nightly)
OS: Windows10
Keyboard language: ja
Worked before: Unsure
Example URL(s): github.com

**Comment by progandy** [comment]
It is likely that your tabs are running in their own threads. You'll have to use frame.js and vimfx.send to access the page source. 
https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md#framejs

**Comment by lolilolicon** [comment]
I think you want `vim.window.content.document`

**Comment by lydell** [comment]
- `vim.window` is the `window` in the _browser_ console (`<c-J>`), not the _web_ console (`<c-K>`).
- You don’t want `vim.window.content.document`. That’s a terrible hack, which will stop working when e10s is enabled for all users.
- You want to follow this example: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#vimfxsendvim-message-data--null-callback--null

**Comment by typetonk2** [comment]
Oops, I had a misunderstanding.
Thank you everyone, I will read the document again.

**Comment by lydell** [comment]
I've updated the config file documentation to make it easier to understand.

**Comment by typetonk2** [comment]
I was able to get the element using frame.js, Thank you!
