### ISSUE TITLE
how to load preference.set in a separated file

### ISSUE THREAD

**Issue by dupontjoy** [akhodakivskiy/VimFx#817]
in config.js we can set preferences values
`Preferences.set({
'devtools.chrome.enabled': true,
})`

because I have so many lines of preferences values so I wonder is there a way to
1. store the preferences in a separated file like user.js in folder `dirname`
2. load the user.js file using config.js

**Comment by lydell** [comment]
This should do the trick:

```js
// config.js

let {utils: Cu} = Components
let {Preferences} = Cu.import('resource://gre/modules/Preferences.jsm', {})
let {PREFS} = Cu.import(`${__dirname}/user.js`, {})

Preferences.set(PREFS)
```

```js
// user.js

const EXPORTED_SYMBOLS = ['PREFS']

const PREFS = {
  'devtools.chrome.enabled': true,
  // ...
}
```

**Comment by dupontjoy** [comment]
Thanks for your reply but it seems not working

**Comment by dupontjoy** [comment]
Thanks for your reply but it seems not working

**Comment by lydell** [comment]
Sorry about that. Apparently Firefox does not allow exporting `const`s (but `var`s work). I've updated the code.

**Comment by dupontjoy** [comment]
Thanks a lot, problem solved
