### ISSUE TITLE
Paste to go doesn't use updated (via yv) clipboard

### ISSUE THREAD

**Issue by hjri** [akhodakivskiy/VimFx#818]
Steps to reproduce:

1. Copy some text URL using `yv`
2. Press `p` or `P` to open clipboard in current/new tab.
3. Page opens with copied url - OK.
4. Go back to previous page (close tab or go back)
5. Repeat steps 1 and 2 using other URL.

Expected result: 
Page opens with recently copied url

Actual result: 
Page opens with previously copied url

Some more info: 
* firefox context menu "Paste and go" works fine. 
* `yv` command updates clipboard correctly (i can paste it anywhere in OS, but not while using `P`).
* `p` and `P` work normal when using default system shortcuts. (Ctrl-C/Ctrl-X)

VimFx version:  0.19.1
Firefox version:  49.0
OS:  Debian Linux x64 testing
Keyboard language:  English US
Worked before: no
Example URL(s): https://jsbin.com/figinasapi

**Comment by lolilolicon** [comment]
AFAIK, VimFx behaves this way under X,
* Since #382 `p` and `P` pastes PRIMARY selection.
* `yv` copies text to clipboard only.
* `yy` `yf` and Caret mode `y` (since text is *selected*, duh) copy to both.
