### ISSUE TITLE
Text inputs inside frames immediately blur after being focused using an `f` command

### ISSUE THREAD

**Issue by knobhead** [akhodakivskiy/VimFx#825]
- [X] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [X] I've provided the below details:

VimFx version: 0.20.1
Firefox version: 49.0.1
OS: Win7 64-bit
Keyboard language: de_DE
Example URL (if any): can't give, internal system at work :(

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

**Steps to reproduce:**

1. Open data entry form in a new tab. (It's a crappy, 2003-style web-based application that actually still uses frames, but VimFX used to work just fine until recently.) Text-box auto-focus on page load is disabled.
2. Press 'f' key to show hints and enter the hint letters.

**Expected result:**  
The text box is focused, I can see the blinking cursor inside the text field and start typing.

**Actual result:**  
The text box is focused, I can see the blinking cursor inside the text field, but focus is lost immediately, before I can start typing.

**Additional info:**  

- When I press TAB after the focus was lost, focus should be set on the next/following text box or focusable element. Instead, a focus border is drawn around the first frame in the frameset.
- I tried to reproduce this in a fresh Firefox profile with the newest VimFX version from addons.mozilla.org, both with default VimFX settings and imported VimFX settings from my main profile. 
- On non-frameset pages, focusing text boxes works fine.
- Unfortunately I can't tell which was the last version that worked, because I wasn't in the office for a few weeks and don't recall what version I was using back then. When I returned, FF updated itself and the extensions.

Any ideas? Thanks once more for this priceless tool!

**Comment by lydell** [comment]
Thanks for your report! This seems to happen for iframes as well.
