### ISSUE TITLE
zF not working 

### ISSUE THREAD

**Issue by johnwmail** [akhodakivskiy/VimFx#826]
VimFx version: 0.20.3
Firefox version: 49.0
OS: Debian/64bit
Keyboard language: English
Example URL (if any): 

I noticed, function key 'zF' not working any more.
type zF on any page, nothing to happen

**Comment by lolilolicon** [comment]
The default shortcuts was changed in 6b5f267 two months ago.
You can always press `?` to see your key bindings, where `/` can be used to search for keywords.

**Comment by johnwmail** [comment]
Yes, zF changed to eb now, thanks.
