### ISSUE TITLE
Searching in PDF causes weird bugs

### ISSUE THREAD

**Issue by d125q** [akhodakivskiy/VimFx#827]
VimFx version: 0.20.3
Firefox version: 49.0.2
OS: 64-bit GNU/Linux
Keyboard language: us
Example URL (if any): http://infolab.stanford.edu/~ullman/ialc/spr10/slides/rs2.pdf

Steps to reproduce:
1. Open http://infolab.stanford.edu/~ullman/ialc/spr10/slides/rs2.pdf
2. Open the search bar by pressing `/`, then type a search string such as `int`
3. Press `n` a few times.

Expected result: VimFx continues searching.

Actual result: VimFx stops searching.  Furthermore, VimFx stops working completely on _all_ other tabs.  In order to make it work again, you have to go back to the PDF, press `Esc` to exit from the Find mode, then press `/` again, then exit normally again.

Note that this is not limited to the PDF given above.

**Comment by aleprovencio** [comment]
Yes, I can confirm that also.
