### ISSUE TITLE
seems not support HTML <img> usemap Attribute

### ISSUE THREAD

**Issue by seaspeak** [akhodakivskiy/VimFx#828]
- [x] I've searched for duplicates – also closed issues
- [ ] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [ ] I've provided the below details:

VimFx version: 0.20.3
Firefox version: 49.0.2
OS: Windows10
Keyboard language: En
Example URL (if any): http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_areamap

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [x] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [ ] Something else

Steps to reproduce:

1. Go to http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_areamap
2. Press `f`.

Expected result: There should be hint marker for the planets.

Actual result:  There is no hint marker for the planets

**Comment by lydell** [comment]
Thank you for your report! :)

Closing until examples of _real_ sites where supporting this is needed are provided.

**Comment by seaspeak** [comment]
real site: http://ever-transmission.com.tw/
Please reopen the issue, thanks.

**Comment by seaspeak** [comment]
with a real stie and other discussion provided, still being closed. nice way...!

**Comment by lydell** [comment]
Yes, _one_ site, reported by _one_ person. That doesn’t justify the time needed to implement and maintain support for it.

But don’t worry – it’s not uncommon that issues get re-opened after some time, when more information has been provided and more people have chimed in.
