### ISSUE TITLE
how to implement select text and use the default search engine to searh the selected text in new tab

### ISSUE THREAD

**Issue by blueyi** [akhodakivskiy/VimFx#832]
I need search some text in current tab, so I have to select it use caret mode, then right click in the page and select search "Search google for "some text"" use mouse. I have searched VimFx document, but find nothing about it. So I need help, how to implement select text and use the default search engine to search the selected text in new tab, thanks.

**Comment by blueyi** [comment]
@lydell   Thanks, but I got an syntax error when I use  your command in my config.js. The following is the error detail, can you help me, thanks a lot.
![synct](https://cloud.githubusercontent.com/assets/6254020/20036411/e639313a-a442-11e6-9f4e-cc358559ec90.jpg)

```
// config.js
vimfx.addCommand({
  name: 'search_selected_text',
  description: 'Search for the selected text'
}, ({vim}) => {
  let {messageManager} = vim.window.gBrowser.selectedBrowser
  let callback = ({data: {selection}}) => {
  vimfx.send(vim, 'getSelection', null, selection => {
    let inTab = true // Change to `false` if you’d like to search in current tab.
    vim.window.BrowserSearch.loadSearch(selection, inTab)
  })
})
map('s', 'search_selected_text', true)
````
following code is frame.js
```
vimfx.listen('getSelection', (data, callback) => {
    let selection = content.getSelection().toString()
    callback(selection)
})
```

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#search-for-the-selected-text

(Also, you can use the `<menu>` key on your keyboard instead of right-clicking.)

**Comment by lydell** [comment]
> I got an syntax error when I use your command in my config.js

Sorry about that. I’ve updated the code.

(To others reading: The last two comments somehow are in the wrong order.)

**Comment by blueyi** [comment]
@lydell  Thanks
