### ISSUE TITLE
Add support for `j` and `k` keys in back/forward button menu

### ISSUE THREAD

**Issue by comradealain** [akhodakivskiy/VimFx#833]
VimFx version: 0.20.3
Firefox version: 49.0.2
OS: Ubuntu 16.04(64-bit)
Keyboard language: English

This is a **feature request**

When I press `gH` it opens up back/forward button menu. For moving up and down on the menu I've to either use mouse or arrow keys. It will be helpful if we can use `j` and `k` for moving down and up respectively.

**Comment by lydell** [comment]
Sorry, this is unfortunately not possible. You might be interested in:

- #642 
- https://github.com/akhodakivskiy/VimFx/blob/d7defc96e99ccfefdbf68a9c14833c9baceaea39/documentation/handy-standard-firefox-features.md#menus
- A custom keyboard layout with better placement of the arrow keys :)

**Comment by comradealain** [comment]
Fine. Thanks for the links.
