### ISSUE TITLE
Search for text in xul element

### ISSUE THREAD

**Issue by sleighsoft** [akhodakivskiy/VimFx#838]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.4
Firefox version: 50
OS: Windows
Keyboard language: us
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [x] A feature request
  - [x] I've given a **detailed** _example_ below
- [ ] Somehting else

When being on the `about:addons` options panel of VimFx `/` does not search in `xul` elements. When searching for `pin` for example only 1 match is returned instead of 3. The match comes from the addon description but it does not pick up the Pin/unpin menu. This is not intuitive as I expected to jump to that section with my search. Instead I was forced to scroll and search it.

**Comment by lydell** [comment]
I totally agree. I've also wanted to search in about:addons pages many times. However, VimFx simply uses Firefox's own find bar. So it is a bug in Firefox, not VimFx.

**Comment by lydell** [comment]
Btw, as a workaround for finding the text input for changing a shortcut: https://github.com/akhodakivskiy/VimFx/blob/72485ddbf4e0c8a57201fe27f1dc69502542e01f/documentation/questions-and-answers.md#can-i-edit-shortcuts-in-the-keyboard-shortcuts-help-dialog
