### ISSUE TITLE
Skipping through tabs writes to page forms instead if one has the focus

### ISSUE THREAD

**Issue by devnoname120** [akhodakivskiy/VimFx#839]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.4
Firefox version: 50.0
OS: Archlinux (Linux 4.8.8-2-ARCH)
Keyboard language: US (Qwerty)
Example URL (if any): Any page containing a form

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Something else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Open 3 pages, with the 2nd having a form
2. In the 2nd page, click on the form then click on the first tab with the mouse
3. With the keyboard, click on Shift + K to go to the next tab (the 2nd one)
4. While Shift is still pressed, press again K to go to the next tab (the 3rd one)

Expected result: 
The third tab is displayed.

Actual result: 
The form on the 2nd page gets a 'K' added to it.

Additional information:
This is especially annoying when I have a lot of tabs and want to skip through them quickly but instead fill random forms, and need to press Esc every time I mistakenly fill a form.

Suggestion on how to fix this:
Don't give the input to the inside of the page until Shift is released.

**Comment by lydell** [comment]
This won't happen. Sorry. See this for alternatives: https://github.com/akhodakivskiy/VimFx/blob/72485ddbf4e0c8a57201fe27f1dc69502542e01f/documentation/questions-and-answers.md#how-do-i-switch-tabs

(You could also see if you can come up with some custom [config file](https://github.com/akhodakivskiy/VimFx/blob/72485ddbf4e0c8a57201fe27f1dc69502542e01f/documentation/config-file.md) code that blur focused text inputs whenever you want them to.)
