### ISSUE TITLE
The new Responsive Design Mode in Firefox 52 breaks VimFx

### ISSUE THREAD

**Issue by lydell** [akhodakivskiy/VimFx#840]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.4
Firefox version: 52.0a2 (2016-11-24) (64-bit)
OS: Ubuntu 16.04
Keyboard language: en-US
Example URL (if any): https://developer.mozilla.org/en-US/

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Go to https://developer.mozilla.org/en-US/
2. Enter Responsive Design Mode by pressing `<c-M>`.
3. Click the search field near the top of the page.
4. Type something into it, for example `t`.

Expected result: The VimFx icon turns grey and VimFx lets you type in the search field.

Actual result: The VimFx icon stays green and when trying to type in the search field VimFx commands are activated. For example, when trying to type a `t`, a new tab is opened.

Additional info:

- This happens on any site.
- Even after closing the Repsonsive Design Mode, VimFx still doesn't recognize text inputs in that tab. Reloading the page does not help.

---

I've looked into the issue a bit, and it seems like Firefox replaces the entire page with a special Responsive Design Mode page with an `<iframe>` containing the original page. When focusing anything inside that `<iframe>`, VimFx seems to only see that the `<iframe>` itself is focused, but not what's focused inside. Tricky problem.

**Comment by lydell** [comment]
Part of the problem seems to be a Firefox bug. I've reported it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1320159

**Comment by lydell** [comment]
Actually, all communication with the webpage and VimFx is cut off as soon as Repsonsive Design Mode is opened. For example, the `f` commands find the clickable elements in the RDM UI itself, but nothing in the actual webpage – even after closing RDM! 

VimFx behaves as if you visited `about:blank` in tabs were RDM has been opened. There seems to be no way to "revive" the tab. Closing it and opening a new one is the workaround.

**Comment by interleaved** [comment]
Just FTR some references, hope @lydell doesn't mind. I had to search for it. Otherwise, I remove the comment :)

[Description of the Responsive_Design_Mode, Dec 2, 2016](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode)

[New Responsive Design Mode: RDM Lands in Firefox Dev Tools, Nov 22, 2016](https://hacks.mozilla.org/2016/11/new-responsive-design-mode-rdm-lands-in-firefox-dev-tools/)

[Introducing: Responsive Design Mode in Firefox Developer Tools, Nov 28, 2016](https://medium.com/mozilla-tech/introducing-responsive-design-mode-in-firefox-developer-tools-d34a144a0a67)

Is it needed that VimFx is able to handle RDM? Or better detect if the user switched to it and disable VimFx on that event?

**Comment by lydell** [comment]
I don't know how to answer your questions, but here's what I can say:

The old RDM was completely transparent to add-ons. They couldn't tell that RDM was open or not (unless they specifically went looking for that). The new RDM is completely different. Opening it is like opening a new tab with a bunch of buttons and a single, empty `<iframe>` in it (which throws errors if you try to go inside of it). Closing it is like opening a new tab which add-ons never get to know about (basically).

**Comment by lydell** [comment]
Closing since this won't be fixed.
