### ISSUE TITLE
Scrolling with d/u grinds to a halt, but j/k works fine

### ISSUE THREAD

**Issue by HunterGraubard** [akhodakivskiy/VimFx#843]
**Bug report:**

Scrolling with the "d" and "u" keys works smoothly at first, but when holding them down to scroll longer pages, the scrolling starts getting slower and slower - eventually it grinds to a halt. However, if I scroll with the "j" and "k" keys, it works fine and doesn't slow down.

I experience this issue with both Firefox and Tor Browser, and have therefore listed the versions for both below.

**VimFx version:** 0.20.4
**Firefox version:** 50.0.2
**Tor Browser version:** 6.0.7 (based on Firefox 45.5.1)
**OS:** Ubuntu 16.10
**Keyboard language:** UK
**Example URL (if any):** https://www.reddit.com/r/linux/comments/nau2j/why_is_kde_not_more_popular_when_its_toolsutils/

**Steps to reproduce:**
1. Load a long page.
2. Hold the "d" key to scroll down it.

**Expected result:** The page should scroll smoothly all the way to the bottom.

**Actual result:** The page scrolls slower and slower until it grinds to a halt.

**Comment by lydell** [comment]
Sigh. I'm getting really tired of this scrolling crap.

**Comment by lydell** [comment]
I found a workaround. There's the occasional little hickup, and holding `<space>` is not quite the same as holding `<space>` in Ignore mode, but I think it is good enough.
