### ISSUE TITLE
number in urlbar add 1?

### ISSUE THREAD

**Issue by dupontjoy** [akhodakivskiy/VimFx#846]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.3
Firefox version: 49.0.2
OS: Win10_64
Keyboard language: en-US
Example URL (if any): https://github.com/qiwsir/ITArticles/blob/master/BasicPython/207.md

there is number "207" in the example URL.
I want to add "1" to "208" when pressing certain key.
I find the below code from mouse gesture, how can I use it in VimFx? Thanks
````
{
label: "URL number add 1",
command: function(event) {
	loadURI(content.location.href.replace(/(\d+)(?=\D*$)/, function($0) {
		return +$0 + 1
	}));
}
````

**Comment by progandy** [comment]
You can adapt the command to [Open a specific URL](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#open-a-specific-url)
This also uses the ```count``` prefix so you can add larger numbers than 1.
```
vimfx.addCommand({
  name: 'goto_increment',
  description: 'Increment URI',
  category: 'location',
}, ({vim, count}) => {
  if (!count) count = 1;
  let uri = vim.window.gBrowser.selectedBrowser.currentURI.spec;
  vim.window.gBrowser.loadURI(uri.replace(/(\d+)(?=\D*$)/, function($0) {
        return +$0 + count;
      }));
});
```

**Comment by lydell** [comment]
Thanks for helping out, @progandy! :+1:

I've added this to the [Custom commands](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#incrementdecrement-the-last-number-in-the-url) section in the wiki.

**Comment by dupontjoy** [comment]
Thanks a lot
