### ISSUE TITLE
Regular Expression Search and History (Custom Find Bar?)

### ISSUE THREAD

**Issue by hackel** [akhodakivskiy/VimFx#847]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.5
Firefox version: 52.0a2
OS: Ubuntu 16.10
Keyboard language: us (altgr-intl)

This is …

- [x] A feature request
  - [x] I've given a **detailed** _example_ below

It would be really convenient if searching worked a bit more like Vim, instead of just opening the stock find bar.  I would like to be able to press up/down to cycle through my search history, use regular expressions in search, and have smart case sensitivity (case insensitive unless an upper-case letter is used).  The [cVim](https://github.com/1995eaton/chromium-vim) Chrome extension provides a great reference implementation of this feature.

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/blob/fe25b9dfdb6d0c73ec4ef060974a619b83d1e22f/documentation/questions-and-answers.md#will-vimfx-provide-advanced-find-features

**Comment by hackel** [comment]
Ahh, missed that.  Pity. :(

**Comment by a13ph** [comment]
@hackel there are addons which provide that or similar features, for now at least
i've found these 2, but i didn't test if they still work or not:
https://addons.mozilla.org/en-US/firefox/addon/xulmigemo/
https://addons.mozilla.org/en-US/firefox/addon/regex-find/

**Comment by hackel** [comment]
@a13ph Thanks, I'll definitely give those a shot!  The history is really what I miss most, though.
