### ISSUE TITLE
Reloading config fails to clean up after `vimfx.addKeyOverrides()`

### ISSUE THREAD

**Issue by f1u77y** [akhodakivskiy/VimFx#849]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.5
Firefox version: 53.0a1
OS: GNU/Linux
Keyboard language: en-US
Example URL (if any): None

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Start with an empty config
2. Add `vimfx.addKeyOverrides([() => true, ['j']]);` to config
3. Reload it
4. Remove the line from config
5. Reload it again
6. Repeat steps 2-5 once more

Expected result: 

`j` scrolls down as usual

Actual result:

`j` is ignored by the addon

Additional info:

There are no errors/warnings in Browser Console(with "vimfx" filter)

**Comment by lydell** [comment]
Thanks for your clear report. Unfortunately, I cannot reproduce. (Did you press `gC` to reload the config file? Was there any errors in it?)

VimFx version: 0.20.5
Firefox version: 53.0a1 (2016-12-04) (64-bit)
OS: Ubuntu 16.04
Keyboard language: en-US

**Comment by f1u77y** [comment]
Oh, I thought I've found the regularity but I was very far. I've updated the issue. I'm not sure if this is the right regularity but at least I've tried to reproduce it several times on some site and it was always reproducible.
