### ISSUE TITLE
Shortcut keys don't work on imgur.com/xxxxxx pages

### ISSUE THREAD

**Issue by gulkily** [akhodakivskiy/VimFx#851]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.5
Firefox version: 50.1.0
OS: OSX 10.11.3
Keyboard language: en-us
Example URL (if any): https://imgur.com/g66J1IE

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Open an imgur page, e.g.: https://imgur.com/g66J1IE
2. Press a shortcut key like j or k

Expected result: Shortcut works (page scrolls down with j)

Actual result: No action

**Comment by lydell** [comment]
imgur autofocuses the following (hidden) element on page load (presumably only in Firefox):

```html
<div class="ff-paste-hack" contenteditable="true"></div>
```

This means that when you type `j` to scroll down, you are actually typing into the above element. If you look at VimFx’s [toolbar button](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/button.md) you’ll see that it is grey, indicating that an element which you can type into is focused.

I’m not sure what feature imgur needs this hack for.

What you can do include:

- Learn to press `<escape>` when going to imgur.
- Enable the [Prevent autofocus](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/options.md#prevent-autofocus) option.
- Enable the Prevent autofocus option only on imgur by using a [config file](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/config-file.md).
- Contact imgur and tell them that their "ff-paste-hack" is causing accessibility problems for keyboard users.

**Comment by gulkily** [comment]
>Enable the Prevent autofocus option.

Thank you. I chose that route. It wasn't clear to me that you were referring to extensions.VimFx.prevent_autofocus in about:config, so I am just adding that here.

**Comment by lydell** [comment]
It's easier to hit the checkbox in [VimFx’s options page in the Add-ons Manager](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/options.md#regular-options) :wink:

**Comment by WishCow** [comment]
In case someone else is looking for the per-site setting in config.js:

```js
vimfx.addOptionOverrides([
    ({ hostname }) => `${hostname}` === 'imgur.com',
    { prevent_autofocus: true }
]);
```
