### ISSUE TITLE
Implement "ZZ" as "save and exit"

### ISSUE THREAD

**Issue by xuhdev** [akhodakivskiy/VimFx#853]
- [X] I've searched for duplicates – also closed issues
- [X] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [X] I've provided the below details:

VimFx version: 0.20.6
Firefox version: 50.1
OS: Debian Jessie
Keyboard language: English

This is

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [X] A feature request
  - [x] I've given a **detailed** _example_ below
- [ ] Somehting else

Firefox is known to have the builtin ability to save session (e.g. all tabs) when it exits. It would be nice to implement "ZZ" (the Vim keybinding for save and exit) as the key to save the current session and exit, which provide some flexibility to choose between a "plain" exit or an exit with session saving.

**Comment by lydell** [comment]
This won't make it into the default set of commands.

However, I encourage you to try to add it as a custom command (see [config file](https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/config-file.md)). I guess you could base it off of the [Close window](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#close-window) custom command. Could be as easy as setting the "save session" pref right before, and re-setting it on startup.

**Comment by xuhdev** [comment]
@lydell How do I add code on startup then?

**Comment by lydell** [comment]
Just stick it directly into `config.js`. If you put `console.log('Hello!')` in it, "Hello!" will be logged in the console every time the config file is run (such as on startup).

**Comment by xuhdev** [comment]
@lydell Thanks. while it can do now, it seems that WebExtension does not support modifying preferences... Do you have any suggestions?

**Comment by lydell** [comment]
Yes: Do not use any non-WebExtension add-ons. Then you won’t miss any functionality when Mozilla stops supporting “legacy” add-ons (which is planned to happen at the end of 2017). VimFx will become a WebExtension during the year, but it will take a long time. It will take an even longer time before WebExtensions are able to do “everything” that add-ons can do today. There are features in VimFx that will never work as a WebExtension. This is a bit sad, but also a necessary evil to be able to move the Firefox project forward.
