### ISSUE TITLE
Follow Hints should scale with browsers zoom level

### ISSUE THREAD

**Issue by mweinelt** [akhodakivskiy/VimFx#854]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.6
Firefox version: 53
OS: Linux
Keyboard language: en
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [x] A feature request
  - [x] I've given a **detailed** _example_ below
- [ ] Somehting else

When zoomed into a webpage text and image elements are enlarged, the follow hints (toggled by `F`) however stay at their default font size. They should scale with the browser zoom to offer better accessibility.

**Comment by lydell** [comment]
I consider it a feature that the hint markers are unaffected by the zoom level.

How would this improve accessibility? If the hint markers are too small for you to read, the solution is making the hint markers larger, not zooming the page, isn't it?

**Comment by mweinelt** [comment]
I'm using the browser at several distances, sitting and standing, depending on my distance to the screen I also prefer different sizes, at which the follow hints might become unreadable.

**Comment by lydell** [comment]
Thanks for providing a use case!

I use zoom on sites with smaller text than I can read comfortably, such as http://www.quirksmode.org/blog/. Personally, I would be annoyed if the hint markers got larger then.

It feels as if your use case, while valid, is the more uncommon one, so I'll close this. You might be able to achieve what you want by building off of a [custom zoom command](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#zoom), though. Feel free to come back to this issue and ask questions, if needed!
