### ISSUE TITLE
select nth tab

### ISSUE THREAD

**Issue by erjoalgo** [akhodakivskiy/VimFx#855]
Is there a command to switch to the nth tab (for example, "4 g" to go the fourth tab")? 
I couldn't find anything in the docs.

Thanks

**Comment by lydell** [comment]
See https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/questions-and-answers.md#how-do-i-switch-tabs

Make sure to follow the links from there as well, especially this one: https://github.com/akhodakivskiy/VimFx/blob/6c24199eba90d09e17dc93cf1c1e5cf3b860d621/documentation/commands.md#g0-g-g
