### ISSUE TITLE
Don`t recognize keys in non-english layout

### ISSUE THREAD

**Issue by stealzy** [akhodakivskiy/VimFx#856]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.6
Firefox version: 47.0
OS: Win 7 SP1
Keyboard language: ru-RU
Example URL (if any): any

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Set non-english layout.
2. Press any key: [F] / [J] / [K] / ...
3. No reaction.

Expected result: work in any layout.

Actual result: not work in other layout.

**Comment by lydell** [comment]
https://github.com/akhodakivskiy/VimFx/blob/8670eb8d1f9e10038d7bb601b7cdcbb0e7da38f3/documentation/questions-and-answers.md#vimfxs-shortcuts-work-in-my-english-layout-but-not-in-my-other-layout
