### ISSUE TITLE
Go up n levels using the gu shortcut

### ISSUE THREAD

**Issue by elager** [akhodakivskiy/VimFx#858]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.6
Firefox version: 50.1.0
OS: Linux
Keyboard language: Swedish
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [x] A feature request
  - [x] I've given a **detailed** _example_ below
- [ ] Somehting else

I have good use of the `gu` shortcut, but I would have even more use of it if it was possible to go up an arbitrary number or levels.

For example, if I get linked to the VimFx code here on github, say https://github.com/akhodakivskiy/VimFx/tree/master, and I want to navigate to https://github.com/akhodakivskiy/VimFx to check out the main page, it would be really nice to be able to go up 2 levels at once.

Following the vim syntax I suggest `gnu`, where n is any number. So in the example above, `g2u`would do the trick.

**Comment by Tunous** [comment]
Isn't it already possible?

`2gu` should work for you looking at the wiki: https://github.com/akhodakivskiy/VimFx/blob/master/documentation/commands.md#gu

**Comment by elager** [comment]
Yeah, that works just as expected. I completely missed that when I looked for it in the docs. Thanks!
