### ISSUE TITLE
Facebook emoji hovering/focus cannot be done

### ISSUE THREAD

**Issue by avinashh2** [akhodakivskiy/VimFx#859]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version:  0.20.6
Firefox version: 50.1.0
OS: Fedora 25
Keyboard language: en_US
Example URL (if any): https://www.facebook.com/

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - [ ] I've given a **detailed** _example_ below
- [ ] Somehting else

1. Log in on facebook.com
2. In the main feed on the start page when you are logged in, look for the “like” button on any post.
3. Hover it with the mouse. A little panel pops up with a bunch of emojis that you can click on.
4. Now, try to pop that panel up using VimFx’s `f` commands.

Actual result: There seems to be no way of doing so.

Expected result: It should be possible to use the “emoji picker” using VimFx!

**Comment by lydell** [comment]
Thanks for your issue!

I’ve just pushed a commit that makes the `ef` command show a hint marker for the “like” button. However, when I activate that hint marker, the “emoji picker” shows for a second or so before disappearing. I’ll have to investigate if anything can be done there.

The workaround is to focus the “comment link” next to the “like” button (using the `ef` command), and then press `<s-tab>`. That seems to consistently make the “emoji picker” pop up. Then, use the `f` command to click on the desired emoji.
