### ISSUE TITLE
Single Character mode

### ISSUE THREAD

**Issue by bhajneet** [akhodakivskiy/VimFx#862]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.8
Firefox version: 51
OS: Linux
Keyboard language: us (english)
Example URL (if any): n/a

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [x] A question
- [ ] Somehting else

Can we select the first letter of markers with css? I have tried using the pseudo class ::first-letter

I'm trying to make all the characters except the first one hidden, so that dense sections are still easily identifiable for starting the sequence.

**Comment by bhajneet** [comment]
I was able to get a partial fix with:

```
#VimFxMarkersContainer .marker {
    font-size: 16px !important; /* Specific font size. */
    letter-spacing: 1em !important;
    padding: 0px !important;
    font-family: "Noto Sans" !important;
    font-weight: bold !important;
    /*text-transform: lowercase !important; /* Lowercase text. */
    opacity: 1 !important; /* Semi-transparent. Warning: Might be slow! */
    background-color: rgba(255, 236, 179, 0.0) !important;
    border: 0px !important;
    color: #e23029 !important;
    width: .8em !important;
    height: 1.2em !important;
    overflow: hidden !important;
    -moz-transform:rotate(-0deg);
    -webkit-text-stroke: 1px rgba(255,255,255,.25) !important;;
    text-shadow: 2px 2px 4px white !important; 
}
#VimFxMarkersContainer .marker--matched,
#VimFxMarkersContainer .marker-char--matched {
  display: none !important;
}
```

identifying the css element for First letter would still be helpful

**Comment by lydell** [comment]
```css
#VimFxMarkersContainer .marker:first-child {
  color: red;
}
```

https://developer.mozilla.org/en/docs/Web/CSS/Pseudo-classes
