### ISSUE TITLE
Unable to install in Seamonkey

### ISSUE THREAD

**Issue by gulkily** [akhodakivskiy/VimFx#863]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.8
Firefox version: 2.46 (Seamonkey)
OS: macos 10.11.3
Keyboard language: en-us
Example URL (if any): https://addons.mozilla.org/En-us/firefox/addon/vimfx/

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Install latest stable Seamonkey build (2.46 at the moment)
2. Go to https://addons.mozilla.org/En-us/firefox/addon/vimfx/

Expected: Install button

Actual: Link to Firefox

**Comment by lydell** [comment]
SeaMonkey is cool, but not supported. Sorry!

**Comment by gulkily** [comment]
Why not? I submitted a similar bug report for uBlock, and all it took was changing the "max version" setting to fix it. Won't you please consider it? Thank you.

**Comment by lydell** [comment]
I tried marking SeaMonkey 2.0 and later as compatible on AMO. Does it work for you? If so, I'll add it to the manifest file so that every new VimFx version is automatically set as compatible with SeaMonkey.

**Comment by gulkily** [comment]
1. I was able to download the .xpi from the "Add to Seamonkey" button here:
https://addons.mozilla.org/en-US/seamonkey/addon/vimfx/
2. I was initially not able to install it in Seamonkey, until I added the following to install.rdf:
```
<em:targetApplication>
  <!-- SeaMonkey -->
  <Description>
    <em:id>{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}</em:id>
    <em:minVersion>2.0</em:minVersion>
    <em:maxVersion>2.*</em:maxVersion>
  </Description>
</em:targetApplication>
```
3. Sadly, it does not seem to work, as the VimFX button has not appeared in the toolbar, and shortcuts don't work on a page.

I am a newbie when it comes to Mozilla extensions. Is there anything you know that I can do to help debug this and get it working?

**Comment by lydell** [comment]
Thanks for trying it out! What you did in step 2 is what I meant with "I'll add it to the manifest file". At least we know that _has_ to be done as well now.

Does/will SeaMonkey support WebExtensions?

- Yes → We'll revisit this in the future when #860 is resolved.
- No → You have to learn how extensions currently work (deprecated by Mozilla), and maintain a SeaMonkey fork of VimFx.
