### ISSUE TITLE
mode.normal.esc: <escape> is treated specially

### ISSUE THREAD

**Issue by mkoskar** [akhodakivskiy/VimFx#864]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.8
Firefox version: 51.0.1
OS: Linux x86_64
Keyboard language: US
Example URL (if any): 

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

Set: `vimfx.set('mode.normal.esc', '<force><escape> <force><c-[>')`

1. Go to https://www.mozilla.org/en-US/about/
2. Press `o`.
3. Type `example`
4. Press `<c-[>`

Expected result: 

Url in urlbar should be reset to <https://www.mozilla.org/en-US/about/>, same way as it is for when `<escape>` is used.

Actual result: 

Url in urlbar reads `example`.

**Comment by lydell** [comment]
Thanks for the issue! :)

Yes, [`<escape>` is treated specially](https://github.com/akhodakivskiy/VimFx/blob/ac79c43b6c60d60fc2182e5f1fa39993aad6878b/extension/lib/modes.coffee#L93-L114). The location bar reset thing is a Firefox feature that VimFx has taken care to preserve. Unfortunately, there's no simple way to emulate it with some other key. Also, this won't be possible as a WebExtension, so I don't think it makes sense to spend any time on it.

**Comment by mkoskar** [comment]
I think I've found a workaround:

```
vimfx.addCommand({
    name: 'esc_alt',
    description: 'esc_alt',
}, ({event, vim}) => {
    let win = vim.window, active = event.target
    active.dispatchEvent(new win.KeyboardEvent('keypress', {keyCode: 27}))
    active.dispatchEvent(new win.KeyboardEvent('keypress', {keyCode: 27}))
    active.blur()
})
vimfx.set('custom.mode.normal.esc_alt', '<force><c-[>')
```
