### ISSUE TITLE
When do you have a Safari version?

### ISSUE THREAD

**Issue by haoxuexiaoyao** [akhodakivskiy/VimFx#866]
When will there be an extension of the Safari version?

**Comment by lydell** [comment]
Most likely never. There's something called [vimari](https://github.com/guyht/vimari) though.

**Comment by haoxuexiaoyao** [comment]
I know, but it's not convenient for you to extend this plugin! I hope you can also develop a Safari extension!

**Comment by haoxuexiaoyao** [comment]
I would like to ask how the input box in the web to prohibit AF? Every time you open a page with the input box, VIM will not be able to use the.
