### ISSUE TITLE
There is no lower left corner saying which mode the user is currently in

### ISSUE THREAD

**Issue by duytrung** [akhodakivskiy/VimFx#868]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.9
Firefox version: 50.0.1
OS: Windows 10
Keyboard language: US
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [x] A question
- [x] Something else

Expected result: There is a little textbox in the lower left corner to say which mode the user is currently in
How can I turn this on?
Actual result: no sign.

**Comment by duytrung** [comment]
I just found it so confusing without the mode indicator. Thanks!

**Comment by lydell** [comment]
Thanks for your issue!

VimFx's [toolbar button](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/button.md) acts as a mode indicator.

If that's not enough for you, I'll refer you to https://github.com/akhodakivskiy/VimFx/issues/752#issuecomment-223918675.
