### ISSUE TITLE
Cannot navigate through search matches while keeping highlighting on

### ISSUE THREAD

**Issue by dbedrenko** [akhodakivskiy/VimFx#869]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.9
Firefox version: 50.1.0
OS: 64-bit ArchLinux
Keyboard language: US-Dvorak
Example URL (if any): https://addons.mozilla.org/de/firefox/addon/vimfx/developers

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Go to the example URL.
2. Type `a/vim`. Notice how all instances are highlighted.
3. Press `<enter>`. Notice how the highlighting is gone.

Expected result: I should be able to navigate through search matches (going next and previous) with highlighting still enabled.

Actual result: Highlighting is lost as soon as I press `<enter>`. I can navigate the search results, but no highlighting.

I saw some issues where it was implied that this was supposed to work. I tried this with a clean Firefox profile.

PS: Love this extension! Thanks for all the great work!

**Comment by lydell** [comment]
Thanks for your very clear issue!

VimFx's find commands are basically just light wrappers around Firefox's find bar. This is how it works without VimFx:

1. Press `<c-f>` to open the find bar.
2. Press `<a-l>` to toggle Highlight All (text exact shortcut depends on your Firefox locale).
3. Type `vim`. Notice how all instances are highlighted.
4. Press `<escape>` to close the find bar. Notice how the highlighting is gone.
4. Press `<f3>` to find the next instance. Notice how the highlighting comes back, and won't go away until you open the find bar and toggle Highlight All.

VimFx works the same. Substitute `<c-f>` + `<a-l>` with `a/`, `<escape>` with `<enter>` (optionally) and `<f3>` with `n`.

Also note that:

- The Firefox default shortcuts for going to the previous/next results are `<f3>`/`<s-f3>` or `<c-g>`/`<c-G>`. They work even when the find bar is focused.
- You can remove `<enter>` from VimFx's "Close find bar" command if you don't want it to close the find bar, but instead do the Firefox default of going to the next match.

**Comment by dbedrenko** [comment]
Oh I didn't see that the highlighting comes back once you press "F3". Thanks for the tips!
