### ISSUE TITLE
Caret mode has other uses

### ISSUE THREAD

**Issue by dalb8** [akhodakivskiy/VimFx#870]
I use caret mode to help me focus while reading longer passages. It's also useful as a marker when returning from a digression. The readme implies that caret mode is just for selecting text. 

And of course, Vim itself always has a cursor, so caret mode isn't just "inspired by Vim visual mode".

VimFX is very useful for me as it allows me to quickly move the caret to the beginning of the line without the mouse.

**Comment by lydell** [comment]
I see!
