### ISSUE TITLE
<s-escape> does not exit ignore mode #568 

### ISSUE THREAD

**Issue by woctezuma** [akhodakivskiy/VimFx#871]
- [X] I've searched for duplicates – also closed issues
- [X] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [X] I've provided the below details:

VimFx version: 0.20.9
Firefox version: 51.0.1 (32-bit)
OS: Windows 10
Keyboard language: French AZERTY
Example URL (if any): https://www.mozilla.org/en-US/about/

This is … (pick one!)

- [X] A bug report
  - [X] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Something else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [X] Something else

Steps to reproduce:

1. Go to any webpage, e.g. https://www.mozilla.org/en-US/about/
2. Press `i` to enter ignore mode
3. Press `<s-escape>`
4. Optionally, press `<s-F1>` and notice that it works, it is just `<s-escape>` which does not work

Expected result: Enter normal mode

Actual result: Still in ignore mode

**Comment by lydell** [comment]
Thanks for the issue!

I can’t reproduce this. Could you try with a new Firefox profile, just to make sure there’s nothing wrong with your configuration?

**Comment by letientai299** [comment]
@woctezuma Just notice that you use different keyboard layout. Could you try again with English keyboard? I think that the source of the problem.

**Comment by woctezuma** [comment]
@lydell I have tried with a fresh Firefox profile, and the issue is still there.

@letientai299 I have tried switching from French to English using the `Alt+Shift` Windows shortcut, and the issue is still there.

**Comment by lydell** [comment]
@woctezuma 

1. Go to VimFx's settings page in the Add-ons Manager.
2. Foucs the text input for the "Return to Normal mode" command for Ignore mode.
3. `<c-q><s-escape>`

Expected behavior: The text `<s-escape>` is inserted into the text input.

What happens for you?

A similar experiment:

1. Press `m<s-escape>`.

Expected behavior: A notification appears, saying "Mark set: \<s-escape>".

What happens for you?

**Comment by woctezuma** [comment]
@lydell Result for the first experiment: nothing is inserted. I have tried other commands following <c-q> such as <c-s> or <escape> and both work. However, <s-escape> does not.

For the second experiment, is it still for the text input for the "Return to Normal mode" command for Ignore mode?

**Comment by lydell** [comment]
No, the second experiment is about the "Mark scroll position" command. When you press `m` a notification appears, saying "Mark scroll position (press a key…)". I suspect that nothing in particular will happen when you then press `<s-escape>`, and that notification to still be there.

I seems as if Firefox does not receive the `<s-escape>` key press at all. Some other program or your operating system must be eating it.

For a very short time, the default shortcut was `<c-escape>`, but it was changed to `<s-escape>` to support Windows: #441.

**Comment by woctezuma** [comment]
You are right. I have looked for the possible culprit and I have found this page [on StackOverflow](http://stackoverflow.com/q/28781557/). It turns out I do have this `PIconStartup.exe` in my `msconfig` startup menu. I also have `Intel Management and Security Status` in the tray notification part of the Windows task bar.

**Comment by lydell** [comment]
Nice find! 👍
