### ISSUE TITLE
Prevent autofocus on devdocs.io

### ISSUE THREAD

**Issue by losingkeys** [akhodakivskiy/VimFx#875]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.9
Firefox version: 52.0.1
OS: Arch Linux 4.10.3-1-ARCH
Keyboard language: English
Example URL (if any): https://devdocs.io/dom_events/mouseover

This is … (pick one!)

- [x] A bug report
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Something else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Ensure 'Prevent autofocus of text inputs' is checked in your VimFx preferences
1. Go to https://devdocs.io/dom_events/mouseover
1. Blur all text boxes (by clicking on the background or hitting ESC)
1. Scroll to the bottom of the page 
1. Click one of the 'See also' links, e.g. 'mousedown' (using these links because they link back to devdocs, not an external site)

Expected result: The search box isn't focused

Actual result: The search box _is_ focused

**Comment by lydell** [comment]
Thank you for your super clear issue report! 👍 

I agree that sites which keep autofocusing some text input as soon as you interact with anything on the page are pretty annoying. Unfortunately, there’s nothing we can do about them, as stated in the [documentation]()https://github.com/akhodakivskiy/VimFx/blob/a781264727c6bf430994b809614b755e00813021/documentation/options.md#prevent-autofocus:

> Autofocus on page load and when coming back to a tab are the two most common cases [and the only two tha VimFx will prevent]. Some sites, though, automatically focus a text input in other cases as well. Trying to catch those cases as well, VimFx used to prevent all focusing that didn’t occur within a fixed number of milliseconds after your last interaction (click or keypress). However, this proved to be too aggressive, preventing too much focusing. In other words, the time-based check was not sufficient to distinguish between intended focusing and automatic unwanted focusing. It made things worse more than it helped. Since these cases are so difficult (if not impossible) to detect, it is better to leave them. Thankfully they are not very common.

**Comment by losingkeys** [comment]
Hmm.. What if vimfx prevented autofocusing on onpopstate or other history api events? It seems like you struck a good balance between being too aggressive and too relaxed.. Maybe this would fit in that balance?akhodakivskiy/VimFx wrote:Thank you for your super clear issue report! 👍
I agree that sites which keep autofocusing some text input as soon as you interact with anything on the page are pretty annoying. Unfortunately, there’s nothing we can do about them, as stated in the documentationhttps://github.com/akhodakivskiy/VimFx/blob/a781264727c6bf430994b809614b755e00813021/documentation/options.md#prevent-autofocus:

Autofocus on page load and when coming back to a tab are the two most common cases [and the only two tha VimFx will prevent]. Some sites, though, automatically focus a text input in other cases as well. Trying to catch those cases as well, VimFx used to prevent all focusing that didn’t occur within a fixed number of milliseconds after your last interaction (click or keypress). However, this proved to be too aggressive, preventing too much focusing. In other words, the time-based check was not sufficient to distinguish between intended focusing and automatic unwanted focusing. It made things worse more than it helped. Since these cases are so difficult (if not impossible) to detect, it is better to leave them. Thankfully they are not very common.

**Comment by lydell** [comment]
Good idea about `onpopstate`! I think that might be useful on Slack.

However, it won’t solve your devdocs.io case.

**Comment by losingkeys** [comment]
Dang! I just assumed devdocs was using that.. I suppose clicking a link wouldn't... Maybe it'll solve other devdocs focus issues though.akhodakivskiy/VimFx wrote:Good idea about onpopstate! I think that might be useful on Slack.
However, it won’t solve your devdocs.io case.

**Comment by lydell** [comment]
Devdocs might very well be using `pushState`. What I meant is that `popstate` only fires when navigating the history.

**Comment by losingkeys** [comment]
Are you sure? Thinking about it again (and looking it up:
https://devdocs.io/dom_events/popstate) it seems like popstate might fire
when a link is clicked, because it's a history event (add the new page to
the history).

**Comment by lydell** [comment]
Yes, I’m sure. The `popstate` event is fired when state is popped, not pushed. And the page you linked to even says it:

> Note that just calling `history.pushState()` or `history.replaceState()` won't trigger a popstate event. The popstate event will been triggered by doing a browser action such as a click on the back or forward button (or calling `history.back()` or `history.forward()` in JavaScript).

**Comment by losingkeys** [comment]
Whoops.. Doc reading fail. I'll look into devdocs more later then :)akhodakivskiy/VimFx wrote:Yes, I’m sure. The popstate event is fired when state is popped, not pushed. And the page you linked to even says it:

Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event. The popstate event will been triggered by doing a browser action such as a click on the back or forward button (or calling history.back() or history.forward() in JavaScript).
