### ISSUE TITLE
View page source

### ISSUE THREAD

**Issue by glutaminefree** [akhodakivskiy/VimFx#876]
- [ x] I've searched for duplicates – also closed issues
- [ x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [ x] I've provided the below details:

VimFx version: 0.20.9
Firefox version: 52.0
OS: Fedora 24 x86_64
Keyboard language: en/ru

How can I see page source without Firefox context menu? Ctrl+U scroll page to top direction.

**Comment by lydell** [comment]
VimFx does not override `<c-u>` by default. You’ve either bound `<c-u>` to something, or some other add-on has.
