### ISSUE TITLE
How to change a key's action based on the current location?

### ISSUE THREAD

**Issue by Taconut** [akhodakivskiy/VimFx#879]
Hi! When I'm on my new tab page, sometimes I subconsciously press the "i" key instead of the "o" key to try and enter text in the url bar. My brain kind of associates entering text with insert mode, so I press "i" by accident.

Additionally, instead of pressing "p" on the home page, sometimes I'll accidentally type "Ctrl+v" when trying to paste and go on my new tab page.

So my question is this: is there any way to configure config.js to remap "i" to "o" and "Ctrl+V" to "p" when I'm at a certain page? I know how to add custom commands and overrides, but not how to swap one key for another conditionally.

Thanks!

**Comment by lydell** [comment]
I don’t think there is.

What you can do, though, is to add a custom command that in turn invokes different commands based on the current location.

**Comment by lydell** [comment]
I think the approach of creating custom "do-this-or-that-based-on-location" commands is a fine approach for this very specific use case. Feel free to ask if you need more help!
