### ISSUE TITLE
Access to browser modules from config.js

### ISSUE THREAD

**Issue by e2dubba** [akhodakivskiy/VimFx#880]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.10
Firefox version: 52.0.1
OS: Win 7
Keyboard language: English
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue #860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [x] A question
- [ ] Somehting else

I am trying to make an add on that will reformat some clipboard text and then open it in google translate. Everything works as I want it to, except for the part where it opens a new tab. 
I have `browser.tabs.create({url: psURL})` where `psURL` is the encoded URL. But when I run it as a module, it says that `browser is not defined`. I also tried `chrome` and some other stuff I found online, but how do I access the `browser.tabs.create()` function from the vimfx config.js? 

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [ ] Something else

Steps to reproduce:

1. 
2. 
3. 

Expected result: 

Actual result:

**Comment by lydell** [comment]
`browser` (and `chrome`) are part of the new WebExtensions API. In VimFx, you can use any Firefox APIs except the WebExtension APIs.

**Comment by e2dubba** [comment]
The other API for that is from the addons API, correct? 
```
var tabs = require('sdk/tabs');
tabs.open(url)
```
I still get a similar error: `require is not defined`

**Comment by lydell** [comment]
Not sure if it is possible to use SDK APIs. Didn't think of that. Anyway, it sounds like you're new to this. Then I'd say don't bother learning it. Firefox will support nothing but the WebExtension APIs at the end of the year. See #860.

**Comment by f1u77y** [comment]
@e2dubba you could use
```js
const { utils: Cu } = Components;
const { require } = Cu.import("resource://gre/modules/commonjs/toolkit/require.js", {});
```
for acessing to `require` function. Not sure if it could access to SDK API but give it a try.

Anyway, lydell is right, and there will be no need to use these APIs in near future. (And I am pretty aware of this because WebExt don't provide many useful APIs and AFAIK won't ever do this)
