### ISSUE TITLE
Move tab to previous window

### ISSUE THREAD

**Issue by Noitidart** [akhodakivskiy/VimFx#883]
I know feature requests are banned due to webext port not happening. However I suuuuuper loved this addon and am putting this issue here so maybe if you do go to webext, maybe you can add this in.

I use "Move tab to new window" a lot, but also have the need to "move tab to previous window" (i think "next window" would be same)

I fully expect you to close this, I am just hanging out on hope for webext version. I hate to see Google Chrome developers replacing the loyal Firefox addon devs products just because webextension schedule didn't line up with firefox addon devs schedule to do the re-make.

- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.10
Firefox version: 53.0b9
OS: macOS 10.12.3
Keyboard language: English
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've tested in a new [Firefox profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)
  - [ ] I've filled in steps to reproduce below
- [x] A feature request
  - Sorry, feature requests are not accepted.
    See [issue 860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [ ] Something else

Steps to reproduce:

1. 
2. 
3. 

Expected result: 

Actual result:

**Comment by lydell** [comment]
Thanks for the suggestion! 👍 

As you guessed, I’m going to close this one, but hopefully other people will find it when searching so they can +1 it. Who knows, perhaps this feature comes true somewhere some day.

**Comment by Noitidart** [comment]
Thanks @lydell 
Quick question. I could never get <insert> key to work. Is that the right code for it? I'm on OS X.

**Comment by lydell** [comment]
At least on my system it is. Tip! Use [`<c-q>`](https://github.com/akhodakivskiy/VimFx/blob/16d72926b11b8ed63b27a779047599b62eecaf62/documentation/shortcuts.md#helper-keyboard-shortcuts) inside a text input for a shortcut to have VimFx automatically "spell" keys correctly for you.

**Comment by Noitidart** [comment]
Holy smokes! <c-q> is amazing!! Thanks!
