### ISSUE TITLE
how to work with instapaper javascript

### ISSUE THREAD

**Issue by lilarcor** [akhodakivskiy/VimFx#884]
hello,
instapaper has a javascript like following, which can normally save as a bookmarket then click and run to save current page into personal instapaper list.
I was using the same URL in pentadactyl , but I am switching to vimfx. Is there possible to make a custom command in config.js ?

```js
function iprl5(){var d=document,z=d.createElement('scr'+'ipt'),b=d.body,l=d.location;try{if(!b)throw(0);d.title='(Saving...) '+d.title;z.setAttribute('src',l.protocol+'//www.instapaper.com/j/xxxxxxxx?a=read-later&u='+encodeURIComponent(l.href)+'&t='+(new Date().getTime()));b.appendChild(z);}catch(e){alert('Please wait until the page has loaded.');}}iprl5();void(0)
```

**Comment by letientai299** [comment]
Please format your code block using [Github code fence](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for readability. 

Also, I don't really see if this has anything related to VimFx. Please explain how did you use Instapaper (a webapp, bootmarket or addon?) alone and with Pentadactyl.

**Comment by lydell** [comment]
You seem to want to create a [custom command](). Something like this:

```js
// config.js
vimfx.addCommand({
  name: 'instapaper',
  description: 'Invoke Instapaper',
}, () => {
  vimfx.send(vim, 'instapaper')
})
```

```js
// frame.js
function iprl5() {
  var d = content.document,
    z = d.createElement('script'),
    b = d.body,
    l = d.location
  try {
    if (!b) throw 0
    d.title = '(Saving...) ' + d.title
    z.setAttribute(
      'src',
      l.protocol +
        '//www.instapaper.com/j/xxxxxxxx?a=read-later&u=' +
        encodeURIComponent(l.href) +
        '&t=' +
        new Date().getTime()
    )
    b.appendChild(z)
  } catch (e) {
    content.alert('Please wait until the page has loaded.')
  }
}

vimfx.listen('instapaper', () => {
  iprl5()
})
```

**Comment by lilarcor** [comment]
thank you, lydell. I added your codes in to config files, and added 
`vimfx.set('custom.mode.normal.instapaper', 'sn')`
restart my firefox and type 'sn'

but somehow, it's not working. no output

**Comment by lilarcor** [comment]
@letientai299, i was using it with Pentadactyl like following
`command! -description='Save to Instapaper' instapaper open javascript:function%20iprl5(){var%20d=document,z=d.createElement('scr'+'ipt'),b=d.body,l=d.location;try{if(!b)throw(0);d.title='(Saving...)%20'+d.title;z.setAttribute('src',l.protocol+'//www.instapaper.com/j/xxxxxx?a=read-later&u='+encodeURIComponent(l.href)+'&t='+(new%20Date().getTime()));b.appendChild(z);}catch(e){alert('Please%20wait%20until%20the%20page%20has%20loaded.');}}iprl5();void(0);
`
