### ISSUE TITLE
Disable copy-on-delete

### ISSUE THREAD

**Issue by mdibaiee** [akhodakivskiy/VimFx#885]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.10
Firefox version: 52.0a2 (Developer Edition)
OS: Archlinux
Keyboard language: English
Example URL (if any): 

This is … (pick one!)

- [ ] A bug report
  - [ ] I've tested in a new [Firefox profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)
  - [ ] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue 860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [x] A question
- [ ] Somehting else

Hey! First of all, thanks a lot for this, really helpful addon.

I wanted to ask whether it's possible to disable copy-on-delete in VimFx, couldn't find such an option. I know, in Vim that useful, but I find it a little irritating in the browser to have anything I delete in my clipboard.

Thanks

**Comment by lydell** [comment]
Hi! Thanks for your issue.

What is "copy-on-delete" in VimFx? Could you post steps to reproduce your problem?

**Comment by mdibaiee** [comment]
@lydell in Vim, when you delete a piece of text (using `d`), the text is yanked (copied) to your clipboard. The same happens in VimFx, when I delete a text from an input (nothing special about it, select the text, backspace), the text is copied to my clipboard.

Sample:

1. In an input write: 'Hello'
2. Select and delete the text
3. Paste and you get 'Hello'

**Comment by lydell** [comment]
That's not VimFx's fault. Disable VimFx and you'll see that you get same behavior.

**Comment by mdibaiee** [comment]
@lydell nope, it only happens when VimFx is enabled, after disabling VimFx everything goes back to normal.

**Comment by mdibaiee** [comment]
Not sure if this is related or not: https://github.com/akhodakivskiy/VimFx/blob/c5141a71eaddcb37dc4bf10b9ccf0f9424f12c38/extension/lib/modes.coffee#L182

**Comment by lydell** [comment]
Well, I can't reproduce even with VimFx enabled. Also, VimFx takes care to do as little as possible whenever a text input is focused. The code you linked to applies to Caret mode (which you can enter by pressing `v` and choosing a hint), which should not be entered when you focus a text input.

- You seem to be using a 2 versions old Firefox Developer Edition. Try updating and see if it helps.
- Please try in a new [Firefox profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles).
- Does it happen in the comment text box on this page?

VimFx version: 0.20.10
Firefox version: 54.0a2 (2017-04-18) (64-bit)
OS: Ubuntu 16.04
Keyboard language: English

**Comment by mdibaiee** [comment]
@lydell oops, I found the issue to be a general one with my Linux (I was syncing Selection and Copy clipboards), it was just a coincidence that installation of VimFx happened at the same time.

Anyways, sorry about the hassle, and again, thanks for the great addon. :+1: :grin:
