### ISSUE TITLE
Cannot highlight text in carat mode with hjkl

### ISSUE THREAD

**Issue by tokelove** [akhodakivskiy/VimFx#886]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 
Firefox version: 53.0
OS: 0.20.10
Keyboard language: en_GB
Example URL (if any): 

This is … (pick one!)

- [x] A bug report
  - [x] I've tested in a new [Firefox profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)
  - [x] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue 860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [ ] A question
- [ ] Somehting else

This bug is about … (pick one!)

- [ ] A missing hint marker on a specific page
- [ ] VimFx not recognizing a text input on a specific page
- [x] Something else

Steps to reproduce:

1. Enter Carat mode (v)
2. Hold shift to highlight text
3. Move with h,j,k,l

Expected result: Highlight text as the cursor moves

Actual result: Cursor does not move

**Comment by letientai299** [comment]
To highlight text in **Caret mode** of VimFx, please use `v`. If you use `shift` then you should use the arrow keys instead. I don't think in Vim we can select text by `shift-h` or `shift-l`. :)
