### ISSUE TITLE
Question: opening a new tab with text selected in the url bar

### ISSUE THREAD

**Issue by rnhmjoj** [akhodakivskiy/VimFx#887]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.10
Firefox version: 55.0.1
OS: GNU/Linux
Keyboard language: en-us

- [ ] A bug report
  - [ ] I've tested in a new [Firefox profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)
  - [ ] I've filled in steps to reproduce below
- [ ] A feature request
  - Sorry, feature requests are not accepted.
    See [issue 860](https://github.com/akhodakivskiy/VimFx/issues/860)
- [x] A question
- [ ] Somehting else

I used to press `t` opening a new tab, type something (in the url bar) and press enter to search/go to an url. It appears that on version 55.0(.1) Firefox will position the cursor at the end of the line instead of selecting the whole text, so the previous workflow result in the browser searching for garbage: 
`file:///home/rnhmjoj/.local/share/startpage.htmlstuffthatityped`

I have to first press `t`, then `ESC` and `o` before starting to type and it's quite annoying.
Do you know if it's possible and how to revert the behavior?

**Comment by lydell** [comment]
Sorry, I have no idea.
