### ISSUE TITLE
How to move highlighted marked link 

### ISSUE THREAD

**Issue by ooker777** [akhodakivskiy/VimFx#890]
- [x] I've searched for duplicates – also closed issues
- [x] I've looked at the [change log](https://github.com/akhodakivskiy/VimFx/blob/master/CHANGELOG.md)
- [x] I've provided the below details:

VimFx version: 0.20.10
Firefox version: 54.0.1
OS: Windows
Keyboard language: QWERTY

I want to navigate the highlighted link (the green one) by arrows or Tab/Shift+Tab. I think the answer lies somewhere in [Custom Hint Commands](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/api.md#custom-hint-commands) and [Options](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/options.md#hint-characters), but I still don't know what to do.

**Comment by lydell** [comment]
You can't. This was discussed when the "filter hint markers by text" feature was implemented, and it was a conscious choice not to implement it. See #789 and #803.
