### ISSUE TITLE
Firefox fork compatibility

### ISSUE THREAD

**Issue by sonarforte** [akhodakivskiy/VimFx#891]
It looks like VimFx is not compatible with IceCat and neither is Vimium-FF. Are there older versions of either of these plugins that are compatible, and if not, what are the other options for a vim plugin on IceCat?

**Comment by lydell** [comment]
Vimium-FF has never been compatible with IceCat.

I think VimFx has been compatible with IceCat at least at some point. I suggest you go to the [releases](https://github.com/akhodakivskiy/VimFx/releases) page and download versions from 0.6.0 to 0.20.10 and “binary search” your way to the latest VimFx version that work with IceCat.

**Comment by sonarforte** [comment]
I tried all the versions in the range you mentioned and none of them worked. Guess I'll have to stick with vimperator

**Comment by lydell** [comment]
Ah, that's sad. I hope vimperator will work out for you. I am impressed that you actually had the patience to try out all those 43 versions!
