### ISSUE TITLE
Hope to help move smooth scrolling feature to saka. 

### ISSUE THREAD

**Issue by sudoyang** [akhodakivskiy/VimFx#897]
Could anyone please tell me which part of VimFx code should I refer to? Thanks!

**Comment by lydell** [comment]
Hi! This has been discussed in #860. The short version is that the way VimFx does smooth scrolling is not possible in a WebExtension. See https://github.com/akhodakivskiy/VimFx/issues/860#issuecomment-300020654 and a few comments down.

You are aware that Saka Key has smooth scrolling, right? Do you like VimFx's smooth scrolling better? If so, it'd be interesting to hear how!

**Comment by sudoyang** [comment]
My feeling is like this. Maybe the description is a little vague. 

The spring stiffness is adjustable so that at the beginning of a scroll, it can start with a slow speed. As you keep pushing the button, scrolling speed can increase to a reasonable large value and stay with this value. Short-time scroll is slow and smooth enough so that you can read material simultaneously. Long time scroll is fast so that you can move to different part of webpage effectively.
