### ISSUE TITLE
Please port it to the new Firefox.

### ISSUE THREAD

**Issue by ssfjhh** [akhodakivskiy/VimFx#898]
This is one of the best AddOns available for Firefox. Please port it to the new Firefox.

**Comment by letientai299** [comment]
Please see the discussion in #860. We all love VimFx, but we must accept the fact that this plugins is die for Firefox to continue.

**Comment by ssfjhh** [comment]
It's a sad story.

**Comment by lydell** [comment]
I'm glad to hear that you like VimFx! Like @letientai299 said, see #860. We've already had like a year to think about this, and things won't change now. The new Vim-style extensions (see the readme) look promising, though.
