### ISSUE TITLE
VimFx does not work on Firefox 57

### ISSUE THREAD

**Issue by GreatBahram** [akhodakivskiy/VimFx#899]
Is there any hope to update this project works on firefox 57 ? 
I love this Add-ons :-(

**Comment by lydell** [comment]
Glad to hear you like VimFx. Sadly, VimFx won’t be rewritten to a WebExtension. As mentioned in the issue template:

> VimFx is a dead project

and the readme:

> **Note:** VimFx is a _legacy_ Firefox extension, which is **not**  [compatible
with Firefox 57+][firefox-57+].

See #898 and #860 for more history.

[firefox-57+]: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by GreatBahram** [comment]
Hmm, By the way thank you. It was pretty awesome add-one.

**Comment by al2helal** [comment]
I also like VimFx. Now I am using vimium but it's short key showing is not good.
