### ISSUE TITLE
Release Version for Legacy-enabled Firefox Versions

### ISSUE THREAD

**Issue by kevincox** [akhodakivskiy/VimFx#903]
https://github.com/akhodakivskiy/VimFx/pull/901 went in a while ago but it appears that no version was released.

Will Mozilla be allowing updates to legacy extensions, or do we need to take another route?

**Comment by lydell** [comment]
It was released in 0.20.11, which is available on AMO, and has been for a while.

**Comment by kevincox** [comment]
Werd, my browsers are downloading 0.20.10 and not updating to 0.20.11. I could download it manually though. I should probably open a bug with mozilla.
