### ISSUE TITLE
not work with Firefox 20171203, -moz-document gone

### ISSUE THREAD

**Issue by lilydjwg** [akhodakivskiy/VimFx#904]
It seems that `-moz-document` is no longer supported in XUL addons, so the styles are gone. I tried to remove that declaration from skin/style.css, and it worked for me (both the versions before and after that commit). I don't know why it is there though. Can we remove it?

See also [bug 1035091](https://bugzilla.mozilla.org/show_bug.cgi?id=1035091) of Firefox.

**Comment by lydell** [comment]
Yes, I think it should be safe to remove it. Feel free to make a pull request!
