### ISSUE TITLE
not work with Firefox 20180111+, Ci.inIDOMUtils gone

### ISSUE THREAD

**Issue by lilydjwg** [akhodakivskiy/VimFx#907]
https://bugzilla.mozilla.org/show_bug.cgi?id=1427419
https://reviewboard.mozilla.org/r/209654/diff/3#index_header

Seems there is no alternative.

**Comment by lydell** [comment]
Well, not much is lost if we remove it so that could be a path forward if somebody's interested.

**Comment by kevincox** [comment]
I can look into this.

**Comment by kevincox** [comment]
I have a patch that fixes this. I will upload tomorrow. It just removes the calls to this interface.

**Comment by lydell** [comment]
@kevincox I would rather have a try-catch than just removing it, though.

**Comment by kevincox** [comment]
Ack, I can do that if you prefer.

**Comment by lydell** [comment]
Released in v0.20.12.

**Comment by kevincox** [comment]
Thanks 😄
