### ISSUE TITLE
Waterfox

### ISSUE THREAD

**Issue by mb720** [akhodakivskiy/VimFx#911]
I switched to [Waterfox](https://www.waterfoxproject.org/) to be able to use this great add-on.

It would be nice if VimFx could live on without Firefox. Either through Waterfox or [other browsers](https://github.com/akhodakivskiy/VimFx/issues/895).

**Comment by lydell** [comment]
So far it seems to be working with Waterfox, and some helpful people have contributed fixes to keep it going (#917).
