### ISSUE TITLE
VimFx v0.20.12 FF59 support

### ISSUE THREAD

**Issue by jord-bh** [akhodakivskiy/VimFx#914]
Hi,

I saw that it would be possible to use latest VimFx version with FF59 in case legacy extensions was enabled:

> Fixed: VimFx should now work in Firefox 59 (if you have enabled legacy extensions). Thanks to Kevin Cox (@kevincox) and 依云 (@lilydjwg)!

I have Firefox 59.0.1 installed, I have `extensions.legacy.enabled=true` in about:config, and I have restarted Firefox after enabling this setting. I also have VimFx v0.20.12 version installed.
![firefox_version](https://user-images.githubusercontent.com/33550653/38024756-30f9c84c-3286-11e8-9d14-f95c41637e0a.png)
![ff_legacy_extensions_enabled](https://user-images.githubusercontent.com/33550653/38024775-38404e28-3286-11e8-9028-55ce7b53f89d.png)
![vimfx_version](https://user-images.githubusercontent.com/33550653/38024794-475c4e66-3286-11e8-8a7c-090f37b604fa.png)

However, VimFx is still greyed out in the addons list, and I cannot seem to find a way to enable it. Are there any other configuration settings which may need to be enabled for this to work?
![vimfx_inactivated](https://user-images.githubusercontent.com/33550653/38024812-55fa7b46-3286-11e8-90cb-7f23a91d19a6.png)

Highly appreciate any help that may be provided!

**Comment by lilydjwg** [comment]
You have to use nightly (and be aware that VimFx breaks frequently when nigthly is changing).

Here is [my build](https://mega.nz/#!Ct90SDrZ!3Jyb82l6qvNpHteIvL0CxT2UIcueh-72zfP1HZJLbvg) (sha1: ae5f0c4a29ae96b9f814b7287168e2af4e84959c) for the latest nightly I'm using in case you want it. It includes patches that are still in pull requests. You'll need to search signatures in about:config to disable that check.

**Comment by kevincox** [comment]
IIUC you don't have to use nightly, you can use any non-release build. This includes developer, beta and unbranded as well.

I unfortunately can't find a source on this bug I am using Firefox Developer Edition and it definitely works here.

**Comment by lilydjwg** [comment]
Maybe you can still enable legacy addons with other versions (I don't remember), but I remember that in beta and dev you can't install unsigned xpis. With reguard to unbranded, it depends on the build configuration used. (I had some other xpis that needed to be fixed manually.)

**Comment by kevincox** [comment]
I can definitely turn on unsigned on dev. I'm not sure about beta but seeing the marketing for dev it makes sense :)

**Comment by jord-bh** [comment]
Ah, I understand, thanks for the clarification.

In that case, it might be beneficial to update CHANGELOG.md to reflect this particular information too? I.e., 

>  Fixed: VimFx should now work in Firefox 59 (if you have enabled legacy extensions)

to

> Fixed: VimFx should now work in the beta, developer or nightly edition of Firefox 59 (if you have enabled legacy extensions)

**Comment by lydell** [comment]
Nah, I think it's good enough.
