### ISSUE TITLE
'F' stops working on current ESR (52.*)

### ISSUE THREAD

**Issue by stobenski** [akhodakivskiy/VimFx#918]
'F' stops working on current ESR branch (52.7.4) after latest (0.20.13) VimFX update.

Workaround: install VimFX [0.20.12](https://addons.mozilla.org/firefox/downloads/file/844222/vimfx-0.20.12-fx.xpi) and disable plugin autoupdate.

**Comment by jiixyj** [comment]
See issue #917.
