### ISSUE TITLE
btw, Version 0.20.13 "just stopped working". Pinning it to 0.20.12 still works, tho.

### ISSUE THREAD

**Issue by OwenAR** [akhodakivskiy/VimFx#921]
(Using Firefox ESR 52.7.4 (64-bit).)

I just noticed vimfx "just wasn't responding"
(I thought Firefox was just frozen for a moment).

I assume it was because vimfx updated itself to Version 0.20.13,
so I downgraded to Version 0.20.12 and disabled automatic updates,
and it seems fine now.

**Comment by lydell** [comment]
Thanks! This is already tracked in #917.
