### ISSUE TITLE
0.20.13 do not work in firfox56.0.2 when set "Prevents autofocus input boxes"

### ISSUE THREAD

**Issue by pangchol** [akhodakivskiy/VimFx#922]
I always stay at firefox56 just for using VimFx, But I recently discovered that 0.20.13 do not work in firfox56.0.2 when set "Prevents autofocus input boxes", I think it case by 0.20.13 update to support for firefox61. can fix this probalm for our firefox56 users?

**Comment by lydell** [comment]
Thanks! This is already tracked in #917.
