### ISSUE TITLE
Hint Markers overlap in link-dense pages

### ISSUE THREAD

**Issue by mvrozanti** [akhodakivskiy/VimFx#923]
Hello again, thank you for fixing Follow fo fast!

About Follow functionality: 

This is not a bug but sometimes I'm trying to get to a link that is right beside another and their markers overlap leaving me no way to know what I should combo to open it.  I'm not sure if there's any way to distribute the markers so that they don't overlap AND still keep the marker location intuitive in relation to the position of the link.

Not really necessary but might be something to think about, would be a cool enhancement if possible.

Keep up the great work!

**Comment by lilydjwg** [comment]
FYI, you can use `shift-space` to change the order of the overlapped hints. (And tt's `space` with Vimium.) You still don't see the underlying text but you can tell which is the right one by position for the most of time.

**Comment by mvrozanti** [comment]
This actually solves the whole problem. Damn, they thought out everything! I think this is not meant to be added since thi `shift-space` does this. Closing!
