### ISSUE TITLE
Search bar broken in FF 52 VimFx 0.20.14

### ISSUE THREAD

**Issue by amonakov** [akhodakivskiy/VimFx#925]
I'm seeing an unfortunate regression using VimFx on Firefox 52: when searching in page (using either '/' or Ctrl-F), hitting Enter does not unfocus the search panel. Hitting Esc does not work either.

As I recall it worked fine with VimFx 0.20.12. Not sure about 0.20.13.

Thank you.

**Comment by lydell** [comment]
That's sad to hear! Luckily, you can go back to 0.20.12. You won't be missing out on any features or anything.

**Comment by amonakov** [comment]
Ah, I wasn't aware until now that downgrades are easy on AMO, thanks for pointing that out.

I can confirm it works fine on 0.20.13.

**Comment by girst** [comment]
I've just upgraded to ff-dev 61b and I'm having the same issue with the search not getting dismissed. 

 * a workaround is to hit tab, then escape 

I've also tried 0.20.13 and .12 (in a clean profile, with `firefox --profile /tmp`), but pressing '/' just breaks any keyboard input (even in html forms). 0.20.11 and below don't work at all (no toolbar icon either).

**Comment by girst** [comment]
On Sun, Jul 01, 2018 at 04:26:30AM -0700, peter099 wrote:
>  if i hit Enter to find the next occurrence the findbar hide itself. 

that is actually normal behaviour: you are supposed to use `n` and `N`
to jump back and forth between matches.

**Comment by peter099** [comment]
I didn't know that. But than i have another problem: i don't see the popup in the right bottom corner that shows the number of found occurrences. I guess it is a conflict with some other addon.

**Comment by girst** [comment]
On Sun, Jul 01, 2018 at 04:56:46AM -0700, peter099 wrote:
>  i don't see the popup in the right bottom corner that shows the number of found occurrences.

I have never seen such a popup. the only thing that shows down there for
me is the 'search wrapped around to the top' thingie. 

(you can just search for something, not press enter, and then use the
mouse to click the button and it'll show the number of occurrences.)

**Comment by peter099** [comment]
> I have never seen such a popup. the only thing that shows down there for me is the 'search wrapped around to the top' thingie.

There is a popup:
https://i.imgur.com/ZfACs2W.png

**Comment by matsuhav** [comment]
In windows 10 with Nightly63.0a1 or 52 esr,  there is no popups and no indicator at scroll bar.  Also I noticed that gC to Reload config file doesn't show a popup at 63.0a1.  I think it's a bug.

By the way, I made a PR only about Enter and Esc at Search bar. #926
The last commit affected this.

**Comment by lydell** [comment]
Does v0.20.15 (should be on AMO in a day or so) work any better?

**Comment by girst** [comment]
20.15 has the search bar fixed, thank you all. (I had troubles with my profile, but it works on a fresh one. So I'll probably have to redo that yet again)

you can probably safely close that ticket now.

**Comment by amonakov** [comment]
v0.20.15 seems to work for me. Nice, thanks!
