### ISSUE TITLE
Consider adding support for JupyterLab

### ISSUE THREAD

**Issue by smashgen** [akhodakivskiy/VimFx#927]
VimFx is a great tool for me and my daily workflow. I use Waterfox instead of newer Firefox versions because I rely on certain add-ons of which I have currently not found an adequate replacement for. VimFx is one of those tools. I have started using JupyterLab for my recent project and noticed that VimFx only works partially with it. Some clickable items are not selectable using the find shortcut. I think this would be a great improvement.

**Comment by lydell** [comment]
Hi! Glad to hear you like VimFx! Unfortunately, VimFx is a discontinued project. Some enthusiasts keep it working ok-ish with newer Firefox and Waterfox and suchlike, but no development is made. Sorry!
