### ISSUE TITLE
Question: Copy links in multiple tabs (to the right or left)

### ISSUE THREAD

**Issue by RaitaroH** [akhodakivskiy/VimFx#928]
I know you can copy one link using default vimfx behavior. I am also aware that `let url = vim.window.gBrowser.selectedBrowser.currentURI.spec` is used to copy the current URI but I am trying to create comands such as `gy$` that will copy the url for all the tabs to the right, and `gy0` will copy the urls for the tabs to the left. Will be great if the tabs don't have to be loaded but even then is fine. 

Thank you.

**Comment by lydell** [comment]
`gBrowser.visibleTabs.slice(0, gBrowser.selectedTab._tPos).map(tab => tab.linkedBrowser.currentURI.spec)` returns an array of URLs to the left.

`gBrowser.visibleTabs.slice(gBrowser.selectedTab._tPos + 1).map(tab => tab.linkedBrowser.currentURI.spec)` for the right side.

You can add `gBrowser._numPinnedTabs` to the mix if you want to exclude pinned tabs.

**Comment by RaitaroH** [comment]
```
// Copy links
let {commands} = vimfx.modes.normal
vimfx.addCommand({
  name: 'copy_links_left',
  description: 'Copy the links of tabs to the left',
  category: 'tabs',
}, ({vim}) => {
  let url = vim.window.gBrowser.visibleTabs.slice(0, gBrowser.selectedTab._tPos).map(tab => tab.linkedBrowser.currentURI.spec)
  gClipboardHelper.copyString(url)
})
vimfx.set('custom.mode.normal.copy_links_left', 'gy0')

let {commands} = vimfx.modes.normal
vimfx.addCommand({
  name: 'copy_links_right',
  description: 'Copy the links of tabs to the right',
  category: 'tabs',
}, ({vim}) => {
  let url = vim.window.gBrowser.visibleTabs.slice(gBrowser.selectedTab._tPos + 1).map(tab => tab.linkedBrowser.currentURI.spec)
  gClipboardHelper.copyString(url)
})
vimfx.set('custom.mode.normal.copy_links_right', 'gy$')
```

I assume this is correct right? It doesn't seem to work though. Also related, the gClipboard doesn't work with the copy link as markdown showed in the examples you provide either. So I am not sure what is going on... My config file is [here](https://github.com/RaitaroH/Random-Code/blob/master/vimfx/config.js)

**Comment by lydell** [comment]
To me it sounds like a function named `copyString` expects a _string_ to copy. You are passing it an _array_ (`url`). Maybe an error is thrown because of that type mismatch? See if there's an error in the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console). Perhaps you are looking for [`.join()`](copyString) to turn that array into a string?

But really, I think you'll get better help on StackOverflow for JavaScript questions and some Waterfox community for Waterfox API stuff.

**Comment by RaitaroH** [comment]
@lydell, very well, I will ask around. Thank you.
