### ISSUE TITLE
hints mode doesn't follow links any more

### ISSUE THREAD

**Issue by girst** [akhodakivskiy/VimFx#930]
Hi, I've just upgraded to Firefox 63 (fedora) and when I type `f` or `F`, the hints pop up, but clicking on them doesn't work. The link gets selected, but not navigated to. I'm using VimFx 0.20.15 from AMO. It worked in FF62.0.3

**Comment by girst** [comment]
@lydell (or @kevincox or whoever) -- I'm offering a case of beer or two if this gets fixed and released on GH ;-) my email is at the [bottom there](https://gir.st/)

**Comment by girst** [comment]
Gah! you're right -- removed by bugzilla-#857456 in firefox 65!
WebExtensions are useless for this kind of addon, as it can't interact
with the browser itself / 'special' pages (or before the html is parsed). 

:(

Just talking out loud: some of firefox' features are implemented as
internal extensions (i believe the screenshot-functionality is one).
would that be a viable method? I don't mind recompiling firefox
(fedora's mock is quite nice to use).

**Comment by kevincox** [comment]
On Mon., Dec. 24, 2018, 15:38 girst <notifications@github.com wrote:

> WebExtensions are useless for this kind of addon, as it can't interact
> with the browser itself / 'special' pages (or before the html is parsed).
>

This is why I recommended WebExtension Experiments. They are packaged as
WebExtensions but have access to browser internals.

>

**Comment by girst** [comment]
Oh, i was unaware there was a difference! if that's the case, then this
seems the way forward, probably. 
here are some links about webext-experiments (for those who are/were
lost as well): 

https://wiki.mozilla.org/WebExtensions/Experiments 
https://webextensions-experiments.readthedocs.io/en/latest/

**Comment by lydell** [comment]
Fixed in [v0.21.0](https://github.com/akhodakivskiy/VimFx/releases/tag/v0.21.0).

**Comment by girst** [comment]
muchos gracias! :D
