### ISSUE TITLE
Mozilla Download Link broken

### ISSUE THREAD

**Issue by 8** [akhodakivskiy/VimFx#931]
The mozilla download link (https://addons.mozilla.org/en-US/firefox/addon/vimfx/) stopped working / is broken.

I am looking for a download link to the latest versions.

Thanks!

Take care,
Martin

**Comment by girst** [comment]
mozilla dropped all legacy extensions from AMO (that was announced some time ago). you can download the latest (last?) version from the[releases page](https://github.com/akhodakivskiy/VimFx/releases)

**Comment by 8** [comment]
Thanks for the release link, I didn't find it!

Take care,
Martin
