### ISSUE TITLE
Click browser element doesn't allow to switch to tab

### ISSUE THREAD

**Issue by mdumitru** [akhodakivskiy/VimFx#949]
I'm using Firefox 77.0.1, with the latest LegacyFox and version 0.23.3 of VimFX.

When using the "click browser element" command (eb), labels are properly placed everywhere they should and most of them seem to work from what I've seen, except those placed above tabs whose purpose is to switch to a particular tab. 

Typing the label works in every other way (the label changes color, the letters are greyed out one by one, the label disappears when completed), but it doesn't switch to the tab.

**Comment by girst** [comment]
I've just tried to reproduce this in fx77 and nightly. It works on my 
machine™. can you please try it while the browser console is open 
(ctrl-shift-j), and see if any messages come up during any part between 
typing 'eb' and the label name? also, it might be worth to try it in a 
new profile, or even a fresh copy downloaded from mozilla.org

**Comment by mdumitru** [comment]
Thank you for the swift reply!

The console reveals this error:
`ReferenceError: ShadowRoot is not defined                utils.js:31:10`

Installing a fresh copy of firefox didn't help. If it's relevant, I'm using Ubuntu 18.04 and Arch (this happens on both systems).

**Comment by girst** [comment]
On Fri, Jun 12, 2020 at 04:38:14AM -0700, mdumitru wrote:
>The console reveals this error:
>`ReferenceError: ShadowRoot is not defined                utils.js:31:10`

d'oh! i fixed that bug 6 weeks ago and completely forgot! (i tried to 
reproduce the bug with the fix already applied)

the commit message of 
https://github.com/girst/VimFx/commit/8e2377db0ee9e0333cebf530effa1926082431a6 
even mentions the exact STR!

i'll cut you a new release tomorrow :|

**Comment by girst** [comment]
ok, i lied: i won't wait till tomorrow.

here's a new version: https://github.com/akhodakivskiy/VimFx/releases/tag/v0.24.0

(and i just noticed: it should've been a patch release. oh well. )

**Comment by mdumitru** [comment]
Thank you very much!
