### ISSUE TITLE
"F" (Follow Link in a new background tab) not working on vimfx v0.24.1

### ISSUE THREAD

**Issue by Jonathan-79** [akhodakivskiy/VimFx#952]
Hi, thank you for supporting this wonderful extension.

I'm using "Mozilla Firefox 79.0" with legacyfox 2.0-1 from the AUR and after updating to VimFx 0.24.1 I've noticed that "follow link in a new background tab" feature is not working properly. After pressing "F", the hints appear, but selecting them does not result in any tab being opened.

This does not happen on VimFx 0.24.0.

Thank you again for reviving this excellent extension.

**Comment by girst** [comment]
I apologize; that last update was really half-baked. I pushed a new release.
