### ISSUE TITLE
Tab crashes and passwords not showing

### ISSUE THREAD

**Issue by matsuhav** [akhodakivskiy/VimFx#953]
Hello, thank you for supporting this best extension!

I'm using Firefox Developer edition 84.0b4.
After I upgraded to latest VimFx v0.24.3, I encountered a few problems.

- Tab crashes on Google Drive(ex. https://drive.google.com/drive/my-drive).
- `about:logins` shows none of my passwords as if there were no entries.

I tried some changes and it looks like this diff fixes them.

``` diff
diff --git a/extension/bootstrap.coffee b/extension/bootstrap.coffee
index 8663324..f2b771a 100644
--- a/extension/bootstrap.coffee
+++ b/extension/bootstrap.coffee
@@ -18,7 +18,8 @@ do (global = this) ->
 
   # Make `Services` and `console` available globally and in frame scripts.
   Cu.import('resource://gre/modules/Services.jsm')
-  Cu.import('resource://gre/modules/Console.jsm')
+  unless IS_FRAME_SCRIPT
+    Cu.import('resource://gre/modules/Console.jsm')
 
   shutdownHandlers = []
 
```
I haven't tested this patch on Waterfox or other Firefox releases.
If it looks ok, please merge it!

**Comment by girst** [comment]
I'm sorry; I fixed that bug two days ago in my [development repo](https://git.gir.st/VimFx.git), but didn't know it caused issues so I didn't release anything. I've tagged <https://github.com/akhodakivskiy/VimFx/releases/tag/v0.24.4> now.
