### ISSUE TITLE
Firefox 84 disabled VimFx

### ISSUE THREAD

**Issue by Jonathan-79** [akhodakivskiy/VimFx#957]
Hi, it's me again.

I'm using "VimFx 0.24.4" with legacyfox 2.3-1 from the AUR and after updating to Firefox 84.0.1 I've noticed that VimFx stopped working. After reinstalling legacyfox and VimFx, I've noticed that VimFx is actually disabled in Firefox config

![image](https://user-images.githubusercontent.com/69280939/103090639-5fefd780-45d0-11eb-8090-1e91895de994.png)

I've double-checked the about:config page, and it does appear that xpinstall signature is not required... 

![image](https://user-images.githubusercontent.com/69280939/103090773-d260b780-45d0-11eb-987d-9eae629dd05c.png)

Nevertheless, thank you so much for dedicating time to support this great extension.

**Comment by girst** [comment]
I'm not exactly sure what you're trying to say. Does VimFx work, but it 
shows the red warning bar? If so, you can ignore it (the wording is 
wrong; the addon is not disabled). If VimFx doesn't work, please try 
restarting your browser and if it still doesn't work, I'd like to ask 
you to perform these debugging steps: 
https://github.com/akhodakivskiy/VimFx/issues/956#issuecomment-743108617

**Comment by Jonathan-79** [comment]
Yes, the issue is that VimFx stopped working as soon as I updated to Firefox 84

> - please check that resource://legacy/ gives you a list of three .jsm
   files (and that they aren't empty)
![image](https://user-images.githubusercontent.com/69280939/103102892-05b93b80-45fd-11eb-98f9-c5f051adc9ba.png)

> - open about:config and type 'general.config'. post results.
![image](https://user-images.githubusercontent.com/69280939/103102921-300af900-45fd-11eb-8741-0afe1c38a173.png)

> - open about:support and search for 'application binary'. go to this
   directory and verify that config.js, legacy.manifest, legacy/*.jsm and
   defaults/pref/config-prefs.js are present.
![image](https://user-images.githubusercontent.com/69280939/103103031-bd4e4d80-45fd-11eb-813c-0946c8556f8b.png)

> - hit f12 to open devtools, then f1 to open settings and enable both
   "enable browser chrome and add-on debugging toolboxes" and "enable
   remote debugging". then open the browser console (ctrl-shift-j) again.
   it will now allow you to run javascript code with the highest
   privilege level. issue the following:
     ({AddonManagerPrivate} = Cu.import("resource://gre/modules/AddonManager.jsm"))
     AddonManagerPrivate.externalExtensionLoaders
   and expand the Map object and its 'entries' subobject. you should see
   a "bootstrap -> Object {...}" entry there.]
![image](https://user-images.githubusercontent.com/69280939/103103091-0c947e00-45fe-11eb-8185-31ca41d71f70.png)

> - where did you install firefox/nightly from (arch repo, aur,
   mozilla,...)? can you reproduce it with the binaries from
   'https://mozilla.org/nightly'?

Arch repo
![image](https://user-images.githubusercontent.com/69280939/103103120-2e8e0080-45fe-11eb-9d5a-117f006f22f4.png)

![image](https://user-images.githubusercontent.com/69280939/103103174-6137f900-45fe-11eb-98c0-00b4368ea4ec.png)

I didn't try to install the nightly version from mozilla yet. Do you thing it might solve the issue? Are you using firefox 84 without any problems?

**Comment by Jonathan-79** [comment]
Hi, I installed firefox from Mozilla website and after using it to launch my profile once, VimFx started to work again. It is even working with the Arch firefox package now...

I guess I should close this issue...

Thank you for helping me and indeed the instructions from the other issue made it work again

**Comment by girst** [comment]
First, thank you for trying all those steps (i know it's a lot). It 
shows that legacyfox was properly installed, so that wasn't it.

I'm still on fx83 (i'm in perma-private-mode, so upgrading will close 
all my tabs), but i've tested with nightly 84 whenever that came out.


On Thu, Dec 24, 2020 at 10:58:12AM -0800, Jonathan-79 wrote:
>Hi, I installed firefox from Mozilla website and after using it to 
>launch my profile once, VimFx started to work again. It is even working 
>with the Arch firefox package now...

This is an interesting obervation. Not sure what to do with this yet, 
but I'll keep it in mind for future legacyfox development.

glad it worked out for you in the end ;)
