### ISSUE TITLE
Trying to make custom command to edit location bar at the end

### ISSUE THREAD

**Issue by FACKDAWURLD** [akhodakivskiy/VimFx#959]
I really do not have the experience to create/implement this myself, so I have deleted all the stuff I pulled and tried from StackOverflow and elsewhere. If I had something worth including I would, but I had absolutely no luck so I am throwing the question out there if anyone can give me some help.

**Comment by girst** [comment]
not exactly sure what you mean; like this?

```
vimfx.addCommand({
	name: 'focus_location_bar_noselect',
	description: 'Focus the location bar without selecting the text within',
	category: 'location',
}, ({vim}) => {
	let urlBar = vim.window.gURLBar;
	urlBar.select();
	urlBar.selectionStart = urlBar.selectionEnd;
});
```

make sure to read the documentation on how to use this:

https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md

**Comment by FACKDAWURLD** [comment]
Yes thank you! This is exactly what I was looking for. Cannot tell you how long I was trying to figure this out. Thanks so much!
