### ISSUE TITLE
Automatic function possible ?

### ISSUE THREAD

**Issue by docop** [akhodakivskiy/VimFx#964]
Hi  Very great extension and perhaps a small function can be added too. Can it be possible to add an automatic function ? As to have a <keyboard shortcut> that will be automaticaly press every 30sec ..  That can be quite great.
Thanks in advance and happy new year.

**Comment by lydell** [comment]
Hi! I don’t quite understand what you mean. Can you provide an example?

**Comment by girst** [comment]
If i understand correctly, you want vimfx to automatically press a series of keystrokes every X seconds, right? I think this is outside of the scope of vimfx. you're better served by writing a userscript or looking for a dedicated webextension to do whatever website automation you want to do.

If i've misunderstood you, feel free to reopen this ticket ;)
