### ISSUE TITLE
'gX' Open the Recently Closed Tabs menu not working properly on VimFx v0.24.5

### ISSUE THREAD

**Issue by Ok-pass** [akhodakivskiy/VimFx#966]
Hello, thank you for the great extension.
OS: ArchLinux
Browser: Mozilla Firefox 96.0.2
Legacyfox: 2.3
VimFx v0.24.5
Noticed that **Open the Recently Closed Tabs menu** does not open a menu, instead just creates a blank space at the top of the browser. 
![2](https://user-images.githubusercontent.com/60102027/151360175-b0bc0940-d82e-4198-b757-b1d118099b71.png)

It correctly recognizes when there aren't any closed tabs and send the **No recently closed tabs** notification, so I'm guessing the problem is with the popup injection itself.

Tested on Waterfox Classic 2022.01 on the same system where it's working without issues.

**Comment by girst** [comment]
mozregression: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=29bdbbe89264b91d1bd4205c45536c9222a8d6ee&tochange=257f2c96cef502a1d674df56c8e39d76d8ed4d89

**Comment by girst** [comment]
thank you for the report! that was quite an interesting search through the pushlog :)

fix released in v0.24.6

**Comment by girst** [comment]
>Tested on Waterfox Classic 2022.01 on the same system where it's working without issues.

@Ok-pass: which vimfx version did you test this with? the recent versions of vimfx should require at least firefox 68, iirc.

**Comment by Ok-pass** [comment]
Thank you for the fix. 

> which vimfx version did you test this with? the recent versions of vimfx should require at least firefox 68, iirc.

My bad, I forgot to mention I'm using VimFx 0.20.15 on Waterfox.
