### ISSUE TITLE
Smoothe scrolling ? 

### ISSUE THREAD

**Issue by SamDc73** [akhodakivskiy/VimFx#972]
I'm using Firefox 100.0.2, when using < j  k> for navigation there is a slight shuttering, although I'm not having this problem with the arrow keys, 
I'm running Fedora 36 KDE wayland session [but this problem is occurring under X11 too]

**Comment by girst** [comment]
when you say "navigate", you mean scrolling up/down the page, right? i 
can't see any stuttering on my end. can you try the following please:

1. open about:config
2. search for "extensions.VimFx.scroll.reset_timeout" (should be default 
1000)
3. increase this value until stuttering stops. try to do it this way:
    a. check the stuttering
    b. if it is bad, double the value (e.g. now=1000 => next=2000)
    c. if it is good, try the middle of the old and new value
       (old=1000, now=2000 => next=1500)
    d. if your number changes by less than 25, STOP.
    e. otherwise, GOTO a.
4. report the numbers you tried and the results.

vimfx's scrolling is implemented in [1] (and cursor keys use firefox' 
built-in scrolling), so there might be a difference in how they work due 
to [2].

[1]: https://github.com/akhodakivskiy/VimFx/blob/615968f2a09cbf809cbad0bc3878d935b6f143e1/extension/lib/commands.coffee#L145 
[2]: https://github.com/akhodakivskiy/VimFx/commit/8d838199c9bd423f666ac87d1a0bdc7282c61a25

**Comment by SamDc73** [comment]
Thanks for your help, it's set o 2000 and the shuttering is gone . 
although i feel it's "slow" is there a way to make scrolling more faster ?
