### ISSUE TITLE
Vimfx doesn't work in Firefox 102

### ISSUE THREAD

**Issue by yuandi42** [akhodakivskiy/VimFx#973]
Vimfx (both v0.24.6 and v0.24.7 with latest legacyfox) stopped working as soon as I updated to Firefox 102. And I failed to reinstall Vimfx as Firefox claimed that an unsigned add-on couldn't be installed. 

I've preform debugging steps below:
- [x] resource://legacy/ gives you a list of three .jsm files (and that they aren't empty)
- [x] open about:config and type 'general.config'. post results
![1656477384](https://user-images.githubusercontent.com/42729673/176352803-773d5146-5096-4463-b436-e30352eec281.png)
- [x] open about:support and search for 'application binary'. go to this directory and verify that config.js, legacy.manifest, legacy/*.jsm and defaults/pref/config-prefs.js are present.
![1656477617](https://user-images.githubusercontent.com/42729673/176353143-ebcbcf0c-34b3-4654-be7d-bc983d355095.png)
- [x] hit f12 to open devtools, ...
![1656477924](https://user-images.githubusercontent.com/42729673/176353805-bd6d8dea-3c68-4c81-a450-5c4d66fd4213.png)
- [x] where did you install firefox/nightly from (arch repo, aur, mozilla,...)? can you reproduce it with the binaries from 'https://mozilla.org/nightly'?
Installed from arch repo
```
% paru -Qs firefox
local/firefox 102.0-1
    Standalone web browser from mozilla.org
local/legacyfox 2.3-1
    Legacy bootstrapped extensions for Firefox 65 and beyond
```
I didn't try to install nigthy from mozilla.org yet. I'm wondering how to solve the problem and I find it difficult for me to browse Internet with this add-on. Thank you for your prompt reply.

**Comment by kooskaspers** [comment]
Same issue here :(. Can't enable the plugin either.

**Comment by kooskaspers** [comment]
Thanks. Fixed the issue. My steps: 

```
wget https://git.gir.st/LegacyFox.git/snapshot/0548b59e51d966622e8733c62690078b61713d48.zip
$> unzip 0548b59e51d966622e8733c62690078b61713d48.zip
$> cd LegacyFox-0548b59
$> sudo make install DESTDIR=/usr/lib/firefox/
tar xzf legacyfox.tar.gz -C "/usr/lib/firefox/"
```
Then download the latest VimFx release. Don't try to install it directly by clicking on the latest release, but download the xpi file, and open it in firefox. Now it should be installed. Ignore the warning 'VimFx could not be verified for use in Firefox an has been disabled.'.

**Comment by yuandi42** [comment]
Thanks! Updating legacyfox works for my problem too.
