### ISSUE TITLE
How to open a link in the current tab while "typing" vimium?

### ISSUE THREAD

**Issue by Major-Cdompet** [akhodakivskiy/VimFx#974]
How to open a link in the current tab while "typing" vimium? Because while typing if you press "f" then it just write f and does not open link in the current tab.

Can you please suggest me how to do this or if there is no shortcut for this during typing then how to get out of typing?
Or I would like to use "alt+f" while typing to use the functionality of "f"

**Comment by girst** [comment]
On Tue, Jun 28, 2022 at 10:41:53PM -0700, Major-Cdompet wrote:
>How to open a link in the current tab while "typing" vimium? Because while typing if you press "f" then it just write f and does not open link in the current tab.
>
>Can you please suggest me how to do this or if there is no shortcut for this during typing then how to get out of typing?
>Or I would like to use "alt+f" while typing to use the functionality of "f"

when an input element is focused you can get back to normal mode by 
pressing escape. is this what you want?

**Comment by Major-Cdompet** [comment]
Yes this will do the thing. Thank you so much.
