### ISSUE TITLE
hotkeys mapping for website button

### ISSUE THREAD

**Issue by Major-Cdompet** [akhodakivskiy/VimFx#976]
Is there way I could map some keys for pressing a specific button on a website using vimium?
For example, I would like to use "ctrl+s" to press the button "submit new issue", can we do this? If not, let me know if there is some other chrome extension available for this?

**Comment by girst** [comment]
> Is there way I could map some keys for pressing a specific button on a website using vimium?

this extension is called vimfx, not vimium.

> For example, I would like to use "ctrl+s" to press the button "submit new issue", can we do this? If not, let me
+know if there is some other chrome extension available for this?

you can program a custom command. see the documentation sections config file
and api. however, that is pretty advanced and you will have to do this
yourself.

**Comment by girst** [comment]
On Wed, Jun 29, 2022 at 01:49:39AM -0700, Major-Cdompet wrote:
>Is there way I could map some keys for pressing a specific button on a website using vimium?

this extension is called vimfx, not vimium.

>For example, I would like to use "ctrl+s" to press the button "submit new issue", can we do this? If not, let me know if there is some other chrome extension available for this?

you can program a custom command. see the documentation sections config 
file and api. however, that is pretty advanced and you will have to do 
this yourself.
