### ISSUE TITLE
"Close tabs to the left" wiki command doesn't work

### ISSUE THREAD

**Issue by i-c-u-p** [akhodakivskiy/VimFx#977]
I followed the steps in [config-file.md](https://github.com/akhodakivskiy/VimFx/blob/master/documentation/config-file.md) for setting up config.js/frame.js:
1. Create empty `config.js` and `frame.js` files in `~/.config/vimfx`
2. In about:config, set `extensions.VimFx.config_file_directory` to `~/.config/vimfx` and `security.sandbox.content.read_path_whitelist` to `/home/username/.config/vimfx/`
3. Copy the wiki's ["Close tabs to the left"](https://github.com/akhodakivskiy/VimFx/wiki/Custom-Commands#close-tabs-to-the-left) command code into `~/.config/vimfx/config.js`

<details>
<summary>
~/.config/vimfx/config.js
</summary>

```js
let {commands} = vimfx.modes.normal
vimfx.addCommand({
  name: 'tab_close_to_start',
  description: 'Close tabs to the left',
  category: 'tabs',
  order: commands.tab_close_to_end.order + 1,
}, ({vim}) => {
  let {gBrowser} = vim.window
  Array.slice(gBrowser.tabs, gBrowser._numPinnedTabs, gBrowser.selectedTab._tPos)
    .forEach(tab => gBrowser.removeTab(tab))
})
```

</details>

4. Type gC to reload config file
5. Go to VimFx settings (chrome://vimfx/content/options.xhtml) and set "Close tabs to the left" to gx0

When I then type gx0 to close tabs to the left, this error appears in the browser console:
```
TypeError: Array.slice is not a function config.js:9:9
    <anonymous> file:///home/username/.config/vimfx/config.js:9
    onInput chrome://vimfx/content/lib/modes.js:78
    _call chrome://vimfx/content/lib/vim.js:199
    _onInput chrome://vimfx/content/lib/vim.js:165
    consumeKeyEvent chrome://vimfx/content/lib/events.js:212
    addListeners chrome://vimfx/content/lib/events.js:52
```

I'm using the latest VimFx version (v0.24.7) and have the latest commit of [LegacyFox](https://git.gir.st/LegacyFox.git) installed

**Comment by girst** [comment]
change Array.slice(gBrowser.tabs, ...) to gBrowser.tabs.slice(...)

if you can, please update the wiki!

**Comment by i-c-u-p** [comment]
> change Array.slice(gBrowser.tabs, ...) to gBrowser.tabs.slice(...) if you can, please update the wiki!

Seems like that fixed it!

<details>
<summary>
Updated code
</summary>

```js
let {commands} = vimfx.modes.normal
vimfx.addCommand({
  name: 'tab_close_to_start',
  description: 'Close tabs to the left',
  category: 'tabs',
  order: commands.tab_close_to_end.order + 1,
}, ({vim}) => {
  let {gBrowser} = vim.window
  gBrowser.tabs.slice(gBrowser._numPinnedTabs, gBrowser.selectedTab._tPos)
    .forEach(tab => gBrowser.removeTab(tab))
})
```

</details>

I'll update the wiki with the fix.

**Comment by girst** [comment]
On Fri, Aug 12, 2022 at 01:56:16PM -0700, i-c-u-p wrote:
>Seems like that fixed it!

glad i could help :)

>I'll update the wiki with the fix.

appreciated, thanks!
