### ISSUE TITLE
Can not install on firefox 105

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [akhodakivskiy/VimFx#980]
![image](https://user-images.githubusercontent.com/30759571/194669870-e9a09042-64bd-4f58-85b7-efbf26f85694.png)
I get this error msg even though, I can install extensions from other GitHub

I have the latest version of legacyfox installed from the `arch` repos

**Comment by girst** [comment]
On Fri, Oct 07, 2022 at 03:15:08PM -0700, Kallinteris Andreas wrote:
>![image](https://user-images.githubusercontent.com/30759571/194669870-e9a09042-64bd-4f58-85b7-efbf26f85694.png)
>I get this error msg even though, I can install extensions from other GitHub
>
>I have the latest version of legacyfox installed from the `arch` repos

that's unfortunately a known bug. i don't know exactly what's going 
wrong. as a workaround, download the extension and navigate the 
browser to your downloads directory. you should be able to install it 
from there. it should also be possible to install it from 
about:addons->gear icon->install addon from file.

when you say other addons work through github: do you mean other 
legacy extensions or new webextensions?

**Comment by Kallinteris-Andreas** [comment]
works now thanks!

"""
when you say other addons work through github: do you mean other
legacy extensions or new webextensions?
"""
webextensions work through github, i have not tested legacy

**Comment by girst** [comment]
On Fri, Oct 07, 2022 at 03:15:08PM -0700, Kallinteris Andreas wrote:
>![image](https://user-images.githubusercontent.com/30759571/194669870-e9a09042-64bd-4f58-85b7-efbf26f85694.png)
>I get this error msg even though, I can install extensions from other GitHub
>
>I have the latest version of legacyfox installed from the `arch` repos

that's unfortunately a known bug. i don't know exactly what's going 
wrong. as a workaround, download the extension and navigate the browser 
to your downloads directory. you should be able to install it from 
there. it should also be possible to install it from about:addons->gear 
icon->install addon from file.

when you say other addons work through github: do you mean other legacy 
extensions or new webextensions?
