### ISSUE TITLE
Fx 106.0.5: "This add-on could not be installed because it appears to be corrupt"

### ISSUE THREAD

**Issue by Ace-Who** [akhodakivskiy/VimFx#982]
After putting LegacyFox files in the profile folder and downloading VimFx.xpi v0.24.7, I install the add-on from the file, then Fx 106.0.5 says "This add-on could not be installed because it appears to be corrupt". Then I created a new blank profile and installed VimFx for it, the same error was reported. However, It was installed successfully on Nightly 108.

**Comment by Ace-Who** [comment]
Sorry, wrong step. I put LegacyFox files in to wrong folder. I'll try again.

**Comment by Ace-Who** [comment]
This time nothing happened, no error and no add-on was actually installed.

**Comment by girst** [comment]
have you looked at similar issues?

https://github.com/akhodakivskiy/VimFx/issues/956
https://github.com/akhodakivskiy/VimFx/issues/973
https://github.com/akhodakivskiy/VimFx/issues/980

try downloading the xpi from github to your downloads directory. then go 
to about:addons, click the gear icon and install it from there.

if that does not work, please work through the following troubleshooting 
steps:


- open about:config and type 'general.config'.

- hit f12 to open devtools, then f1 to open settings and enable both
    "enable browser chrome and add-on debugging toolboxes" and "enable
    remote debugging". then open the browser console (ctrl-shift-j) again.
    it will now allow you to run javascript code with the highest
    privilege level. issue the following:
      ({AddonManagerPrivate} = Cu.import("resource://gre/modules/AddonManager.jsm"))
      AddonManagerPrivate.externalExtensionLoaders
    and expand the Map object and its 'entries' subobject. you should see
    a "bootstrap -> Object {...}" entry there.

- open the browser console (ctrl-shift-j) and press ctrl-alt-r to 
   restart firefox. are there any errors reported?


then post your results.

**Comment by Ace-Who** [comment]
I'd read two of the issues and have read the rest one now. I downloaded the xpi file from github and installed it on `about:addons` page from file and failed. I created a new profile which I hadn't tried to install VimFx for, and took the troubleshooting steps:

- open `about:config` and type `general.config`:

![image](https://user-images.githubusercontent.com/17397070/201227318-10c151d4-9c6f-4b96-a3dd-abf1d588d666.png)

- hit F12 then F1 and enable the two options and run javascript code:

![image](https://user-images.githubusercontent.com/17397070/201228552-b686c267-14e7-4d5f-ac26-341c7e776017.png)

- press Ctrl-Alt-r on previously opened browser console:

Fx was restarted and the browser console is opened, and no error is reported.

![image](https://user-images.githubusercontent.com/17397070/201229309-d5256c87-6d5c-4ab3-9d54-48f014f71860.png)

Then I tried installed VimFx on `about:addon`. When I clicked `Install Add-on From File...` and open the xpi I downloaded before, the browser console output this:

```
Uncaught (in promise) TypeError: (new TypeError("this.addon._repositoryAddon is undefined", "resource://gre/modules/addons/XPIInstall.jsm", 1659)) is not iterable
    init resource://gre/modules/addons/XPIInstall.jsm:2118
```

![image](https://user-images.githubusercontent.com/17397070/201230891-dbb7112a-2247-445e-8d96-8913b7d7e676.png)

**Comment by girst** [comment]
The bad news is that this is a bug I haven't encoutered before. I 
usually test with nightly on Linux only.

The good news is: you installed legacyfox correctly. And I am able to 
reproduce this on linux using any localized (i.e non-english) version of 
firefox downloaded from mozilla. it even breaks on en_US firefox with 
any language pack installed (vimfx installed before adding a langpack 
will keep working, but even removing all langpacks will not make it 
possible to re-install vimfx until the whole browser profile is 
deleted).

I will try to find the cause for this issue, but I can't promise 
anything. As a workaround, you could use the en_US/english version of 
firefox, if that's an option to you.

**Comment by girst** [comment]
ok, i found the culprit, and an even easier workaround:

it's caused by the about:config preference "intl.locale.requested".

if a language pack is enabled (about:preferences -> language), it 
changes to a non-empty string.

on en_US firefox: deleting the pref or setting it to "" (empty string) 
again reverts to the default language and installation works. language 
packs can be reenabled afterwards.

on localized firefox: the pref does not exist, but creating it and 
setting it to "" keeps the default language, but vimfx installation now 
works.

@Ace-Who: please go to about:config, press the "i understand" button and 
type "intl.locale.requested" into the search box. set the check box to 
"string", and click create. then without typing anything klick the 
ok/checkmark button. vimfx installation should then work.

**Comment by Ace-Who** [comment]
Thanks. Wish you success. I'll keep using the en-US Nightly for a while and leave the zh-CN Firefox unchanged.

**Comment by girst** [comment]
more good news: the problem appears to be with vimfx's install.rdf file. i have a patch ready that would enable vimfx to work on unmodified localized firefox. can you please test the file attached?

[vimfx.zip](https://github.com/akhodakivskiy/VimFx/files/9990607/vimfx.zip)

note to self: the problem can be solved by copying `<em:name>` from the global `<Description>` section to the one in `<em:localized>`.

@Ace-Who: what was the last version of cn-firefox vimfx worked for you?

**Comment by Ace-Who** [comment]
> ok, i found the culprit, and an even easier workaround: it's caused by the about:config preference "intl.locale.requested". if a language pack is enabled (about:preferences -> language), it changes to a non-empty string. on en_US firefox: deleting the pref or setting it to "" (empty string) again reverts to the default language and installation works. language packs can be reenabled afterwards. on localized firefox: the pref does not exist, but creating it and setting it to "" keeps the default language, but vimfx installation now works. @Ace-Who: please go to about:config, press the "i understand" button and type "intl.locale.requested" into the search box. set the check box to "string", and click create. then without typing anything klick the ok/checkmark button. vimfx installation should then work.

Glad to see this, I'll try this later.

**Comment by Ace-Who** [comment]
> @Ace-Who: what was the last version of cn-firefox vimfx worked for you?

None. Because I upgraded from v56, which means the current version (106?) is my first try on a zh-CN Fx Quantum.

> more good news: the problem appears to be with vimfx's install.rdf file. i have a patch ready that would enable vimfx to work on unmodified localized firefox. can you please test the file attached?
> 
> [vimfx.zip](https://github.com/akhodakivskiy/VimFx/files/9990607/vimfx.zip)

Good news here too, this patch works on my zh-CN Fx v106.0.5. It is installed successfully.

**Comment by girst** [comment]
thank you for your help finding and debugging this issue! i posted a new release here: https://github.com/akhodakivskiy/VimFx/releases/tag/v0.25.0

**Comment by Ace-Who** [comment]
My pleasure and thank you.
