### ISSUE TITLE
Question about the behaviour of the search command

### ISSUE THREAD

**Issue by StreakyCobra** [akhodakivskiy/VimFx#987]
Hi there,

First thanks a lot for maintaining this project, the installation and integration went flawlessly despite being unsupported by Firefox :1st_place_medal: 

I'm used to several vim implementations (vim, evil, vim-vixen, …) and I find the behaviour of the search command weird. I'm not sure if this is expected or an issue with my setup.

When I want to search for something, I press <kbd>/</kbd> and that opens the search bar at the bottom. I can then enter the text I want to search and press <kbd>Enter</kbd> what brings me to the first occurrence, all good until there. Then if I want to navigate to the next instance I press <kbd>n</kbd>, what brings me to the next instance **but** that also opens the search bar at the bottom and, more problematically, _gives the focus to the search input_. This means I can not navigate through the results by successively pressing <kbd>n</kbd> because all the following `n` get appended to the search input.

Is that the expected behaviour or did I missed something / have an issue with my setup?

Thanks!

**Comment by girst** [comment]
On Tue, Nov 29, 2022 at 08:49:48AM -0800, uossoqnᗡ uǝıqɐℲ wrote:
>Hi there,
>
>First thanks a lot for maintaining this project, the installation and integration went flawlessly despite being unsupported by Firefox :1st_place_medal:

always happy to hear from people still using this :)

>
>I'm used to several vim implementations (vim, evil, vim-vixen, …) and I find the behaviour of the search command weird. I'm not sure if this is expected or an issue with my setup.
>
>When I want to search for something, I press <kbd>/</kbd> and that opens the search bar at the bottom. I can then enter the text I want to search and press <kbd>Enter</kbd> what brings me to the first occurrence, all good until there. Then if I want to navigate to the next instance I press <kbd>n</kbd>, what brings me to the next instance **but** that also opens the search bar at the bottom and, more problematically, _gives the focus to the search input_. This means I can not navigate through the results by successively pressing <kbd>n</kbd> because all the following `n` get appended to the search input.
>
>Is that the expected behaviour or did I missed something / have an issue with my setup?

this is definitely a bug. might be in your setup or in vimfx. usually, 
searching should work as you described (search bar stays closed).

i will try to find some time to debug this, but before that, please open 
the browser console (not normal devtools) by pressing ctrl+shift+j. do a 
seach and check for any errors.

**Comment by StreakyCobra** [comment]
>this is definitely a bug. might be in your setup or in vimfx. usually,
searching should work as you described (search bar stays closed).

Knowing this is not the expected behaviour is already helpful. So I tried to find what was causing the problem on my setup. After having tried to enable/disable all other extensions and looked at the `about:config` changed settings I finally found the cause:

🥁 *drumroll*

> findbar.modalHighlight = true

I guess I set this to `true` at some point to get the (now gone?) fancy highlighting. You can search google image if you are curious what it looked like. Setting it to the default value `false` fixed the problem 🙌

For me the problem is solved so I close the issue. If you want to act on it feel free to reopen it 😃

**Comment by girst** [comment]
On Tue, Nov 29, 2022 at 11:51:46AM -0800, uossoqnᗡ uǝıqɐℲ wrote:
>>this is definitely a bug. might be in your setup or in vimfx. usually,
>searching should work as you described (search bar stays closed).
>
>Knowing this is not the expected behaviour is already helpful. So I tried to find what was causing the problem on my setup. After having tried to enable/disable all other extensions and looked at the `about:config` changed settings I finally found the cause:
>
>🥁 *drumroll*
>
>> findbar.modalHighlight = true
>
>I guess I set this to `true` at some point to get the (now gone?) fancy highlighting. You can search google image if you are curious what it looked like. Setting it to the default value `false` fixed the problem 🙌

interesting. you learn about a new obscure about:config pref every day! 
it seems, it's not completely removed, there are quite a few references 
in the codebase still: https://searchfox.org/mozilla-central/search?q=modalHighlight&path=&case=false&regexp=false

>
>For me the problem is solved so I close the issue. If you want to act on it feel free to reopen it 😃

yep, perfect! glad you found the issue.
