### ISSUE TITLE
VimFx 0.26.0 doesn't work when extensions.VimFx.config_file_directory is set to "~/vimfx"

### ISSUE THREAD

**Issue by Ace-Who** [akhodakivskiy/VimFx#994]
When `extensions.VimFx.config_file_directory` is set to "~/vimfx", VimFx 0.26.0 doesn't work and the Browser Console outputs:

> 1685894585359	addons.xpi	WARN	Exception running bootstrap method startup on VimFx-unlisted@akhodakivskiy.github.com: ReferenceError: PathUtils is not defined(chrome://vimfx/content/lib/config.js:57:3) JS Stack trace: loadFile@config.js:57:3

**Comment by girst** [comment]
Sorry, I really dropped the ball with testing of the last release. v0.26.1 out now!

**Comment by Ace-Who** [comment]
Still not working:

    1686032659989	addons.xpi	WARN	Exception running bootstrap method startup on VimFx-unlisted@akhodakivskiy.github.com: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://vimfx/content/lib/config.js :: loadFile :: line 60"  data: no] Stack trace: loadFile()@config.js:60

**Comment by girst** [comment]
On Mon, Jun 05, 2023 at 11:50:38PM -0700, Ace-Who wrote:
>Still not working:
>
>    1686032659989	addons.xpi	WARN	Exception running bootstrap method startup on ***@***.***: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://vimfx/content/lib/config.js :: loadFile :: line 60"  data: no] Stack trace: ***@***.***:60

please share your about:config values for

- security.sandbox.content.read_path_whitelist
- extensions.VimFx.config_file_directory

also, firefox version and operating system please

**Comment by Ace-Who** [comment]
- security.sandbox.content.read_path_whitelist 
I don't have this option.
![图片](https://github.com/akhodakivskiy/VimFx/assets/17397070/59dd6e40-e444-4e41-8a72-89115087039f)

- extensions.VimFx.config_file_directory
value: `~/vimfx`
![图片](https://github.com/akhodakivskiy/VimFx/assets/17397070/893567c5-09ac-455e-b468-c385d4c78172)

Firefox Nightly 116.0a1 64bit, Windows 10 1903 build 18362.356
Firefox 113.0.2 64bit, Windows 10 1903 build 18362.356

**Comment by Ace-Who** [comment]
I don't know why `security.sandbox.content.read_path_whitelist` is not present now, but I created it again and set it to `C:\Users\***\vimfx` then restarted Firefox and got the same warning.

![图片](https://github.com/akhodakivskiy/VimFx/assets/17397070/42a28f97-488b-4beb-822f-cbee4c3a2313)

> 1686103598415	addons.xpi	WARN	Exception running bootstrap method startup on VimFx-unlisted@akhodakivskiy.github.com: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: chrome://vimfx/content/lib/config.js :: loadFile :: line 60"  data: no] Stack trace: loadFile()@config.js:60

**Comment by girst** [comment]
ok, this is an issue with windows. previously, vimfx 0.25.0 used this 
code:

const {OS} = ChromeUtils.import('resource://gre/modules/osfile.jsm');
let path = OS.Path.toFileURI("C:/");

this returned "file://C:", as expected.

both replacements, PathUtils.toFileURI("C:/") and new 
FileUtils.File("C:/"), cannot handle windows drive letters, possibly 
also with backslashes. 

i don't have a windows computer to test, but please try the following:

1. open a browser console
    a. press f12, then f1 to open devtools settings
    b. check "enable browser chrome and add-on debugging"
    c. check "enable remote debugging"
    d. press ctrl+shift+j to open a browser console
2. type `(new FileUtils.File("/Users/***/vimfx")).exists()`

does this also raise an error? if not, does it return true or false?
try using this for the path in extensions.VimFx.config_file_directory

**Comment by Ace-Who** [comment]
Now I set `security.sandbox.content.read_path_whitelist` to `C:\Users\***\vimfx\`.

`(new FileUtils.File("/Users/***/vimfx")).exists()` raises an error:

```
Uncaught NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.initWithPath]
    <anonymous> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:251
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:172
    evaluateJS resource://devtools/server/actors/webconsole.js:960
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:851
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
debugger eval code:1:2
```

I did replace `***` with actual user name.

> try using this for the path in extensions.VimFx.config_file_directory

Sorry I don't get what does "this" mean.

**Comment by matsuhav** [comment]
For anyone experiencing this issue, just emptying `extensions.VimFx.config_file_directory` let us use VimFx with previously loaded configs 😄 👍 ,
if you have a simple config.js which only set some keys and an empty frame.js like me, because all key settings are stored in about:config values.

So, I would also suggest that we surround file loading part of code with try-catch for future breakage of them again.
It's such a pain VimFx is not loaded and not usable at all...

---

First, thank you for supporting this great extension @girst !
I'm experiencing the same issue on Windows and I did some tests. I hope this helps.

`security.sandbox.content.read_path_whitelist` was empty and I also created as `C:\Users\username\.vimfx\`
I tried following values as `extensions.VimFx.config_file_directory` and the FileUtils.File() argument.

--- | when set `extensions.VimFx.config_file_directory` | `FileUtils.File("%s").exists()`
--- | --- | ---
`~/.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | `NS_ERROR_FILE_UNRECOGNIZED_PATH`
`~\.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | `NS_ERROR_FILE_UNRECOGNIZED_PATH`
`~\\.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | `NS_ERROR_FILE_UNRECOGNIZED_PATH`
`C:\Users\username\.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | false
`C:/Users/username/.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | `NS_ERROR_FILE_UNRECOGNIZED_PATH`
`file:///C:/Users/username/.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | `NS_ERROR_FILE_UNRECOGNIZED_PATH`
`C:\\Users\\username\\.vimfx` | `NS_ERROR_FILE_UNRECOGNIZED_PATH` | true

**Comment by matsuhav** [comment]
Of course! The output is below. The first one showed double backslashes and I pasted here as is.
Double backslashes thing is so tricky..
```
Services.dirsvc.get('Home', Ci.nsIFile).path
"C:\\Users\\username"
Services.io.newFileURI(new FileUtils.File("C:\\foo\\bar")).spec
"file:///C:/foo/bar"
```

**Comment by girst** [comment]
[vimfx-testbuild.zip](https://github.com/akhodakivskiy/VimFx/files/11706919/vimfx-testbuild.zip)

thanks, i think i got it now. instead of a premature release, i do what i should have done from the beginning and attach a test build. can both of you please try the attached xpi? [here's the diff](https://git.gir.st/VimFx.git/commitdiff/9ccfe9f62e69129c41b06c85a3998f70b5c82688) in case you're curious.

i'll have to do the try-catch logic you suggested.

**Comment by matsuhav** [comment]
Thank you very much!
Now `~\.vimfx` and `C:\Users\username\.vimfx` works without errors as `extensions.VimFx.config_file_directory` values! 👍 

`~/.vimfx` still shows the same error but I think it's OK.
Though I think it was working in 0.25.0, it's so trivial for Windows users to use back slashes when they set `extensions.VimFx.config_file_directory` but on the other hand, it can be complicated and error prone for VimFx to translate forward slashes to back slashes.
VimFx is in maintenance mode, so the try-catch is also optional thing of course.

**Comment by girst** [comment]
https://github.com/akhodakivskiy/VimFx/releases/tag/v0.26.2

**Comment by Ace-Who** [comment]
I don't know the details about code, but doesn't Windows accept both slashes and backslashes as path separators?

> [vimfx-testbuild.zip](https://github.com/akhodakivskiy/VimFx/files/11706919/vimfx-testbuild.zip)

I tested this on Firefox Nightly 116.0a1 in my daily used profile. For `config_file_directory`, neither `~/vimfx` nor `~\vimfx` works and both raise an error:

    1686324861418	addons.xpi	WARN	Exception running bootstrap method startup on VimFx@akhodakivskiy.github.com: TypeError: can't access property "startsWith", aId is undefined(resource:///modules/CustomizableUI.sys.mjs:1713:1) JS Stack trace: isSpecialWidget@CustomizableUI.sys.mjs:1713:1

But in a test profile `~\vimfx` works. Then I installed VimFx v0.25.0 to try my luck, and it works. Then I intalled the test build again, and it works too. However seems they both raise an error like this:

    1686329512705	addons.xpi	WARN	Exception running bootstrap method startup on VimFx-unlisted@akhodakivskiy.github.com: [Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://vimfx/content/lib/utils.js :: <TOP_LEVEL> :: line 6"  data: no] Stack trace: utils.js:6

When I noticed the VimFx version was still shown as 0.25.0, I thought was I expected to always do a clean install? Then I clean install v0.25.0 again and It doesn't work as expected. Then a  cleaned installed test build works again, and no error.

**Comment by Ace-Who** [comment]
For prudential reason, is it right that when referring to errors I ignore this common one:

    VimFx: Fission is enabled in your browser. VimFx will not be able to interact with third party iframes. main.js:127

**Comment by girst** [comment]
On Fri, Jun 09, 2023 at 10:13:00AM -0700, Ace-Who wrote:
>I don't know the details about code, but doesn't Windows accept both slashes and backslashes as path separators?

we use a piece of firefox code to handle paths. that firefox code 
stopped accepting / on windows (it seems).

>
>I tested this on Firefox Nightly 116.0a1 in my daily used profile. For `config_file_directory`, neither `~/vimfx` nor `~\vimfx` works and both raise an error:
>
>    1686324861418	addons.xpi	WARN	Exception running bootstrap method startup on ***@***.***: TypeError: can't access property "startsWith", aId is undefined(resource:///modules/CustomizableUI.sys.mjs:1713:1) JS Stack trace: ***@***.***:1713:1
>

this has nothing to do with this bug; i don't know what is broken here 
without backtraces. uninstall vimfx completely and reinstall it.

>But in a test profile `~\vimfx` works. Then I installed VimFx v0.25.0 to try my luck, and it works. Then I intalled the test build again, and it works too. However seems they both raise an error like this:
>
>    1686329512705	addons.xpi	WARN	Exception running bootstrap method startup on ***@***.***: [Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://vimfx/content/lib/utils.js :: <TOP_LEVEL> :: line 6"  data: no] Stack trace: utils.js:6

have you set security.sandbox.content.read_path_whitelist?

>
>When I noticed the VimFx version was still shown as 0.25.0, I thought was I expected to always do a clean install? Then I clean install v0.25.0 again and It doesn't work as expected. Then a  cleaned installed test build works again, and no error.
>

then you have installed something else. remove vimfx completely and 
install it fresh (your config is stored in about:config, so you won't 
lose anything)

On Fri, Jun 09, 2023 at 10:25:58AM -0700, Ace-Who wrote:
>For prudential reason, is it right that when referring to errors I ignore this common one:
>
>    VimFx: Fission is enabled in your browser. VimFx will not be able to interact with third party iframes. main.js:127
>

yes, you can ignore that. or fix it ;) => 
https://github.com/akhodakivskiy/VimFx/blob/master/documentation/known-bugs.md#fission

**Comment by Ace-Who** [comment]
Thank you.

> have you set security.sandbox.content.read_path_whitelist?

Yes. Anyway everything is OK now, provided `extensions.VimFx.config_file_directory` is set to `~\vimfx`.

> yes, you can ignore that. or fix it ;) => https://github.com/akhodakivskiy/VimFx/blob/master/documentation/known-bugs.md#fission

Oh, I must have read this and forgot it.

**Comment by girst** [comment]
On Mon, Jun 12, 2023 at 03:10:34AM -0700, Ace-Who wrote:
>Thank you.
>
>> have you set security.sandbox.content.read_path_whitelist?
>
>Yes. Anyway everything is OK now, provided `extensions.VimFx.config_file_directory` is set to `~\vimfx`.

good to hear! reach out again if anything breaks again :)
