### ISSUE TITLE
Firefox Add-ons link given in About section of github repo is not working.

### ISSUE THREAD

**Issue by dpthegrey** [akhodakivskiy/VimFx#995]
**The link given in the About is dead.**

![image](https://github.com/akhodakivskiy/VimFx/assets/49444980/9cf3936d-6352-45f5-b8cc-45d68df03b4b)

**On clicking that link it shows this page.**

![image](https://github.com/akhodakivskiy/VimFx/assets/49444980/5677de36-0655-4539-be2a-54811d1ebc83)

**Comment by ZWindL** [comment]
Yes, because this add-on is not compatible with the newer versions of firefox, so it is removed from the store. Please follow the instructions in README.
